# Generated by Django 5.2.17 on 2026-09-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='يرث هذا الدور كافة صلاحيات الدور الأب تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='users.role', verbose_name='الدور الأب (الوراثة)'),
        ),
        migrations.AddField(
            model_name='user',
            name='revoked_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات محجوبة من هذا المستخدم حتى لو كانت ممنوحة له من أدواره', related_name='users_with_revoked_permissions', to='auth.permission', verbose_name='صلاحيات مستثناة/محجوبة'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_roles',
            field=models.ManyToManyField(blank=True, help_text='أدوار إضافية مدمجة للموظفين متعددي المهام', related_name='secondary_users', to='users.role', verbose_name='الأدوار الثانوية'),
        ),
    ]
