# Generated by Django 4.2.23 on 2025-10-31 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات إضافية خارج الدور الأساسي', related_name='users_with_custom_permissions', to='auth.permission', verbose_name='صلاحيات إضافية'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الدور')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system_role', models.BooleanField(default=False, help_text='الأدوار الأساسية لا يمكن حذفها', verbose_name='دور نظام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_roles', to='auth.permission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='الدور الأساسي للمستخدم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='الدور'),
        ),
    ]
