# Generated by Django 4.2.26 on 2026-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["timestamp"], name="users_activ_timesta_22698c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "timestamp"], name="users_activ_user_id_049bc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action", "timestamp"], name="users_activ_action_cdfe71_idx"
            ),
        ),
    ]
