# Generated by Django 4.2.7 on 2025-10-22 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial", "0001_initial_clean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم العميل")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم الشركة إذا كان العميل شركة",
                        max_length=255,
                        verbose_name="اسم الشركة",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف بالصيغة: '+999999999'. يسمح بـ 15 رقم كحد أقصى.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True,
                        help_text="رقم الهاتف الأساسي للتواصل",
                        max_length=20,
                        verbose_name="رقم الهاتف الأساسي",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="رقم هاتف إضافي للتواصل",
                        max_length=20,
                        verbose_name="رقم الهاتف الثانوي",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="المدينة التي يقع فيها العميل",
                        max_length=100,
                        verbose_name="المدينة",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود العميل"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الحد الائتماني",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "فرد"),
                            ("company", "شركة"),
                            ("government", "جهة حكومية"),
                            ("vip", "عميل مميز"),
                        ],
                        default="individual",
                        help_text="تصنيف العميل حسب النوع",
                        max_length=20,
                        verbose_name="نوع العميل",
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاريخ آخر تواصل مع العميل",
                        null=True,
                        verbose_name="تاريخ آخر اتصال",
                    ),
                ),
                (
                    "contact_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("yearly", "سنوي"),
                        ],
                        help_text="معدل التواصل المطلوب مع العميل",
                        max_length=20,
                        verbose_name="تكرار الاتصال",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "financial_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="الحساب المحاسبي المرتبط بهذا العميل في دليل الحسابات",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer",
                        to="financial.chartofaccounts",
                        verbose_name="الحساب المحاسبي",
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="تاريخ الدفع")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_payments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدفوعات العميل",
                "verbose_name_plural": "مدفوعات العملاء",
                "ordering": ["-payment_date"],
            },
        ),
    ]
