# Generated by Django 4.2.26 on 2026-08-31 12:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="الحالة السابقة"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="الحالة الجديدة"),
                ),
                ("reason", models.TextField(verbose_name="السبب / الملاحظات")),
                (
                    "related_document",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="المستند المرتبط",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
            ],
            options={
                "verbose_name": "تدقيق حوكمة الائتمان",
                "verbose_name_plural": "سجلات تدقيق حوكمة الائتمان",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم العميل")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم الشركة إذا كان العميل شركة",
                        max_length=255,
                        verbose_name="اسم الشركة",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="اسم الشخص المسؤول أو مندوب التواصل في المؤسسة أو الشركة",
                        max_length=150,
                        null=True,
                        verbose_name="الشخص المسؤول / جهة الاتصال",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True,
                        help_text="رقم الهاتف الأساسي للتواصل",
                        max_length=20,
                        verbose_name="رقم الهاتف الأساسي",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="رقم هاتف إضافي للتواصل",
                        max_length=20,
                        verbose_name="رقم الهاتف الثانوي",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="مصر",
                        help_text="دولة إقامة العميل أو مقر المنشأة",
                        max_length=100,
                        verbose_name="الدولة",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="المدينة أو المحافظة التي يقع فيها العميل",
                        max_length=100,
                        verbose_name="المدينة / المحافظة",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود العميل"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الحد الائتماني",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="الرقم القومي المكون من 14 رقماً للأفراد وفقاً لمنظومة الضرائب المصرية",
                        max_length=14,
                        null=True,
                        verbose_name="الرقم القومي (للأفراد)",
                    ),
                ),
                (
                    "commercial_registry",
                    models.CharField(
                        blank=True,
                        help_text="رقم السجل التجاري للشركات والمؤسسات",
                        max_length=50,
                        null=True,
                        verbose_name="السجل التجاري",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "فرد"),
                            ("company", "شركة / منشأة"),
                            ("government", "جهة حكومية"),
                        ],
                        default="individual",
                        help_text="تصنيف الكيان القانوني: فرد (شخص طبيعي) أو شركة أو جهة حكومية",
                        max_length=20,
                        verbose_name="نوع العميل (الكيان القانوني)",
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(
                        default=False,
                        help_text="تمييز العميل كعميل ذو أولوية خاصة ومعاملة استثنائية",
                        verbose_name="عميل مميز (VIP)",
                    ),
                ),
                (
                    "last_contact_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="تاريخ آخر تواصل مع العميل",
                        null=True,
                        verbose_name="تاريخ آخر اتصال",
                    ),
                ),
                (
                    "contact_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("quarterly", "ربع سنوي"),
                            ("yearly", "سنوي"),
                        ],
                        help_text="معدل التواصل المطلوب مع العميل",
                        max_length=20,
                        verbose_name="تكرار الاتصال",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAllocationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_reference",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="مرجع التوزيع الفريد",
                    ),
                ),
                (
                    "source_document_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نوع المستند المصدر",
                    ),
                ),
                (
                    "source_document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند المصدر",
                    ),
                ),
                (
                    "target_document_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نوع المستند المستهدف",
                    ),
                ),
                (
                    "target_document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند المستهدف",
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_TO_INVOICE", "سداد فاتورة"),
                            ("CREDIT_NOTE_TO_INVOICE", "تسوية إشعار دائن"),
                            ("ADVANCE_TO_INVOICE", "تسوية دفعة مقدمة"),
                            ("REVERSAL", "عكس توزيع سداد"),
                        ],
                        default="PAYMENT_TO_INVOICE",
                        max_length=30,
                        verbose_name="نوع التوزيع",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المخصص بالعملة الأصلي",
                    ),
                ),
                (
                    "allocation_currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="عملة التوزيع"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي المخصص (EGP)",
                    ),
                ),
                (
                    "realized_fx_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="فروق عملة محققة (EGP)",
                    ),
                ),
                (
                    "allocation_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("RESERVED", "محتجز"),
                            ("APPLIED", "مطبق"),
                            ("REVERSED", "معكوس"),
                            ("FAILED", "تعثر"),
                        ],
                        default="APPLIED",
                        max_length=20,
                        verbose_name="حالة التوزيع",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التوزيع"
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="توقيع إثبات التوزيع SHA256",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
            ],
            options={
                "verbose_name": "تدقيق توزيعات سداد العملاء",
                "verbose_name_plural": "سجلات تدقيق توزيعات سداد العملاء",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCreditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="حد الائتمان المرخص",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="NET_30",
                        max_length=50,
                        verbose_name="شروط الدفع النصية",
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=0, verbose_name="أيام الإمهال التقديرية"
                    ),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("WARNING", "تحذير"),
                            ("ON_HOLD", "معلق"),
                            ("BLOCKED", "محظور"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="حالة الائتمان",
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض المخاطر"),
                            ("MEDIUM", "متوسط المخاطر"),
                            ("HIGH", "مرتفع المخاطر"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="تصنيف المخاطر",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ البدء"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="تاريخ المراجعة الائتمانية القادمة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف الائتمان والحوكمة للعميل",
                "verbose_name_plural": "ملفات الائتمان والحوكمة للعملاء",
            },
        ),
        migrations.CreateModel(
            name="CustomerCreditStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="الحالة السابقة"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="الحالة الجديدة"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="السبب / الملاحظات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التعديل"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة الائتمان",
                "verbose_name_plural": "سجلات حالة الائتمان",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ المعاملة",
                    ),
                ),
                (
                    "exchange_rate_snapshot",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="لقطة سعر الصرف",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأساسية (EGP)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="تاريخ الدفع")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "status",
                    models.CharField(
                        default="posted", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "allocated_currency_amount_cached",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المبلغ المخصص المخبأ بعملة الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدفوعات العميل",
                "verbose_name_plural": "مدفوعات العملاء",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم شرط الدفع"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود الشرط"
                    ),
                ),
                (
                    "days",
                    models.IntegerField(default=30, verbose_name="عدد أيام الإمهال"),
                ),
                (
                    "is_credit",
                    models.BooleanField(
                        default=True, verbose_name="يعتبر بيعاً ائتمانياً"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="نسبة خصم التعجيل %",
                    ),
                ),
                (
                    "discount_days",
                    models.IntegerField(default=0, verbose_name="أيام خصم التعجيل"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "شرط دفع",
                "verbose_name_plural": "شروط الدفع",
                "ordering": ["days", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "فاتورة مبيعات"),
                            ("CREDIT_NOTE", "إشعار دائن"),
                            ("PAYMENT", "تحصيل دائن"),
                            ("ADVANCE", "دفعة مقدمة"),
                            ("WRITE_OFF", "إعدام دين"),
                        ],
                        max_length=20,
                        verbose_name="نوع المعاملة",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=50, verbose_name="رقم المعاملة"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="نوع المرجع",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="معرف المرجع",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأجنبية",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الوظيفية (EGP)",
                    ),
                ),
                (
                    "open_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المفتوح غير المسدد (EGP)",
                    ),
                ),
                (
                    "open_amount_functional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح الوظيفي (EGP)",
                    ),
                ),
                (
                    "open_amount_foreign",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح غير المسدد (الأصلي)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "مفتوح"),
                            ("PARTIAL", "مسدد جزئياً"),
                            ("CLOSED", "مغلق"),
                        ],
                        default="OPEN",
                        max_length=15,
                        verbose_name="حالة البند",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subledger_transactions",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة أستاذ العملاء الفرعي",
                "verbose_name_plural": "معاملات أستاذ العملاء الفرعي",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
    ]
