# Generated by Django 4.2.23 on 2025-10-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف'),
        ),
    ]
