# Generated by Django 4.2.26 on 2026-07-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_order", "__first__"),
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
    ]
