# Generated by Django 4.2.26 on 2026-08-20 16:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_order", "0001_initial"),
        ("client", "0002_initial"),
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_payments_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.chartofaccounts",
                verbose_name="الخزينة / البنك المصدر",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="customercreditprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="customercreditprofile",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_profile",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="customercreditprofile",
            name="default_payment_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.paymentterm",
                verbose_name="شروط الدفع المعيارية",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation_audits",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="invoice_transaction",
            field=models.ForeignKey(
                db_column="target_transaction_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_allocations",
                to="client.customertransaction",
                verbose_name="معاملة الفاتورة المستهدفة",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="payment_transaction",
            field=models.ForeignKey(
                db_column="source_transaction_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="client.customertransaction",
                verbose_name="معاملة التحصيل/الإشعار",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="reversed_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="client.customerallocationaudit",
                verbose_name="سجل التدقيق المعكوس",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="العملة الافتراضية المعتمدة لفتح فواتير ومعاملات هذا العميل تلقائياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers_default_currency",
                to="financial.currency",
                verbose_name="العملة الافتراضية",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="financial_account",
            field=models.OneToOneField(
                blank=True,
                help_text="الحساب المحاسبي المرتبط بهذا العميل في دليل الحسابات",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer",
                to="financial.chartofaccounts",
                verbose_name="الحساب المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="creditauditlog",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_audit_logs",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="creditauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                condition=models.Q(("status", "OPEN")),
                fields=["customer", "due_date"],
                name="idx_cust_open_ar_partial",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerpayment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("allocated_currency_amount_cached__lte", models.F("amount")),
                    ("allocated_currency_amount_cached__gte", Decimal("0.00")),
                ),
                name="chk_customer_payment_alloc_valid_range",
            ),
        ),
        migrations.AddIndex(
            model_name="customerallocationaudit",
            index=models.Index(
                fields=["customer", "allocation_date"],
                name="client_cust_custome_56c742_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerallocationaudit",
            index=models.Index(
                fields=["allocation_reference", "created_at"],
                name="idx_cust_alloc_corr_time",
            ),
        ),
    ]
