# Generated by Django 4.2.26 on 2026-08-21 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customercreditstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "سجل حالة الائتمان",
                "verbose_name_plural": "سجلات حالة الائتمان",
            },
        ),
    ]
