# Generated by Django 4.2.26 on 2026-08-04 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0014_currency_journalentryline_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0003_customerpayment_work_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "فاتورة مبيعات"),
                            ("CREDIT_NOTE", "إشعار دائن"),
                            ("PAYMENT", "تحصيل دائن"),
                            ("ADVANCE", "دفعة مقدمة"),
                            ("WRITE_OFF", "إعدام دين"),
                        ],
                        max_length=20,
                        verbose_name="نوع المعاملة",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=50, verbose_name="رقم المعاملة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأجنبية",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الوظيفية (EGP)",
                    ),
                ),
                (
                    "open_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المفتوح غير المسدد (EGP)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "مفتوح"),
                            ("PARTIAL", "مسدد جزئياً"),
                            ("CLOSED", "مغلق"),
                        ],
                        default="OPEN",
                        max_length=15,
                        verbose_name="حالة البند",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="open_item_transactions",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة عميل مفتوحة",
                "verbose_name_plural": "معاملات العملاء المفتوحة",
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAllocationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المخصص (EGP)",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التوزيع"
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="توقيع إثبات التوزيع SHA256",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_audits",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "invoice_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations_to",
                        to="client.customertransaction",
                        verbose_name="الفاتورة المسددة",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations_from",
                        to="client.customertransaction",
                        verbose_name="معاملة السداد/الإشعار",
                    ),
                ),
            ],
            options={
                "verbose_name": "تدقيق توزيع مبالغ العميل",
                "verbose_name_plural": "سجلات تدقيق توزيعات العملاء",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                fields=["customer", "status", "due_date"],
                name="client_cust_custome_2f8824_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="client_cust_transac_9e10a8_idx",
            ),
        ),
    ]
