# Generated by Django 4.2.26 on 2026-08-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_customertransaction_customerallocationaudit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertransaction",
            name="open_amount_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="المبلغ الأجنبي المفتوح",
            ),
        ),
        migrations.AddField(
            model_name="customertransaction",
            name="open_amount_functional",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="المبلغ الوظيفي المفتوح غير المسدد (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="customertransaction",
            name="reference_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="معرف المرجع"
            ),
        ),
        migrations.AddField(
            model_name="customertransaction",
            name="reference_type",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="نوع المرجع"
            ),
        ),
    ]
