# Generated by Django 4.2.26 on 2026-08-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_missing_columns(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)

        if "client_customer" in table_names:
            customer_cols = [c.name for c in connection.introspection.get_table_description(cursor, "client_customer")]
            if "commercial_registry" not in customer_cols:
                cursor.execute("ALTER TABLE client_customer ADD COLUMN commercial_registry VARCHAR(50) NULL")
            if "national_id" not in customer_cols:
                cursor.execute("ALTER TABLE client_customer ADD COLUMN national_id VARCHAR(14) NULL")

        if "client_customercreditstatushistory" in table_names:
            history_cols = [c.name for c in connection.introspection.get_table_description(cursor, "client_customercreditstatushistory")]
            if "created_by_id" not in history_cols and "created_by" not in history_cols:
                cursor.execute("ALTER TABLE client_customercreditstatushistory ADD COLUMN created_by_id BIGINT NULL")
            if "customer_id" not in history_cols and "customer" not in history_cols:
                cursor.execute("ALTER TABLE client_customercreditstatushistory ADD COLUMN customer_id BIGINT NULL")
        else:
            cursor.execute("""
                CREATE TABLE client_customercreditstatushistory (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    old_status VARCHAR(20) NOT NULL,
                    new_status VARCHAR(20) NOT NULL,
                    reason LONGTEXT NULL,
                    created_at DATETIME(6) NOT NULL,
                    created_by_id BIGINT NULL,
                    customer_id BIGINT NULL
                )
            """)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0004_alter_customercreditstatushistory_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="customer",
                    name="commercial_registry",
                    field=models.CharField(
                        blank=True,
                        help_text="رقم السجل التجاري للشركات والمؤسسات",
                        max_length=50,
                        null=True,
                        verbose_name="السجل التجاري",
                    ),
                ),
                migrations.AddField(
                    model_name="customer",
                    name="national_id",
                    field=models.CharField(
                        blank=True,
                        help_text="الرقم القومي المكون من 14 رقماً للأفراد وفقاً لمنظومة الضرائب المصرية",
                        max_length=14,
                        null=True,
                        verbose_name="الرقم القومي (للأفراد)",
                    ),
                ),
                migrations.AddField(
                    model_name="customercreditstatushistory",
                    name="created_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_status_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                migrations.AddField(
                    model_name="customercreditstatushistory",
                    name="customer",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_status_histories",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_missing_columns, reverse_code=migrations.RunPython.noop),
            ]
        ),
    ]
