# Generated by Django 4.2.26 on 2026-08-04 14:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0005_customertransaction_open_amount_foreign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCreditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="حد الائتمان المرخص",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        default="NET_30", max_length=50, verbose_name="شروط الدفع"
                    ),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("WARNING", "تحذير"),
                            ("ON_HOLD", "معلق"),
                            ("BLOCKED", "محظور"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="حالة الائتمان",
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض المخاطر"),
                            ("MEDIUM", "متوسط المخاطر"),
                            ("HIGH", "مرتفع المخاطر"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="تصنيف المخاطر",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ البدء"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_profile",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف ائتمان العميل",
                "verbose_name_plural": "ملفات ائتمان العملاء",
            },
        ),
        migrations.CreateModel(
            name="CreditAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="الحالة السابقة"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="الحالة الجديدة"),
                ),
                ("reason", models.TextField(verbose_name="السبب / الملاحظات")),
                (
                    "related_document",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="المستند المرتبط",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="التاريخ والوقت"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_audit_logs",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق ائتمان العميل",
                "verbose_name_plural": "سجلات تدقيق ائتمان العملاء",
                "ordering": ["-timestamp"],
            },
        ),
    ]
