# Generated by Django 4.2.26 on 2026-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0005_customer_commercial_registry_customer_national_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_vip",
            field=models.BooleanField(
                default=False,
                help_text="تمييز العميل كعميل ذو أولوية خاصة ومعاملة استثنائية",
                verbose_name="عميل مميز (VIP)",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("individual", "فرد"),
                    ("company", "شركة"),
                    ("government", "جهة حكومية"),
                ],
                default="individual",
                help_text="تصنيف الكيان القانوني: فرد (شخص طبيعي) أو شركة أو جهة حكومية",
                max_length=20,
                verbose_name="نوع العميل (الكيان القانوني)",
            ),
        ),
    ]
