# Generated by Django 4.2.26 on 2026-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_customer_is_vip_alter_customer_client_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="اسم الشخص المسؤول أو مندوب التواصل في المؤسسة أو الشركة",
                max_length=150,
                null=True,
                verbose_name="الشخص المسؤول / جهة الاتصال",
            ),
        ),
    ]
