# Generated by Django 4.2.26 on 2026-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_customer_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True,
                default="مصر",
                help_text="دولة إقامة العميل أو مقر المنشأة",
                max_length=100,
                verbose_name="الدولة",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="المدينة أو المحافظة التي يقع فيها العميل",
                max_length=100,
                verbose_name="المدينة / المحافظة",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("individual", "فرد"),
                    ("company", "شركة / منشأة"),
                    ("government", "جهة حكومية"),
                ],
                default="individual",
                help_text="تصنيف الكيان القانوني: فرد (شخص طبيعي) أو شركة أو جهة حكومية",
                max_length=20,
                verbose_name="نوع العميل (الكيان القانوني)",
            ),
        ),
    ]
