# Generated by Django 4.2.26 on 2026-08-04 14:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0007_paymentterm_customercreditprofile_grace_period_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerallocationaudit",
            name="allocation_currency",
            field=models.CharField(
                default="EGP", max_length=3, verbose_name="عملة التوزيع"
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="allocation_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="مرجع التوزيع"
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="allocation_status",
            field=models.CharField(
                choices=[
                    ("CREATED", "منشأ"),
                    ("APPLIED", "مطبق"),
                    ("REVERSED", "معكوس"),
                ],
                default="APPLIED",
                max_length=20,
                verbose_name="حالة التوزيع",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="allocation_type",
            field=models.CharField(
                choices=[
                    ("PAYMENT_TO_INVOICE", "سداد فاتورة"),
                    ("ADVANCE_TO_INVOICE", "تطبيق دفعة مقدمة"),
                    ("CREDIT_NOTE_TO_INVOICE", "تسوية إشعار دائن"),
                    ("REFUND_ALLOCATION", "توزيع رد مبلغ"),
                    ("WRITE_OFF_ALLOCATION", "توزيع شطب ديون"),
                ],
                default="PAYMENT_TO_INVOICE",
                max_length=30,
                verbose_name="نوع التوزيع",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="functional_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ الوظيفي المخصص (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="customerallocationaudit",
            name="realized_fx_difference",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="فروق عملة محققة (EGP)",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                verbose_name="المبلغ المخصص بالعملة الأصلي",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="invoice_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations_to",
                to="client.customertransaction",
                verbose_name="معاملة الهدف (الفاتورة المسددة)",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations_from",
                to="client.customertransaction",
                verbose_name="معاملة المصدر (سداد/دفعة/إشعار)",
            ),
        ),
    ]
