# Generated by Django 4.2.26 on 2026-08-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0009_customerallocationaudit_reversed_audit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerallocationaudit",
            options={
                "ordering": ["-allocation_date", "-created_at"],
                "verbose_name": "تدقيق توزيعات سداد العملاء",
                "verbose_name_plural": "سجلات تدقيق توزيعات سداد العملاء",
            },
        ),
        migrations.AddIndex(
            model_name="customerallocationaudit",
            index=models.Index(
                fields=["customer", "allocation_date"],
                name="client_cust_custome_56c742_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customertransaction",
            index=models.Index(
                condition=models.Q(("status", "OPEN")),
                fields=["customer", "due_date"],
                name="idx_cust_open_ar_partial",
            ),
        ),
    ]
