# Generated by Django 4.2.26 on 2026-08-23 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0007_salesorder_down_payment_override_and_more"),
        ("financial", "0009_alter_journalentry_entry_type_and_more"),
        ("client", "0009_customer_default_price_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.costcenter",
                verbose_name="مركز التكلفة",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="down_payments",
                to="sale.salesorder",
                verbose_name="أمر البيع المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="salesman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_payments_assisted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
    ]
