# Generated by Django 4.2.26 on 2026-08-05 04:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0021_add_fiscalyear_timestamps"),
        ("client", "0010_alter_customerallocationaudit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditauditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "تدقيق حوكمة الائتمان",
                "verbose_name_plural": "سجلات تدقيق حوكمة الائتمان",
            },
        ),
        migrations.AlterModelOptions(
            name="customercreditprofile",
            options={
                "verbose_name": "ملف الائتمان والحوكمة للعميل",
                "verbose_name_plural": "ملفات الائتمان والحوكمة للعملاء",
            },
        ),
        migrations.AlterModelOptions(
            name="customercreditstatushistory",
            options={
                "managed": False,
                "ordering": ["-created_at"],
                "verbose_name": "سجل حالة الائتمان",
                "verbose_name_plural": "سجلات حالة الائتمان",
            },
        ),
        migrations.AlterModelOptions(
            name="customertransaction",
            options={
                "ordering": ["-issue_date", "-created_at"],
                "verbose_name": "معاملة أستاذ العملاء الفرعي",
                "verbose_name_plural": "معاملات أستاذ العملاء الفرعي",
            },
        ),

        migrations.AlterField(
            model_name="customerallocationaudit",
            name="allocation_reference",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=100,
                unique=True,
                verbose_name="مرجع التوزيع الفريد",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="allocation_status",
            field=models.CharField(
                choices=[("APPLIED", "مطبق"), ("REVERSED", "معكوس")],
                default="APPLIED",
                max_length=20,
                verbose_name="حالة التوزيع",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="allocation_type",
            field=models.CharField(
                choices=[
                    ("PAYMENT_TO_INVOICE", "سداد فاتورة"),
                    ("CREDIT_NOTE_TO_INVOICE", "تسوية إشعار دائن"),
                    ("ADVANCE_TO_INVOICE", "تسوية دفعة مقدمة"),
                    ("REVERSAL", "عكس توزيع سداد"),
                ],
                default="PAYMENT_TO_INVOICE",
                max_length=30,
                verbose_name="نوع التوزيع",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="invoice_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_allocations",
                to="client.customertransaction",
                verbose_name="معاملة الفاتورة المستهدفة",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="client.customertransaction",
                verbose_name="معاملة التحصيل/الإشعار",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="source_document_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="رقم المستند المصدر"
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="source_document_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نوع المستند المصدر"
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="target_document_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="رقم المستند المستهدف",
            ),
        ),
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="target_document_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="نوع المستند المستهدف",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subledger_transactions",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="قيد الأستاذ مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="open_amount_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ المفتوح غير المسدد (الأصلي)",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="open_amount_functional",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ المفتوح الوظيفي (EGP)",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="reference_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="معرف المرجع",
            ),
        ),
        migrations.AlterField(
            model_name="customertransaction",
            name="reference_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="نوع المرجع",
            ),
        ),
    ]
