# Generated by Django 4.2.26 on 2026-08-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0011_alter_creditauditlog_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerallocationaudit",
            index=models.Index(
                fields=["allocation_reference", "created_at"],
                name="idx_cust_alloc_corr_time",
            ),
        ),
    ]
