# Generated by Django 4.2.26 on 2026-08-05 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0012_remove_customertransaction_client_cust_custome_2f8824_idx_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="customertransaction",
                    name="client_cust_custome_2f8824_idx",
                ),
                migrations.RemoveIndex(
                    model_name="customertransaction",
                    name="client_cust_transac_9e10a8_idx",
                ),
            ],
            database_operations=[],
        ),
    ]

