# Generated by Django 4.2.26 on 2026-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0013_remove_customertransaction_client_cust_custome_2f8824_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="status",
            field=models.CharField(
                default="posted", max_length=20, verbose_name="الحالة"
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
    ]
