# Generated by Django 4.2.26 on 2026-08-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0033_chartofaccounts_opening_balance_foreign_and_more"),
        ("client", "0015_alter_customerallocationaudit_invoice_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="العملة الافتراضية المعتمدة لفتح فواتير ومعاملات هذا العميل تلقائياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers_default_currency",
                to="financial.currency",
                verbose_name="العملة الافتراضية",
            ),
        ),
    ]
