# Generated by Django 4.2.26 on 2026-08-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0043_partneradvancesettlement"),
        (
            "client",
            "0017_customerpayment_base_amount_customerpayment_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.chartofaccounts",
                verbose_name="الخزينة / البنك المصدر",
            ),
        ),
    ]
