# Generated by Django 4.2.26 on 2026-08-09 11:46

from decimal import Decimal
from django.db import migrations, models


def populate_historical_allocations(apps, schema_editor):
    CustomerPayment = apps.get_model("client", "CustomerPayment")
    SalePayment = apps.get_model("sale", "SalePayment")
    CustomerAllocationAudit = apps.get_model("client", "CustomerAllocationAudit")
    from django.db.models import Sum

    for cp in CustomerPayment.objects.all():
        sp_sum = SalePayment.objects.filter(customer_payment_id=cp.id, status="posted").aggregate(s=Sum("amount"))["s"] or Decimal("0.00")
        aud_sum = CustomerAllocationAudit.objects.filter(source_document_number=f"PAY-{cp.id}", allocation_status="APPLIED").aggregate(s=Sum("allocated_amount"))["s"] or Decimal("0.00")
        tot = max(sp_sum, aud_sum)
        if tot > Decimal("0.00"):
            cp.allocated_currency_amount_cached = min(cp.amount, tot)
            cp.save(update_fields=["allocated_currency_amount_cached"])


def reverse_historical_allocations(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0018_customerpayment_financial_account"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpayment",
            name="allocated_currency_amount_cached",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المبلغ المخصص المخبأ بعملة الدفعة",
            ),
        ),
        migrations.RunPython(populate_historical_allocations, reverse_code=reverse_historical_allocations),
        migrations.AddConstraint(
            model_name="customerpayment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("allocated_currency_amount_cached__lte", models.F("amount")),
                    ("allocated_currency_amount_cached__gte", Decimal("0.00")),
                ),
                name="chk_customer_payment_alloc_valid_range",
            ),
        ),
    ]

