# Generated by Django 4.2.26 on 2026-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0019_customerpayment_allocated_currency_amount_cached_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerallocationaudit",
            name="allocation_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("RESERVED", "محتجز"),
                    ("APPLIED", "مطبق"),
                    ("REVERSED", "معكوس"),
                    ("FAILED", "تعثر"),
                ],
                default="APPLIED",
                max_length=20,
                verbose_name="حالة التوزيع",
            ),
        ),
    ]
