# Generated by Django 4.2.26 on 2026-08-20 16:35

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="active",
                        max_length=15,
                        verbose_name="الحالة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("metric_value", models.FloatField(verbose_name="قيمة المقياس")),
                ("threshold_value", models.FloatField(verbose_name="قيمة العتبة")),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإقرار"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الحل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تنبيه",
                "verbose_name_plural": "التنبيهات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القاعدة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("error_rate", "Error Rate"),
                            ("response_time", "Response Time"),
                            ("memory_usage", "Memory Usage"),
                            ("cpu_usage", "CPU Usage"),
                            ("disk_usage", "Disk Usage"),
                            ("failed_logins", "Failed Logins"),
                            ("concurrent_users", "Concurrent Users"),
                            ("database_connections", "Database Connections"),
                        ],
                        max_length=30,
                        verbose_name="نوع المقياس",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("eq", "Equal"),
                            ("ne", "Not Equal"),
                        ],
                        max_length=5,
                        verbose_name="المشغل",
                    ),
                ),
                ("threshold_value", models.FloatField(verbose_name="قيمة العتبة")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        verbose_name="مستوى الخطورة",
                    ),
                ),
                (
                    "time_window_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="نافذة الوقت (دقائق)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "email_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses",
                        verbose_name="مستقبلو البريد الإلكتروني",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "قاعدة التنبيه",
                "verbose_name_plural": "قواعد التنبيهات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف الأصلي"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="رقم الإصدار"),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="النسخة الأحدث"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ الحذف الناعم",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
            ],
            options={
                "verbose_name": "مرفق مستند",
                "verbose_name_plural": "مرفقات المستندات",
            },
        ),
        migrations.CreateModel(
            name="AttachmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "رفع"),
                            ("VIEWED", "عرض"),
                            ("DOWNLOADED", "تنزيل"),
                            ("REPLACED", "استبدال / تحديث إصدار"),
                            ("DELETED", "حذف ناعم"),
                            ("RESTORED", "استعادة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "user_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="لقطة اسم المستخدم",
                    ),
                ),
                (
                    "user_email_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="لقطة بريد المستخدم",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق مرفق",
                "verbose_name_plural": "سجلات تدقيق المرفقات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="كود الفئة",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الفئة")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "max_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="الحد الأقصى لحجم الملف (ميجابايت)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="pdf,png,jpg,jpeg,docx,xlsx",
                        max_length=255,
                        verbose_name="الامتدادات المسموح بها",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="مدة الاستبقاء القانونية (أيام)"
                    ),
                ),
                (
                    "requires_integrity_check",
                    models.BooleanField(
                        default=True, verbose_name="يتطلب فحص السلامة (SHA-256)"
                    ),
                ),
                (
                    "permission_required",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="الصلاحية المطلوبة للوصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة مستندات",
                "verbose_name_plural": "فئات المستندات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentOrphanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOUND", "مكتشف كأيتام"),
                            ("REVIEWED", "تمت المراجعة"),
                            ("MARKED_FOR_DELETE", "مُعلم للحذف"),
                            ("DELETED", "تم الحذف النهائي"),
                        ],
                        default="FOUND",
                        max_length=30,
                        verbose_name="حالة المراجعة",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="توقيت الاكتشاف"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف النهائي"
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة مستند يتيتم",
                "verbose_name_plural": "مراجعات المستندات الأيتام",
            },
        ),
        migrations.CreateModel(
            name="BackupFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("database", "Database Dump"),
                            ("media", "Media Archive"),
                            ("config", "Configuration Files"),
                            ("logs", "Log Files"),
                            ("other", "Other Files"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("size_bytes", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("is_compressed", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ملف النسخة الاحتياطية",
                "verbose_name_plural": "ملفات النسخ الاحتياطية",
                "db_table": "core_backup_file",
                "ordering": ["file_type", "filename"],
            },
        ),
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("database", "Database Only"),
                            ("media", "Media Files Only"),
                            ("config", "Configuration Only"),
                            ("incremental", "Incremental Backup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("verified", "Verified"),
                            ("corrupted", "Corrupted"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Storage"),
                            ("s3", "Amazon S3"),
                            ("ftp", "FTP Server"),
                            ("sftp", "SFTP Server"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                ("file_count", models.IntegerField(default=0)),
                ("compression_ratio", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("verified_files", models.IntegerField(default=0)),
                ("failed_files", models.IntegerField(default=0)),
                ("verification_errors", models.TextField(blank=True)),
                ("remote_path", models.CharField(blank=True, max_length=500)),
                ("remote_upload_status", models.CharField(blank=True, max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "سجل النسخة الاحتياطية",
                "verbose_name_plural": "سجلات النسخ الاحتياطية",
                "db_table": "core_backup_record",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                ("value", models.CharField(max_length=100, verbose_name="القيمة")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="اللون"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("yearly", "سنوي"),
                            ("current", "حالي"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="الفترة",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sales", "مبيعات"),
                            ("purchases", "مشتريات"),
                            ("inventory", "مخزون"),
                            ("finance", "مالي"),
                            ("customers", "عملاء"),
                            ("suppliers", "موردين"),
                            ("users", "مستخدمين"),
                            ("invoices", "فواتير"),
                        ],
                        default="sales",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "change_value",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="قيمة التغيير",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("increase", "زيادة"),
                            ("decrease", "نقصان"),
                            ("no_change", "لا تغيير"),
                        ],
                        default="no_change",
                        max_length=20,
                        verbose_name="نوع التغيير",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إحصائية لوحة التحكم",
                "verbose_name_plural": "إحصائيات لوحة التحكم",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="DataClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                (
                    "classification_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requires_encryption", models.BooleanField(default=False)),
                ("requires_anonymization", models.BooleanField(default=False)),
                ("retention_days", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تصنيف البيانات",
                "verbose_name_plural": "تصنيفات البيانات",
                "db_table": "core_data_classification",
                "ordering": ["model_name", "field_name"],
            },
        ),
        migrations.CreateModel(
            name="DataProtectionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("backup_created", "Backup Created"),
                            ("backup_verified", "Backup Verified"),
                            ("backup_restored", "Backup Restored"),
                            ("data_encrypted", "Data Encrypted"),
                            ("data_decrypted", "Data Decrypted"),
                            ("data_anonymized", "Data Anonymized"),
                            ("data_deleted", "Data Deleted"),
                            ("key_rotated", "Key Rotated"),
                            ("policy_applied", "Policy Applied"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "سجل تدقيق حماية البيانات",
                "verbose_name_plural": "سجلات تدقيق حماية البيانات",
                "db_table": "core_data_protection_audit",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("records_found", models.IntegerField(default=0)),
                ("records_deleted", models.IntegerField(default=0)),
                ("records_archived", models.IntegerField(default=0)),
                ("records_anonymized", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("errors", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "تنفيذ سياسة الاحتفاظ",
                "verbose_name_plural": "تنفيذات سياسات الاحتفاظ",
                "db_table": "core_data_retention_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("model_name", models.CharField(max_length=100)),
                ("retention_days", models.IntegerField()),
                ("archive_before_delete", models.BooleanField(default=True)),
                ("anonymize_before_delete", models.BooleanField(default=False)),
                ("cascade_delete", models.BooleanField(default=False)),
                ("notification_days", models.IntegerField(default=30)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("exclude_conditions", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "سياسة الاحتفاظ بالبيانات",
                "verbose_name_plural": "سياسات الاحتفاظ بالبيانات",
                "db_table": "core_data_retention_policy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="نوع الحدث"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="نوع المستند"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند الناتج",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        default="DEFAULT", max_length=50, verbose_name="كود الشركة"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="USER", max_length=20, verbose_name="مصدر الطلب"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="تاريخ وتوقيت الحدث",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="السبب / الملاحظات"
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القيمة القديمة",
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القيمة الجديدة",
                    ),
                ),
                (
                    "prefix_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="لقطة البادئة",
                    ),
                ),
                (
                    "padding_snapshot",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="لقطة الطول"
                    ),
                ),
                (
                    "year_snapshot",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="لقطة السنة"
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الرقم التسلسلي المجرد"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق الترقيم",
                "verbose_name_plural": "سجلات تدقيق الترقيم",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        db_index=True,
                        default="DEFAULT",
                        max_length=50,
                        verbose_name="كود الشركة",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="نوع المستند"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="السنة التسلسلية"
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="آخر رقم تسلسلي"
                    ),
                ),
                (
                    "last_reserved_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاريخ آخر حجز/توليد"
                    ),
                ),
            ],
            options={
                "verbose_name": "عداد ترقيم مستند",
                "verbose_name_plural": "عدادات ترقيم المستندات",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        db_index=True,
                        default="DEFAULT",
                        max_length=50,
                        verbose_name="كود الشركة",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="نوع المستند"
                    ),
                ),
                ("prefix", models.CharField(max_length=20, verbose_name="البادئة")),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=4, verbose_name="طول الخانة التسلسلية"
                    ),
                ),
                (
                    "numbering_basis",
                    models.CharField(
                        default="POSTING_DATE",
                        max_length=20,
                        verbose_name="أساس السنة التسلسلية",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="إصدار القاعدة"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="تقفل القاعدة تلقائياً بعد إنتاج أول رقم لحماية تاريخ السجلات",
                        verbose_name="مقفلة لإنشاء مستندات حقيقية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="ACTIVE", max_length=20, verbose_name="الحالة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قاعدة ترقيم مستند",
                "verbose_name_plural": "قواعد ترقيم المستندات",
            },
        ),
        migrations.CreateModel(
            name="DraftAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "draft_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="رمز المسودة الموقت",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="مفتاح الجلسة"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف الأصلي"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="تاريخ الانتهاء"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة مرفق مؤقتة",
                "verbose_name_plural": "مسودات المرفقات المؤقتة",
            },
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("key_hash", models.CharField(max_length=64)),
                ("algorithm", models.CharField(default="fernet", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("rotated", "Rotated"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("encryption_count", models.IntegerField(default=0)),
                ("decryption_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("rotation_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "مفتاح التشفير",
                "verbose_name_plural": "مفاتيح التشفير",
                "db_table": "core_encryption_key",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="بصمة الملف (SHA-256)",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.attachment_upload_path,
                        verbose_name="الملف الفيزيائي",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="حجم الملف (بايت)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="نوع MIME"),
                ),
                (
                    "company_id",
                    models.PositiveIntegerField(
                        db_index=True, default=1, verbose_name="معرف الشركة"
                    ),
                ),
                (
                    "reference_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عداد الإشارات المرجعية الذري"
                    ),
                ),
                (
                    "security_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الفحص"),
                            ("CLEAN", "سليم"),
                            ("BLOCKED", "محظور"),
                            ("QUARANTINED", "في الحجر الصحي"),
                        ],
                        default="CLEAN",
                        max_length=20,
                        verbose_name="حالة الأمان",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "كتلة تخزين فيزيائية",
                "verbose_name_plural": "كتل التخزين الفيزيائية",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "معلومات"),
                            ("success", "نجاح"),
                            ("warning", "تحذير"),
                            ("danger", "خطر"),
                            ("inventory_alert", "تنبيه مخزون"),
                            ("product_expiry", "انتهاء صلاحية منتج"),
                            ("stock_transfer", "نقل مخزون"),
                            ("new_sale", "مبيعات جديدة"),
                            ("sale_payment", "دفعة مبيعات"),
                            ("sale_return", "إرجاع مبيعات"),
                            ("new_purchase", "مشتريات جديدة"),
                            ("purchase_payment", "دفعة مشتريات"),
                            ("purchase_return", "إرجاع مشتريات"),
                            ("payment_received", "دفعة مستلمة"),
                            ("payment_made", "دفعة مسددة"),
                            ("new_invoice", "فاتورة جديدة"),
                            ("hr_leave_request", "طلب إجازة"),
                            ("hr_attendance", "حضور وانصراف"),
                            ("hr_payroll", "رواتب"),
                            ("hr_contract", "عقد موظف"),
                            ("return_request", "طلب إرجاع"),
                            ("system_alert", "تنبيه نظام"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="الرابط المباشر للصفحة المتعلقة بالإشعار",
                        max_length=255,
                        null=True,
                        verbose_name="رابط",
                    ),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True,
                        help_text="مثل: Sale, Purchase, Product",
                        max_length=50,
                        null=True,
                        verbose_name="النموذج المرتبط",
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن المرتبط"
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_inventory_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيهات المخزون المنخفض ونفاذ المنتجات",
                        verbose_name="تنبيهات المخزون",
                    ),
                ),
                (
                    "enable_invoice_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="فواتير المبيعات والمشتريات الجديدة",
                        verbose_name="إشعارات الفواتير",
                    ),
                ),
                (
                    "enable_payment_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="الدفعات المستلمة والمسددة",
                        verbose_name="إشعارات الدفعات",
                    ),
                ),
                (
                    "enable_return_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="طلبات إرجاع المبيعات والمشتريات",
                        verbose_name="إشعارات الإرجاع",
                    ),
                ),
                (
                    "enable_customer_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="عملاء جدد وتحديثات العملاء",
                        verbose_name="إشعارات العملاء",
                    ),
                ),
                (
                    "enable_product_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="منتجات جديدة وتحديثات المنتجات",
                        verbose_name="إشعارات المنتجات",
                    ),
                ),
                (
                    "enable_user_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="مستخدمين جدد وتحديثات المستخدمين",
                        verbose_name="إشعارات المستخدمين",
                    ),
                ),
                (
                    "enable_system_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="إشعارات النظام والتحديثات المهمة",
                        verbose_name="إشعارات النظام",
                    ),
                ),
                (
                    "notify_in_app",
                    models.BooleanField(
                        default=True,
                        help_text="عرض الإشعارات داخل النظام",
                        verbose_name="داخل النظام",
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        default=False,
                        help_text="إرسال إشعارات عبر البريد الإلكتروني",
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "email_for_notifications",
                    models.EmailField(
                        blank=True,
                        help_text="البريد الإلكتروني المستخدم لإرسال الإشعارات",
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني للإشعارات",
                    ),
                ),
                (
                    "notify_sms",
                    models.BooleanField(
                        default=False,
                        help_text="إرسال إشعارات عبر رسائل SMS",
                        verbose_name="رسائل SMS",
                    ),
                ),
                (
                    "phone_for_notifications",
                    models.CharField(
                        blank=True,
                        help_text="رقم الهاتف المستخدم لإرسال الإشعارات",
                        max_length=20,
                        null=True,
                        verbose_name="رقم الهاتف للإشعارات",
                    ),
                ),
                (
                    "notify_whatsapp",
                    models.BooleanField(
                        default=False,
                        help_text="إرسال إشعارات للعملاء عبر واتساب",
                        verbose_name="واتساب",
                    ),
                ),
                (
                    "inventory_check_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "كل ساعة"),
                            ("3hours", "كل 3 ساعات"),
                            ("6hours", "كل 6 ساعات"),
                            ("daily", "يومياً"),
                        ],
                        default="6hours",
                        max_length=20,
                        verbose_name="تكرار فحص المخزون",
                    ),
                ),
                (
                    "invoice_check_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "يومياً"),
                            ("3days", "كل 3 أيام"),
                            ("weekly", "أسبوعياً"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="تكرار فحص الفواتير",
                    ),
                ),
                (
                    "send_daily_summary",
                    models.BooleanField(
                        default=False,
                        help_text="إرسال ملخص يومي بجميع الإشعارات",
                        verbose_name="إرسال ملخص يومي",
                    ),
                ),
                (
                    "daily_summary_time",
                    models.TimeField(
                        default="09:00",
                        help_text="الوقت المفضل لإرسال الملخص اليومي",
                        verbose_name="وقت الملخص اليومي",
                    ),
                ),
                (
                    "alert_on_minimum_stock",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيه عند وصول المخزون للحد الأدنى",
                        verbose_name="تنبيه عند الحد الأدنى",
                    ),
                ),
                (
                    "alert_on_half_minimum",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيه عند وصول المخزون لـ 50% من الحد الأدنى",
                        verbose_name="تنبيه عند 50% من الحد الأدنى",
                    ),
                ),
                (
                    "alert_on_out_of_stock",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيه عند نفاذ المخزون تماماً",
                        verbose_name="تنبيه عند نفاذ المخزون",
                    ),
                ),
                (
                    "invoice_due_days_before",
                    models.IntegerField(
                        default=3,
                        help_text="عدد الأيام قبل استحقاق الفاتورة للتنبيه",
                        verbose_name="التنبيه قبل الاستحقاق بـ (أيام)",
                    ),
                ),
                (
                    "alert_on_invoice_due",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيه عند استحقاق الفاتورة",
                        verbose_name="تنبيه عند الاستحقاق",
                    ),
                ),
                (
                    "alert_on_invoice_overdue",
                    models.BooleanField(
                        default=True,
                        help_text="تنبيه بعد تأخر سداد الفاتورة",
                        verbose_name="تنبيه بعد التأخير",
                    ),
                ),
                (
                    "invoice_overdue_days_after",
                    models.IntegerField(
                        default=1,
                        help_text="عدد الأيام بعد التأخير للتنبيه",
                        verbose_name="التنبيه بعد التأخير بـ (أيام)",
                    ),
                ),
                (
                    "enable_do_not_disturb",
                    models.BooleanField(
                        default=False,
                        help_text="عدم إرسال إشعارات في أوقات محددة",
                        verbose_name="تفعيل عدم الإزعاج",
                    ),
                ),
                (
                    "do_not_disturb_start",
                    models.TimeField(
                        blank=True,
                        default="22:00",
                        help_text="وقت بداية فترة عدم الإزعاج",
                        null=True,
                        verbose_name="بداية عدم الإزعاج",
                    ),
                ),
                (
                    "do_not_disturb_end",
                    models.TimeField(
                        blank=True,
                        default="08:00",
                        help_text="وقت نهاية فترة عدم الإزعاج",
                        null=True,
                        verbose_name="نهاية عدم الإزعاج",
                    ),
                ),
                (
                    "auto_delete_read_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="حذف الإشعارات المقروءة بعد فترة محددة",
                        verbose_name="حذف الإشعارات المقروءة تلقائياً",
                    ),
                ),
                (
                    "auto_delete_after_days",
                    models.IntegerField(
                        default=30,
                        help_text="عدد الأيام قبل حذف الإشعارات المقروءة",
                        verbose_name="الحذف بعد (أيام)",
                    ),
                ),
                (
                    "auto_archive_old_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="أرشفة الإشعارات القديمة بعد فترة محددة",
                        verbose_name="أرشفة الإشعارات القديمة تلقائياً",
                    ),
                ),
                (
                    "auto_archive_after_months",
                    models.IntegerField(
                        default=6,
                        help_text="عدد الأشهر قبل أرشفة الإشعارات",
                        verbose_name="الأرشفة بعد (أشهر)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تفضيلات الإشعارات",
                "verbose_name_plural": "تفضيلات الإشعارات",
                "db_table": "core_notification_preference",
            },
        ),
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود التطبيق"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="الاسم بالإنجليزية"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-cube", max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("core", "تطبيق أساسي"),
                            ("optional", "تطبيق اختياري"),
                        ],
                        default="optional",
                        max_length=20,
                        verbose_name="نوع التطبيق",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="مفعّل")),
                (
                    "url_namespace",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="URL Namespace"
                    ),
                ),
                (
                    "menu_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="معرف القائمة"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تطبيق النظام",
                "verbose_name_plural": "تطبيقات النظام",
                "ordering": ["order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "نص"),
                            ("integer", "عدد صحيح"),
                            ("decimal", "عدد عشري"),
                            ("boolean", "منطقي"),
                            ("json", "JSON"),
                            ("date", "تاريخ"),
                            ("datetime", "تاريخ ووقت"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="نوع البيانات",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("finance", "مالي"),
                            ("inventory", "مخزون"),
                            ("sales", "مبيعات"),
                            ("purchases", "مشتريات"),
                            ("hr", "موارد بشرية"),
                            ("system", "نظام"),
                            ("whatsapp", "واتساب"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="المجموعة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "ordering": ["group", "key"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("system", "System Log"),
                            ("security", "Security Log"),
                            ("performance", "Performance Log"),
                            ("audit", "Audit Log"),
                            ("metric", "System Metric"),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name="نوع السجل",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "تصحيح"),
                            ("INFO", "معلومات"),
                            ("WARNING", "تحذير"),
                            ("ERROR", "خطأ"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="المستوى",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("authentication", "مصادقة"),
                            ("authorization", "صلاحيات"),
                            ("performance", "أداء"),
                            ("security", "أمان"),
                            ("audit", "مراجعة"),
                            ("financial", "مالي"),
                            ("database", "قاعدة بيانات"),
                            ("integration", "تكامل"),
                            ("system_metric", "مقاييس النظام"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="الفئة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="معرف الطلب"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="وكيل المستخدم"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores all type-specific data",
                        verbose_name="البيانات",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="الوقت"
                    ),
                ),
            ],
            options={
                "verbose_name": "السجل الموحد",
                "verbose_name_plural": "السجلات الموحدة",
                "ordering": ["-timestamp"],
            },
        ),
    ]
