# Generated by Django 4.2.23 on 2025-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('value', models.CharField(max_length=100, verbose_name='القيمة')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('period', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('yearly', 'سنوي'), ('current', 'حالي')], default='monthly', max_length=20, verbose_name='الفترة')),
                ('type', models.CharField(choices=[('sales', 'مبيعات'), ('purchases', 'مشتريات'), ('inventory', 'مخزون'), ('finance', 'مالي'), ('customers', 'عملاء'), ('suppliers', 'موردين'), ('users', 'مستخدمين'), ('invoices', 'فواتير')], default='sales', max_length=20, verbose_name='النوع')),
                ('change_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='قيمة التغيير')),
                ('change_type', models.CharField(choices=[('increase', 'زيادة'), ('decrease', 'نقصان'), ('no_change', 'لا تغيير')], default='no_change', max_length=20, verbose_name='نوع التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إحصائية لوحة التحكم',
                'verbose_name_plural': 'إحصائيات لوحة التحكم',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('danger', 'خطر'), ('inventory_alert', 'تنبيه مخزون'), ('product_expiry', 'انتهاء صلاحية منتج'), ('stock_transfer', 'نقل مخزون'), ('new_sale', 'مبيعات جديدة'), ('sale_payment', 'دفعة مبيعات'), ('sale_return', 'إرجاع مبيعات'), ('new_purchase', 'مشتريات جديدة'), ('purchase_payment', 'دفعة مشتريات'), ('purchase_return', 'إرجاع مشتريات'), ('payment_received', 'دفعة مستلمة'), ('payment_made', 'دفعة مسددة'), ('new_invoice', 'فاتورة جديدة'), ('hr_leave_request', 'طلب إجازة'), ('hr_attendance', 'حضور وانصراف'), ('hr_payroll', 'رواتب'), ('hr_contract', 'عقد موظف'), ('return_request', 'طلب إرجاع'), ('system_alert', 'تنبيه نظام')], default='info', max_length=20, verbose_name='النوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('link_url', models.CharField(blank=True, help_text='الرابط المباشر للصفحة المتعلقة بالإشعار', max_length=255, null=True, verbose_name='رابط')),
                ('related_model', models.CharField(blank=True, help_text='مثل: Sale, Purchase, Product', max_length=50, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_inventory_alerts', models.BooleanField(default=True, help_text='تنبيهات المخزون المنخفض ونفاذ المنتجات', verbose_name='تنبيهات المخزون')),
                ('enable_invoice_notifications', models.BooleanField(default=True, help_text='فواتير المبيعات والمشتريات الجديدة', verbose_name='إشعارات الفواتير')),
                ('enable_payment_notifications', models.BooleanField(default=True, help_text='الدفعات المستلمة والمسددة', verbose_name='إشعارات الدفعات')),
                ('enable_return_notifications', models.BooleanField(default=True, help_text='طلبات إرجاع المبيعات والمشتريات', verbose_name='إشعارات الإرجاع')),
                ('enable_customer_notifications', models.BooleanField(default=False, help_text='عملاء جدد وتحديثات العملاء', verbose_name='إشعارات العملاء')),
                ('enable_product_notifications', models.BooleanField(default=False, help_text='منتجات جديدة وتحديثات المنتجات', verbose_name='إشعارات المنتجات')),
                ('enable_user_notifications', models.BooleanField(default=False, help_text='مستخدمين جدد وتحديثات المستخدمين', verbose_name='إشعارات المستخدمين')),
                ('enable_system_notifications', models.BooleanField(default=True, help_text='إشعارات النظام والتحديثات المهمة', verbose_name='إشعارات النظام')),
                ('notify_in_app', models.BooleanField(default=True, help_text='عرض الإشعارات داخل النظام', verbose_name='داخل النظام')),
                ('notify_email', models.BooleanField(default=False, help_text='إرسال إشعارات عبر البريد الإلكتروني', verbose_name='البريد الإلكتروني')),
                ('email_for_notifications', models.EmailField(blank=True, help_text='البريد الإلكتروني المستخدم لإرسال الإشعارات', max_length=254, null=True, verbose_name='البريد الإلكتروني للإشعارات')),
                ('notify_sms', models.BooleanField(default=False, help_text='إرسال إشعارات عبر رسائل SMS', verbose_name='رسائل SMS')),
                ('phone_for_notifications', models.CharField(blank=True, help_text='رقم الهاتف المستخدم لإرسال الإشعارات', max_length=20, null=True, verbose_name='رقم الهاتف للإشعارات')),
                ('inventory_check_frequency', models.CharField(choices=[('hourly', 'كل ساعة'), ('3hours', 'كل 3 ساعات'), ('6hours', 'كل 6 ساعات'), ('daily', 'يومياً')], default='6hours', max_length=20, verbose_name='تكرار فحص المخزون')),
                ('invoice_check_frequency', models.CharField(choices=[('daily', 'يومياً'), ('3days', 'كل 3 أيام'), ('weekly', 'أسبوعياً')], default='daily', max_length=20, verbose_name='تكرار فحص الفواتير')),
                ('send_daily_summary', models.BooleanField(default=False, help_text='إرسال ملخص يومي بجميع الإشعارات', verbose_name='إرسال ملخص يومي')),
                ('daily_summary_time', models.TimeField(default='09:00', help_text='الوقت المفضل لإرسال الملخص اليومي', verbose_name='وقت الملخص اليومي')),
                ('alert_on_minimum_stock', models.BooleanField(default=True, help_text='تنبيه عند وصول المخزون للحد الأدنى', verbose_name='تنبيه عند الحد الأدنى')),
                ('alert_on_half_minimum', models.BooleanField(default=True, help_text='تنبيه عند وصول المخزون لـ 50% من الحد الأدنى', verbose_name='تنبيه عند 50% من الحد الأدنى')),
                ('alert_on_out_of_stock', models.BooleanField(default=True, help_text='تنبيه عند نفاذ المخزون تماماً', verbose_name='تنبيه عند نفاذ المخزون')),
                ('invoice_due_days_before', models.IntegerField(default=3, help_text='عدد الأيام قبل استحقاق الفاتورة للتنبيه', verbose_name='التنبيه قبل الاستحقاق بـ (أيام)')),
                ('alert_on_invoice_due', models.BooleanField(default=True, help_text='تنبيه عند استحقاق الفاتورة', verbose_name='تنبيه عند الاستحقاق')),
                ('alert_on_invoice_overdue', models.BooleanField(default=True, help_text='تنبيه بعد تأخر سداد الفاتورة', verbose_name='تنبيه بعد التأخير')),
                ('invoice_overdue_days_after', models.IntegerField(default=1, help_text='عدد الأيام بعد التأخير للتنبيه', verbose_name='التنبيه بعد التأخير بـ (أيام)')),
                ('enable_do_not_disturb', models.BooleanField(default=False, help_text='عدم إرسال إشعارات في أوقات محددة', verbose_name='تفعيل عدم الإزعاج')),
                ('do_not_disturb_start', models.TimeField(blank=True, default='22:00', help_text='وقت بداية فترة عدم الإزعاج', null=True, verbose_name='بداية عدم الإزعاج')),
                ('do_not_disturb_end', models.TimeField(blank=True, default='08:00', help_text='وقت نهاية فترة عدم الإزعاج', null=True, verbose_name='نهاية عدم الإزعاج')),
                ('auto_delete_read_notifications', models.BooleanField(default=False, help_text='حذف الإشعارات المقروءة بعد فترة محددة', verbose_name='حذف الإشعارات المقروءة تلقائياً')),
                ('auto_delete_after_days', models.IntegerField(default=30, help_text='عدد الأيام قبل حذف الإشعارات المقروءة', verbose_name='الحذف بعد (أيام)')),
                ('auto_archive_old_notifications', models.BooleanField(default=False, help_text='أرشفة الإشعارات القديمة بعد فترة محددة', verbose_name='أرشفة الإشعارات القديمة تلقائياً')),
                ('auto_archive_after_months', models.IntegerField(default=6, help_text='عدد الأشهر قبل أرشفة الإشعارات', verbose_name='الأرشفة بعد (أشهر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'db_table': 'core_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('data_type', models.CharField(choices=[('string', 'نص'), ('integer', 'عدد صحيح'), ('decimal', 'عدد عشري'), ('boolean', 'منطقي'), ('json', 'JSON'), ('date', 'تاريخ'), ('datetime', 'تاريخ ووقت')], default='string', max_length=20, verbose_name='نوع البيانات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('group', models.CharField(choices=[('general', 'عام'), ('finance', 'مالي'), ('inventory', 'مخزون'), ('sales', 'مبيعات'), ('purchases', 'مشتريات'), ('hr', 'موارد بشرية'), ('system', 'نظام')], default='general', max_length=20, verbose_name='المجموعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['group', 'key'],
            },
        ),
    ]
