# Generated by Django 4.2.26 on 2026-04-13 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unified_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="required_modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_modules",
                to="core.systemmodule",
                verbose_name="التطبيقات المطلوبة",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="encryptionkey",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataretentionexecution",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.dataretentionpolicy",
            ),
        ),
        migrations.AddField(
            model_name="dataprotectionaudit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataclassification",
            unique_together={("model_name", "field_name")},
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="backupfile",
            name="backup_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.backuprecord",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإقرار بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.alertrule",
                verbose_name="القاعدة",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["log_type", "timestamp"], name="core_unifie_log_typ_c77c99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["level", "timestamp"], name="core_unifie_level_bde256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["category", "timestamp"], name="core_unifie_categor_212abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["user", "timestamp"], name="core_unifie_user_id_c95818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "created_at"], name="core_alert_status_b34d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["rule", "created_at"], name="core_alert_rule_id_b054f9_idx"
            ),
        ),
    ]
