# Generated by Django 4.2.26 on 2026-08-31 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unified_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="systemmodule",
            name="required_modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependent_modules",
                to="core.systemmodule",
                verbose_name="التطبيقات المطلوبة",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="fileblob",
            index=models.Index(
                fields=["sha256_hash"], name="core_filebl_sha256__9c1a1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileblob",
            index=models.Index(
                fields=["company_id", "security_status"],
                name="core_filebl_company_2d4844_idx",
            ),
        ),
        migrations.AddField(
            model_name="encryptionkey",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.attachmentcategory",
                verbose_name="فئة المستند",
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_attachments",
                to="core.fileblob",
                verbose_name="كتلة التخزين",
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالرفع",
            ),
        ),
        migrations.AddField(
            model_name="documentsequencerule",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequence_rules",
                to="product.warehouse",
                verbose_name="المخزن / الفرع",
            ),
        ),
        migrations.AddField(
            model_name="documentsequencecounter",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counters",
                to="core.documentsequencerule",
                verbose_name="قاعدة الترقيم المرتبطة",
            ),
        ),
        migrations.AddField(
            model_name="documentsequencecounter",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequence_counters",
                to="product.warehouse",
                verbose_name="المخزن / الفرع",
            ),
        ),
        migrations.AddField(
            model_name="documentsequenceaudit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم (إن وجد)",
            ),
        ),
        migrations.AddField(
            model_name="documentsequenceaudit",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.warehouse",
                verbose_name="المخزن / الفرع",
            ),
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataretentionexecution",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="core.dataretentionpolicy",
            ),
        ),
        migrations.AddField(
            model_name="dataprotectionaudit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataclassification",
            unique_together={("model_name", "field_name")},
        ),
        migrations.AddField(
            model_name="backuprecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="backupfile",
            name="backup_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.backuprecord",
            ),
        ),
        migrations.AddField(
            model_name="attachmentorphanreview",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orphan_reviews",
                to="core.fileblob",
            ),
        ),
        migrations.AddField(
            model_name="attachmentorphanreview",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المراجع",
            ),
        ),
        migrations.AddField(
            model_name="attachmentauditlog",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.attachment",
                verbose_name="المرفق",
            ),
        ),
        migrations.AddField(
            model_name="attachmentauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالإجراء",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="core.attachmentcategory",
                verbose_name="فئة المستند",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="core.fileblob",
                verbose_name="كتلة التخزين الفيزيائية",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالرفع",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإقرار بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.alertrule",
                verbose_name="القاعدة",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["log_type", "timestamp"], name="core_unifie_log_typ_c77c99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["level", "timestamp"], name="core_unifie_level_bde256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["category", "timestamp"], name="core_unifie_categor_212abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedlog",
            index=models.Index(
                fields=["user", "timestamp"], name="core_unifie_user_id_c95818_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequencerule",
            constraint=models.UniqueConstraint(
                fields=("company_code", "warehouse", "document_type", "version"),
                name="unique_sequence_rule_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequencecounter",
            constraint=models.UniqueConstraint(
                fields=("company_code", "warehouse", "document_type", "year"),
                name="unique_sequence_counter_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["content_type", "object_id", "is_latest"],
                name="core_attach_content_e1e08c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["deleted_at"], name="core_attach_deleted_8a6200_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "created_at"], name="core_alert_status_b34d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["rule", "created_at"], name="core_alert_rule_id_b054f9_idx"
            ),
        ),
    ]
