# Generated by Django 4.2.23 on 2025-10-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='رمز العملة الدولي مثل EGP, USD, SAR', max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(help_text='الاسم الكامل للعملة مثل: جنيه مصري', max_length=50, verbose_name='اسم العملة')),
                ('symbol', models.CharField(help_text='الرمز المستخدم في العرض مثل: ج.م، $، ر.س', max_length=10, verbose_name='رمز العملة')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='عدد الأرقام بعد الفاصلة العشرية', verbose_name='عدد المنازل العشرية')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='سعر الصرف مقابل العملة الأساسية', max_digits=10, verbose_name='سعر الصرف')),
                ('is_active', models.BooleanField(default=True, help_text='هل العملة نشطة ومتاحة للاستخدام؟', verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, help_text='هل هذه هي العملة الافتراضية للنظام؟', verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
