# Generated by Django 4.2.26 on 2026-08-27 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
            },
        ),
    ]
