# Generated by Django 4.2.26 on 2026-08-04 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0014_inventoryreservation_idx_inv_res_active_sweep"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        db_index=True,
                        default="DEFAULT",
                        max_length=50,
                        verbose_name="كود الشركة",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("JOURNAL_ENTRY", "قيد يومية عامة"),
                            ("ADJUSTMENT_JOURNAL", "قيد تسوية"),
                            ("REVERSAL_JOURNAL", "قيد عكسي"),
                            ("SALES_INVOICE", "فاتورة مبيعات"),
                            ("CREDIT_NOTE", "إشعار دائن (مبيعات)"),
                            ("PURCHASE_INVOICE", "فاتورة مشتريات"),
                            ("DEBIT_NOTE", "إشعار مدين (مشتريات)"),
                            ("CUSTOMER_RECEIPT", "سند مقبوضات عميل"),
                            ("VENDOR_PAYMENT", "سند مدفوعات مورد"),
                            ("FIXED_ASSET_ENTRY", "قيد أصول ثابتة"),
                            ("DELIVERY_NOTE", "إذن تسليم وشحن"),
                            ("GOODS_RECEIPT_NOTE", "إذن استلام مشتريات"),
                            ("PURCHASE_ORDER", "أمر شراء"),
                            ("SALES_ORDER", "أمر مبيعات"),
                            ("STOCK_RECEIPT", "إذن استلام مخزني"),
                            ("STOCK_ISSUE", "إذن صرف مخزني"),
                            ("STOCK_TRANSFER", "إذن تحويل مخزني"),
                            ("INVENTORY_ADJUSTMENT", "تسوية مخزنية"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="نوع المستند",
                    ),
                ),
                ("prefix", models.CharField(max_length=20, verbose_name="البادئة")),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=5, verbose_name="طول الخانة التسلسلية"
                    ),
                ),
                (
                    "numbering_basis",
                    models.CharField(
                        choices=[
                            ("POSTING_DATE", "تاريخ الترحيل / التاريخ المحاسبي"),
                            ("FISCAL_YEAR", "السنة المالية"),
                            ("SYSTEM_DATE", "تاريخ النظام"),
                        ],
                        default="POSTING_DATE",
                        max_length=20,
                        verbose_name="أساس السنة التسلسلية",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="إصدار القاعدة"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="تقفل القاعدة تلقائياً بعد إنتاج أول رقم لحماية تاريخ السجلات",
                        verbose_name="مقفلة لإنشاء مستندات حقيقية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("SUSPENDED", "معلق"),
                            ("CLOSED", "مغلق"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_rules",
                        to="product.warehouse",
                        verbose_name="المخزن / الفرع",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة ترقيم مستند",
                "verbose_name_plural": "قواعد ترقيم المستندات",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        db_index=True,
                        default="DEFAULT",
                        max_length=50,
                        verbose_name="كود الشركة",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("JOURNAL_ENTRY", "قيد يومية عامة"),
                            ("ADJUSTMENT_JOURNAL", "قيد تسوية"),
                            ("REVERSAL_JOURNAL", "قيد عكسي"),
                            ("SALES_INVOICE", "فاتورة مبيعات"),
                            ("CREDIT_NOTE", "إشعار دائن (مبيعات)"),
                            ("PURCHASE_INVOICE", "فاتورة مشتريات"),
                            ("DEBIT_NOTE", "إشعار مدين (مشتريات)"),
                            ("CUSTOMER_RECEIPT", "سند مقبوضات عميل"),
                            ("VENDOR_PAYMENT", "سند مدفوعات مورد"),
                            ("FIXED_ASSET_ENTRY", "قيد أصول ثابتة"),
                            ("DELIVERY_NOTE", "إذن تسليم وشحن"),
                            ("GOODS_RECEIPT_NOTE", "إذن استلام مشتريات"),
                            ("PURCHASE_ORDER", "أمر شراء"),
                            ("SALES_ORDER", "أمر مبيعات"),
                            ("STOCK_RECEIPT", "إذن استلام مخزني"),
                            ("STOCK_ISSUE", "إذن صرف مخزني"),
                            ("STOCK_TRANSFER", "إذن تحويل مخزني"),
                            ("INVENTORY_ADJUSTMENT", "تسوية مخزنية"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="السنة التسلسلية"
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="آخر رقم تسلسلي"
                    ),
                ),
                (
                    "last_reserved_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاريخ آخر حجز/توليد"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counters",
                        to="core.documentsequencerule",
                        verbose_name="قاعدة الترقيم المرتبطة",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_counters",
                        to="product.warehouse",
                        verbose_name="المخزن / الفرع",
                    ),
                ),
            ],
            options={
                "verbose_name": "عداد ترقيم مستند",
                "verbose_name_plural": "عدادات ترقيم المستندات",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GENERATED", "توليد رقم مستند"),
                            ("ROLLED_BACK", "تراجع عن معاملة (Rollback)"),
                            ("FAILED", "فشل توليد الرقم"),
                            ("CONFIG_CHANGED", "تغيير إعدادات القاعدة"),
                            ("MANUAL_EDIT_BLOCKED", "محاولة تعديل يدوية محظورة"),
                            ("CANCELLED_BEFORE_APPROVAL", "إلغاء مسودة قبل الاعتماد"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="نوع الحدث",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("JOURNAL_ENTRY", "قيد يومية عامة"),
                            ("ADJUSTMENT_JOURNAL", "قيد تسوية"),
                            ("REVERSAL_JOURNAL", "قيد عكسي"),
                            ("SALES_INVOICE", "فاتورة مبيعات"),
                            ("CREDIT_NOTE", "إشعار دائن (مبيعات)"),
                            ("PURCHASE_INVOICE", "فاتورة مشتريات"),
                            ("DEBIT_NOTE", "إشعار مدين (مشتريات)"),
                            ("CUSTOMER_RECEIPT", "سند مقبوضات عميل"),
                            ("VENDOR_PAYMENT", "سند مدفوعات مورد"),
                            ("FIXED_ASSET_ENTRY", "قيد أصول ثابتة"),
                            ("DELIVERY_NOTE", "إذن تسليم وشحن"),
                            ("GOODS_RECEIPT_NOTE", "إذن استلام مشتريات"),
                            ("PURCHASE_ORDER", "أمر شراء"),
                            ("SALES_ORDER", "أمر مبيعات"),
                            ("STOCK_RECEIPT", "إذن استلام مخزني"),
                            ("STOCK_ISSUE", "إذن صرف مخزني"),
                            ("STOCK_TRANSFER", "إذن تحويل مخزني"),
                            ("INVENTORY_ADJUSTMENT", "تسوية مخزنية"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند الناتج",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        default="DEFAULT", max_length=50, verbose_name="كود الشركة"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("USER", "مستخدم"),
                            ("SYSTEM", "النظام"),
                            ("API", "واجهة برمجية API"),
                            ("JOB", "مهمة خلفية Background Job"),
                        ],
                        default="USER",
                        max_length=20,
                        verbose_name="مصدر الطلب",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ وتوقيت الحدث",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="السبب / الملاحظات"
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القيمة القديمة",
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القيمة الجديدة",
                    ),
                ),
                (
                    "prefix_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="لقطة البادئة",
                    ),
                ),
                (
                    "padding_snapshot",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="لقطة الطول"
                    ),
                ),
                (
                    "year_snapshot",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="لقطة السنة"
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الرقم التسلسلي المجرد"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم (إن وجد)",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.warehouse",
                        verbose_name="المخزن / الفرع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق الترقيم",
                "verbose_name_plural": "سجلات تدقيق الترقيم",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentsequencerule",
            constraint=models.UniqueConstraint(
                fields=("company_code", "warehouse", "document_type", "version"),
                name="unique_sequence_rule_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequencecounter",
            constraint=models.UniqueConstraint(
                fields=("company_code", "warehouse", "document_type", "year"),
                name="unique_sequence_counter_scope",
            ),
        ),
    ]
