# Generated by Django 4.2.26 on 2026-08-05 13:41

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_documentsequencerule_documentsequencecounter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف الأصلي"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="رقم الإصدار"),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="النسخة الأحدث"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="تاريخ الحذف الناعم",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
            ],
            options={
                "verbose_name": "مرفق مستند",
                "verbose_name_plural": "مرفقات المستندات",
            },
        ),
        migrations.CreateModel(
            name="AttachmentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "رفع"),
                            ("VIEWED", "عرض"),
                            ("DOWNLOADED", "تنزيل"),
                            ("REPLACED", "استبدال / تحديث إصدار"),
                            ("DELETED", "حذف ناعم"),
                            ("RESTORED", "استعادة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "user_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="لقطة اسم المستخدم",
                    ),
                ),
                (
                    "user_email_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="لقطة بريد المستخدم",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق مرفق",
                "verbose_name_plural": "سجلات تدقيق المرفقات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="كود الفئة",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الفئة")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "max_size_mb",
                    models.PositiveIntegerField(
                        default=10, verbose_name="الحد الأقصى لحجم الملف (ميجابايت)"
                    ),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        default="pdf,png,jpg,jpeg,docx,xlsx",
                        max_length=255,
                        verbose_name="الامتدادات المسموح بها",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="مدة الاستبقاء القانونية (أيام)"
                    ),
                ),
                (
                    "requires_integrity_check",
                    models.BooleanField(
                        default=True, verbose_name="يتطلب فحص السلامة (SHA-256)"
                    ),
                ),
                (
                    "permission_required",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="الصلاحية المطلوبة للوصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة مستندات",
                "verbose_name_plural": "فئات المستندات",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AttachmentOrphanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOUND", "مكتشف كأيتام"),
                            ("REVIEWED", "تمت المراجعة"),
                            ("MARKED_FOR_DELETE", "مُعلم للحذف"),
                            ("DELETED", "تم الحذف النهائي"),
                        ],
                        default="FOUND",
                        max_length=30,
                        verbose_name="حالة المراجعة",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="توقيت الاكتشاف"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف النهائي"
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة مستند يتيتم",
                "verbose_name_plural": "مراجعات المستندات الأيتام",
            },
        ),
        migrations.CreateModel(
            name="DraftAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "draft_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="رمز المسودة الموقت",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="مفتاح الجلسة"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف الأصلي"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="تاريخ الانتهاء"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مسودة مرفق مؤقتة",
                "verbose_name_plural": "مسودات المرفقات المؤقتة",
            },
        ),
        migrations.CreateModel(
            name="FileBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="بصمة الملف (SHA-256)",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.attachment_upload_path,
                        verbose_name="الملف الفيزيائي",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="حجم الملف (بايت)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="نوع MIME"),
                ),
                (
                    "company_id",
                    models.PositiveIntegerField(
                        db_index=True, default=1, verbose_name="معرف الشركة"
                    ),
                ),
                (
                    "reference_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عداد الإشارات المرجعية الذري"
                    ),
                ),
                (
                    "security_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الفحص"),
                            ("CLEAN", "سليم"),
                            ("BLOCKED", "محظور"),
                            ("QUARANTINED", "في الحجر الصحي"),
                        ],
                        default="CLEAN",
                        max_length=20,
                        verbose_name="حالة الأمان",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "كتلة تخزين فيزيائية",
                "verbose_name_plural": "كتل التخزين الفيزيائية",
            },
        ),
        migrations.RemoveField(
            model_name="documentsequencecounter",
            name="rule",
        ),
        migrations.RemoveField(
            model_name="documentsequencecounter",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="documentsequencerule",
            name="warehouse",
        ),
        migrations.DeleteModel(
            name="DocumentSequenceAudit",
        ),
        migrations.DeleteModel(
            name="DocumentSequenceCounter",
        ),
        migrations.DeleteModel(
            name="DocumentSequenceRule",
        ),
        migrations.AddIndex(
            model_name="fileblob",
            index=models.Index(
                fields=["sha256_hash"], name="core_filebl_sha256__9c1a1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileblob",
            index=models.Index(
                fields=["company_id", "security_status"],
                name="core_filebl_company_2d4844_idx",
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.attachmentcategory",
                verbose_name="فئة المستند",
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_attachments",
                to="core.fileblob",
                verbose_name="كتلة التخزين",
            ),
        ),
        migrations.AddField(
            model_name="draftattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالرفع",
            ),
        ),
        migrations.AddField(
            model_name="attachmentorphanreview",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orphan_reviews",
                to="core.fileblob",
            ),
        ),
        migrations.AddField(
            model_name="attachmentorphanreview",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المراجع",
            ),
        ),
        migrations.AddField(
            model_name="attachmentauditlog",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.attachment",
                verbose_name="المرفق",
            ),
        ),
        migrations.AddField(
            model_name="attachmentauditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالإجراء",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="core.attachmentcategory",
                verbose_name="فئة المستند",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="file_blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="core.fileblob",
                verbose_name="كتلة التخزين الفيزيائية",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="القائم بالرفع",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["content_type", "object_id", "is_latest"],
                name="core_attach_content_e1e08c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["deleted_at"], name="core_attach_deleted_8a6200_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_latest", True)),
                fields=("content_type", "object_id", "category"),
                name="one_latest_attachment_per_category",
            ),
        ),
    ]
