# Generated by Django 5.2.17 on 2026-09-28 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_register_operational_submodules'),
        ('customer', '0006_customer_whatsapp_opt_out_and_more'),
        ('supplier', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم المستلم')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المستلم')),
                ('is_custom_phone', models.BooleanField(default=False, verbose_name='رقم مخصص يدوياً')),
                ('template_name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('language_code', models.CharField(default='ar', max_length=10, verbose_name='رمز اللغة')),
                ('has_media', models.BooleanField(default=False, verbose_name='يحتوي على مرفق PDF')),
                ('media_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرف الوسائط (Media ID)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف المستند')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الإرسال'), ('SENT', 'تم التسليم لـ Meta'), ('DELIVERED', 'تم التسليم للهاتف'), ('READ', 'تمت القراءة'), ('FAILED', 'فشل الإرسال'), ('SKIPPED', 'تم التخطي (Opt-Out)')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الرسالة')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='معرف الرسالة من Meta (wamid)')),
                ('error_code', models.CharField(blank=True, default='', max_length=50, verbose_name='كود الخطأ')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='نص وتفاصيل الخطأ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='توقيت الإرسال')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='إرسال تلقائي حدثي')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد محاولات الإعادة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='نوع المستند المرتبط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='customer.customer', verbose_name='العميل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='supplier.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سجل رسالة WhatsApp',
                'verbose_name_plural': 'سجلات رسائل WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_whatsa_status_3161a0_idx'), models.Index(fields=['recipient_phone', '-created_at'], name='core_whatsa_recipie_29ab54_idx')],
            },
        ),
    ]
