# Generated by Django 4.2.23 on 2025-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_currency_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='الرابط الذي سيتم التوجيه إليه عند النقر على الإشعار', max_length=255, null=True, verbose_name='رابط الإجراء'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='مثل: sale, purchase, invoice', max_length=50, null=True, verbose_name='نوع الكائن المرتبط'),
        ),
    ]
