# Generated by Django 4.2.23 on 2025-10-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_currency_notification_action_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, help_text='الرابط المباشر للصفحة المتعلقة بالإشعار', max_length=255, null=True, verbose_name='رابط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_model',
            field=models.CharField(blank=True, help_text='مثل: Sale, Purchase, Product', max_length=50, null=True, verbose_name='النموذج المرتبط'),
        ),
    ]
