# Generated by Django 5.2.17 on 2026-09-28 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='توقيت التسليم للهاتف'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='document_reference_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مرجع المستند النصي الدائم'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='توقيت القراءة'),
        ),
    ]
