# Generated by Django 4.2.26 on 2026-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_attachment_attachmentauditlog_attachmentcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequenceaudit",
            name="document_type",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="نوع المستند"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequenceaudit",
            name="event_type",
            field=models.CharField(
                db_index=True, max_length=30, verbose_name="نوع الحدث"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequenceaudit",
            name="source_type",
            field=models.CharField(
                default="USER", max_length=20, verbose_name="مصدر الطلب"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequenceaudit",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاريخ وتوقيت الحدث"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequencecounter",
            name="document_type",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="نوع المستند"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequencerule",
            name="document_type",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="نوع المستند"
            ),
        ),
        migrations.AlterField(
            model_name="documentsequencerule",
            name="numbering_basis",
            field=models.CharField(
                default="POSTING_DATE",
                max_length=20,
                verbose_name="أساس السنة التسلسلية",
            ),
        ),
        migrations.AlterField(
            model_name="documentsequencerule",
            name="status",
            field=models.CharField(
                default="ACTIVE", max_length=20, verbose_name="الحالة"
            ),
        ),
    ]
