# Generated by Django 4.2.23 on 2025-10-31 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_notification_action_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_inventory_alerts', models.BooleanField(default=True, help_text='تنبيهات المخزون المنخفض ونفاذ المنتجات', verbose_name='تنبيهات المخزون')),
                ('enable_invoice_notifications', models.BooleanField(default=True, help_text='فواتير المبيعات والمشتريات الجديدة', verbose_name='إشعارات الفواتير')),
                ('enable_payment_notifications', models.BooleanField(default=True, help_text='الدفعات المستلمة والمسددة', verbose_name='إشعارات الدفعات')),
                ('enable_return_notifications', models.BooleanField(default=True, help_text='طلبات إرجاع المبيعات والمشتريات', verbose_name='إشعارات الإرجاع')),
                ('enable_customer_notifications', models.BooleanField(default=False, help_text='عملاء جدد وتحديثات العملاء', verbose_name='إشعارات العملاء')),
                ('enable_product_notifications', models.BooleanField(default=False, help_text='منتجات جديدة وتحديثات المنتجات', verbose_name='إشعارات المنتجات')),
                ('enable_user_notifications', models.BooleanField(default=False, help_text='مستخدمين جدد وتحديثات المستخدمين', verbose_name='إشعارات المستخدمين')),
                ('enable_system_notifications', models.BooleanField(default=True, help_text='إشعارات النظام والتحديثات المهمة', verbose_name='إشعارات النظام')),
                ('notify_in_app', models.BooleanField(default=True, help_text='عرض الإشعارات داخل النظام', verbose_name='داخل النظام')),
                ('notify_email', models.BooleanField(default=False, help_text='إرسال إشعارات عبر البريد الإلكتروني', verbose_name='البريد الإلكتروني')),
                ('email_for_notifications', models.EmailField(blank=True, help_text='البريد الإلكتروني المستخدم لإرسال الإشعارات', max_length=254, null=True, verbose_name='البريد الإلكتروني للإشعارات')),
                ('notify_sms', models.BooleanField(default=False, help_text='إرسال إشعارات عبر رسائل SMS', verbose_name='رسائل SMS')),
                ('phone_for_notifications', models.CharField(blank=True, help_text='رقم الهاتف المستخدم لإرسال الإشعارات', max_length=20, null=True, verbose_name='رقم الهاتف للإشعارات')),
                ('inventory_check_frequency', models.CharField(choices=[('hourly', 'كل ساعة'), ('3hours', 'كل 3 ساعات'), ('6hours', 'كل 6 ساعات'), ('daily', 'يومياً')], default='6hours', max_length=20, verbose_name='تكرار فحص المخزون')),
                ('invoice_check_frequency', models.CharField(choices=[('daily', 'يومياً'), ('3days', 'كل 3 أيام'), ('weekly', 'أسبوعياً')], default='daily', max_length=20, verbose_name='تكرار فحص الفواتير')),
                ('send_daily_summary', models.BooleanField(default=False, help_text='إرسال ملخص يومي بجميع الإشعارات', verbose_name='إرسال ملخص يومي')),
                ('daily_summary_time', models.TimeField(default='09:00', help_text='الوقت المفضل لإرسال الملخص اليومي', verbose_name='وقت الملخص اليومي')),
                ('alert_on_minimum_stock', models.BooleanField(default=True, help_text='تنبيه عند وصول المخزون للحد الأدنى', verbose_name='تنبيه عند الحد الأدنى')),
                ('alert_on_half_minimum', models.BooleanField(default=True, help_text='تنبيه عند وصول المخزون لـ 50% من الحد الأدنى', verbose_name='تنبيه عند 50% من الحد الأدنى')),
                ('alert_on_out_of_stock', models.BooleanField(default=True, help_text='تنبيه عند نفاذ المخزون تماماً', verbose_name='تنبيه عند نفاذ المخزون')),
                ('invoice_due_days_before', models.IntegerField(default=3, help_text='عدد الأيام قبل استحقاق الفاتورة للتنبيه', verbose_name='التنبيه قبل الاستحقاق بـ (أيام)')),
                ('alert_on_invoice_due', models.BooleanField(default=True, help_text='تنبيه عند استحقاق الفاتورة', verbose_name='تنبيه عند الاستحقاق')),
                ('alert_on_invoice_overdue', models.BooleanField(default=True, help_text='تنبيه بعد تأخر سداد الفاتورة', verbose_name='تنبيه بعد التأخير')),
                ('invoice_overdue_days_after', models.IntegerField(default=1, help_text='عدد الأيام بعد التأخير للتنبيه', verbose_name='التنبيه بعد التأخير بـ (أيام)')),
                ('enable_do_not_disturb', models.BooleanField(default=False, help_text='عدم إرسال إشعارات في أوقات محددة', verbose_name='تفعيل عدم الإزعاج')),
                ('do_not_disturb_start', models.TimeField(blank=True, default='22:00', help_text='وقت بداية فترة عدم الإزعاج', null=True, verbose_name='بداية عدم الإزعاج')),
                ('do_not_disturb_end', models.TimeField(blank=True, default='08:00', help_text='وقت نهاية فترة عدم الإزعاج', null=True, verbose_name='نهاية عدم الإزعاج')),
                ('auto_delete_read_notifications', models.BooleanField(default=False, help_text='حذف الإشعارات المقروءة بعد فترة محددة', verbose_name='حذف الإشعارات المقروءة تلقائياً')),
                ('auto_delete_after_days', models.IntegerField(default=30, help_text='عدد الأيام قبل حذف الإشعارات المقروءة', verbose_name='الحذف بعد (أيام)')),
                ('auto_archive_old_notifications', models.BooleanField(default=False, help_text='أرشفة الإشعارات القديمة بعد فترة محددة', verbose_name='أرشفة الإشعارات القديمة تلقائياً')),
                ('auto_archive_after_months', models.IntegerField(default=6, help_text='عدد الأشهر قبل أرشفة الإشعارات', verbose_name='الأرشفة بعد (أشهر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'db_table': 'core_notification_preference',
            },
        ),
    ]
