# Generated by Django 5.2.17 on 2026-10-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_whatsappmessagelog_delivered_at_and_more'),
        ('customer', '0006_customer_whatsapp_opt_out_and_more'),
        ('supplier', '0003_supplier_whatsapp_opt_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessagelog',
            options={'ordering': ['-created_at'], 'permissions': [('can_send_whatsapp', 'يمكنه إرسال إشعارات ومستندات عبر الواتساب')], 'verbose_name': 'سجل رسائل الواتساب', 'verbose_name_plural': 'سجلات رسائل الواتساب'},
        ),
        migrations.RenameIndex(
            model_name='whatsappmessagelog',
            new_name='core_whatsa_recipie_76b4a9_idx',
            old_name='core_whatsa_recipie_29ab54_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessagelog',
            new_name='core_whatsa_status_11c149_idx',
            old_name='core_whatsa_status_3161a0_idx',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='body_text',
            field=models.TextField(blank=True, default='', verbose_name='نص ومحتوى الرسالة'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND_ERP', 'صادرة من النظام 🖥️'), ('OUTBOUND_MOBILE', 'صادرة من الموبايل 📱'), ('INBOUND', 'واردة من الشريك 📥')], db_index=True, default='OUTBOUND_ERP', max_length=20, verbose_name='اتجاه ومصدر الرسالة'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='inbound_media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_inbound/%Y/%m/', verbose_name='ملف الوسائط الواردة محلياً'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='message_type',
            field=models.CharField(choices=[('template', 'قالب معتمد (Template)'), ('text', 'نص حر (Free Text)'), ('image', 'صورة (Image)'), ('document', 'مستند (Document/PDF)'), ('audio', 'صوت (Audio)'), ('location', 'موقع (Location)'), ('interactive', 'تفاعلي (Interactive)'), ('unknown', 'غير محدد (Unknown)')], db_index=True, default='template', max_length=20, verbose_name='نوع الرسالة'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='pricing_category',
            field=models.CharField(choices=[('UTILITY', 'خدمية (Utility)'), ('AUTHENTICATION', 'تحقق وأمان (Authentication)'), ('MARKETING', 'تسويقية (Marketing)'), ('SERVICE', 'خدمة عملاء (Service)')], default='UTILITY', max_length=30, verbose_name='فئة التسعير'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ وتوقيت الإرسال'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنشئ'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='customer.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الخطأ'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الخطأ'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='إرسال تلقائي'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='language_code',
            field=models.CharField(default='ar', max_length=10, verbose_name='لغة القالب'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='media_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='معرف الوسائط (Media ID)'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='معرف الرسالة (wamid)'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='توقيت فتح وقراءة العميل 👁️'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المستلم / المرسل'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='recipient_phone',
            field=models.CharField(db_index=True, max_length=30, verbose_name='رقم المستلم / المرسل'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد محاولات الإرسال'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الإرسال'), ('SENT', 'تم الإرسال لـ Meta'), ('DELIVERED', 'تم التسليم للهاتف'), ('READ', 'تمت القراءة 👁️'), ('FAILED', 'فشل الإرسال'), ('SKIPPED', 'تم التخطي (رقم غير صالح / Opt-Out)')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الرسالة'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='supplier.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم القالب'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['direction', '-created_at'], name='core_whatsa_directi_40f160_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='core_whatsa_content_c0bc32_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['customer', '-created_at'], name='core_whatsa_custome_cfbd60_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['supplier', '-created_at'], name='core_whatsa_supplie_34fef5_idx'),
        ),
    ]
