# Generated by Django 4.2.26 on 2026-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_attachment_one_latest_attachment_per_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsequencerule",
            name="padding",
            field=models.PositiveIntegerField(
                default=4, verbose_name="طول الخانة التسلسلية"
            ),
        ),
    ]
