# Generated by Django 4.2.25 on 2025-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="group",
            field=models.CharField(
                choices=[
                    ("general", "عام"),
                    ("finance", "مالي"),
                    ("inventory", "مخزون"),
                    ("sales", "مبيعات"),
                    ("purchases", "مشتريات"),
                    ("hr", "موارد بشرية"),
                    ("system", "نظام"),
                ],
                default="general",
                max_length=20,
                verbose_name="المجموعة",
            ),
        ),
    ]
