# Generated by Django 4.2.23 on 2025-11-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_systemsetting_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('danger', 'خطر'), ('inventory_alert', 'تنبيه مخزون'), ('product_expiry', 'انتهاء صلاحية منتج'), ('stock_transfer', 'نقل مخزون'), ('new_sale', 'مبيعات جديدة'), ('sale_payment', 'دفعة مبيعات'), ('sale_return', 'إرجاع مبيعات'), ('new_purchase', 'مشتريات جديدة'), ('purchase_payment', 'دفعة مشتريات'), ('purchase_return', 'إرجاع مشتريات'), ('payment_received', 'دفعة مستلمة'), ('payment_made', 'دفعة مسددة'), ('new_invoice', 'فاتورة جديدة'), ('hr_leave_request', 'طلب إجازة'), ('hr_attendance', 'حضور وانصراف'), ('hr_payroll', 'رواتب'), ('hr_contract', 'عقد موظف'), ('return_request', 'طلب إرجاع'), ('system_alert', 'تنبيه نظام')], default='info', max_length=20, verbose_name='النوع'),
        ),
    ]
