# Generated by Django 5.2.17 on 2026-10-04 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_auto_bootstrap_whatsapp_account'),
        ('customer', '0007_customer_whatsapp_opt_out_reason_and_more'),
        ('supplier', '0003_supplier_whatsapp_opt_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whatsapp_messages', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول / المستلم'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['assigned_user', '-created_at'], name='core_whatsa_assigne_f0eb16_idx'),
        ),
    ]
