# Generated by Django 5.2.17 on 2026-10-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsapp_assigned_user'),
        ('customer', '0007_customer_whatsapp_opt_out_reason_and_more'),
        ('supplier', '0003_supplier_whatsapp_opt_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('campaign_type', models.CharField(choices=[('STATEMENT', 'كشوف حسابات دورية (Statement of Account)'), ('COLLECTION_REMINDER', 'تذكير مالي ومطالبات تحصيل'), ('PROMOTIONAL', 'حملة ترويجية وإعلانية (Marketing)'), ('SERVICE_ANNOUNCEMENT', 'إعلان خدمي عام (Utility/Service)')], default='STATEMENT', max_length=30, verbose_name='نوع الحملة')),
                ('audience_type', models.CharField(choices=[('ALL_CUSTOMERS', 'جميع العملاء النشطين'), ('CUSTOMERS_WITH_BALANCE', 'العملاء ذوو الأرصدة المدينة (> 0)'), ('CUSTOMER_TIER', 'شريحة عملاء محددة'), ('ALL_SUPPLIERS', 'جميع الموردين'), ('CUSTOM_LIST', 'قائمة مخصصة')], default='CUSTOMERS_WITH_BALANCE', max_length=30, verbose_name='الجمهور المستهدف')),
                ('template_name', models.CharField(default='order_status_ar', max_length=100, verbose_name='اسم القالب المعتمد')),
                ('language_code', models.CharField(default='ar', max_length=10, verbose_name='لغة القالب')),
                ('custom_message', models.TextField(blank=True, default='', verbose_name='نص مخصص إضافي')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SCHEDULED', 'مجدولة'), ('RUNNING', 'قيد الإرسال والتنفيذ 🚀'), ('COMPLETED', 'مكتملة بنجاح ✅'), ('PAUSED', 'متوقفة مؤقتاً ⏸️'), ('FROZEN_QUALITY', 'مجمدة لحماية جودة الرقم 🛡️'), ('FAILED', 'فشلت ❌')], db_index=True, default='DRAFT', max_length=30, verbose_name='حالة الحملة')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='إجمالي المستلمين')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تم الإرسال لـ Meta')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='تم التسليم للهواتف')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='تمت القراءة 👁️')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='فشل الإرسال')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='تم التخطي (Opt-Out / أرضي)')),
                ('throttle_rate', models.PositiveIntegerField(default=15, help_text='الحد الأقصى للرسائل في الثانية لحماية مؤشر جودة الرقم', verbose_name='معدل التدفق (رسالة/ثانية)')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال المجدول')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التنفيذ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال الحملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.whatsappaccount', verbose_name='حساب الواتساب المرسل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنشئ')),
                ('customer_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to='customer.customertier', verbose_name='شريحة العملاء')),
            ],
            options={
                'verbose_name': 'حملة واتساب جماعية',
                'verbose_name_plural': 'حملات واتساب الجماعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='core.whatsappcampaign', verbose_name='الحملة المرتبطة'),
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم الهاتف')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المستلم')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('SENT', 'تم الإرسال لـ Meta'), ('DELIVERED', 'تم التسليم للهاتف'), ('READ', 'تمت القراءة 👁️'), ('FAILED', 'فشل الإرسال'), ('SKIPPED', 'تم التخطي (Opt-Out / أرضي)')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الإرسال')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ إن وجدت')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.whatsappcampaign', verbose_name='الحملة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='customer.customer', verbose_name='العميل')),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipient_entry', to='core.whatsappmessagelog', verbose_name='سجل الرسالة المرتبط')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='supplier.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'مستلم في حملة واتساب',
                'verbose_name_plural': 'مستلمو حملات واتساب',
                'ordering': ['id'],
                'unique_together': {('campaign', 'recipient_phone')},
            },
        ),
    ]
