# Generated by Django 4.2.26 on 2026-08-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("financial", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="قيد الأستاذ مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="customerpayment",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.costcenter",
                verbose_name="مركز التكلفة",
            ),
        ),
    ]
