# Generated by Django on 2026-08-31 12:18 (Operations consolidated in 0002_initial)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_initial"),
    ]

    operations = []

