# Generated by Django 5.2.17 on 2026-09-20 09:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('sale', '0003_alter_salesorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(default='CUST-', help_text='مثال: CUST- أو CLI-', max_length=10, verbose_name='بادئة كود العميل')),
                ('code_digits', models.PositiveIntegerField(default=4, help_text='عدد الخانات الرقمية مثل 4 لإنتاج CUST-0001', verbose_name='عدد خانات الترقيم')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الائتماني الافتراضي للعملاء الجدد')),
                ('default_grace_period_days', models.IntegerField(default=0, verbose_name='فترة السماح الافتراضية (أيام)')),
                ('credit_limit_enforcement', models.CharField(choices=[('HARD_STOP', 'إيقاف آلي صارم للبيع'), ('WARNING', 'تحذير فقط مع طلب اعتماد')], default='HARD_STOP', max_length=20, verbose_name='سياسة تجاوز سقف الائتمان')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات العملاء والائتمان العامة',
                'verbose_name_plural': 'إعدادات العملاء والائتمان العامة',
            },
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='الشرط الافتراضي للنظام'),
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشريحة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-users', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='var(--primary-color)', max_length=50, verbose_name='اللون')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الائتماني الافتراضي')),
                ('default_risk_category', models.CharField(choices=[('LOW', 'منخفض المخاطر'), ('MEDIUM', 'متوسط المخاطر'), ('HIGH', 'مرتفع المخاطر')], default='LOW', max_length=20, verbose_name='تصنيف المخاطر الافتراضي')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة خصم الشريحة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='شريحة نظامية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('default_payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tiers', to='customer.paymentterm', verbose_name='شروط الدفع الافتراضية')),
                ('default_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tiers', to='sale.pricelist', verbose_name='قائمة الأسعار الافتراضية')),
            ],
            options={
                'verbose_name': 'شريحة عملاء',
                'verbose_name_plural': 'شرائح العملاء',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='الشريحة التجارية المعتمدة للعميل التي تحدد إعدادات التسعير وشروط الدفع والائتمان تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.customertier', verbose_name='الشريحة التجارية'),
        ),
    ]
