# Generated by Django 5.2.17 on 2026-09-20 09:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
        ('sale', '0003_alter_salesorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(default='CUST-', help_text='مثال: CUST- أو CLI-', max_length=10, verbose_name='بادئة كود العميل')),
                ('code_digits', models.PositiveIntegerField(default=4, help_text='عدد الخانات الرقمية مثل 4 لإنتاج CUST-0001', verbose_name='عدد خانات الترقيم')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الائتماني الافتراضي للعملاء الجدد')),
                ('default_grace_period_days', models.IntegerField(default=0, verbose_name='فترة السماح الافتراضية (أيام)')),
                ('credit_limit_enforcement', models.CharField(choices=[('HARD_STOP', 'إيقاف آلي صارم للبيع'), ('WARNING', 'تحذير فقط مع طلب اعتماد')], default='HARD_STOP', max_length=20, verbose_name='سياسة تجاوز سقف الائتمان')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات العملاء والائتمان العامة',
                'verbose_name_plural': 'إعدادات العملاء والائتمان العامة',
            },
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(default=False, help_text='هل هذا الشرط هو الافتراضي تلقائياً عند إنشاء عميل جديد؟', verbose_name='افتراضي للعملاء الجدد'),
        ),
    ]
