# Generated by Django 5.2.17 on 2026-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customergeneralsettings_paymentterm_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='كود الشرط'),
        ),
    ]
