# Generated by Django 5.2.17 on 2026-09-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_paymentterm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_out',
            field=models.BooleanField(default=False, verbose_name='إلغاء الاشتراك في رسائل WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إلغاء الاشتراك'),
        ),
    ]
