# Generated by Django 5.2.17 on 2026-10-04 09:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_whatsapp_opt_out_and_more'),
        ('sale', '0004_alter_creditnote_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_opt_out_reason',
            field=models.CharField(blank=True, help_text='سبب ومصدر تعديل حالة الاشتراك (مثال: Inbound Keyword Webhook أو يدوي بواسطة المحاسب)', max_length=255, null=True, verbose_name='سبب ومصدر تعديل الاشتراك'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_opt_out',
            field=models.BooleanField(default=False, help_text='إلغاء اشتراك العميل في استلام الإشعارات التلقائية عبر الواتساب بناءً على طلبه', verbose_name='إلغاء الاشتراك في رسائل الواتساب (Opt-Out)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ وتوقيت آخر تعديل لحالة اشتراك الواتساب', null=True, verbose_name='تاريخ آخر تعديل للاشتراك'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='الشرط الافتراضي للنظام'),
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشريحة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-users', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='var(--primary-color)', max_length=50, verbose_name='اللون')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('default_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الحد الائتماني الافتراضي')),
                ('default_risk_category', models.CharField(choices=[('LOW', 'منخفض المخاطر'), ('MEDIUM', 'متوسط المخاطر'), ('HIGH', 'مرتفع المخاطر')], default='LOW', max_length=20, verbose_name='تصنيف المخاطر الافتراضي')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة خصم الشريحة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, verbose_name='شريحة نظامية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('default_payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tiers', to='customer.paymentterm', verbose_name='شروط الدفع الافتراضية')),
                ('default_price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tiers', to='sale.pricelist', verbose_name='قائمة الأسعار الافتراضية')),
            ],
            options={
                'verbose_name': 'شريحة عملاء',
                'verbose_name_plural': 'شرائح العملاء',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='الشريحة التجارية المعتمدة للعميل التي تحدد إعدادات التسعير وشروط الدفع والائتمان تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer.customertier', verbose_name='الشريحة التجارية'),
        ),
    ]
