# Generated by Django 4.2.23 on 2025-11-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='المدير'),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_prices_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='supplier.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='product.warehouse', verbose_name='من المخزن'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_transfers', to=settings.AUTH_USER_MODEL, verbose_name='شحن بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='product.warehouse', verbose_name='إلى المخزن'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='reserved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='محجوز بواسطة'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='product.warehouse', verbose_name='المخزن المستلم'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='financial.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterUniqueTogether(
            name='serialnumber',
            unique_together={('document_type', 'year')},
        ),
        migrations.AddField(
            model_name='reservationrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='reservationrule',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='فئة المنتج'),
        ),
        migrations.AddField(
            model_name='reservationrule',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='reservationfulfillment',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نُفذ بواسطة'),
        ),
        migrations.AddField(
            model_name='reservationfulfillment',
            name='inventory_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.inventorymovement', verbose_name='حركة المخزون المرتبطة'),
        ),
        migrations.AddField(
            model_name='reservationfulfillment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='product.stockreservation', verbose_name='الحجز'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='product.locationshelf', verbose_name='الرف'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batches', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brand', verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='المورد الافتراضي لهذا المنتج', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='supplier.supplier', verbose_name='المورد الافتراضي'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.unit', verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='غُير بواسطة'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='supplier_product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.supplierproductprice', verbose_name='سعر المنتج للمورد'),
        ),
        migrations.AddField(
            model_name='locationzone',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_zones', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المصرح لهم'),
        ),
        migrations.AddField(
            model_name='locationzone',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='locationzone',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='locationtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='مُعين إلى'),
        ),
        migrations.AddField(
            model_name='locationtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='locationtask',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='product.productlocation', verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='locationtask',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='locationshelf',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='product.locationaisle', verbose_name='الممر'),
        ),
        migrations.AddField(
            model_name='locationmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='product.productlocation', verbose_name='من الموقع'),
        ),
        migrations.AddField(
            model_name='locationmovement',
            name='inventory_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.inventorymovement', verbose_name='حركة المخزون المرتبطة'),
        ),
        migrations.AddField(
            model_name='locationmovement',
            name='moved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نُقل بواسطة'),
        ),
        migrations.AddField(
            model_name='locationmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_movements', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='locationmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='product.productlocation', verbose_name='إلى الموقع'),
        ),
        migrations.AddField(
            model_name='locationaisle',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='product.locationzone', verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_approved', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='financial.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reference_movement',
            field=models.ForeignKey(blank=True, help_text='الحركة المرتبطة (مثل التحويل المقابل)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to='product.inventorymovement', verbose_name='الحركة المرجعية'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reversal_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_movement', to='product.inventorymovement', verbose_name='حركة العكس'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_items', to='product.inventoryadjustment', verbose_name='التسوية'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='expiryrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='expiryrule',
            name='notify_users',
            field=models.ManyToManyField(blank=True, help_text='المستخدمون الذين سيتلقون التنبيهات', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون المُنبهون'),
        ),
        migrations.AddField(
            model_name='expiryrule',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='فئة المنتج'),
        ),
        migrations.AddField(
            model_name='expiryrule',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اطلع عليه'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='product.productbatch', verbose_name='الدفعة'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='التصنيف الأم'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='batchreservation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='product.productbatch', verbose_name='الدفعة'),
        ),
        migrations.AddField(
            model_name='batchconsumption',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='product.productbatch', verbose_name='الدفعة'),
        ),
        migrations.AddField(
            model_name='batchconsumption',
            name='consumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='استُهلك بواسطة'),
        ),
        migrations.AddField(
            model_name='batchconsumption',
            name='inventory_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.inventorymovement', verbose_name='حركة المخزون المرتبطة'),
        ),
        migrations.AddIndex(
            model_name='supplierproductprice',
            index=models.Index(fields=['product', 'supplier'], name='product_sup_product_eb4bee_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproductprice',
            index=models.Index(fields=['product', 'is_default'], name='product_sup_product_651301_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproductprice',
            index=models.Index(fields=['is_active'], name='product_sup_is_acti_7c4221_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproductprice',
            unique_together={('product', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='product_sto_from_wa_90e6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'request_date'], name='product_sto_status_ddf03b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['product'], name='product_sto_product_46ecab_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['snapshot_date', 'warehouse'], name='product_sto_snapsho_3cd877_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['product', 'snapshot_date'], name='product_sto_product_ce603a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'warehouse', 'status'], name='product_sto_product_78df27_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['status', 'expires_at'], name='product_sto_status_44552b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reservation_type', 'status'], name='product_sto_reserva_ba7202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['product', 'warehouse'], name='product_pro_product_fed599_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['warehouse', 'quantity'], name='product_pro_warehou_cc3905_idx'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['is_active'], name='product_pro_is_acti_75a22e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='productlocation',
            unique_together={('product', 'shelf', 'level', 'position')},
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'warehouse', 'status'], name='product_pro_product_6be83d_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['expiry_date', 'status'], name='product_pro_expiry__dd295c_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['batch_number'], name='product_pro_batch_n_232b55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('batch_number', 'product')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['supplier_product_price', '-change_date'], name='product_pri_supplie_3c9874_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['change_reason'], name='product_pri_change__95417a_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['change_date'], name='product_pri_change__c67f53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationzone',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='locationshelf',
            unique_together={('aisle', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='locationaisle',
            unique_together={('zone', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'warehouse'], name='product_inv_product_5f5312_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_date', 'movement_type'], name='product_inv_movemen_d791c6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['document_type', 'document_number'], name='product_inv_documen_30569b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['is_approved', 'is_reversed'], name='product_inv_is_appr_94d4e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryadjustmentitem',
            unique_together={('adjustment', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['warehouse', 'adjustment_date'], name='product_inv_warehou_009ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['status', 'adjustment_type'], name='product_inv_status_00ae6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expiryalert',
            unique_together={('batch', 'alert_type', 'alert_date')},
        ),
    ]
