# Generated by Django 5.2.17 on 2026-09-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryadjustment',
            options={'ordering': ['-adjustment_date', '-created_at'], 'permissions': [('approve_inventory_adjustment', 'اعتماد تسوية فروق الجرد المخزني')], 'verbose_name': 'تسوية مخزون', 'verbose_name_plural': 'تسويات المخزون'},
        ),
    ]
