# Generated by Django 5.2.17 on 2026-10-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_financialaccountrole'),
        ('product', '0003_alter_inventoryadjustment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_currency',
            field=models.ForeignKey(blank=True, help_text='العملة المرجعية الأساسية لتسعير هذا المنتج (افتراضياً: العملة الوظيفية للمنشأة)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_priced', to='financial.currency', verbose_name='عملة التسعير المرجعية'),
        ),
    ]
