# Generated by Django 4.2.26 on 2026-07-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_inventorymovement_batch_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="اسم الوحدة بالإنجليزية",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("purchase", "شراء"),
                    ("purchase_return", "مرتجع مشتريات"),
                    ("sale", "بيع"),
                    ("sale_return", "مرتجع مبيعات"),
                    ("transfer", "تحويل"),
                    ("adjustment", "جرد"),
                    ("opening", "رصيد"),
                    ("batch_voucher", "إذن جماعي"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=20,
                verbose_name="نوع المستند",
            ),
        ),
    ]
