# Generated by Django 4.2.26 on 2026-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_inventorycostlayer_warehouse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="purpose_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supplies_gifts", "مستلزمات ومهمات وهدايا"),
                    ("inventory_gain", "زيادة جرد"),
                    ("office_supplies", "مستلزمات إدارية"),
                    ("educational_supplies", "مستلزمات تعليمية"),
                    ("activity_materials", "خامات أنشطة"),
                    ("classroom_equipment", "تجهيزات فصول"),
                    ("maintenance", "صيانة"),
                    ("cleaning", "نظافة"),
                    ("samples", "عينات مجانية"),
                    ("exhibition", "معرض"),
                    ("advertising", "إعلانات"),
                    ("gifts", "هدايا"),
                    ("charity", "تبرع خيري"),
                    ("damage", "تلف"),
                    ("expired", "منتهي الصلاحية"),
                    ("theft", "سرقة/فقدان"),
                    ("inventory_loss", "نقص جرد"),
                ],
                help_text="غرض الإذن (يحدد الحساب المحاسبي المقابل)",
                max_length=30,
                null=True,
                verbose_name="غرض الإذن",
            ),
        ),
    ]
