# Generated by Django 4.2.23 on 2025-10-23 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_add_created_by_to_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
    ]
