# Generated by Django 4.2 on 2026-07-27
import re
from django.db import migrations
from django.utils import timezone


def seed_serial_numbers(apps, schema_editor):
    SerialNumber = apps.get_model("product", "SerialNumber")
    Sale = apps.get_model("sale", "Sale")
    JournalEntry = apps.get_model("financial", "JournalEntry")
    Purchase = apps.get_model("purchase", "Purchase")

    current_year = timezone.now().year

    # Helper function to extract numeric suffix
    def extract_max_number(queryset, field_name="number"):
        max_num = 0
        for obj in queryset:
            val = getattr(obj, field_name, "")
            if val:
                # Find all digit groups
                digits = re.findall(r"\d+", str(val))
                if digits:
                    # Take the last group of digits as sequence number
                    num = int(digits[-1])
                    if num > max_num:
                        max_num = num
        return max_num

    # 1. Seed Sale Serial
    sale_max = extract_max_number(Sale.objects.all())
    SerialNumber.objects.update_or_create(
        document_type="sale",
        year=current_year,
        defaults={"prefix": "SALE-", "last_number": sale_max},
    )

    # 2. Seed Journal Entry Serial
    je_max = extract_max_number(JournalEntry.objects.all())
    SerialNumber.objects.update_or_create(
        document_type="journal_entry",
        year=current_year,
        defaults={"prefix": "JE-", "last_number": je_max},
    )

    # 3. Seed Purchase Serial
    pur_max = extract_max_number(Purchase.objects.all())
    SerialNumber.objects.update_or_create(
        document_type="purchase",
        year=current_year,
        defaults={"prefix": "PUR-", "last_number": pur_max},
    )


def reverse_seed_serial_numbers(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_unit_name_en_alter_stockmovement_document_type"),
    ]

    operations = [
        migrations.RunPython(seed_serial_numbers, reverse_seed_serial_numbers),
    ]
