# Generated by Django 4.2.26 on 2026-07-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_seed_serial_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serialnumber",
            name="document_type",
            field=models.CharField(max_length=50, verbose_name="نوع المستند"),
        ),
        migrations.AlterField(
            model_name="serialnumber",
            name="prefix",
            field=models.CharField(blank=True, max_length=20, verbose_name="بادئة"),
        ),
    ]
