# Generated by Django 4.2.26 on 2026-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_serialnumber_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="اسم التصنيف بالإنجليزية",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="الوصف بالإنجليزية"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="اسم المنتج/الخدمة بالإنجليزية",
            ),
        ),
    ]
