# Generated by Django 4.2.26 on 2026-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_category_name_en_product_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="اسم التصنيف (عربي)"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="اسم التصنيف (English)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="الوصف (عربي)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="الوصف (English)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="الاسم (عربي)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="الاسم (English)"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=50, verbose_name="اسم الوحدة (عربي)"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="اسم الوحدة (English)",
            ),
        ),
    ]
