# Generated by Django 4.2.26 on 2026-08-04 12:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0012_bankreconciliationmatch_bankstatementbatch_and_more"),
        ("supplier", "0002_initial"),
        ("product", "0008_alter_category_name_alter_category_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم سطر أستاذ المخزون"
                    ),
                ),
                (
                    "movement_service_ref",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="مرجع خدمة الحركة"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "استلام مشتريات/توريد"),
                            ("ISSUE", "صرف مبيعات/تصدير"),
                            ("TRANSFER_IN", "تحويل وارد"),
                            ("TRANSFER_OUT", "تحويل صادر"),
                            ("ADJUSTMENT_IN", "تسوية تسليم/زيادة"),
                            ("ADJUSTMENT_OUT", "تسوية صرف/عجز"),
                            ("SCRAP", "تخريد/إتلاف"),
                            ("REVALUATION", "إعادة تقييم تكلفة"),
                        ],
                        max_length=30,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="موجب للوارد، سالب للمنصرف",
                        max_digits=15,
                        verbose_name="الكمية بوحدة القياس الأساسية",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="تكلفة الوحدة بالعملة الوظيفية",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "qty_balance_after",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="رصيد الكمية بعد الحركة (كاش)",
                    ),
                ),
                (
                    "val_balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="رصيد التقييم بعد الحركة (كاش)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "base_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.unit",
                        verbose_name="وحدة القياس الأساسية",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ledger_entries",
                        to="financial.journalentry",
                        verbose_name="قيد اليومية المالي المرتبط",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ledger_entries",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ledger_entries",
                        to="product.productvariant",
                        verbose_name="النوع/التباين",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_ledger_entries",
                        to="product.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر أستاذ المخزون",
                "verbose_name_plural": "أسطر أستاذ المخزون",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="LandedCostDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="رقم مستند التكاليف الإضافية",
                    ),
                ),
                (
                    "allocation_method",
                    models.CharField(
                        choices=[
                            ("QUANTITY", "حسب الكمية"),
                            ("WEIGHT", "حسب الوزن"),
                            ("VALUE", "حسب القيمة المالية"),
                        ],
                        default="VALUE",
                        max_length=20,
                        verbose_name="طريقة التوزيع",
                    ),
                ),
                (
                    "total_landed_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي التكاليف الإضافية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("POSTED", "مرحل وموزع"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.journalentry",
                        verbose_name="قيد التسوية المالي المرتبط",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier.supplier",
                        verbose_name="المورد/شركة الشحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند تكاليف إضافية",
                "verbose_name_plural": "مستندات التكاليف الإضافية",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LandedCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="التكلفة المخصصة الكلية",
                    ),
                ),
                (
                    "allocated_to_asset",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المحمل على أصل المخزون المتبقي",
                    ),
                ),
                (
                    "allocated_to_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المحمل على فروقات COGS للبضاعة المباعة",
                    ),
                ),
                (
                    "landed_cost_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="product.landedcostdocument",
                        verbose_name="مستند التكاليف الإضافية",
                    ),
                ),
                (
                    "stock_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landed_cost_allocations",
                        to="product.stockledgerentry",
                        verbose_name="سطر استلام الشحنة بأستاذ المخزون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تخصيص تكاليف إضافية",
                "verbose_name_plural": "سجلات تخصيص التكاليف الإضافية",
            },
        ),
        migrations.CreateModel(
            name="InventoryValuationAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم مستند التسوية"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("COST_REVALUATION", "إعادة تقييم تكلفة"),
                            ("DAMAGE_WRITE_OFF", "شطب تلفيات/أضرار"),
                            ("EXPIRY_SCRAP", "إتلاف انتهاء صلاحية"),
                            ("COUNT_VARIANCE", "تسوية فروق جرد"),
                        ],
                        max_length=30,
                        verbose_name="نوع التسوية",
                    ),
                ),
                (
                    "qty_adjusted",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المعدلة بالوحدة الأساسية",
                    ),
                ),
                (
                    "cost_adjusted",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ التكلفة المعدل",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب التسوية")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.accountingperiod",
                        verbose_name="الفترة المحاسبية المفتوحة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.journalentry",
                        verbose_name="قيد تسوية تقييم المخزون المالي",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_adjustments",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_adjustments",
                        to="product.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسوية تقييم مخزون",
                "verbose_name_plural": "تسويات تقييم المخزون",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCostLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_date",
                    models.DateTimeField(db_index=True, verbose_name="تاريخ الاستلام"),
                ),
                (
                    "original_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="الكمية الأصلية بالوحدة الأساسية",
                    ),
                ),
                (
                    "remaining_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="الكمية المتبقية بالوحدة الأساسية",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="تكلفة الوحدة بالعملة الوظيفية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "مفتوحة"), ("DEPLETED", "مستهلكة بالكامل")],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "stock_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="product.stockledgerentry",
                        verbose_name="سطر الاستلام بأستاذ المخزون",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layers",
                        to="product.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "طبقة تكلفة مخزون",
                "verbose_name_plural": "طبقات تكلفة المخزون",
                "ordering": ["receipt_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCostConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumption_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم تتبع الاستهلاك"
                    ),
                ),
                (
                    "consumed_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المستهلكة"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="تكلفة الوحدة المصروفة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي تكلفة الصرف (COGS)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "cost_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumptions",
                        to="product.inventorycostlayer",
                        verbose_name="طبقة التكلفة المصروف منها",
                    ),
                ),
                (
                    "stock_ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_consumptions",
                        to="product.stockledgerentry",
                        verbose_name="سطر الصرف بأستاذ المخزون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل استهلاك تكلفة",
                "verbose_name_plural": "سجلات استهلاك التكلفة",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockledgerentry",
            index=models.Index(
                fields=["product", "warehouse", "created_at"],
                name="product_sto_product_4935bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockledgerentry",
            index=models.Index(
                fields=["movement_service_ref"], name="product_sto_movemen_f847a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorycostlayer",
            index=models.Index(
                fields=["product", "warehouse", "status", "receipt_date"],
                name="product_inv_product_56cf33_idx",
            ),
        ),
    ]
