# Generated by Django 4.2.26 on 2026-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_stockledgerentry_landedcostdocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landedcostdocument",
            name="shipment_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="مرجع الشحنة/دورة الاستيراد"
            ),
        ),
    ]
