# Generated by Django 4.2.23 on 2025-10-06 09:58

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from decimal import Decimal
from django.core.validators import MinValueValidator
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_add_enhanced_inventory_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # إنشاء جدول ProductBatch
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "product_productbatch" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "batch_number" varchar(100) NOT NULL UNIQUE,
                "initial_quantity" integer unsigned NOT NULL CHECK ("initial_quantity" >= 0),
                "current_quantity" integer unsigned NOT NULL CHECK ("current_quantity" >= 0),
                "reserved_quantity" integer unsigned NOT NULL CHECK ("reserved_quantity" >= 0),
                "production_date" date,
                "expiry_date" date,
                "received_date" date NOT NULL,
                "unit_cost" decimal(12, 2) NOT NULL,
                "status" varchar(20) NOT NULL,
                "notes" text,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL,
                "product_id" bigint NOT NULL REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED,
                "warehouse_id" bigint NOT NULL REFERENCES "product_warehouse" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS product_productbatch;",
        ),
        # إنشاء جدول StockReservation
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "product_stockreservation" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "quantity" decimal(12, 3) NOT NULL,
                "reserved_for" varchar(255) NOT NULL,
                "reservation_type" varchar(20) NOT NULL,
                "status" varchar(20) NOT NULL,
                "expires_at" datetime,
                "notes" text,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL,
                "product_id" bigint NOT NULL REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED,
                "warehouse_id" bigint NOT NULL REFERENCES "product_warehouse" ("id") DEFERRABLE INITIALLY DEFERRED,
                "created_by_id" bigint NOT NULL REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS product_stockreservation;",
        ),
        # إنشاء جدول LocationZone
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "product_locationzone" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "name" varchar(100) NOT NULL,
                "code" varchar(20) NOT NULL,
                "description" text,
                "is_active" bool NOT NULL,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL,
                "warehouse_id" bigint NOT NULL REFERENCES "product_warehouse" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS product_locationzone;",
        ),
    ]
