# Generated by Django 4.2.26 on 2026-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_landedcostdocument_shipment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="valuation_method",
            field=models.CharField(
                choices=[
                    ("FIFO", "الوارد أولاً يصرف أولاً (FIFO)"),
                    ("MOVING_AVERAGE", "المتوسط المتحرك (AVCO)"),
                ],
                default="FIFO",
                help_text="طريقة تقييم تكلفة المخزون الصادر (FIFO أو AVCO)",
                max_length=20,
                verbose_name="طريقة التقييم المحاسبي",
            ),
        ),
    ]
