# Generated by Django 4.2.26 on 2026-08-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_product_valuation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="valuation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIFO", "الوارد أولاً يصرف أولاً (FIFO)"),
                    ("MOVING_AVERAGE", "المتوسط المتحرك (AVCO)"),
                ],
                help_text="سياسة التقييم المحاسبي الافتراضية لفئة المنتجات",
                max_length=20,
                null=True,
                verbose_name="طريقة التقييم المحاسبي الفئة",
            ),
        ),
    ]
