# Generated by Django 4.2.26 on 2026-08-04 15:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0019_salespolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0012_category_valuation_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="الكمية المحجوزة الكلية",
                    ),
                ),
                (
                    "fulfilled_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المستوفاة/المسلمة",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("PARTIALLY_FULFILLED", "مستوفى جزئياً"),
                            ("FULFILLED", "مستوفى بالكامل"),
                            ("RELEASED", "محرر"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="ACTIVE",
                        max_length=25,
                        verbose_name="حالة الحجز",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحجز"),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإفراج/الإلغاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_reservations",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reservations",
                        to="sale.salesorder",
                        verbose_name="أمر البيع",
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reservations",
                        to="sale.salesorderitem",
                        verbose_name="سطر أمر البيع",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_reservations",
                        to="product.warehouse",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "حجز مخزون أمر البيع",
                "verbose_name_plural": "حجوزات مخزون أوامر البيع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReservationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "إنشاء حجز"),
                            ("UPDATED", "تعديل حجز"),
                            ("PARTIALLY_FULFILLED", "استيفاء جزئي"),
                            ("FULFILLED", "استيفاء كامل"),
                            ("RELEASED", "إفراج عن حجز"),
                            ("CANCELLED", "إلغاء حجز"),
                        ],
                        max_length=25,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "previous_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية السابقة",
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية الجديدة",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="السبب / الملاحظات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإجراء"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="product.inventoryreservation",
                        verbose_name="الحجز المرتبط",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تدقيق حجز المخزون",
                "verbose_name_plural": "سجلات تدقيق حجوزات المخزون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["warehouse", "product", "reservation_status"],
                name="product_inv_warehou_14444f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["sales_order", "reservation_status"],
                name="product_inv_sales_o_1b64ec_idx",
            ),
        ),
    ]
