# Generated by Django 4.2.26 on 2026-08-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_inventoryreservation_inventoryreservationaudit_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                condition=models.Q(("reservation_status", "ACTIVE")),
                fields=["product", "warehouse", "created_at"],
                name="idx_inv_res_active_sweep",
            ),
        ),
    ]
