# Generated by Django 4.2.26 on 2026-08-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_inventorycostlayer_base_unit_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="valuation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIFO", "الوارد أولاً يصدر أولاً"),
                    ("MOVING_AVERAGE", "المتوسط المتحرك"),
                ],
                default="FIFO",
                max_length=20,
                null=True,
                verbose_name="طريقة تقييم المخزون الإفتراضية",
            ),
        ),
    ]
