# Generated by Django 4.2.26 on 2026-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_category_valuation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryreservation",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ وقت انتهاء صلاحية الحجز"
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "منخفض"),
                    ("NORMAL", "عادي"),
                    ("HIGH", "مرتفع"),
                    ("URGENT", "عاجل"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="أولوية الحجز",
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservation",
            name="reservation_source_type",
            field=models.CharField(
                choices=[
                    ("SALES_ORDER", "أمر بيع"),
                    ("PRODUCTION_ORDER", "أمر تصنيع"),
                    ("TRANSFER_ORDER", "أمر تحويل"),
                    ("MANUAL", "حجز يدوي"),
                ],
                default="SALES_ORDER",
                max_length=30,
                verbose_name="مصدر الحجز",
            ),
        ),
        migrations.AddField(
            model_name="inventoryreservationaudit",
            name="evidence_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="توقيع إثبات التدقيق SHA256",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservation",
            name="reservation_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "نشط"),
                    ("PARTIALLY_FULFILLED", "مستوفى جزئياً"),
                    ("FULFILLED", "مستوفى بالكامل"),
                    ("RELEASED", "محرر"),
                    ("CANCELLED", "ملغي"),
                    ("EXPIRED", "منتهي الصلاحية"),
                ],
                default="ACTIVE",
                max_length=25,
                verbose_name="حالة الحجز",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryreservationaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "إنشاء حجز"),
                    ("UPDATED", "تعديل حجز"),
                    ("PARTIALLY_FULFILLED", "استيفاء جزئي"),
                    ("FULFILLED", "استيفاء كامل"),
                    ("RELEASED", "إفراج عن حجز"),
                    ("CANCELLED", "إلغاء حجز"),
                    ("EXPIRED", "انقضاء صلاحية"),
                ],
                max_length=25,
                verbose_name="نوع الإجراء",
            ),
        ),
    ]
