# Generated by Django 4.2.26 on 2026-08-07 02:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0033_chartofaccounts_opening_balance_foreign_and_more"),
        ("product", "0017_inventoryreservation_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCurrencyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicative_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="سعر البيع المعتمد بالعملة المحددة",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "indicative_cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="سعر التكلفة المعتمد بالعملة المحددة",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="سعر التكلفة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سعر المنتج بالعملة",
                "verbose_name_plural": "أسعار المنتجات بالعملات",
                "ordering": ["product", "currency__code"],
            },
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_histories",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="document_reference",
            field=models.CharField(
                blank=True,
                help_text="رقم الفاتورة أو المستند المرجعي",
                max_length=100,
                null=True,
                verbose_name="مرجع المستند",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=18,
                null=True,
                verbose_name="سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="product.product",
                verbose_name="المنتج",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CATALOG_BASE", "كتالوج - السعر الأساسي EGP"),
                    ("CATALOG_FX", "كتالوج - سعر عملة أجنبية"),
                    ("SUPPLIER_PRICE", "سعر مورد"),
                    ("PURCHASE_INVOICE", "فاتورة مشتريات"),
                    ("SALE_INVOICE", "فاتورة مبيعات"),
                ],
                default="CATALOG_BASE",
                max_length=30,
                verbose_name="مصدر التغيير",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="change_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="مقدار التغيير",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="change_reason",
            field=models.CharField(
                choices=[
                    ("purchase", "شراء جديد"),
                    ("manual_update", "تحديث يدوي"),
                    ("supplier_notification", "إشعار من المورد"),
                    ("market_change", "تغيير السوق"),
                    ("bulk_update", "تحديث جماعي"),
                    ("system_sync", "مزامنة النظام"),
                    ("sale", "بيع"),
                ],
                default="manual_update",
                max_length=30,
                verbose_name="سبب التغيير",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="new_price",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="السعر الجديد",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name="السعر القديم",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="purchase_reference",
            field=models.CharField(
                blank=True,
                help_text="رقم فاتورة الشراء إذا كان التغيير بسبب شراء جديد",
                max_length=50,
                null=True,
                verbose_name="مرجع الشراء القديم",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="supplier_product_price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="product.supplierproductprice",
                verbose_name="سعر المنتج للمورد",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product", "-change_date"],
                name="product_pri_product_af5d00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["source_type"], name="product_pri_source__e300c9_idx"
            ),
        ),
        migrations.AddField(
            model_name="productcurrencyprice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_currency_prices_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="productcurrencyprice",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_prices",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="productcurrencyprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_prices",
                to="product.product",
                verbose_name="المنتج",
            ),
        ),
        migrations.AddField(
            model_name="productcurrencyprice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_currency_prices_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عُدل بواسطة",
            ),
        ),
        migrations.AddIndex(
            model_name="productcurrencyprice",
            index=models.Index(
                fields=["product", "currency"], name="product_pro_product_403af6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcurrencyprice",
            unique_together={("product", "currency")},
        ),
    ]
