# Generated by Django 4.2.26 on 2026-08-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0041_partnercurrencybalancesnapshot"),
        ("product", "0018_productcurrencyprice_pricehistory_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="financial.taxcode",
                verbose_name="كود الضريبة المعياري",
            ),
        ),
    ]
