# Generated by Django 4.2.23 on 2025-10-06 22:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supplier", "0004_supplier_financial_account"),
        ("client", "0004_customer_financial_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoatingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FinishingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PaperSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PaperType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlateServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlateSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PrintDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PrintSide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PricingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("offset", "أوفست"), ("digital", "ديجيتال")],
                        max_length=10,
                        verbose_name="نوع الطلب",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان الطلب")),
                ("description", models.TextField(blank=True, verbose_name="وصف الطلب")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "has_internal_content",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على محتوى داخلي"
                    ),
                ),
                (
                    "colors_front",
                    models.PositiveIntegerField(
                        default=4, verbose_name="عدد ألوان الوجه الأمامي"
                    ),
                ),
                (
                    "colors_back",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد ألوان الوجه الخلفي"
                    ),
                ),
                (
                    "press",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="نوع الماكينة"
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة الخامات",
                    ),
                ),
                (
                    "printing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة الطباعة",
                    ),
                ),
                (
                    "finishing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة خدمات الطباعة",
                    ),
                ),
                (
                    "extra_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكاليف إضافية",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        verbose_name="هامش الربح (%)",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="معتمد"),
                ),
                (
                    "is_executed",
                    models.BooleanField(default=False, verbose_name="منفذ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("executed", "منفذ"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التنفيذ"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الاعتماد بواسطة",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "coating_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coating_orders",
                        to="pricing.supplierservice",
                        verbose_name="خدمة التغطية",
                    ),
                ),
                (
                    "coating_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pricing.coatingtype",
                        verbose_name="نوع التغطية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
                (
                    "paper_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pricing.papersize",
                        verbose_name="مقاس المنتج",
                    ),
                ),
                (
                    "paper_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pricing.papertype",
                        verbose_name="نوع الورق",
                    ),
                ),
                (
                    "print_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pricing.printdirection",
                        verbose_name="اتجاه الطباعة",
                    ),
                ),
                (
                    "print_sides",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pricing.printside",
                        verbose_name="جوانب الطباعة",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تسعير",
                "verbose_name_plural": "طلبات التسعير",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderFinishing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="السعر الإجمالي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "finishing_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_services",
                        to="pricing.finishingtype",
                        verbose_name="نوع خدمات مابعد الطباعة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishing_services",
                        to="pricing.pricingorder",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "supplier_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_services",
                        to="pricing.supplierservice",
                        verbose_name="خدمة المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تشطيب الطلب",
                "verbose_name_plural": "تشطيبات الطلب",
            },
        ),
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="التعليق")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pricing.pricingorder",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق الطلب",
                "verbose_name_plural": "تعليقات الطلب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الصفحات",
                    ),
                ),
                (
                    "colors_front",
                    models.PositiveIntegerField(
                        default=4, verbose_name="عدد ألوان الوجه الأمامي"
                    ),
                ),
                (
                    "colors_back",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد ألوان الوجه الخلفي"
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة الخامات",
                    ),
                ),
                (
                    "printing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة الطباعة",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_content",
                        to="pricing.pricingorder",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "paper_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_contents",
                        to="pricing.papersize",
                        verbose_name="مقاس المنتج",
                    ),
                ),
                (
                    "paper_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_contents",
                        to="pricing.papertype",
                        verbose_name="نوع الورق",
                    ),
                ),
                (
                    "print_sides",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_contents",
                        to="pricing.printside",
                        verbose_name="جوانب الطباعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "محتوى داخلي",
                "verbose_name_plural": "محتويات داخلية",
            },
        ),
        migrations.CreateModel(
            name="ExtraExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المصروف")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_expenses",
                        to="pricing.pricingorder",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف إضافي",
                "verbose_name_plural": "مصاريف إضافية",
            },
        ),
        migrations.CreateModel(
            name="CtpPlates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="للمحتوى الداخلي"),
                ),
                (
                    "plates_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الزنكات",
                    ),
                ),
                (
                    "plate_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الزنك"
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="تكلفة الانتقالات",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ctp_plates",
                        to="pricing.pricingorder",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "plate_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_plates",
                        to="pricing.platesize",
                        verbose_name="مقاس الزنك",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_plates",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "زنك CTP",
                "verbose_name_plural": "زنكات CTP",
            },
        ),
    ]
