# Generated by Django 4.2.7 on 2025-10-07 13:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_customer_financial_account"),
        ("supplier", "0005_add_pricing_services_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pricing", "0005_add_client_fields_to_pricingorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coatingtype",
            options={
                "ordering": ["name"],
                "verbose_name": "نوع التغطية",
                "verbose_name_plural": "أنواع التغطية",
            },
        ),
        migrations.AlterModelOptions(
            name="finishingtype",
            options={
                "ordering": ["name"],
                "verbose_name": "نوع التشطيب",
                "verbose_name_plural": "أنواع التشطيب",
            },
        ),
        migrations.AlterModelOptions(
            name="papersize",
            options={
                "ordering": ["name"],
                "verbose_name": "مقاس الورق",
                "verbose_name_plural": "مقاسات الورق",
            },
        ),
        migrations.AlterModelOptions(
            name="papertype",
            options={
                "ordering": ["name"],
                "verbose_name": "نوع الورق",
                "verbose_name_plural": "أنواع الورق",
            },
        ),
        migrations.AlterModelOptions(
            name="plateservicedetails",
            options={
                "ordering": ["supplier", "plate_size"],
                "verbose_name": "تفاصيل خدمة الزنك",
                "verbose_name_plural": "تفاصيل خدمات الزنكات",
            },
        ),
        migrations.AlterModelOptions(
            name="platesize",
            options={
                "ordering": ["name"],
                "verbose_name": "مقاس الزنك",
                "verbose_name_plural": "مقاسات الزنكات",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingapproval",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "موافقة التسعير",
                "verbose_name_plural": "موافقات التسعير",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingapprovalworkflow",
            options={
                "ordering": ["name"],
                "verbose_name": "تدفق الموافقات",
                "verbose_name_plural": "تدفقات الموافقات",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingkpi",
            options={
                "ordering": ["-date"],
                "verbose_name": "مؤشر أداء التسعير",
                "verbose_name_plural": "مؤشرات أداء التسعير",
            },
        ),
        migrations.AlterModelOptions(
            name="pricingreport",
            options={
                "ordering": ["-generated_at"],
                "verbose_name": "تقرير التسعير",
                "verbose_name_plural": "تقارير التسعير",
            },
        ),
        migrations.AlterModelOptions(
            name="printdirection",
            options={
                "ordering": ["name"],
                "verbose_name": "اتجاه الطباعة",
                "verbose_name_plural": "اتجاهات الطباعة",
            },
        ),
        migrations.AlterModelOptions(
            name="printside",
            options={
                "ordering": ["name"],
                "verbose_name": "جانب الطباعة",
                "verbose_name_plural": "جوانب الطباعة",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierservice",
            options={
                "ordering": ["supplier", "service_type", "name"],
                "verbose_name": "خدمة المورد",
                "verbose_name_plural": "خدمات الموردين",
            },
        ),
        migrations.RemoveConstraint(
            model_name="digitalprintingdetails",
            name="unique_digital_service",
        ),
        migrations.RemoveConstraint(
            model_name="paperservicedetails",
            name="unique_paper_service",
        ),
        migrations.RenameField(
            model_name="pricingapproval",
            old_name="created_at",
            new_name="requested_at",
        ),
        migrations.RenameField(
            model_name="pricingreport",
            old_name="created_at",
            new_name="generated_at",
        ),
        migrations.AlterUniqueTogether(
            name="pricingapproval",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="kpi_type",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="period_end",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="period_start",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="period_type",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="target_value",
        ),
        migrations.RemoveField(
            model_name="pricingkpi",
            name="value",
        ),
        migrations.AddField(
            model_name="coatingtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coatingtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="coatingtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="finishingtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإنشاء",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finishingtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="finishingtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="papersize",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="papersize",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="الطول (سم)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="papersize",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="papersize",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
        migrations.AddField(
            model_name="papersize",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="العرض (سم)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="papertype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="papertype",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="papertype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="papertype",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="minimum_quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="الحد الأدنى للكمية"
            ),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="plate_size",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="pricing.platesize",
                verbose_name="مقاس الزنك",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="price_per_plate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="سعر الزنك",
            ),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="setup_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="تكلفة الإعداد",
            ),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plate_services",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="transportation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="تكلفة النقل",
            ),
        ),
        migrations.AddField(
            model_name="plateservicedetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddField(
            model_name="platesize",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platesize",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="الطول (سم)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platesize",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="platesize",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="العرض (سم)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingapproval",
            name="approval_level",
            field=models.CharField(
                choices=[
                    ("primary", "أساسي"),
                    ("secondary", "ثانوي"),
                    ("final", "نهائي"),
                ],
                default="primary",
                max_length=20,
                verbose_name="مستوى الموافقة",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingapproval",
            name="notification_method",
            field=models.CharField(
                choices=[
                    ("email", "بريد إلكتروني"),
                    ("whatsapp", "واتساب"),
                    ("both", "كلاهما"),
                    ("none", "بدون إشعار"),
                ],
                default="email",
                max_length=20,
                verbose_name="طريقة الإشعار",
            ),
        ),
        migrations.AddField(
            model_name="pricingapproval",
            name="notification_sent",
            field=models.BooleanField(default=False, verbose_name="تم إرسال الإشعار"),
        ),
        migrations.AddField(
            model_name="pricingapproval",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ إرسال الإشعار"
            ),
        ),
        migrations.AddField(
            model_name="pricingapproval",
            name="responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الرد"
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="accepted_quotations",
            field=models.PositiveIntegerField(
                default=0, verbose_name="العروض المقبولة"
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="accepted_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="قيمة العروض المقبولة",
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="active_clients",
            field=models.PositiveIntegerField(default=0, verbose_name="عملاء نشطين"),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="active_suppliers",
            field=models.PositiveIntegerField(default=0, verbose_name="موردين نشطين"),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="average_order_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="متوسط قيمة الطلب",
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="average_profit_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="متوسط هامش الربح %",
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="average_response_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="متوسط وقت الرد (أيام)"
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name="التاريخ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="expired_quotations",
            field=models.PositiveIntegerField(
                default=0, verbose_name="العروض المنتهية الصلاحية"
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="new_clients",
            field=models.PositiveIntegerField(default=0, verbose_name="عملاء جدد"),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="pending_quotations",
            field=models.PositiveIntegerField(default=0, verbose_name="العروض المعلقة"),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="rejected_quotations",
            field=models.PositiveIntegerField(
                default=0, verbose_name="العروض المرفوضة"
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="rejected_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="قيمة العروض المرفوضة",
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="success_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="معدل النجاح %",
            ),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="total_quotations",
            field=models.PositiveIntegerField(default=0, verbose_name="إجمالي العروض"),
        ),
        migrations.AddField(
            model_name="pricingkpi",
            name="total_quoted_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="إجمالي قيمة العروض",
            ),
        ),
        migrations.AddField(
            model_name="pricingreport",
            name="is_scheduled",
            field=models.BooleanField(default=False, verbose_name="تقرير مجدول"),
        ),
        migrations.AddField(
            model_name="pricingreport",
            name="schedule_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "يومي"),
                    ("weekly", "أسبوعي"),
                    ("monthly", "شهري"),
                    ("quarterly", "ربع سنوي"),
                ],
                max_length=10,
                verbose_name="تكرار الجدولة",
            ),
        ),
        migrations.AddField(
            model_name="pricingreport",
            name="summary",
            field=models.TextField(blank=True, verbose_name="ملخص التقرير"),
        ),
        migrations.AddField(
            model_name="printdirection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printdirection",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="printdirection",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="printdirection",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
        migrations.AddField(
            model_name="printside",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printside",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="printside",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="printside",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="minimum_quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="الحد الأدنى للكمية"
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("coating", "تغطية"),
                    ("folding", "طي"),
                    ("die_cut", "قص"),
                    ("spot_uv", "ورنيش موضعي"),
                    ("binding", "تجليد"),
                    ("other", "أخرى"),
                ],
                default="coating",
                max_length=20,
                verbose_name="نوع الخدمة",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="سعر الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="coatingtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم نوع التغطية"),
        ),
        migrations.AlterField(
            model_name="finishingtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم نوع التشطيب"),
        ),
        migrations.AlterField(
            model_name="papersize",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم المقاس"),
        ),
        migrations.AlterField(
            model_name="papertype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم نوع الورق"),
        ),
        migrations.AlterField(
            model_name="platesize",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم مقاس الزنك"),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعتمد",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="comments",
            field=models.TextField(blank=True, verbose_name="تعليقات"),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "منخفضة"),
                    ("normal", "عادية"),
                    ("high", "عالية"),
                    ("urgent", "عاجلة"),
                ],
                default="normal",
                max_length=10,
                verbose_name="الأولوية",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="طلب الموافقة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "في الانتظار"),
                    ("approved", "معتمد"),
                    ("rejected", "مرفوض"),
                    ("cancelled", "ملغي"),
                ],
                default="pending",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapproval",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pricing.pricingapprovalworkflow",
                verbose_name="تدفق الموافقة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapprovalworkflow",
            name="auto_approve_below_limit",
            field=models.BooleanField(
                default=False, verbose_name="موافقة تلقائية تحت الحد الأدنى"
            ),
        ),
        migrations.AlterField(
            model_name="pricingapprovalworkflow",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapprovalworkflow",
            name="primary_approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_approval_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعتمد الأساسي",
            ),
        ),
        migrations.AlterField(
            model_name="pricingapprovalworkflow",
            name="require_both_approvers",
            field=models.BooleanField(
                default=False, verbose_name="يتطلب موافقة المعتمدين"
            ),
        ),
        migrations.AlterField(
            model_name="pricingapprovalworkflow",
            name="secondary_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_approval_workflows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعتمد الثانوي",
            ),
        ),
        migrations.AlterField(
            model_name="pricingquotation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_quotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingquotation",
            name="delivery_terms",
            field=models.TextField(
                default="التسليم خلال 7-10 أيام عمل", verbose_name="شروط التسليم"
            ),
        ),
        migrations.AlterField(
            model_name="pricingquotation",
            name="payment_terms",
            field=models.TextField(
                default="50% مقدم، 50% عند التسليم", verbose_name="شروط الدفع"
            ),
        ),
        migrations.AlterField(
            model_name="pricingquotation",
            name="sent_to_person",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="تم الإرسال إلى"
            ),
        ),
        migrations.AlterField(
            model_name="pricingquotation",
            name="sent_via",
            field=models.CharField(
                choices=[
                    ("email", "بريد إلكتروني"),
                    ("whatsapp", "واتساب"),
                    ("hand_delivery", "تسليم يد"),
                    ("fax", "فاكس"),
                    ("postal", "بريد عادي"),
                    ("phone", "هاتف"),
                ],
                default="email",
                max_length=20,
                verbose_name="طريقة الإرسال",
            ),
        ),
        migrations.AlterField(
            model_name="pricingreport",
            name="client_filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.customer",
                verbose_name="فلتر العميل",
            ),
        ),
        migrations.AlterField(
            model_name="pricingreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="pricingreport",
            name="order_type_filter",
            field=models.CharField(
                blank=True,
                choices=[("offset", "أوفست"), ("digital", "ديجيتال")],
                max_length=10,
                verbose_name="فلتر نوع الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="pricingreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("client_analysis", "تحليل العملاء"),
                    ("supplier_comparison", "مقارنة الموردين"),
                    ("pricing_trends", "اتجاهات التسعير"),
                    ("quotation_success", "معدل نجاح العروض"),
                    ("profit_analysis", "تحليل الربحية"),
                    ("monthly_summary", "ملخص شهري"),
                    ("quarterly_summary", "ملخص ربع سنوي"),
                ],
                max_length=20,
                verbose_name="نوع التقرير",
            ),
        ),
        migrations.AlterField(
            model_name="pricingreport",
            name="supplier_filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplier",
                verbose_name="فلتر المورد",
            ),
        ),
        migrations.AlterField(
            model_name="printdirection",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم الاتجاه"),
        ),
        migrations.AlterField(
            model_name="printside",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم الجانب"),
        ),
        migrations.AlterField(
            model_name="supplierservice",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم الخدمة"),
        ),
        migrations.AlterUniqueTogether(
            name="digitalprintingdetails",
            unique_together={("supplier", "paper_size", "color_type")},
        ),
        migrations.AlterUniqueTogether(
            name="paperservicedetails",
            unique_together={
                ("supplier", "paper_type", "paper_size", "weight", "origin")
            },
        ),
        migrations.AlterUniqueTogether(
            name="plateservicedetails",
            unique_together={("supplier", "plate_size")},
        ),
        migrations.AlterUniqueTogether(
            name="pricingapproval",
            unique_together={("pricing_order", "approver", "approval_level")},
        ),
        migrations.RemoveField(
            model_name="plateservicedetails",
            name="name",
        ),
        migrations.RemoveField(
            model_name="pricingapproval",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="pricingapproval",
            name="updated_at",
        ),
    ]
