# Generated by Django 4.2.23 on 2025-10-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0013_add_digital_machine_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الوزن")),
                (
                    "gsm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)],
                        verbose_name="الوزن (جرام)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "وزن الورق",
                "verbose_name_plural": "أوزان الورق",
                "ordering": ["gsm"],
                "unique_together": {("gsm",)},
            },
        ),
    ]
