# Generated by Django 4.2.23 on 2025-10-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0017_pricingorder_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingorder",
            name="paper_size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pricing.productsize",
                verbose_name="مقاس المنتج",
            ),
        ),
    ]
