# Generated by Django 4.2.7 on 2025-10-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0026_update_coating_terminology"),
        ("pricing", "0019_update_coating_terminology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingorder",
            name="coating_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coating_orders",
                to="supplier.specializedservice",
                verbose_name="خدمة التغطية",
            ),
        ),
    ]
