# Generated by Django 4.2.7 on 2025-10-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0020_alter_pricingorder_coating_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="coatingtype",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="افتراضي"),
        ),
    ]
