# Generated by Django 4.2.7 on 2025-10-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0021_add_is_default_to_coating_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingorder",
            name="paper_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pricing.papertype",
                verbose_name="نوع الورق",
            ),
        ),
    ]
