# Generated by Django 4.2.23 on 2025-10-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_remove_design_fields'),
        ('pricing', '0023_merge_20251016_0259'),
    ]

    operations = [
    ]
