# Generated by Django 4.2.23 on 2025-10-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_restore_design_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printside',
            options={'ordering': ['id'], 'verbose_name': 'جانب الطباعة', 'verbose_name_plural': 'جوانب الطباعة'},
        ),
        migrations.RenameField(
            model_name='internalcontent',
            old_name='paper_size',
            new_name='product_size',
        ),
        migrations.RenameField(
            model_name='pricingorder',
            old_name='paper_size',
            new_name='product_size',
        ),
    ]
