# Generated by Django 4.2.23 on 2025-10-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_rename_paper_size_to_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontent',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_contents', to='pricing.papersize', verbose_name='مقاس المنتج'),
        ),
        migrations.AlterField(
            model_name='pricingorder',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pricing.productsize', verbose_name='مقاس المنتج'),
        ),
    ]
