# Generated by Django 4.2.23 on 2025-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_allow_null_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingorder',
            name='piece_size',
            field=models.CharField(blank=True, choices=[('', '-- اختر مقاس القطع --'), ('A4', 'A4 (21×29.7 سم)'), ('A5', 'A5 (14.8×21 سم)'), ('A6', 'A6 (10.5×14.8 سم)'), ('10x15', '10×15 سم'), ('15x20', '15×20 سم'), ('20x30', '20×30 سم'), ('custom', 'مقاس مخصص')], max_length=50, null=True, verbose_name='مقاس القطع'),
        ),
    ]
