# Generated by Django 4.2.23 on 2025-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0028_pricingorder_piece_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقاس')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('paper_type', models.CharField(blank=True, choices=[('100x70', 'فرخ كامل 100×70'), ('101x70', 'فرخ كامل 101×70'), ('102x70', 'فرخ كامل 102×70'), ('103x70', 'فرخ كامل 103×70'), ('104x70', 'فرخ كامل 104×70'), ('105x70', 'فرخ كامل 105×70'), ('88x66', 'فرخ جائر 88×66'), ('89x66', 'فرخ جائر 89×66'), ('90x66', 'فرخ جائر 90×66'), ('85x60', 'فرخ طبع جائر 85×60'), ('86x60', 'فرخ طبع جائر 86×60'), ('87x60', 'فرخ طبع جائر 87×60')], max_length=50, verbose_name='نوع الورق الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مقاس القطع',
                'verbose_name_plural': 'مقاسات القطع',
                'ordering': ['paper_type', 'name'],
            },
        ),
    ]
