# Generated by Django 4.2.23 on 2025-10-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_piecesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecesize',
            name='paper_type',
            field=models.ForeignKey(blank=True, help_text='مقاس الورق الذي يناسب هذا المقاس من القطع', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.papersize', verbose_name='مقاس الورق الأساسي'),
        ),
    ]
