# Generated by Django 4.2.23 on 2025-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0030_alter_piecesize_paper_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piecesize',
            options={'ordering': ['name'], 'verbose_name': 'مقاس القطع', 'verbose_name_plural': 'مقاسات القطع'},
        ),
        migrations.RemoveField(
            model_name='piecesize',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='piecesize',
            name='paper_types',
            field=models.ManyToManyField(blank=True, help_text='مقاسات الورق التي تناسب هذا المقاس من القطع', related_name='piece_sizes', to='pricing.papersize', verbose_name='مقاسات الورق الأساسية'),
        ),
    ]
