# Generated by Django 4.2.23 on 2025-10-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0031_alter_piecesize_options_remove_piecesize_paper_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecesize',
            name='paper_types',
        ),
    ]
