# Generated by Django 4.2.23 on 2025-10-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0032_remove_piecesize_paper_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecesize',
            name='paper_type',
            field=models.ForeignKey(blank=True, help_text='مقاس الورق الأساسي المناسب لهذا المقاس من القطع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_sizes', to='pricing.papersize', verbose_name='مقاس الورق الأساسي'),
        ),
    ]
