# Generated by Django 4.2.23 on 2025-10-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_piecesize_paper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecesize',
            name='pieces_per_sheet',
            field=models.PositiveIntegerField(blank=True, help_text='عدد القطع التي يمكن قطعها من فرخ واحد من مقاس الورق الأساسي', null=True, verbose_name='عدد القطع في الفرخ'),
        ),
    ]
