"""
Django settings for corporate_erp project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# إعداد PyMySQL كبديل لـ mysqlclient للتوافق مع cPanel
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

from pathlib import Path
import os
import sys
import environ
import warnings
from celery.schedules import crontab

# ✅ PHASE 2: Import connection error types for Redis configuration
try:
    from redis.exceptions import ConnectionError, TimeoutError
except ImportError:
    # Fallback for older Redis versions
    ConnectionError = Exception
    TimeoutError = Exception

# إخفاء تحذيرات smart_selects المتعلقة بـ pkg_resources أثناء التطوير
warnings.filterwarnings(
    "ignore",
    message="pkg_resources is deprecated as an API",
    category=UserWarning,
    module="smart_selects",
)

# إخفاء تحذيرات widget_tweaks المتعلقة بـ pkg_resources
warnings.filterwarnings(
    "ignore", 
    message="pkg_resources is deprecated as an API",
    category=UserWarning,
    module="widget_tweaks"
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists - prevents crash on first log write
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Testing environment detection
TESTING = 'test' in sys.argv or env.bool("TESTING", default=False)

# قراءة ALLOWED_HOSTS من .env
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "testserver"])

# إضافة testserver للاختبارات
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# Site URL Configuration
# Used for generating absolute URLs (e.g., QR codes, emails)
SITE_URL = env("SITE_URL", default="http://127.0.0.1:8000")

# CSRF Settings for Production
# بناء CSRF_TRUSTED_ORIGINS تلقائياً من ALLOWED_HOSTS
CSRF_TRUSTED_ORIGINS = []
for host in ALLOWED_HOSTS:
    if host not in ["localhost", "127.0.0.1", "*"]:
        CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{host}")
    else:
        CSRF_TRUSTED_ORIGINS.append(f"http://{host}:8000")
        CSRF_TRUSTED_ORIGINS.append(f"http://{host}")

# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Third party apps
    'corsheaders',  # ✅ SECURITY: CORS headers for API security
    'django_bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    'django_tables2',
    'widget_tweaks',
    'mptt',
    'import_export',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'simple_history',  # ❌ DISABLED - no HistoricalRecords in any model
    'bootstrap_datepicker_plus',
    'compressor',
    'smart_selects',
    'colorfield',
    'django_select2',
    
    # Project apps
    'core.apps.CoreConfig',
    'users',
    'governance.apps.GovernanceConfig',
    'client',  # ✅ Client/Customer management
    'sale',    # ✅ Sales management
    'supplier',
    'product.apps.ProductConfig',
    'printing_pricing',  # نظام تسعير المطبوعات
    'purchase',
    'financial',
    'hr.apps.HrConfig',
    'utils',
    'api',
]

MIDDLEWARE = [
    # ✅ PERFORMANCE: Optimized middleware - reduced from 24 to 12
    # Core Django (8)
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    # Essential Custom (4)
    "core.middleware.current_user.CurrentUserMiddleware",
    "core.middleware.security_headers.AdvancedSecurityHeadersMiddleware",
    # "simple_history.middleware.HistoryRequestMiddleware",  # ❌ DISABLED - no HistoricalRecords in any model
    "corsheaders.middleware.CorsMiddleware",
]

# تعطيل Debug Toolbar مؤقتا
ENABLE_DEBUG_TOOLBAR = False  # تغيير إلى True لإعادة تفعيل Debug Toolbar

if DEBUG and ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "corporate_erp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Core Django (4) - ضروري
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                
                # Custom (3 فقط) - الأساسي - Memory optimization
                "core.context_processors_optimized.global_settings",
                "core.context_processors_optimized.payment_accounts",
                "utils.context_processors.common_variables",
                
                # ❌ REMOVED - مكرر أو غير ضروري - Memory optimization
                # "core.context_processors.user_permissions",  # مكرر مع auth
                # "core.context_processors.notifications",  # مش مفعل
                # "core.context_processors.enabled_modules",  # نادر الاستخدام
                # "utils.context_processors.user_permissions",  # مكرر
                # "utils.context_processors.breadcrumb_context",  # يدوي أفضل
            ],
        },
    },
]

WSGI_APPLICATION = "corporate_erp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if env("DB_ENGINE", default="sqlite") == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT"),
            "ATOMIC_REQUESTS": True,
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES', NAMES 'utf8mb4'",
                "connect_timeout": 10,
                "read_timeout": 60,
                "write_timeout": 60,
                "use_unicode": True,
            },
            # ✅ PHASE 1: Optimized for cPanel shared hosting
            # CONN_MAX_AGE=0 prevents "Command Out of Sync" on shared hosting
            # where persistent connections cause MySQL state corruption between requests
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": True,  # Verify connection health before use
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "ATOMIC_REQUESTS": True,  # ✅ PHASE 2: Enable atomic requests for reliability
            "OPTIONS": {
                "timeout": 30,  # ✅ PHASE 2: Set query timeout to 30 seconds
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# اللغات المدعومة
LANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
]

# مسار ملفات الترجمة
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = "Africa/Cairo"

USE_I18N = True

USE_TZ = True

# تنسيق التاريخ والوقت المخصص
# USE_L10N = False  # تم إزالة هذا الإعداد لأنه deprecated في Django 5.0
DATE_FORMAT = "d/m/Y"  # تنسيق التاريخ: يوم/شهر/سنة
DATETIME_FORMAT = "d/m/Y H:i"  # تنسيق التاريخ والوقت
SHORT_DATE_FORMAT = "d/m/Y"  # تنسيق التاريخ المختصر
SHORT_DATETIME_FORMAT = "d/m/Y H:i"  # تنسيق التاريخ والوقت المختصر


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Bridge Agent Configuration
# قراءة من .env بصيغة: AGENT_CODE:SECRET_KEY,AGENT_CODE2:SECRET_KEY2
bridge_agents_str = env("BRIDGE_AGENTS", default="")
BRIDGE_AGENTS = {}
if bridge_agents_str:
    for agent in bridge_agents_str.split(","):
        if ":" in agent:
            code, secret = agent.strip().split(":", 1)
            BRIDGE_AGENTS[code.strip()] = secret.strip()

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# Django Compressor settings
COMPRESS_ENABLED = False  # whitenoise handles compression at collectstatic - better than runtime
COMPRESS_CSS_FILTERS = [
    "compressor.filters.css_default.CssAbsoluteFilter",
    "compressor.filters.cssmin.rCSSMinFilter",
]
COMPRESS_JS_FILTERS = ["compressor.filters.jsmin.JSMinFilter"]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# User model
AUTH_USER_MODEL = "users.User"

# Authentication Backends - يدعم Role-based permissions
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'users.backends.RolePermissionBackend',
]

# Login and logout URLs
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# CSRF settings
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# ✅ SECURITY: HTTPS and security headers configuration from environment
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=True)

# ✅ SECURITY: Session and CSRF cookies security
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = env.bool("SESSION_COOKIE_HTTPONLY", default=True)
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Strict")
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_HTTPONLY = env.bool("CSRF_COOKIE_HTTPONLY", default=True)

# ✅ SECURITY: Session timeout reduced to 30 minutes for production security
SESSION_COOKIE_AGE = env.int("SESSION_COOKIE_AGE", default=1800)  # 30 minutes instead of 1 hour
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ✅ File upload security - أمان رفع الملفات
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB في الذاكرة
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB إجمالي
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000  # increased from 100 - admin permissions forms need more
FILE_UPLOAD_PERMISSIONS = 0o644  # صلاحيات الملفات المرفوعة

# Email settings
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="")
SERVER_EMAIL = env("SERVER_EMAIL", default="")
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=30)

# MPTT settings
MPTT_ADMIN_LEVEL_INDENT = 20

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "burst": "60/min",
        "sustained": "1000/day",
        "login": "5/min",
        "register": "3/hour",
        "import_export": "10/hour",
        "report": "30/hour",
        # ✅ إضافة rates للـ JWT Token endpoints
        "token_obtain": "5/min",
        "token_refresh": "10/min",
        "token_verify": "20/min",
    },
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # ✅ استخدام OpenAPI بدلاً من CoreAPI (يحل مشكلة الـ 30 warnings)
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
    # Disable BrowsableAPIRenderer - reduces memory per API call
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    # ✅ تم تقصير المدة للأمان - من ساعة إلى 15 دقيقة
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # ✅ تم تقصير المدة للأمان - من 7 أيام إلى يوم واحد
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(hours=1),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    # Custom serializer مع claims إضافية
    "TOKEN_OBTAIN_SERIALIZER": "users.jwt_serializers.CustomTokenObtainPairSerializer",
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Messages settings - Bootstrap classes
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# Cache settings: Redis for production, LocMem for development
# Redis provides better performance and persistence for production environments
REDIS_URL = env("REDIS_URL", default=None)

if REDIS_URL and not DEBUG:
    # Production: Use Redis for caching with optimized connection pooling for cPanel
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 3600,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 20,
                    "retry_on_timeout": True,
                },
                "SOCKET_CONNECT_TIMEOUT": 2,
                "SOCKET_TIMEOUT": 2,
                "RETRY_ON_TIMEOUT": True,
            },
            "KEY_PREFIX": "corporate_erp",
            "VERSION": 1,
        },
    }

    # Use Redis for session storage in production
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Development: Use local memory cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-erp-local",
            "TIMEOUT": 300,  # 5 minutes
            "OPTIONS": {
                "MAX_ENTRIES": 1000,
            },
        }
    }

# Ensure django-select2 uses the default cache backend
SELECT2_CACHE_BACKEND = "default"

# ==============================================================================
# SENTRY ERROR TRACKING
# ==============================================================================
# Sentry configuration for error tracking in production
# Get your DSN from https://sentry.io after creating a project
SENTRY_DSN = env("SENTRY_DSN", default=None)

if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    
    # Configure Sentry
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                level=None,  # Capture all log levels
                event_level=None  # Send all events
            ),
        ],
        # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
        # Adjust this value in production.
        traces_sample_rate=0.1,  # 10% of transactions
        
        # Set profiles_sample_rate to 1.0 to profile 100% of sampled transactions.
        # Adjust this value in production.
        profiles_sample_rate=0.1,  # 10% of transactions
        
        # Send default PII (Personally Identifiable Information)
        send_default_pii=False,
        
        # Environment
        environment="production" if not DEBUG else "development",
        
        # Release tracking
        release=env("RELEASE_VERSION", default="1.0.0"),
        
        # Before send callback to filter sensitive data
        before_send=lambda event, hint: event if not DEBUG else None,
    )
    
    print("[OK] Sentry Error Tracking initialized successfully")


# Logging Configuration
# حل جذري لمشكلة UnicodeEncodeError في Windows
import sys
import logging.handlers

# إعدادات اللوجات المحسنة للإنتاج والتطوير
if DEBUG:
    # إعدادات التطوير - لوجات مفصلة
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '[{levelname}] {asctime} {module} {message}',
                'style': '{',
            },
            'simple': {
                'format': '[{levelname}] {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
                'stream': sys.stdout,
            },
            'file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'django.log',
                'maxBytes': 50 * 1024 * 1024,  # 50 MB
                'backupCount': 3,
                'formatter': 'verbose',
                'encoding': 'utf-8',
            },
            'daftra_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'daftra_sync.log',
                'maxBytes': 10 * 1024 * 1024,  # 10 MB
                'backupCount': 5,
                'formatter': 'verbose',
                'encoding': 'utf-8',
            },
        },
        'root': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
            'product': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
            'financial': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
            'hr': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
            # Suppress noisy startup/registration INFO logs from governance
            'governance': {
                'handlers': ['file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }
else:
    # إعدادات الإنتاج - لوجات محسنة ومحدودة
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'production': {
                'format': '[{levelname}] {asctime} {name} {message}',
                'style': '{',
            },
            'simple': {
                'format': '[{levelname}] {message}',
                'style': '{',
            },
        },
        'handlers': {
            # ملف اللوجات الأساسي مع rotation
            'main_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'django.log',
                'maxBytes': 10 * 1024 * 1024,  # 10 MB
                'backupCount': 5,
                'formatter': 'production',
                'encoding': 'utf-8',
            },
            # ملف الأخطاء فقط
            'error_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'errors.log',
                'maxBytes': 5 * 1024 * 1024,  # 5 MB
                'backupCount': 3,
                'formatter': 'production',
                'encoding': 'utf-8',
                'level': 'ERROR',
            },
            # Console للأخطاء الحرجة فقط - نستخدم NullHandler لتجنب مشاكل encoding
            'console': {
                'class': 'logging.NullHandler',
            },
            # ملف مزامنة دفترة
            'daftra_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'daftra_sync.log',
                'maxBytes': 10 * 1024 * 1024,  # 10 MB
                'backupCount': 5,
                'formatter': 'production',
                'encoding': 'utf-8',
            },
        },
        'root': {
            'handlers': ['main_file'],
            'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
        },
        'loggers': {
            # Django - ERROR فقط في production للأداء الأمثل
            'django': {
                'handlers': ['main_file', 'error_file'],
                'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
                'propagate': False,
            },
            # Governance - تقليل اللوجات المتكررة
            'governance_switchboard': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'signal_router': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'governance_monitoring': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'authority_service': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            # Monitoring Services - تقليل اللوجات المتكررة
            'monitoring_service': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'governance.payroll_signal_governance': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'payroll_signals': {
                'handlers': ['error_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            # Biometric API - ERROR فقط للأداء
            'biometric_api': {
                'handlers': ['error_file'],
                'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
                'propagate': False,
            },
            # التطبيقات الأساسية - ERROR فقط للأداء الأمثل
            'financial': {
                'handlers': ['error_file'],
                'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
                'propagate': False,
            },
            'hr': {
                'handlers': ['error_file'],
                'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
                'propagate': False,
            },
            'product': {
                'handlers': ['error_file'],
                'level': 'ERROR',  # ✅ PERFORMANCE: Changed from WARNING to ERROR
                'propagate': False,
            },
        },
    }

# ==============================================================================
# PHASE 6: MONITORING & ALERTING CONFIGURATION
# ==============================================================================

# ==============================================================================
# SIMPLIFIED MONITORING CONFIGURATION
# ==============================================================================
# Basic monitoring settings appropriate for business-scale deployment

# Basic monitoring toggle
MONITORING_ENABLED = env("MONITORING_ENABLED", default=True)

# Simple alert email settings
ALERT_EMAIL_ENABLED = env("ALERT_EMAIL_ENABLED", default=True)
DEFAULT_ALERT_EMAIL = env("DEFAULT_ALERT_EMAIL", default="admin@example.com")

# Basic log retention (simplified from multiple retention periods)
LOG_RETENTION_DAYS = env.int("LOG_RETENTION_DAYS", default=30)

# Essential monitoring flags (simplified from granular controls)
ENABLE_ERROR_TRACKING = env("ENABLE_ERROR_TRACKING", default=True)
ENABLE_BASIC_MONITORING = env("ENABLE_BASIC_MONITORING", default=True)

# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================
# Celery settings for asynchronous task processing

# Celery Broker Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/1")

# Celery Task Configuration
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# ✅ PERFORMANCE: Disable Celery Beat in production (use cPanel Cron Jobs instead)
# In shared hosting, Celery Beat consumes memory and CPU unnecessarily
if DEBUG:
    # Development: Keep basic tasks for testing
    CELERY_BEAT_SCHEDULE = {
        'basic-health-check': {
            'task': 'core.tasks.basic_health_check_task',
            'schedule': 1800.0,  # 30 minutes
        },
        'cleanup-old-logs': {
            'task': 'core.tasks.cleanup_old_logs_task',
            'schedule': crontab(hour=2, minute=0),
            'kwargs': {'days_to_keep': LOG_RETENTION_DAYS}
        },
    }
else:
    # Production: Empty schedule - use cPanel Cron Jobs
    # ✅ This saves 10-20MB memory and reduces CPU usage
    # Setup cPanel Cron Jobs for:
    # - Health checks: */30 * * * * cd /path && python manage.py basic_health_check
    # - Log cleanup: 0 2 * * * cd /path && python manage.py cleanup_old_logs
    CELERY_BEAT_SCHEDULE = {}

# Task execution settings
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=DEBUG)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_IGNORE_RESULT = False
CELERY_TASK_STORE_EAGER_RESULT = True

# Task retry and reliability
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute
CELERY_TASK_MAX_RETRIES = 3

# Worker configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_DISABLE_RATE_LIMITS = False

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour
CELERY_RESULT_PERSISTENT = True

# Broker transport options
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 1 hour
    'fanout_prefix': True,
    'fanout_patterns': True
}

# Task routing for different queues
CELERY_TASK_ROUTES = {
    'hr.tasks.process_biometric_logs_task': {'queue': 'hr'},
    'hr.tasks.cleanup_old_biometric_logs': {'queue': 'maintenance'},
    'financial.tasks.generate_financial_report': {'queue': 'reports'},
}

# Queue configuration
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = {
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'notifications': {
        'exchange': 'notifications',
        'routing_key': 'notifications',
    },
    'reports': {
        'exchange': 'reports',
        'routing_key': 'reports',
    },
    'accounting': {
        'exchange': 'accounting',
        'routing_key': 'accounting',
    },
    'bulk_processing': {
        'exchange': 'bulk_processing',
        'routing_key': 'bulk_processing',
    },
    'maintenance': {
        'exchange': 'maintenance',
        'routing_key': 'maintenance',
    },
}

# ==============================================================================
# UNIFIED SYSTEM MIGRATION FEATURE FLAGS
# ==============================================================================
# Feature flags for system services

MIGRATION_FLAGS = {
    # Financial Services
    'USE_PAYMENT_SERVICE': True,
    
    # Product & Inventory
    'BUNDLE_ALTERNATIVES_ENABLED': True,
}

# Merge biometric tasks into the existing CELERY_BEAT_SCHEDULE (don't redefine)
CELERY_BEAT_SCHEDULE.update({
    'process-biometric-logs': {
        'task': 'hr.tasks.process_biometric_logs_task',
        'schedule': 300.0,  # Every 5 minutes
        'options': {'queue': 'hr'}
    },
    'cleanup-old-biometric-logs': {
        'task': 'hr.tasks.cleanup_old_biometric_logs',
        'schedule': 604800.0,  # Weekly
        'options': {'queue': 'maintenance'},
        'kwargs': {'months': 6}
    },
})

# Monitoring and logging
CELERY_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_SEND_EVENTS = True

# Security settings
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_ACKS_LATE = True

# ============================================================
# PHASE 3: PERFORMANCE OPTIMIZATION SETTINGS
# ============================================================

# ✅ PHASE 3: Database query optimization
DATABASE_QUERY_TIMEOUT = env.int("DATABASE_QUERY_TIMEOUT", default=30)
DATABASE_CONN_MAX_AGE = env.int("DATABASE_CONN_MAX_AGE", default=600)

# ✅ PHASE 3: Pagination settings
PAGINATION_SETTINGS = {
    'DEFAULT_PAGE_SIZE': 25,
    'MAX_PAGE_SIZE': 200,
    'CACHE_TIMEOUT': 600,
    'ENABLE_SMART_PAGINATION': True,
}

# ✅ PHASE 3: Static files optimization
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
if not DEBUG:
    # Enable static files compression in production
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ✅ PHASE 3: Media files optimization
MEDIA_OPTIMIZATION = {
    'ENABLE_IMAGE_OPTIMIZATION': True,
    'MAX_IMAGE_SIZE': 5 * 1024 * 1024,  # 5MB
    'DEFAULT_IMAGE_QUALITY': 85,
    'CREATE_THUMBNAILS': True,
    'THUMBNAIL_SIZES': {
        'small': (300, 300),
        'medium': (600, 600),
        'large': (1200, 1200),
    }
}

# ✅ PHASE 3: Async processing settings
ASYNC_PROCESSING = {
    'ENABLE_ASYNC_REPORTS': True,
    'ENABLE_BULK_OPERATIONS': True,
    'BATCH_SIZE': 100,
    'MAX_RETRIES': 3,
}

# ✅ PHASE 3: Performance monitoring
PERFORMANCE_MONITORING = {
    'ENABLE_QUERY_LOGGING': not DEBUG,
    'SLOW_QUERY_THRESHOLD': 1.0,  # Log queries slower than 1 second
    'ENABLE_CACHE_STATS': True,
    'ENABLE_PAGINATION_STATS': True,
}

# ✅ SECURITY: CORS Configuration
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)
CORS_ALLOW_ALL_ORIGINS = False  # Never allow all origins in production

# ✅ SECURITY: Rate Limiting Configuration
RATE_LIMIT_ENABLED = env.bool("RATE_LIMIT_ENABLED", default=True)
API_RATE_LIMIT_AUTH = env("API_RATE_LIMIT_AUTH", default="10/min")
API_RATE_LIMIT_OPERATIONS = env("API_RATE_LIMIT_OPERATIONS", default="100/hour")

# ✅ SECURITY: Additional Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ✅ SECURITY: Content Security Policy (CSP)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")

# ============================================================
# PHASE 5: DATA PROTECTION CONFIGURATION
# ============================================================

# ✅ PHASE 5: Backup Configuration
BACKUP_STORAGE_TYPE = env("BACKUP_STORAGE_TYPE", default="local")
BACKUP_LOCAL_DIR = env("BACKUP_LOCAL_DIR", default=str(BASE_DIR / "backups"))
# DEPRECATED: Use SystemSettings instead (backup_retention_days, backup_retention_type, backup_retention_count)
BACKUP_RETENTION_DAYS = env.int("BACKUP_RETENTION_DAYS", default=30)
BACKUP_ENABLE_ENCRYPTION = env.bool("BACKUP_ENABLE_ENCRYPTION", default=True)
BACKUP_ENABLE_NOTIFICATIONS = env.bool("BACKUP_ENABLE_NOTIFICATIONS", default=True)

# S3 Backup Storage Configuration
BACKUP_S3_BUCKET = env("BACKUP_S3_BUCKET", default="")
BACKUP_S3_ACCESS_KEY = env("BACKUP_S3_ACCESS_KEY", default="")
BACKUP_S3_SECRET_KEY = env("BACKUP_S3_SECRET_KEY", default="")
BACKUP_S3_REGION = env("BACKUP_S3_REGION", default="us-east-1")

# Backup Notification Recipients
BACKUP_NOTIFICATION_EMAILS = env.list("BACKUP_NOTIFICATION_EMAILS", default=[])

# ✅ PHASE 5: Data Encryption Configuration
ENABLE_FIELD_ENCRYPTION = env.bool("ENABLE_FIELD_ENCRYPTION", default=True)
ENCRYPTION_MASTER_KEY = env("ENCRYPTION_MASTER_KEY", default="")
ENCRYPTION_KEY_FILE = env("ENCRYPTION_KEY_FILE", default="encryption.key")
ENCRYPTION_KEY_ROTATION_DAYS = env.int("ENCRYPTION_KEY_ROTATION_DAYS", default=90)

# ✅ PHASE 5: Data Retention Configuration
DATA_RETENTION_ARCHIVE_ENABLED = env.bool("DATA_RETENTION_ARCHIVE_ENABLED", default=True)
DATA_RETENTION_NOTIFICATIONS_ENABLED = env.bool("DATA_RETENTION_NOTIFICATIONS_ENABLED", default=True)
DATA_RETENTION_AUDIT_ENABLED = env.bool("DATA_RETENTION_AUDIT_ENABLED", default=True)

# Data Retention Notification Recipients
DATA_RETENTION_NOTIFICATION_EMAILS = env.list("DATA_RETENTION_NOTIFICATION_EMAILS", default=[])

# GDPR and Compliance Settings
GDPR_COMPLIANCE_ENABLED = env.bool("GDPR_COMPLIANCE_ENABLED", default=False)
DATA_RETENTION_POLICY_DAYS = env.int("DATA_RETENTION_POLICY_DAYS", default=2555)  # 7 years
PERSONAL_DATA_ENCRYPTION = env.bool("PERSONAL_DATA_ENCRYPTION", default=True)

# ✅ PHASE 5: Data Recovery Configuration
DATA_RECOVERY_ENABLED = env.bool("DATA_RECOVERY_ENABLED", default=True)
DATA_RECOVERY_NOTIFICATION_EMAILS = env.list("DATA_RECOVERY_NOTIFICATION_EMAILS", default=[])

# ✅ PHASE 5: Data Anonymization Configuration
DATA_ANONYMIZATION_ENABLED = env.bool("DATA_ANONYMIZATION_ENABLED", default=True)
ANONYMIZATION_SALT = env("ANONYMIZATION_SALT", default="default-salt-change-in-production")

# ✅ PHASE 5: Data Protection Monitoring
DATA_PROTECTION_MONITORING_ENABLED = env.bool("DATA_PROTECTION_MONITORING_ENABLED", default=True)
BACKUP_STORAGE_WARNING_THRESHOLD = env.int("BACKUP_STORAGE_WARNING_THRESHOLD", default=80)
BACKUP_STORAGE_CRITICAL_THRESHOLD = env.int("BACKUP_STORAGE_CRITICAL_THRESHOLD", default=90)

# ✅ PHASE 5: Data Classification
DATA_CLASSIFICATION_ENABLED = env.bool("DATA_CLASSIFICATION_ENABLED", default=True)
SENSITIVE_DATA_PATTERNS = env.list("SENSITIVE_DATA_PATTERNS", default=[
    "ssn", "national_id", "credit_card", "phone", "email", "address"
])

# ✅ PHASE 5: Update Celery Beat Schedule for Data Protection Tasks
if env.bool("CELERY_BEAT_SCHEDULE_BACKUP_DAILY", default=True):
    CELERY_BEAT_SCHEDULE.update({
        'daily-backup': {
            'task': 'core.tasks.backup_tasks.create_daily_backup',
            'schedule': 86400.0,  # Daily at configured time
            'options': {'queue': 'backup'}
        },
    })

if env.bool("CELERY_BEAT_SCHEDULE_BACKUP_WEEKLY", default=True):
    CELERY_BEAT_SCHEDULE.update({
        'weekly-backup': {
            'task': 'core.tasks.backup_tasks.create_weekly_backup',
            'schedule': 604800.0,  # Weekly
            'options': {'queue': 'backup'}
        },
    })

if env.bool("CELERY_BEAT_SCHEDULE_RETENTION_CLEANUP", default=True):
    CELERY_BEAT_SCHEDULE.update({
        'data-retention-cleanup': {
            'task': 'core.tasks.backup_tasks.run_data_retention_cleanup',
            'schedule': 86400.0,  # Daily
            'options': {'queue': 'maintenance'}
        },
        'retention-notifications': {
            'task': 'core.tasks.backup_tasks.send_retention_notifications',
            'schedule': 604800.0,  # Weekly
            'options': {'queue': 'notifications'}
        },
    })

if env.bool("CELERY_BEAT_SCHEDULE_VALIDATION", default=True):
    CELERY_BEAT_SCHEDULE.update({
        'validate-data-protection': {
            'task': 'core.tasks.backup_tasks.validate_data_protection_systems',
            'schedule': 86400.0,  # Daily
            'options': {'queue': 'monitoring'}
        },
        'cleanup-old-backups': {
            'task': 'core.tasks.backup_tasks.cleanup_old_backups',
            'schedule': 86400.0,  # Daily
            'options': {'queue': 'maintenance'}
        },
    })

# ✅ PHASE 5: Add Data Protection Queues to Celery Configuration
CELERY_TASK_QUEUES.update({
    'backup': {
        'exchange': 'backup',
        'routing_key': 'backup',
    },
    'monitoring': {
        'exchange': 'monitoring',
        'routing_key': 'monitoring',
    },
})

# ✅ PHASE 5: Data Protection Task Routes
CELERY_TASK_ROUTES.update({
    'core.tasks.backup_tasks.create_daily_backup': {'queue': 'backup'},
    'core.tasks.backup_tasks.create_weekly_backup': {'queue': 'backup'},
    'core.tasks.backup_tasks.verify_backup_integrity': {'queue': 'backup'},
    'core.tasks.backup_tasks.cleanup_old_backups': {'queue': 'maintenance'},
    'core.tasks.backup_tasks.run_data_retention_cleanup': {'queue': 'maintenance'},
    'core.tasks.backup_tasks.send_retention_notifications': {'queue': 'notifications'},
    'core.tasks.backup_tasks.validate_data_protection_systems': {'queue': 'monitoring'},
})
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)

# ✅ SECURITY: Security Headers Middleware Configuration
SECURITY_HEADERS_ENABLED = env.bool("SECURITY_HEADERS_ENABLED", default=True)

# ============================================================
# PHASE 4: INTEGRATION SECURITY SETTINGS
# ============================================================

# ✅ PHASE 4: Financial Integration Security
FINANCIAL_INTEGRATION_SECURITY = {
    'ENABLE_RETRY_LOGIC': True,
    'MAX_RETRIES': 3,
    'RETRY_DELAYS': [1, 3, 9],  # seconds
    'REQUEST_TIMEOUT': 30,  # seconds
    'CIRCUIT_BREAKER_FAILURE_THRESHOLD': 5,
    'CIRCUIT_BREAKER_RECOVERY_TIMEOUT': 60,  # seconds
    'ENABLE_IDEMPOTENCY_PROTECTION': True,
    'IDEMPOTENCY_EXPIRY_HOURS': 24,
}

# ✅ PHASE 4: API Integration Security
API_INTEGRATION_SECURITY = {
    'ENABLE_SIGNATURE_VALIDATION': True,
    'ENABLE_RATE_LIMITING': True,
    'ENABLE_REQUEST_LOGGING': True,
    'REQUEST_TIMEOUT': 30,  # seconds
    'MAX_RETRIES': 3,
    'CIRCUIT_BREAKER_ENABLED': True,
}

# ✅ PHASE 4: Webhook Security Configuration
WEBHOOK_SECURITY = {
    'ENABLE_IP_WHITELIST': env.bool('WEBHOOK_ENABLE_IP_WHITELIST', default=False),
    'ENABLE_SIGNATURE_VALIDATION': env.bool('WEBHOOK_ENABLE_SIGNATURE_VALIDATION', default=True),
    'SIGNATURE_ALGORITHM': env('WEBHOOK_SIGNATURE_ALGORITHM', default='sha256'),
    'REQUIRE_HTTPS': env.bool('WEBHOOK_REQUIRE_HTTPS', default=True),
}

# Protected webhook paths
PROTECTED_WEBHOOK_PATHS = [
    '/api/webhooks/',
    '/webhooks/',
    '/financial/webhooks/',
    '/payments/webhooks/',
]

# Webhook secrets (should be set via environment variables)
WEBHOOK_SECRETS = {
    'default': env('WEBHOOK_DEFAULT_SECRET', default='change-me-in-production'),
    'financial': env('WEBHOOK_FINANCIAL_SECRET', default=''),
    'payments': env('WEBHOOK_PAYMENTS_SECRET', default=''),
}

# ✅ PHASE 4: API Rate Limiting Configuration
API_RATE_LIMITS = {
    'authenticated': {
        'requests': env.int('API_RATE_LIMIT_AUTH_REQUESTS', default=1000),
        'window': env.int('API_RATE_LIMIT_AUTH_WINDOW', default=3600)  # 1 hour
    },
    'anonymous': {
        'requests': env.int('API_RATE_LIMIT_ANON_REQUESTS', default=100),
        'window': env.int('API_RATE_LIMIT_ANON_WINDOW', default=3600)  # 1 hour
    },
    'webhook': {
        'requests': env.int('API_RATE_LIMIT_WEBHOOK_REQUESTS', default=100),
        'window': env.int('API_RATE_LIMIT_WEBHOOK_WINDOW', default=3600)  # 1 hour
    },
    'financial_api': {
        'requests': env.int('API_RATE_LIMIT_FINANCIAL_REQUESTS', default=500),
        'window': env.int('API_RATE_LIMIT_FINANCIAL_WINDOW', default=3600)  # 1 hour
    }
}

# Protected API paths for rate limiting
PROTECTED_API_PATHS = [
    '/api/',
    '/financial/api/',
    '/purchase/api/',
    '/product/api/',
]

# API paths to log for debugging
LOGGED_API_PATHS = [
    '/api/',
    '/webhooks/',
    '/financial/api/',
    '/purchase/api/',
]

# ✅ PHASE 4: Data Reconciliation Configuration
DATA_RECONCILIATION = {
    'ENABLE_DAILY_RECONCILIATION': env.bool('RECONCILIATION_ENABLE_DAILY', default=True),
    'RECONCILIATION_TIME': env('RECONCILIATION_TIME', default='02:00'),  # 2 AM
    'ACCEPTABLE_VARIANCE_PERCENTAGE': env.float('RECONCILIATION_VARIANCE_PERCENTAGE', default=0.01),  # 1%
    'ACCEPTABLE_VARIANCE_AMOUNT': env.float('RECONCILIATION_VARIANCE_AMOUNT', default=1.00),  # 1 EGP
    'RETENTION_DAYS': env.int('RECONCILIATION_RETENTION_DAYS', default=90),
    'ENABLE_EMAIL_REPORTS': env.bool('RECONCILIATION_ENABLE_EMAIL_REPORTS', default=True),
}

# Email recipients for reconciliation reports
RECONCILIATION_REPORT_RECIPIENTS = env.list('RECONCILIATION_REPORT_RECIPIENTS', default=[])
RECONCILIATION_ALERT_RECIPIENTS = env.list('RECONCILIATION_ALERT_RECIPIENTS', default=[])

# ✅ PHASE 4: Integration Health Monitoring
INTEGRATION_HEALTH_MONITORING = {
    'ENABLE_HEALTH_CHECKS': env.bool('INTEGRATION_ENABLE_HEALTH_CHECKS', default=True),
    'HEALTH_CHECK_INTERVAL': env.int('INTEGRATION_HEALTH_CHECK_INTERVAL', default=300),  # 5 minutes
    'ALERT_ON_CRITICAL': env.bool('INTEGRATION_ALERT_ON_CRITICAL', default=True),
    'ALERT_ON_WARNING': env.bool('INTEGRATION_ALERT_ON_WARNING', default=False),
}

# Email recipients for integration health alerts
INTEGRATION_HEALTH_ALERT_RECIPIENTS = env.list('INTEGRATION_HEALTH_ALERT_RECIPIENTS', default=[])

# ✅ PHASE 4: Audit Trail Configuration
AUDIT_TRAIL = {
    'ENABLE_FINANCIAL_AUDIT': env.bool('AUDIT_ENABLE_FINANCIAL', default=True),
    'ENABLE_API_AUDIT': env.bool('AUDIT_ENABLE_API', default=True),
    'ENABLE_WEBHOOK_AUDIT': env.bool('AUDIT_ENABLE_WEBHOOK', default=True),
    'RETENTION_DAYS': env.int('AUDIT_RETENTION_DAYS', default=365),  # 1 year
    'ENABLE_REAL_TIME_ALERTS': env.bool('AUDIT_ENABLE_REAL_TIME_ALERTS', default=True),
}

# ✅ PHASE 4: Celery Configuration for Reconciliation Tasks
if 'CELERY_BROKER_URL' in os.environ:
    # Celery beat schedule for automated tasks
    CELERY_BEAT_SCHEDULE.update({
        'daily-reconciliation': {
            'task': 'financial.tasks.reconciliation_tasks.run_daily_reconciliation_task',
            'schedule': crontab(hour=2, minute=0),  # Run at 2:00 AM daily
            'options': {'queue': 'reconciliation'}
        },
        'integration-health-check': {
            'task': 'financial.tasks.reconciliation_tasks.check_integration_health_task',
            'schedule': crontab(minute='*/15'),  # Every 15 minutes
            'options': {'queue': 'monitoring'}
        },
        'cleanup-old-reconciliation-data': {
            'task': 'financial.tasks.reconciliation_tasks.cleanup_old_reconciliation_data',
            'schedule': crontab(hour=3, minute=0, day_of_week=0),  # Weekly on Sunday at 3 AM
            'options': {'queue': 'maintenance'}
        },
    })
    
    # Celery queues for different task types
    CELERY_TASK_ROUTES.update({
        'financial.tasks.reconciliation_tasks.*': {'queue': 'reconciliation'},
        '*.check_integration_health_task': {'queue': 'monitoring'},
        '*.cleanup_*': {'queue': 'maintenance'},
    })

# ============================================================
# PHASE 4: SECURITY ENHANCEMENTS
# ============================================================

# ✅ PHASE 4: Enhanced CORS settings for API security
if not DEBUG:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Development settings
    CORS_ALLOW_ALL_ORIGINS = True

# ✅ PHASE 4: Enhanced CSP for API endpoints
# Note: CSP الفعلية بتتبنى من core/csp_config_advanced.py عبر AdvancedSecurityHeadersMiddleware
# هذه الإعدادات للـ django-csp package فقط (لو مستخدم) - مش بتأثر على الـ middleware
CSP_CONNECT_SRC = ("'self'", "https:", "wss:")
# لا تكتب على CSP_SCRIPT_SRC هنا - بيشيل Cloudflare Analytics من الـ whitelist
# CSP_SCRIPT_SRC مُدار في core/csp_config_advanced.py
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https:")

# ✅ PHASE 4: API Security Headers
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ============================================================
# PHASE 4: LOGGING CONFIGURATION FOR INTEGRATION
# ============================================================

# Add integration-specific loggers
_file_handler = 'file' if DEBUG else 'main_file'
LOGGING['loggers'].update({
    # Daftra sync logger - ملف منفصل للمزامنة
    'utils.daftra_sync': {
        'handlers': [_file_handler, 'daftra_file'],
        'level': 'WARNING' if not DEBUG else 'DEBUG',
        'propagate': False,
    },
    'utils.daftra_views': {
        'handlers': [_file_handler, 'daftra_file'],
        'level': 'WARNING' if not DEBUG else 'DEBUG',
        'propagate': False,
    },
    'financial.services.integration_security_service': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
        'propagate': False,
    },
    'core.services.api_integration_security': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
        'propagate': False,
    },
    'financial.services.data_reconciliation_service': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
        'propagate': False,
    },
    'financial.tasks.reconciliation_tasks': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
        'propagate': False,
    },
    'core.middleware.webhook_security_middleware': {
        'handlers': ['file', 'console'],
        'level': 'WARNING',  # Only log warnings and errors
        'propagate': False,
    },
})

# ============================================================
# PHASE 4: ENVIRONMENT-SPECIFIC OVERRIDES
# ============================================================

# Production-specific integration security settings
if not DEBUG:
    # Stricter timeouts in production
    FINANCIAL_INTEGRATION_SECURITY['REQUEST_TIMEOUT'] = 20
    API_INTEGRATION_SECURITY['REQUEST_TIMEOUT'] = 20
    
    # More aggressive rate limiting in production
    API_RATE_LIMITS['anonymous']['requests'] = 50
    API_RATE_LIMITS['webhook']['requests'] = 50
    
    # Enable all security features in production
    WEBHOOK_SECURITY['ENABLE_IP_WHITELIST'] = True
    WEBHOOK_SECURITY['REQUIRE_HTTPS'] = True
    
    # Shorter retention for performance
    DATA_RECONCILIATION['RETENTION_DAYS'] = 60
    AUDIT_TRAIL['RETENTION_DAYS'] = 180

# Development-specific settings
if DEBUG:
    # More lenient settings for development
    FINANCIAL_INTEGRATION_SECURITY['ENABLE_RETRY_LOGIC'] = False
    API_INTEGRATION_SECURITY['ENABLE_RATE_LIMITING'] = False
    WEBHOOK_SECURITY['ENABLE_IP_WHITELIST'] = False
    WEBHOOK_SECURITY['REQUIRE_HTTPS'] = False
    
    # Disable email alerts in development
    DATA_RECONCILIATION['ENABLE_EMAIL_REPORTS'] = False
    INTEGRATION_HEALTH_MONITORING['ALERT_ON_CRITICAL'] = False

# ============================================================
# PHASE 4: INTEGRATION SECURITY - COMPLETED ✅
# ============================================================