# Generated by Django 4.2.26 on 2026-08-20 16:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import financial.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "طلب اعتماد أمر شراء",
                "verbose_name_plural": "طلبات اعتماد أوامر الشراء",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="اسم القاعدة"),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأدنى للقيمة",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("999999999.00"),
                        max_digits=15,
                        verbose_name="الحد الأقصى للقيمة",
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(max_length=50, verbose_name="دور المعتمد"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "قاعدة اعتماد أمر شراء",
                "verbose_name_plural": "قواعد اعتماد أوامر الشراء",
            },
        ),
        migrations.CreateModel(
            name="BillLineMatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المطابقة"
                    ),
                ),
                (
                    "po_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر أمر الشراء الأصلي",
                    ),
                ),
                (
                    "bill_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الفاتورة الفعلي",
                    ),
                ),
                (
                    "price_variance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="فرق السعر الفعلي (PPV)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "مطابقة سطر فاتورة مع إذن استلام",
                "verbose_name_plural": "مطابقات أسطر الفواتير",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم إذن الاستلام GRN"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاستلام الفعلي"
                    ),
                ),
                (
                    "supplier_delivery_note_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم إذن تسليم المورد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم للاعتماد"),
                            ("APPROVED", "معتمد"),
                            ("POSTED", "مرحل مخزنياً ومالياً"),
                            ("REVERSED", "معكوس"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=18,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن استلام مخزني GRN",
                "verbose_name_plural": "أذون الاستلام المخزنية GRN",
                "ordering": ["-received_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المستلمة"
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المفوترة من هذا الإذن",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="تكلفة الاستلام للوحدة (PO Price)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي تكلفة الاستلام",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند إذن استلام GRN",
                "verbose_name_plural": "بنود أذون الاستلام GRN",
            },
        ),
        migrations.CreateModel(
            name="GRNAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الحالة السابقة",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="الحالة الجديدة"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="السبب / التبرير",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات إضافية"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تتبع إذن استلام",
                "verbose_name_plural": "سجلات تتبع أذون الاستلام",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GRNPostingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_movements_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد حركات المخزون"
                    ),
                ),
                (
                    "total_posted_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="إجمالي قيمة الترحيل",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ وتوقيت الترحيل"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل ترحيل إذن استلام",
                "verbose_name_plural": "سجلات ترحيل أذون الاستلام",
                "ordering": ["-posted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الفاتورة"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ الفاتورة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("confirmed", "مؤكدة"),
                            ("cancelled", "ملغية"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الضريبة",
                    ),
                ),
                (
                    "tax_active",
                    models.BooleanField(default=True, verbose_name="الضريبة نشطة"),
                ),
                (
                    "vat_active",
                    models.BooleanField(
                        default=True, verbose_name="ضريبة القيمة المضافة نشطة"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("14.00"),
                        max_digits=5,
                        verbose_name="نسبة القيمة المضافة %",
                    ),
                ),
                (
                    "wht_active",
                    models.BooleanField(
                        default=False, verbose_name="ضريبة الخصم والإضافة نشطة"
                    ),
                ),
                (
                    "wht_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        verbose_name="نسبة الخصم والإضافة %",
                    ),
                ),
                (
                    "wht_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="مبلغ الخصم والإضافة",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=18,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "total_foreign",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="الإجمالي بالعملة الأجنبية",
                    ),
                ),
                (
                    "total_functional",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="الإجمالي بالعملة الأساسية",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        help_text="رمز الحساب المحاسبي أو طريقة الدفع (cash/credit)",
                        max_length=50,
                        verbose_name="طريقة الدفع (account code)",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "مدفوعة"),
                            ("partially_paid", "مدفوعة جزئياً"),
                            ("unpaid", "غير مدفوعة"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "is_service",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="هل هذه فاتورة خدمة أم منتج؟",
                        verbose_name="خدمة",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("course", "كورس تعليمي"),
                            ("consultation", "استشارة"),
                            ("maintenance", "صيانة"),
                            ("other", "أخرى"),
                        ],
                        help_text="نوع الخدمة (إذا كانت فاتورة خدمة)",
                        max_length=20,
                        null=True,
                        verbose_name="نوع الخدمة",
                    ),
                ),
                (
                    "service_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="بيانات إضافية خاصة بالخدمة (JSON)",
                        verbose_name="بيانات الخدمة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "فاتورة مشتريات",
                "verbose_name_plural": "فواتير المشتريات",
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
            ],
            options={
                "verbose_name": "بند الفاتورة",
                "verbose_name_plural": "بنود الفاتورة",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم أمر الشراء"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="تاريخ أمر الشراء")),
                (
                    "delivery_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التوريد المتوقع"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=10,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "cost_source_policy",
                    models.CharField(
                        choices=[
                            ("PO_PRICE", "سعر أمر الشراء الأصلي"),
                            ("LIST_PRICE", "سعر قائمة المورد"),
                            ("CUSTOM", "سعر مخصص"),
                        ],
                        default="PO_PRICE",
                        max_length=20,
                        verbose_name="سياسة سعر التكلفة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم للاعتماد"),
                            ("APPROVED", "معتمد"),
                            ("PARTIALLY_RECEIVED", "مستلم جزئياً"),
                            ("FULLY_RECEIVED", "مستلم بالكامل"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بعملة الفاتورة",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بالعملة الوظيفية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر شراء",
                "verbose_name_plural": "أوامر الشراء",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المطلوبة"
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المستلمة فعلياً",
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المفوترة",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الوحدة المحدد في PO",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي السطر"
                    ),
                ),
            ],
            options={
                "verbose_name": "بند أمر شراء",
                "verbose_name_plural": "بنود أوامر الشراء",
            },
        ),
        migrations.CreateModel(
            name="PurchasePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ المعاملة",
                    ),
                ),
                (
                    "exchange_rate_snapshot",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="لقطة سعر الصرف",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأساسية (EGP)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="تاريخ الدفع")),
                (
                    "payment_method",
                    models.CharField(
                        help_text="رمز الحساب المحاسبي (مثل 10100 للخزنة، 10200 للبنك)",
                        max_length=50,
                        verbose_name="طريقة الدفع (account code)",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "payment_exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="سعر صرف عملة السداد مقابل العملة الأساسية وقت الدفع",
                        max_digits=18,
                        verbose_name="سعر صرف السداد",
                    ),
                ),
                (
                    "amount_paid_currency",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="المبلغ الفعلي المدفوع بعملة الخزينة أو البنك",
                        max_digits=15,
                        verbose_name="المبلغ المسدد بعملة الخزينة",
                    ),
                ),
                (
                    "amount_functional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="القيمة المعادلة بالجنيه المصري المسحوبة من الخزينة",
                        max_digits=15,
                        verbose_name="المعادل بالعملة الوظيفية (EGP)",
                    ),
                ),
                (
                    "amount_settled_invoice_currency",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="المبلغ المخصوم من أصل الفاتورة بعملة الفاتورة",
                        max_digits=15,
                        verbose_name="المبلغ المقفول بعملة الفاتورة",
                    ),
                ),
                (
                    "realized_fx_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="صافي أرباح أو خسائر فروق العملة الناتجة عن السداد",
                        max_digits=15,
                        verbose_name="أرباح / خسائر فروق الصرف المحققة",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="مفتاح فريد لمنع تكرار ترحيل الدفعة",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
                (
                    "financial_status",
                    models.CharField(
                        choices=[
                            ("pending", "معلق"),
                            ("synced", "مربوط"),
                            ("failed", "فشل"),
                            ("manual", "يدوي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الربط المالي",
                    ),
                ),
                (
                    "financial_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="خطأ الربط المالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "مسودة"), ("posted", "مرحّلة")],
                        default="draft",
                        help_text="المسودات يمكن تعديلها، المرحّلة لا يمكن تعديلها",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الترحيل"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CASH", "نقدي"),
                            ("BANK", "تحويل بنكي / شيك"),
                            (
                                "PREPAID_BALANCE",
                                "خصم من الرصيد المسبق / دفعة مقدمة للمورد",
                            ),
                            ("DEBIT_NOTE", "تسوية إشعار خصم/مردودات"),
                        ],
                        default="CASH",
                        help_text="التصنيف الشفاف لمصدر الدفعة المدفوعة",
                        max_length=30,
                        verbose_name="نوع مصدر الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة الفاتورة",
                "verbose_name_plural": "دفعات الفواتير",
                "ordering": ["-payment_date"],
            },
            bases=(financial.mixins.PaymentAuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم المرتجع"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ المرتجع")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الضريبة",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("confirmed", "مؤكد"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "مرتجع مشتريات",
                "verbose_name_plural": "مرتجعات المشتريات",
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="الكمية")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="سبب الإرجاع"),
                ),
            ],
            options={
                "verbose_name": "بند مرتجع مشتريات",
                "verbose_name_plural": "بنود مرتجعات المشتريات",
            },
        ),
        migrations.CreateModel(
            name="SupplierBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الفاتورة في النظام",
                    ),
                ),
                (
                    "supplier_bill_number",
                    models.CharField(
                        max_length=100, verbose_name="رقم فاتورة المورد الأصلي"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("GOODS", "فاتورة بضائع ومخزون - تتطلب GRN معتمد"),
                            ("SERVICE", "فاتورة خدمات مباشرة"),
                            ("EXPENSE", "فاتورة مصاريف تشغيلية"),
                        ],
                        default="GOODS",
                        max_length=20,
                        verbose_name="نوع الفاتورة الحوكمي",
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            (
                                "INVENTORY_INVOICE",
                                "فاتورة بضائع ومخزون (GRN Mandatory)",
                            ),
                            ("SERVICE_INVOICE", "فاتورة خدمات ومصروفات"),
                            ("ADVANCE_INVOICE", "فاتورة دفعة مقدمة"),
                        ],
                        default="INVENTORY_INVOICE",
                        max_length=30,
                        verbose_name="نوع الفاتورة",
                    ),
                ),
                ("bill_date", models.DateField(verbose_name="تاريخ الفاتورة")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=10,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الفاتورة بعملة المورد",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الفاتورة بالعملة الوظيفية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("POSTED", "مرحلة ومرحلة للأستاذ"),
                            ("PAID", "مدفوعة ومسواة"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "فاتورة مورد",
                "verbose_name_plural": "فواتير الموردين",
                "ordering": ["-bill_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المفوترة"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الوحدة في الفاتورة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي مبلغ السطر",
                    ),
                ),
                (
                    "ppv_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ فروق أسعار الشراء (PPV Variance)",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.supplierbill",
                    ),
                ),
                (
                    "grn_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="purchase.goodsreceivednoteitem",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="purchase.purchaseorderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند فاتورة مورد",
                "verbose_name_plural": "بنود فواتير الموردين",
            },
        ),
    ]
