# Generated by Django 5.2.17 on 2026-09-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("purchase", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceivednote",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="supplier.supplier",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="product.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednoteitem",
            name="grn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchase.goodsreceivednote",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="billlinematching",
            name="grn_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_matchings",
                to="purchase.goodsreceivednoteitem",
            ),
        ),
    ]
