# Generated by Django 4.2.23 on 2025-11-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('financial', '0001_initial'),
        ('product', '0002_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchase.purchase', verbose_name='فاتورة المشتريات'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='الخزينة أو البنك المستخدم للدفع', null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.chartofaccounts', verbose_name='الحساب المالي'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.journalentry', verbose_name='المعاملة المالية'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments_posted', to=settings.AUTH_USER_MODEL, verbose_name='رحّلها'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase.purchase', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchase', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='financial.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='supplier.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='product.warehouse', verbose_name='المخزن'),
        ),
    ]
