# Generated by Django 4.2.26 on 2026-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={
                "ordering": ["-date", "-number"],
                "permissions": [
                    ("approve_purchase", "اعتماد فاتورة المشتريات"),
                    ("change_unit_cost", "تعديل تكلفة الشراء"),
                    ("cancel_approved_purchase", "إلغاء فاتورة مشتريات معتمدة"),
                ],
                "verbose_name": "فاتورة مشتريات",
                "verbose_name_plural": "فواتير المشتريات",
            },
        ),
    ]
