# Generated by Django 4.2.26 on 2026-08-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_purchase_work_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["-date", "-number"], name="purchase_pu_date_b80b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["supplier", "-date"], name="purchase_pu_supplie_7bb7f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["warehouse", "-date"], name="purchase_pu_warehou_5d5ed8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["payment_status", "-date"],
                name="purchase_pu_payment_b36411_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["status", "-date"], name="purchase_pu_status_18bb49_idx"
            ),
        ),
    ]
