# Generated by Django 4.2.26 on 2026-08-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_inventorycostlayer_warehouse_and_more"),
        ("purchase", "0003_purchaseorder_adjustment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="product.warehouse",
                verbose_name="المخزن المستهدف",
            ),
        ),
    ]
