# Generated by Django 4.2.26 on 2026-08-27 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0004_alter_purchaseorder_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="is_taxable",
            field=models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="is_taxable",
            field=models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة الضريبة",
            ),
        ),
    ]
