# Generated by Django 4.2.26 on 2026-08-04 13:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_category_valuation_method"),
        ("supplier", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0013_financialstatementsnapshot"),
        ("purchase", "0004_purchase_purchase_pu_date_b80b4d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="اسم القاعدة"),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأدنى للقيمة",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("999999999.00"),
                        max_digits=15,
                        verbose_name="الحد الأقصى للقيمة",
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(max_length=50, verbose_name="دور المعتمد"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "قاعدة اعتماد أمر شراء",
                "verbose_name_plural": "قواعد اعتماد أوامر الشراء",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم إذن الاستلام GRN"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الاستلام الفعلي"
                    ),
                ),
                (
                    "supplier_delivery_note_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم إذن تسليم المورد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="RECEIVED", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن استلام مخزني GRN",
                "verbose_name_plural": "أذون الاستلام المخزنية GRN",
                "ordering": ["-received_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceivedNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المستلمة"
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المفوترة من هذا الإذن",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="تكلفة الاستلام للوحدة (PO Price)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي تكلفة الاستلام",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.goodsreceivednote",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند إذن استلام GRN",
                "verbose_name_plural": "بنود أذون الاستلام GRN",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم أمر الشراء"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="تاريخ أمر الشراء")),
                (
                    "delivery_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التوريد المتوقع"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=10,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "cost_source_policy",
                    models.CharField(
                        choices=[
                            ("PO_PRICE", "سعر أمر الشراء الأصلي"),
                            ("LIST_PRICE", "سعر قائمة المورد"),
                            ("CUSTOM", "سعر مخصص"),
                        ],
                        default="PO_PRICE",
                        max_length=20,
                        verbose_name="سياسة سعر التكلفة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم للاعتماد"),
                            ("APPROVED", "معتمد"),
                            ("PARTIALLY_RECEIVED", "مستلم جزئياً"),
                            ("FULLY_RECEIVED", "مستلم بالكامل"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بعملة الفاتورة",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بالعملة الوظيفية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد بواسطة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="product.warehouse",
                        verbose_name="المستودع المستهدف",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر شراء",
                "verbose_name_plural": "أوامر الشراء",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المطلوبة"
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المستلمة فعلياً",
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المفوترة",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الوحدة المحدد في PO",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي السطر"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.unit",
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.productvariant",
                        verbose_name="النوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند أمر شراء",
                "verbose_name_plural": "بنود أوامر الشراء",
            },
        ),
        migrations.CreateModel(
            name="SupplierBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الفاتورة في النظام",
                    ),
                ),
                (
                    "supplier_bill_number",
                    models.CharField(
                        max_length=100, verbose_name="رقم فاتورة المورد الأصلي"
                    ),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            (
                                "INVENTORY_INVOICE",
                                "فاتورة بضائع ومخزون (GRN Mandatory)",
                            ),
                            ("SERVICE_INVOICE", "فاتورة خدمات ومصروفات"),
                            ("ADVANCE_INVOICE", "فاتورة دفعة مقدمة"),
                        ],
                        default="INVENTORY_INVOICE",
                        max_length=30,
                        verbose_name="نوع الفاتورة",
                    ),
                ),
                ("bill_date", models.DateField(verbose_name="تاريخ الفاتورة")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=10,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الفاتورة بعملة المورد",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الفاتورة بالعملة الوظيفية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("POSTED", "مرحلة ومرحلة للأستاذ"),
                            ("PAID", "مدفوعة ومسواة"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="مفتاح منع التكرار",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.journalentry",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_bills",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة مورد",
                "verbose_name_plural": "فواتير الموردين",
                "ordering": ["-bill_date", "-id"],
                "unique_together": {("supplier", "supplier_bill_number")},
            },
        ),
        migrations.CreateModel(
            name="SupplierBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المفوترة"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الوحدة في الفاتورة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي مبلغ السطر",
                    ),
                ),
                (
                    "ppv_variance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ فروق أسعار الشراء (PPV Variance)",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.supplierbill",
                    ),
                ),
                (
                    "grn_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="purchase.goodsreceivednoteitem",
                    ),
                ),
                (
                    "po_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="purchase.purchaseorderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند فاتورة مورد",
                "verbose_name_plural": "بنود فواتير الموردين",
            },
        ),
        migrations.AddField(
            model_name="goodsreceivednoteitem",
            name="po_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_items",
                to="purchase.purchaseorderitem",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednoteitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="purchase.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="supplier.supplier",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="product.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="BillLineMatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المطابقة"
                    ),
                ),
                (
                    "po_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر أمر الشراء الأصلي",
                    ),
                ),
                (
                    "bill_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="سعر الفاتورة الفعلي",
                    ),
                ),
                (
                    "price_variance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="فرق السعر الفعلي (PPV)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_matchings",
                        to="purchase.supplierbillitem",
                    ),
                ),
                (
                    "grn_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_matchings",
                        to="purchase.goodsreceivednoteitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "مطابقة سطر فاتورة مع إذن استلام",
                "verbose_name_plural": "مطابقات أسطر الفواتير",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="purchase.purchaseorder",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.approvalrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب اعتماد أمر شراء",
                "verbose_name_plural": "طلبات اعتماد أوامر الشراء",
            },
        ),
    ]
