# Generated by Django 4.2.26 on 2026-08-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0005_purchaseitem_is_taxable_purchaseitem_tax_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturnitem",
            name="is_taxable",
            field=models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="مبلغ الضريبة"
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="نسبة الضريبة"
            ),
        ),
    ]
