# Generated by Django 4.2.26 on 2026-08-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "purchase",
            "0005_approvalrule_goodsreceivednote_goodsreceivednoteitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceivednote",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="purchase.purchase",
                verbose_name="فاتورة المشتريات",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="purchase.purchaseorder",
            ),
        ),
    ]
