# Generated by Django 4.2.26 on 2026-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0006_goodsreceivednote_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierbill",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("GOODS", "فاتورة بضائع ومخزون - تتطلب GRN معتمد"),
                    ("SERVICE", "فاتورة خدمات مباشرة"),
                    ("EXPENSE", "فاتورة مصاريف تشغيلية"),
                ],
                default="GOODS",
                max_length=20,
                verbose_name="نوع الفاتورة الحوكمي",
            ),
        ),
    ]
