# Generated by Django 4.2.7 on 2025-10-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchase",
            "0007_purchasepayment_posted_at_purchasepayment_posted_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasepayment",
            name="cash_movement",
        ),
    ]
