# Generated by Django 4.2.23 on 2025-10-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_remove_purchasepayment_cash_movement'),
    ]

    operations = [
        # حذف جدول بنود طلبات الشراء أولاً (بسبب العلاقة الخارجية)
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        # حذف جدول طلبات الشراء
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
