# Generated by Django 4.2.26 on 2026-08-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0009_goodsreceivednote_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceivednote",
            name="status",
        ),
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="currency",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="العملة"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="العملة"
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="currency",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="العملة"
            ),
        ),
    ]
