# Generated by Django 4.2.26 on 2026-08-09 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0045_seed_default_currencies"),
        (
            "purchase",
            "0013_purchasepayment_base_amount_purchasepayment_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceivednote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("SUBMITTED", "مقدم للاعتماد"),
                    ("APPROVED", "معتمد"),
                    ("POSTED", "مرحل مخزنياً ومالياً"),
                    ("REVERSED", "معكوس"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceivednoteitem",
            name="po_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grn_items",
                to="purchase.purchaseorderitem",
            ),
        ),
        migrations.CreateModel(
            name="GRNPostingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_movements_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد حركات المخزون"
                    ),
                ),
                (
                    "total_posted_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="إجمالي قيمة الترحيل",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ وتوقيت الترحيل"
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_logs",
                        to="purchase.goodsreceivednote",
                        verbose_name="إذن الاستلام",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الترحيل بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل ترحيل إذن استلام",
                "verbose_name_plural": "سجلات ترحيل أذون الاستلام",
                "ordering": ["-posted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GRNAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="الحالة السابقة",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="الحالة الجديدة"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="السبب / التبرير",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات إضافية"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "action_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم بواسطة",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="purchase.goodsreceivednote",
                        verbose_name="إذن الاستلام",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تتبع إذن استلام",
                "verbose_name_plural": "سجلات تتبع أذون الاستلام",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
