# Generated by Django 4.2.26 on 2026-08-20 08:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0047_alter_costcenter_code_alter_journalentry_entry_type_and_more",
        ),
        ("purchase", "0014_alter_goodsreceivednote_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasepayment",
            name="amount_functional",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="القيمة المعادلة بالجنيه المصري المسحوبة من الخزينة",
                max_digits=15,
                verbose_name="المعادل بالعملة الوظيفية (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="amount_paid_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ الفعلي المدفوع بعملة الخزينة أو البنك",
                max_digits=15,
                verbose_name="المبلغ المسدد بعملة الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="amount_settled_invoice_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المخصوم من أصل الفاتورة بعملة الفاتورة",
                max_digits=15,
                verbose_name="المبلغ المقفول بعملة الفاتورة",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="payment_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_payments_as_payment_currency",
                to="financial.currency",
                verbose_name="عملة السداد / الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="payment_exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="سعر صرف عملة السداد مقابل العملة الأساسية وقت الدفع",
                max_digits=18,
                verbose_name="سعر صرف السداد",
            ),
        ),
        migrations.AddField(
            model_name="purchasepayment",
            name="realized_fx_difference",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="صافي أرباح أو خسائر فروق العملة الناتجة عن السداد",
                max_digits=15,
                verbose_name="أرباح / خسائر فروق الصرف المحققة",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="tax_active",
            field=models.BooleanField(default=True, verbose_name="الضريبة نشطة"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="vat_active",
            field=models.BooleanField(
                default=True, verbose_name="ضريبة القيمة المضافة نشطة"
            ),
        ),
    ]
