# Generated by Django 4.2.26 on 2026-04-13 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validation_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="transactionattachment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="financial.financialtransaction",
                verbose_name="المعاملة",
            ),
        ),
        migrations.AddField(
            model_name="transactionattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentsyncrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_sync_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentsyncoperation",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="نوع الكائن",
            ),
        ),
        migrations.AddField(
            model_name="paymentsyncoperation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_sync_operations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentsynclog",
            name="sync_operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="financial.paymentsyncoperation",
                verbose_name="عملية التزامن",
            ),
        ),
        migrations.AddField(
            model_name="paymentsyncerror",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_sync_errors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paymentsyncerror",
            name="sync_operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="errors",
                to="financial.paymentsyncoperation",
                verbose_name="عملية التزامن",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_partner_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وافق عليه",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="cash_account",
            field=models.ForeignKey(
                help_text="الحساب النقدي أو البنكي",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_cash_transactions",
                to="financial.chartofaccounts",
                verbose_name="حساب الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_partner_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_transaction",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="partner_account",
            field=models.ForeignKey(
                help_text="حساب جاري الشريك",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_transactions",
                to="financial.chartofaccounts",
                verbose_name="حساب الشريك",
            ),
        ),
        migrations.AddField(
            model_name="partnersettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="partnerpermission",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_partner_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="منح بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="partnerpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="partnerbalance",
            name="partner_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_balance",
                to="financial.chartofaccounts",
                verbose_name="حساب الشريك",
            ),
        ),
        migrations.AddField(
            model_name="partnerauditlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="journalentrytemplateline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_lines",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="journalentrytemplateline",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="financial.journalentrytemplate",
                verbose_name="القالب",
            ),
        ),
        migrations.AddField(
            model_name="journalentrytemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entry_templates_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="financial.journalentry",
                verbose_name="القيد اليومي",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="accounting_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="financial.accountingperiod",
                verbose_name="الفترة المحاسبية",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="financial_category",
            field=models.ForeignKey(
                blank=True,
                help_text="التصنيف المالي للقيد (للتحليل والتقارير)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="financial.financialcategory",
                verbose_name="التصنيف المالي",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="financial_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="التصنيف الفرعي للقيد (للتحليل التفصيلي)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="financial.financialsubcategory",
                verbose_name="التصنيف الفرعي",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="المستخدم الذي قام بقفل القيد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries_locked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="قُفل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="original_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="القيد الأصلي الذي يتم عكسه (للقيود العكسية فقط)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_entries",
                to="financial.journalentry",
                verbose_name="القيد الأصلي",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries_posted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رحل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="invoiceauditlog",
            name="adjustment_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_audit_logs",
                to="financial.journalentry",
                verbose_name="القيد التصحيحي",
            ),
        ),
        migrations.AddField(
            model_name="invoiceauditlog",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_transactions",
                to="financial.chartofaccounts",
                verbose_name="الحساب الرئيسي",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.financialcategory",
                verbose_name="التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_financial_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_financial_transactions",
                to="financial.chartofaccounts",
                verbose_name="الحساب المستلم",
            ),
        ),
        migrations.AddField(
            model_name="financialsubcategory",
            name="parent_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="financial.financialcategory",
                verbose_name="التصنيف الرئيسي",
            ),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="default_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="الحساب المحاسبي الافتراضي للمصروفات من هذا التصنيف",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_categories",
                to="financial.chartofaccounts",
                verbose_name="حساب المصروفات الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="financialcategory",
            name="default_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="الحساب المحاسبي الافتراضي للإيرادات من هذا التصنيف",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenue_categories",
                to="financial.chartofaccounts",
                verbose_name="حساب الإيرادات الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="financial.accounttype",
                verbose_name="نوع الحساب",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chart_accounts_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="financial.chartofaccounts",
                verbose_name="الحساب الأب",
            ),
        ),
        migrations.AddField(
            model_name="categorybudget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="financial.financialcategory",
                verbose_name="التصنيف",
            ),
        ),
        migrations.AddField(
            model_name="categorybudget",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_budgets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliationitem",
            name="reconciliation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="financial.bankreconciliation",
                verbose_name="التسوية",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliation",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_reconciliations",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_reconciliations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_reconciliations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliation",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_reconciliations",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="balancesnapshot",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_snapshots",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="balancereconciliation",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reconciliations",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="balancereconciliation",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="سوى بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="balanceauditlog",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_audit_logs",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.AddField(
            model_name="balanceauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_types_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="financial.accounttype",
                verbose_name="النوع الأب",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أغلق بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="accounts",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                to="financial.chartofaccounts",
                verbose_name="الحسابات",
            ),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_groups_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accountbalancecache",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_cache",
                to="financial.chartofaccounts",
                verbose_name="الحساب",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseTransaction",
            fields=[],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصروفات",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financial.financialtransaction",),
        ),
        migrations.CreateModel(
            name="IncomeTransaction",
            fields=[],
            options={
                "verbose_name": "إيراد",
                "verbose_name_plural": "الإيرادات",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("financial.financialtransaction",),
        ),
        migrations.AddIndex(
            model_name="validationauditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="val_audit_entity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationauditlog",
            index=models.Index(fields=["user", "timestamp"], name="val_audit_user_idx"),
        ),
        migrations.AddIndex(
            model_name="validationauditlog",
            index=models.Index(
                fields=["validation_type", "timestamp"], name="val_audit_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationauditlog",
            index=models.Index(
                fields=["module", "timestamp"], name="val_audit_module_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationauditlog",
            index=models.Index(fields=["timestamp"], name="val_audit_time_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentsyncrule",
            index=models.Index(
                fields=["source_model", "trigger_event"],
                name="financial_p_source__b1b82a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncrule",
            index=models.Index(
                fields=["is_active", "priority"], name="financial_p_is_acti_6ff8af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncoperation",
            index=models.Index(
                fields=["operation_id"], name="financial_p_operati_1e4744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncoperation",
            index=models.Index(
                fields=["status", "created_at"], name="financial_p_status_e96d49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncoperation",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="financial_p_content_4b77fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsynclog",
            index=models.Index(
                fields=["sync_operation", "executed_at"],
                name="financial_p_sync_op_29c8a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsynclog",
            index=models.Index(
                fields=["action", "success"], name="financial_p_action_0f81e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncerror",
            index=models.Index(
                fields=["sync_operation", "occurred_at"],
                name="financial_p_sync_op_c7336e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsyncerror",
            index=models.Index(
                fields=["error_type", "is_resolved"],
                name="financial_p_error_t_bb298b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="financial_p_transac_9bc664_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["partner_account", "status"],
                name="financial_p_partner_2931d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["status", "created_at"], name="financial_p_status_37ff17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerpermission",
            index=models.Index(
                fields=["user", "permission_type", "is_active"],
                name="financial_p_user_id_eabdc8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partnerpermission",
            unique_together={("user", "permission_type")},
        ),
        migrations.AddIndex(
            model_name="partnerauditlog",
            index=models.Index(
                fields=["user", "action", "timestamp"],
                name="financial_p_user_id_b59702_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerauditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="financial_p_action_1b330b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["account", "journal_entry"],
                name="financial_j_account_4e56b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["journal_entry"], name="financial_j_journal_0d4951_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["date", "status"], name="financial_j_date_1898e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["number"], name="financial_j_number_a4f2ef_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="financial_j_referen_8bd693_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_module", "source_model", "source_id"],
                name="financial_j_source__ae7130_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_type", "date"], name="financial_j_entry_t_41d96a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["accounting_period", "status"],
                name="financial_j_account_13ccd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["created_by", "date"], name="financial_j_created_082631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["posted_at"], name="financial_j_posted__721067_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["idempotency_key"], name="financial_j_idempot_759deb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["created_by_service"], name="financial_j_created_9da184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["original_entry", "is_reversal"],
                name="financial_j_origina_d18fd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["is_locked", "status"], name="financial_j_is_lock_724bca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["locked_at"], name="financial_j_locked__7b7ae0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceauditlog",
            index=models.Index(
                fields=["invoice_type", "invoice_id"],
                name="financial_i_invoice_c59e82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceauditlog",
            index=models.Index(
                fields=["invoice_number"], name="financial_i_invoice_a4d82b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceauditlog",
            index=models.Index(
                fields=["created_at"], name="financial_i_created_f4374b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialsubcategory",
            index=models.Index(
                fields=["parent_category", "is_active"],
                name="financial_f_parent__8cffdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialsubcategory",
            index=models.Index(fields=["code"], name="financial_f_code_abb8f1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="financialsubcategory",
            unique_together={("parent_category", "code")},
        ),
        migrations.AddIndex(
            model_name="financialcategory",
            index=models.Index(fields=["code"], name="financial_f_code_1b83f0_idx"),
        ),
        migrations.AddIndex(
            model_name="financialcategory",
            index=models.Index(
                fields=["is_active"], name="financial_f_is_acti_c84966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialcategory",
            index=models.Index(
                fields=["display_order"], name="financial_f_display_c36365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(fields=["code"], name="financial_c_code_8cbc99_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="financial_c_account_938ba3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccounts",
            index=models.Index(
                fields=["parent", "level"], name="financial_c_parent__7d1112_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categorybudget",
            unique_together={("category", "start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["account", "reconciliation_date"],
                name="financial_b_account_e1787f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliation",
            index=models.Index(
                fields=["status", "created_at"], name="financial_b_status_0c0148_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["account", "snapshot_date"],
                name="financial_b_account_9b3132_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["snapshot_date"], name="financial_b_snapsho_37b4d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balancesnapshot",
            unique_together={("account", "snapshot_date")},
        ),
        migrations.AddIndex(
            model_name="balancereconciliation",
            index=models.Index(
                fields=["account", "reconciliation_date"],
                name="financial_b_account_52ce37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balancereconciliation",
            index=models.Index(
                fields=["status", "reconciliation_date"],
                name="financial_b_status_f45fa2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="balancereconciliation",
            unique_together={("account", "reconciliation_date")},
        ),
        migrations.AddIndex(
            model_name="balanceauditlog",
            index=models.Index(
                fields=["account", "timestamp"], name="financial_b_account_44e5a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="balanceauditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="financial_b_action_6958e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="financial_a_entity__eda2a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "timestamp"], name="financial_a_user_id_c7094c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["action", "timestamp"], name="financial_a_action_14d918_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="financial_a_content_9d4feb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttype",
            index=models.Index(
                fields=["category", "is_active"], name="financial_a_categor_d5979a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttype",
            index=models.Index(
                fields=["parent", "level"], name="financial_a_parent__3fbb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttype",
            index=models.Index(fields=["code"], name="financial_a_code_feb165_idx"),
        ),
        migrations.AddIndex(
            model_name="accounttype",
            index=models.Index(
                fields=["is_system_type"], name="financial_a_is_syst_c8b59b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountingperiod",
            unique_together={("start_date", "end_date")},
        ),
        migrations.AddIndex(
            model_name="accountbalancecache",
            index=models.Index(
                fields=["last_updated"], name="financial_a_last_up_50f0c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbalancecache",
            index=models.Index(
                fields=["is_valid", "needs_refresh"],
                name="financial_a_is_vali_679702_idx",
            ),
        ),
    ]
