# Generated by Django 4.2.23 on 2025-10-25 04:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0001_initial_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(help_text='رقم مرجعي للقرض', max_length=50, unique=True, verbose_name='رقم القرض')),
                ('loan_type', models.CharField(choices=[('short_term', 'قصير الأجل (أقل من سنة)'), ('long_term', 'طويل الأجل (أكثر من سنة)')], default='long_term', max_length=20, verbose_name='نوع القرض')),
                ('lender_type', models.CharField(choices=[('bank', 'بنك'), ('supplier', 'مورد'), ('partner', 'شريك'), ('individual', 'فرد'), ('other', 'أخرى')], default='bank', max_length=20, verbose_name='نوع الجهة المقرضة')),
                ('lender_name', models.CharField(help_text='مثال: البنك الأهلي المصري', max_length=200, verbose_name='اسم الجهة المقرضة')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ القرض الأصلي')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مثال: 10.5 تعني 10.5%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='معدل الفائدة السنوي (%)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ استلام القرض')),
                ('duration_months', models.PositiveIntegerField(help_text='عدد الأشهر لسداد القرض', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة القرض (بالأشهر)')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='monthly', max_length=20, verbose_name='دورية السداد')),
                ('description', models.TextField(help_text='تفاصيل عن القرض والغرض منه', verbose_name='وصف القرض')),
                ('notes', models.TextField(blank=True, help_text='أي ملاحظات إضافية', verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل السداد'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bank_account', models.ForeignKey(help_text='الحساب الذي استلم مبلغ القرض', on_delete=django.db.models.deletion.PROTECT, related_name='loans_received', to='financial.chartofaccounts', verbose_name='الحساب البنكي المستلم')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('initial_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_initial_entry', to='financial.journalentry', verbose_name='القيد المحاسبي الأصلي')),
                ('interest_expense_account', models.ForeignKey(blank=True, help_text='مثال: 5300 - فوائد القروض', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_expenses', to='financial.chartofaccounts', verbose_name='حساب مصروف الفوائد')),
                ('loan_account', models.ForeignKey(help_text='مثال: 22010 - القروض طويلة الأجل', on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_liability', to='financial.chartofaccounts', verbose_name='حساب القرض (خصوم)')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField(help_text='رقم القسط من إجمالي الأقساط', verbose_name='رقم القسط')),
                ('scheduled_date', models.DateField(help_text='التاريخ المجدول للدفع', verbose_name='تاريخ الاستحقاق')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='أصل القسط')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الفوائد')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('completed', 'مكتمل'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment_entry', to='financial.journalentry', verbose_name='القيد المحاسبي')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.loan', verbose_name='القرض')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='دفع بواسطة')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments', to='financial.chartofaccounts', verbose_name='حساب الدفع')),
            ],
            options={
                'verbose_name': 'دفعة قرض',
                'verbose_name_plural': 'دفعات القروض',
                'ordering': ['loan', 'payment_number'],
                'indexes': [models.Index(fields=['loan', 'payment_number'], name='financial_l_loan_id_911f9f_idx'), models.Index(fields=['status', 'scheduled_date'], name='financial_l_status_9d42dc_idx')],
                'unique_together': {('loan', 'payment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_number'], name='financial_l_loan_nu_46a4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'start_date'], name='financial_l_status_2993fe_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['lender_type', 'status'], name='financial_l_lender__9105e9_idx'),
        ),
    ]
