# Generated by Django 5.2.17 on 2026-09-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGN', 'إسناد جديد'), ('UPDATE', 'تعديل صلاحيات'), ('REVOKE', 'إلغاء الإسناد')], max_length=15, verbose_name='نوع الإجراء')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل التغيير')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت والتاريخ')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_treasury_audits', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.chartofaccounts', verbose_name='الخزينة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المعني')),
            ],
            options={
                'verbose_name': 'سجل تدقيق صلاحيات الخزن',
                'verbose_name_plural': 'سجلات تدقيق صلاحيات الخزن',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserTreasuryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_deposit', models.BooleanField(default=True, help_text='يتيح استلام النقدية والتحصيل وفواتير البيع النقدية وسندات القبض', verbose_name='صلاحية الإيداع / القبض')),
                ('can_disburse', models.BooleanField(default=True, help_text='يتيح صرف النقدية والمدفوعات وفواتير الشراء النقدية والمصروفات', verbose_name='صلاحية الصرف / الدفع')),
                ('is_default', models.BooleanField(default=False, help_text='يتم اختيارها تلقائياً عند فتح شاشات الدفع والتحصيل بنفس العملة', verbose_name='الخزينة الافتراضية لعملتها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_treasuries', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول المُسند')),
                ('treasury', models.ForeignKey(help_text='يقتصر على الحسابات النقدية والبنكية الطرفية المفعلة', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='financial.chartofaccounts', verbose_name='الخزينة / الحساب البنكي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_accesses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية خزينة لمستخدم',
                'verbose_name_plural': 'صلاحيات الخزن للمستخدمين',
                'ordering': ['user', 'treasury__code'],
                'indexes': [models.Index(fields=['user', 'can_deposit'], name='financial_u_user_id_e52491_idx'), models.Index(fields=['user', 'can_disburse'], name='financial_u_user_id_712ed3_idx'), models.Index(fields=['user', 'is_default'], name='financial_u_user_id_e6bb0f_idx')],
                'unique_together': {('user', 'treasury')},
            },
        ),
    ]
