# Generated by Django 4.2.23 on 2025-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_loan_loanpayment_loan_financial_l_loan_nu_46a4e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(blank=True, help_text='رقم مرجعي للقرض - يتم توليده تلقائياً', max_length=50, unique=True, verbose_name='رقم القرض'),
        ),
    ]
