# Generated by Django 4.2.26 on 2026-07-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_order", "0001_initial"),
        ("financial", "0003_journalentry_work_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_transactions",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
    ]
