# Generated by Django 4.2.26 on 2026-08-21 01:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0003_add_journal_immutability_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcode",
            name="eta_tax_type",
            field=models.CharField(
                blank=True,
                default="T1",
                help_text="مثال: T1 للقيمة المضافة، T4 للخصم تحت الحساب",
                max_length=10,
                null=True,
                verbose_name="كود الضريبة بمنظومة الفاتورة الإلكترونية (ETA)",
            ),
        ),
        migrations.AddField(
            model_name="taxexemptioncertificate",
            name="max_quota_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="أقصى قيمة خاضعة للإعفاء",
                max_digits=15,
                null=True,
                verbose_name="سقف مبلغ الإعفاء المعتمد (إن وجد)",
            ),
        ),
        migrations.AddField(
            model_name="taxexemptioncertificate",
            name="utilized_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ المستهلك من الإعفاء",
            ),
        ),
    ]
