# Generated by Django 4.2.7 on 2025-10-26 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_make_loan_number_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("scheduled", "قسط مجدول"), ("adhoc", "دفعة عشوائية")],
                default="scheduled",
                help_text="مجدول: قسط من جدول السداد | عشوائي: دفعة إضافية",
                max_length=20,
                verbose_name="نوع الدفعة",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="duration_months",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="مدة القرض (بالأشهر)",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="lender_name",
            field=models.CharField(max_length=200, verbose_name="اسم الجهة المقرضة"),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="payment_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="رقم القسط من إجمالي الأقساط (للمجدولة فقط)",
                null=True,
                verbose_name="رقم القسط",
            ),
        ),
    ]
