# Generated by Django 5.2.17 on 2026-09-20 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_treasuryaccessauditlog_usertreasuryaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasuryaccessauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل تدقيق إسناد الخزن', 'verbose_name_plural': 'سجلات تدقيق إسناد الخزن'},
        ),
        migrations.AlterModelOptions(
            name='usertreasuryaccess',
            options={'verbose_name': 'إسناد خزينة لمستخدم', 'verbose_name_plural': 'إسنادات الخزن للمستخدمين'},
        ),
        migrations.RemoveIndex(
            model_name='usertreasuryaccess',
            name='financial_u_user_id_e6bb0f_idx',
        ),
        migrations.RenameIndex(
            model_name='usertreasuryaccess',
            new_name='idx_usr_trsy_dep',
            old_name='financial_u_user_id_e52491_idx',
        ),
        migrations.RenameIndex(
            model_name='usertreasuryaccess',
            new_name='idx_usr_trsy_disb',
            old_name='financial_u_user_id_712ed3_idx',
        ),
        migrations.RemoveField(
            model_name='treasuryaccessauditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='treasuryaccessauditlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='book_balance_at_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='توثيق الرصيد الدفتري لإخلاء الطرف ومحاضر التسليم والتسلم', max_digits=18, null=True, verbose_name='الرصيد الدفتري لحظة التغيير'),
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت التدقيق'),
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='new_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='الصلاحيات الجديدة'),
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='treasuryaccessauditlog',
            name='old_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='الصلاحيات السابقة'),
        ),
        migrations.AddField(
            model_name='usertreasuryaccess',
            name='daily_disbursement_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أقصى إجمالي مبالغ يمكن صرفها تراكمياً خلال اليوم الواحد', max_digits=18, null=True, verbose_name='الحد الأقصى للصرف اليومي التراكمي'),
        ),
        migrations.AddField(
            model_name='usertreasuryaccess',
            name='max_single_disbursement_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أقصى مبلغ مالي يمكن صرفه في عملية أو قيد واحد (اتركه فارغاً لبلا سقف)', max_digits=18, null=True, verbose_name='الحد الأقصى للصرف للحركة الواحدة'),
        ),
        migrations.AddField(
            model_name='usertreasuryaccess',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات / سبب الإسناد'),
        ),
        migrations.AddField(
            model_name='usertreasuryaccess',
            name='valid_from',
            field=models.DateField(blank=True, help_text='تاريخ بدء تفعيل الصلاحية للمستخدم (اختياري للورديات والإجازات)', null=True, verbose_name='ساري من تاريخ'),
        ),
        migrations.AddField(
            model_name='usertreasuryaccess',
            name='valid_until',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء الصلاحية تلقائياً (اختياري)', null=True, verbose_name='ساري حتى تاريخ'),
        ),
        migrations.AlterField(
            model_name='treasuryaccessauditlog',
            name='action',
            field=models.CharField(choices=[('ASSIGNED', 'إسناد جديد'), ('UPDATED', 'تعديل صلاحيات'), ('REVOKED', 'إلغاء إسناد'), ('LIMIT_BREACH_ATTEMPT', 'محاولة تجاوز سقف مالي'), ('TAMPER_ATTEMPT', 'محاولة وصول غير مصرح')], max_length=50, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='treasuryaccessauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_treasury_audits', to=settings.AUTH_USER_MODEL, verbose_name='القائم بالإجراء'),
        ),
        migrations.AlterField(
            model_name='treasuryaccessauditlog',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_access_audit_logs', to='financial.chartofaccounts', verbose_name='الخزينة'),
        ),
        migrations.AlterField(
            model_name='treasuryaccessauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المعني'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_treasury_accesses', to=settings.AUTH_USER_MODEL, verbose_name='تم الإسناد بواسطة'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='can_deposit',
            field=models.BooleanField(default=True, help_text='تتيح للمستخدم تحصيل وقبض النقدية وإيداعها في هذا الحساب', verbose_name='صلاحية الإيداع / التحصيل'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='can_disburse',
            field=models.BooleanField(default=False, help_text='تتيح للمستخدم سداد الفواتير والمصروفات وصرف النقدية من هذا الحساب', verbose_name='صلاحية الصرف / السداد'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='is_default',
            field=models.BooleanField(default=False, help_text='تحديد هذا الحساب كخيار افتراضي عند قيام المستخدم بمعاملات بنفس عملة الحساب', verbose_name='الخزينة الافتراضية للعملة'),
        ),
        migrations.AlterField(
            model_name='usertreasuryaccess',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='financial.chartofaccounts', verbose_name='الخزينة / الحساب البنكي'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccessauditlog',
            index=models.Index(fields=['user', 'treasury'], name='idx_aud_usr_trsy'),
        ),
        migrations.AddIndex(
            model_name='treasuryaccessauditlog',
            index=models.Index(fields=['action', 'created_at'], name='idx_aud_act_date'),
        ),
        migrations.AddIndex(
            model_name='usertreasuryaccess',
            index=models.Index(fields=['user', 'treasury'], name='idx_usr_trsy_acc'),
        ),
        migrations.AddIndex(
            model_name='usertreasuryaccess',
            index=models.Index(fields=['treasury', 'is_default'], name='idx_trsy_is_def'),
        ),
        migrations.AddIndex(
            model_name='usertreasuryaccess',
            index=models.Index(fields=['valid_from', 'valid_until'], name='idx_trsy_validity'),
        ),
    ]
