# Generated by Django 4.2.26 on 2026-08-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0004_taxcode_eta_tax_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcode",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="تحديد هذا الكود كافتراضي لنفس نوع الضريبة",
                verbose_name="افتراضي لنوع الضريبة",
            ),
        ),
        migrations.AlterField(
            model_name="taxrule",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="كود القاعدة"
            ),
        ),
    ]
