# Generated by Django 5.2.17 on 2026-10-07 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_chartofaccounts_max_holding_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransfer',
            name='fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financial.chartofaccounts', verbose_name='حساب المصاريف والعمولات البنكية (54100)'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='fee_vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='مبلغ ضريبة القيمة المضافة على العمولة (11510)'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='transit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in_transit', to='financial.chartofaccounts', verbose_name='حساب نقدية في الطريق (11150)'),
        ),
    ]
