# Generated by Django 4.2.24 on 2025-09-29 11:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0007_add_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الكود')),
                ('type', models.CharField(choices=[('expense', 'مصروف'), ('income', 'إيراد'), ('both', 'مختلط')], max_length=20, verbose_name='النوع')),
                ('priority', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى للإنفاق في هذا التصنيف', max_digits=12, null=True, verbose_name='حد الميزانية')),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='نسبة التحذير من حد الميزانية', max_digits=5, verbose_name='عتبة التحذير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, help_text='فئة أساسية لا يمكن حذفها', verbose_name='فئة نظام')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial.financialcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'فئة مالية',
                'verbose_name_plural': 'التصنيفات المالية',
                'ordering': ['type', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف'), ('transfer', 'تحويل'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع المعاملة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('priority', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع الخارجي')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('processed', 'منفذ'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب موافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('tags', models.CharField(blank=True, help_text='علامات مفصولة بفواصل', max_length=200, null=True, verbose_name='العلامات')),
                ('attachments_count', models.PositiveIntegerField(default=0, verbose_name='عدد المرفقات')),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المورد/العميل')),
                ('vendor_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة الاتصال')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع/الاستلام')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الخصم')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ الصافي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'معاملة مالية',
                'verbose_name_plural': 'المعاملات المالية',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى للسحب على المكشوف', max_digits=15, null=True, verbose_name='حد الائتمان'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='low_balance_alert',
            field=models.BooleanField(default=False, verbose_name='تنبيه الرصيد المنخفض'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='low_balance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='عتبة الرصيد المنخفض'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأدنى المطلوب للرصيد', max_digits=15, null=True, verbose_name='الحد الأدنى للرصيد'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='رمز السويفت'),
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial/attachments/%Y/%m/', verbose_name='الملف')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.PositiveIntegerField(help_text='بالبايت', verbose_name='حجم الملف')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع المحتوى')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='financial.financialtransaction', verbose_name='المعاملة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق معاملة',
                'verbose_name_plural': 'مرفقات المعاملات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='financial.chartofaccounts', verbose_name='الحساب الرئيسي'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.financialcategory', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_financial_transactions', to='financial.chartofaccounts', verbose_name='الحساب المستلم'),
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'شهرية'), ('quarterly', 'ربع سنوية'), ('yearly', 'سنوية'), ('custom', 'مخصصة')], max_length=20, verbose_name='نوع الفترة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الميزانية')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المنفق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='financial.financialcategory', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'ميزانية فئة',
                'verbose_name_plural': 'ميزانيات التصنيفات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.financialtransaction',),
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'إيراد',
                'verbose_name_plural': 'الإيرادات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financial.financialtransaction',),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type', 'date'], name='financial_f_transac_317ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['status', 'created_at'], name='financial_f_status_299db0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', 'date'], name='financial_f_account_8de9e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialcategory',
            unique_together={('name', 'type', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('category', 'start_date', 'end_date')},
        ),
    ]
