# Generated by Django 4.2.26 on 2026-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0007_accountingperiod_fiscal_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="posting_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="مرجع الترحيل"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posting_source",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="مصدر الترحيل"
            ),
        ),
    ]
