# Generated by Django 4.2.26 on 2026-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0008_journalentry_posting_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="reversed_by_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="القيد العاكس الذي قام بعكس هذا القيد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_entries",
                to="financial.journalentry",
                verbose_name="عُكس بواسطة القيد",
            ),
        ),
    ]
