# Generated by Django 5.2.17 on 2026-10-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_cashtransfer_fee_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, help_text='المعرف الموحد للدور المحاسبي (مثل bank_charges_expense)', max_length=100, unique=True, verbose_name='اسم الدور المالي')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف الدور المالي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_roles', to='financial.chartofaccounts', verbose_name='الحساب المحاسبي المرتبط')),
            ],
            options={
                'verbose_name': 'دور محاسبي مالي',
                'verbose_name_plural': 'أدوار الحسابات المالية',
                'ordering': ['role_name'],
            },
        ),
    ]
