# Generated by Django 4.2.23 on 2025-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_cashmovement_cashmovementtype_cashmovementattachment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialtransaction',
            name='financial_f_transac_317ef6_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtransaction',
            name='financial_f_status_299db0_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtransaction',
            name='financial_f_account_8de9e4_idx',
        ),
        migrations.RenameField(
            model_name='transactionattachment',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='transactionattachment',
            name='content_type',
        ),
        migrations.AddField(
            model_name='transactionattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='transactionattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='transactionattachment',
            name='file',
            field=models.FileField(upload_to='financial/transactions/%Y/%m/', verbose_name='الملف'),
        ),
    ]
