# Generated by Django 4.2.26 on 2026-08-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0009_journalentry_reversed_by_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPostingReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(max_length=50, verbose_name="نوع المصدر"),
                ),
                (
                    "source_id",
                    models.CharField(max_length=100, verbose_name="معرف المصدر"),
                ),
                (
                    "posting_type",
                    models.CharField(
                        default="MAIN", max_length=50, verbose_name="نوع الترحيل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_references",
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي المتربط",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرجع ترحيل مالي",
                "verbose_name_plural": "مراجع الترحيل المالية",
            },
        ),
        migrations.AddConstraint(
            model_name="financialpostingreference",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_id", "posting_type"),
                name="unique_posting_reference_per_source_and_type",
            ),
        ),
    ]
