# Generated by Django 4.2.26 on 2026-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0010_financialpostingreference_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(
                fields=["account", "created_at"], name="financial_j_account_2ef894_idx"
            ),
        ),
    ]
