# Generated by Django 4.2.23 on 2025-09-29 19:40

from django.db import migrations, models


def convert_locked_to_closed(apps, schema_editor):
    """تحويل جميع الفترات المقفلة إلى مغلقة"""
    AccountingPeriod = apps.get_model("financial", "AccountingPeriod")
    AccountingPeriod.objects.filter(status="locked").update(status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0011_rename_transaction_table"),
    ]

    operations = [
        # تحويل البيانات القديمة أولاً
        migrations.RunPython(convert_locked_to_closed, migrations.RunPython.noop),
        # ثم تعديل الحقل
        migrations.AlterField(
            model_name="accountingperiod",
            name="status",
            field=models.CharField(
                choices=[("open", "مفتوحة"), ("closed", "مغلقة")],
                default="open",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
    ]
