# Generated by Django 4.2.26 on 2026-08-04 12:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0011_journalentryline_financial_j_account_2ef894_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankReconciliationMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ المطابق"
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("EXACT", "مطابقة تامة"),
                            ("PROBABLE", "مطابقة ترجيحية"),
                            ("MANUAL", "مطابقة يدوية"),
                        ],
                        default="EXACT",
                        max_length=20,
                        verbose_name="نوع المطابقة",
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المطابقة"
                    ),
                ),
                (
                    "journal_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_matches",
                        to="financial.journalentryline",
                        verbose_name="بند قيد اليومية",
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_matches_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طوبق بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل مطابقة بنكية",
                "verbose_name_plural": "سجلات المطابقات البنكية",
            },
        ),
        migrations.CreateModel(
            name="BankStatementBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الدفعة"
                    ),
                ),
                ("statement_date", models.DateField(verbose_name="تاريخ كشف الحساب")),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="رصيد البداية",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="رصيد النهاية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "تم الاستيراد"),
                            ("reconciling", "قيد المطابقة"),
                            ("completed", "مكتمل"),
                        ],
                        default="imported",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_statement_batches",
                        to="financial.chartofaccounts",
                        verbose_name="حساب البنك",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة كشف حساب بنكي",
                "verbose_name_plural": "دفقات كشوف الحسابات البنكية",
                "ordering": ["-statement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="تاريخ المعاملة")),
                (
                    "value_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق/القيمة"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم المرجع البنكي"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="البيان البنكي"),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مدين",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="دائن",
                    ),
                ),
                (
                    "is_matched",
                    models.BooleanField(default=False, verbose_name="مطابق"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financial.bankstatementbatch",
                        verbose_name="الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند كشف حساب بنكي",
                "verbose_name_plural": "بنود كشوف الحسابات البنكية",
                "ordering": ["transaction_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم التخصيص"
                    ),
                ),
                (
                    "debit_document_type",
                    models.CharField(max_length=50, verbose_name="نوع مستند المدين"),
                ),
                (
                    "debit_document_id",
                    models.CharField(max_length=100, verbose_name="معرف مستند المدين"),
                ),
                (
                    "credit_document_type",
                    models.CharField(max_length=50, verbose_name="نوع مستند الدائن"),
                ),
                (
                    "credit_document_id",
                    models.CharField(max_length=100, verbose_name="معرف مستند الدائن"),
                ),
                (
                    "subledger_type",
                    models.CharField(
                        choices=[("customer", "عميل"), ("supplier", "مورد")],
                        max_length=20,
                        verbose_name="نوع الدفتر الفرعي",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        help_text="معرف العميل أو المورد", verbose_name="معرف الكيان"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المخصص",
                    ),
                ),
                ("allocation_date", models.DateField(verbose_name="تاريخ التخصيص")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصيص سداد",
                "verbose_name_plural": "تخصيصات المدفوعات",
                "ordering": ["-allocation_date", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="bankreconciliationitem",
            name="reconciliation",
        ),
        migrations.DeleteModel(
            name="BankReconciliation",
        ),
        migrations.DeleteModel(
            name="BankReconciliationItem",
        ),
        migrations.AddField(
            model_name="bankreconciliationmatch",
            name="statement_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="financial.bankstatementline",
                verbose_name="سطر كشف الحساب البنكي",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["debit_document_type", "debit_document_id"],
                name="financial_p_debit_d_cb72a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["credit_document_type", "credit_document_id"],
                name="financial_p_credit__e35517_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["subledger_type", "entity_id"],
                name="financial_p_subledg_15eae9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankreconciliationmatch",
            constraint=models.UniqueConstraint(
                fields=("statement_line", "journal_line"),
                name="unique_bank_statement_to_journal_line_match",
            ),
        ),
    ]
