# Generated by Django 4.2.23 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_accountingperiod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات إضافية على القيد', null=True, verbose_name='ملاحظات'),
        ),
    ]
