# Generated by Django 4.2.26 on 2026-08-04 13:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0013_financialstatementsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="رمز العملة"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم العملة")),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="رمز الرمزية"
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="الكسور العشريّة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_base",
                    models.BooleanField(
                        default=False, verbose_name="عملة الأساس (EGP)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "عملة",
                "verbose_name_plural": "العملات",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="currency",
            field=models.CharField(default="EGP", max_length=3, verbose_name="العملة"),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="foreign_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="دائن بالعملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="foreign_debit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                verbose_name="مدين بالعملة الأجنبية",
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=18, verbose_name="سعر الصرف"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ السريان"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="MANUAL", max_length=50, verbose_name="المصدر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_rates",
                        to="financial.currency",
                        verbose_name="من عملة",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_rates",
                        to="financial.currency",
                        verbose_name="إلى عملة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سعر صرف",
                "verbose_name_plural": "أسعار الصرف",
                "ordering": ["-effective_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "effective_date"],
                        name="financial_e_from_cu_1f03d2_idx",
                    )
                ],
            },
        ),
    ]
