# Generated by Django 4.2.26 on 2026-08-04 13:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0014_currency_journalentryline_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "المشتريات"),
                            ("SALES", "المبيعات"),
                            ("CREDIT", "حدود الائتمان"),
                        ],
                        default="SALES",
                        max_length=20,
                        verbose_name="الموديول",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="اسم القاعدة"),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأدنى للقيمة",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("999999999.00"),
                        max_digits=15,
                        verbose_name="الحد الأقصى للقيمة",
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        max_length=50, verbose_name="دور المعتمد (مثال: MANAGER, CTO)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قاعدة اعتماد مؤسسية",
                "verbose_name_plural": "قواعد الاعتماد المؤسسية",
            },
        ),
        migrations.CreateModel(
            name="EnterpriseApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "المشتريات"),
                            ("SALES", "المبيعات"),
                            ("CREDIT", "حدود الائتمان"),
                        ],
                        max_length=20,
                        verbose_name="الموديول",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        max_length=100, verbose_name="رقم مرجع المستند (SO/PO/Cust ID)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "معلق"),
                            ("APPROVED", "معتمد"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="ملاحظات / سبب القرار"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ تقديم الطلب"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعتمد",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="financial.enterpriseapprovalrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب اعتماد مؤسسي",
                "verbose_name_plural": "طلبات الاعتماد المؤسسية",
                "ordering": ["-created_at"],
            },
        ),
    ]
