# Generated by Django 4.2.23 on 2025-10-05 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0015_remove_cash_movements'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('post', 'ترحيل'), ('unpost', 'إلغاء ترحيل'), ('sync', 'ربط مالي'), ('unsync', 'إلغاء ربط مالي'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('cancel', 'إلغاء')], max_length=20, verbose_name='العملية')),
                ('entity_type', models.CharField(choices=[('sale_payment', 'دفعة مبيعات'), ('purchase_payment', 'دفعة مشتريات'), ('journal_entry', 'قيد محاسبي'), ('cash_movement', 'حركة خزن'), ('sale', 'فاتورة مبيعات'), ('purchase', 'فاتورة مشتريات')], max_length=30, verbose_name='نوع الكيان')),
                ('entity_id', models.PositiveIntegerField(verbose_name='معرف الكيان')),
                ('entity_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الكيان')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('description', models.TextField(verbose_name='وصف العملية')),
                ('reason', models.TextField(blank=True, verbose_name='سبب العملية')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('status', models.CharField(choices=[('success', 'نجحت'), ('failed', 'فشلت'), ('pending', 'معلقة'), ('cancelled', 'ملغية')], default='success', max_length=20, verbose_name='حالة العملية')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='financial_a_entity__eda2a5_idx'), models.Index(fields=['user', 'timestamp'], name='financial_a_user_id_c7094c_idx'), models.Index(fields=['action', 'timestamp'], name='financial_a_action_14d918_idx'), models.Index(fields=['content_type', 'object_id'], name='financial_a_content_9d4feb_idx')],
            },
        ),
    ]
