# Generated by Django 4.2.26 on 2026-08-04 15:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0019_salespolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0016_enterpriseapprovalrequest_requested_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueRecognitionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_event_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="معرف الحدث المعالج الفريد",
                    ),
                ),
                (
                    "recognition_event",
                    models.CharField(
                        choices=[
                            ("DELIVERY_CONFIRMED", "تأكيد التسليم"),
                            ("CUSTOMER_ACCEPTANCE", "قبول العميل"),
                            ("INSTALLATION_COMPLETED", "إتمام التركيب"),
                            ("SERVICE_COMPLETED", "إتمام الخدمة"),
                            ("TIME_MILESTONE", "محطة زمنية"),
                            ("MANUAL_ADJUSTMENT", "تعديل يدو ي"),
                        ],
                        max_length=30,
                        verbose_name="حدث الاعتراف",
                    ),
                ),
                (
                    "entry_status",
                    models.CharField(
                        choices=[
                            ("POSTED", "مرحل"),
                            ("REVERSED", "معكوس"),
                            ("FAILED", "فاشل"),
                        ],
                        default="POSTED",
                        max_length=20,
                        verbose_name="حالة القيد/السجل",
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="المبلغ بالأجنبي"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي (EGP)",
                    ),
                ),
                (
                    "audit_hash",
                    models.CharField(
                        max_length=64, verbose_name="التوقيع المشفر Canonical SHA256"
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="معرف التتبع الفريد Correlation UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي بالاستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل قيود الاعتراف بالإيراد",
                "verbose_name_plural": "سجلات قيود الاعتراف بالإيراد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueRecognitionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم السياسة")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود السياسة"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="إصدار السياسة"),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="سارية من تاريخ"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="سارية إلى تاريخ"
                    ),
                ),
                (
                    "rule_scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "شامل عام"),
                            ("CATEGORY", "فئة منتجات"),
                            ("PRODUCT", "منتج محدد"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                        verbose_name="نطاق السياسة",
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="قيمة النطاق (معرف الفئة/المنتج)",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("INVOICE_ISSUANCE", "إصدار الفاتورة"),
                            ("DELIVERY_CONFIRMED", "تأكيد التسليم"),
                            ("CUSTOMER_ACCEPTANCE", "قبول العميل"),
                            ("INSTALLATION_COMPLETED", "إتمام التركيب"),
                            ("SERVICE_COMPLETED", "إتمام الخدمة"),
                            ("TIME_MILESTONE", "جدول زمني"),
                        ],
                        default="DELIVERY_CONFIRMED",
                        max_length=30,
                        verbose_name="حدث الاعتراف المحفز",
                    ),
                ),
                (
                    "allocation_method",
                    models.CharField(
                        choices=[
                            ("DIRECT_LINE_VALUE", "قيمة البند المباشرة"),
                            ("PERCENTAGE", "نسبة مئوية"),
                            ("FIXED_AMOUNT", "مبلغ ثابت"),
                            ("STANDALONE_SELLING_PRICE", "سعر البيع المستقل"),
                        ],
                        default="DIRECT_LINE_VALUE",
                        max_length=30,
                        verbose_name="طريقة تخصيص سعر المعاملة",
                    ),
                ),
                (
                    "fx_treatment_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_RATE", "سعر صرف الفاتورة"),
                            ("RECOGNITION_DATE_RATE", "سعر صرف تاريخ الاعتراف"),
                            ("AVERAGE_RATE", "متوسط سعر الصرف"),
                        ],
                        default="INVOICE_RATE",
                        max_length=30,
                        verbose_name="معالجة أسعار الصرف IAS 21",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "سياسة الاعتراف بالإيراد",
                "verbose_name_plural": "سياسات الاعتراف بالإيراد",
                "unique_together": {("code", "version")},
            },
        ),
        migrations.CreateModel(
            name="RevenueRecognitionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_version",
                    models.IntegerField(default=1, verbose_name="إصدار السياسة"),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مرجع العقد التجاري",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "allocated_transaction_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="سعر المعاملة المخصص بالعملة الأصلي",
                    ),
                ),
                (
                    "recognized_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المعترف به تراكمياً",
                    ),
                ),
                (
                    "deferred_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المؤجل المتبقي",
                    ),
                ),
                (
                    "contract_asset_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ أصول العقد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("ACTIVE", "نشط"),
                            ("FULLY_RECOGNIZED", "معترف به بالكامل"),
                            ("REVERSED", "معكوس"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="حالة الجدول",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_schedules",
                        to="sale.salesinvoiceitem",
                        verbose_name="بند الفاتورة",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="financial.revenuerecognitionpolicy",
                        verbose_name="السياسة المطبقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول الاعتراف بالإيراد",
                "verbose_name_plural": "جداول الاعتراف بالإيراد",
            },
        ),
        migrations.CreateModel(
            name="RevenueRecognitionScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField(verbose_name="التسلسل")),
                (
                    "recognition_date",
                    models.DateField(verbose_name="تاريخ المستهدف للاعتراف"),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأجنبية",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي (EGP)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "مجدول"),
                            ("RECOGNIZED", "تم الاعتراف"),
                            ("REVERSED", "معكوس"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="حالة السطر",
                    ),
                ),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.accountingperiod",
                        verbose_name="الفترة المحاسبية Target Period",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financial.revenuerecognitionschedule",
                        verbose_name="الجدول الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر جدول الاعتراف بالإيراد",
                "verbose_name_plural": "أسطر جدول الاعتراف بالإيراد",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="RevenueRecognitionReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reversal_type",
                    models.CharField(
                        default="FULL_REVERSAL", max_length=50, verbose_name="نوع العكس"
                    ),
                ),
                (
                    "reversal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="مبلغ العكس الوظيفي (EGP)",
                    ),
                ),
                (
                    "reversal_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ القيد العكسي",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب العكس")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد العكس بالأستاذ",
                    ),
                ),
                (
                    "original_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="financial.revenuerecognitionentry",
                        verbose_name="القيد الأصلي المعكوس",
                    ),
                ),
            ],
            options={
                "verbose_name": "عكس قيد اعتراف بإيراد",
                "verbose_name_plural": "عكوسات قيود الاعتراف بالإيرادات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="revenuerecognitionentry",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="financial.revenuerecognitionschedule",
                verbose_name="جدول الاعتراف",
            ),
        ),
        migrations.AddField(
            model_name="revenuerecognitionentry",
            name="schedule_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="financial.revenuerecognitionscheduleline",
                verbose_name="سطر الخطة",
            ),
        ),
        migrations.CreateModel(
            name="RevenueRecognitionAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "contract_asset_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_asset_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب أصول العقود",
                    ),
                ),
                (
                    "deferred_revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deferred_rev_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب الإيرادات المؤجلة / التزامات العقود",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_mappings",
                        to="financial.revenuerecognitionpolicy",
                        verbose_name="السياسة",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rev_rec_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب الإيرادات",
                    ),
                ),
            ],
            options={
                "verbose_name": "خريطة حسابات الاعتراف بالإيراد",
                "verbose_name_plural": "خرائط حسابات الاعتراف بالإيراد",
            },
        ),
        migrations.AddConstraint(
            model_name="revenuerecognitionschedule",
            constraint=models.UniqueConstraint(
                fields=("invoice_item", "policy", "policy_version"),
                name="unique_invoice_item_policy_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="revenuerecognitionentry",
            constraint=models.UniqueConstraint(
                fields=("processed_event_id",), name="unique_processed_event_id"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="revenuerecognitionaccountmapping",
            unique_together={("policy", "currency")},
        ),
    ]
