# Generated by Django 4.2.7 on 2025-10-21 13:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0017_partner_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="إجمالي المساهمات",
                    ),
                ),
                (
                    "total_withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="إجمالي السحوبات",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                (
                    "last_transaction_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ آخر معاملة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "رصيد الشريك",
                "verbose_name_plural": "أرصدة الشركاء",
            },
        ),
        migrations.CreateModel(
            name="PartnerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("contribution", "مساهمة"), ("withdrawal", "سحب")],
                        max_length=20,
                        verbose_name="نوع المعاملة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loan", "قرض للشركة"),
                            ("capital_increase", "زيادة رأس المال"),
                            ("temporary", "مساهمة مؤقتة"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع المساهمة",
                    ),
                ),
                (
                    "withdrawal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loan_repayment", "سداد قرض سابق"),
                            ("capital_withdrawal", "سحب من رأس المال"),
                            ("profit_distribution", "توزيع أرباح"),
                            ("personal_expense", "مصروف شخصي"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع السحب",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المعاملة"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="سبب المساهمة أو السحب", verbose_name="الوصف"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات إضافية"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الانتظار"),
                            ("approved", "موافق عليه"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة الشريك",
                "verbose_name_plural": "معاملات الشريك",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="partnerpermission",
            name="unique_user_permission",
        ),
        migrations.RenameIndex(
            model_name="partnerauditlog",
            new_name="financial_p_user_id_b59702_idx",
            old_name="financial_p_user_id_b8b9a8e_idx",
        ),
        migrations.RenameIndex(
            model_name="partnerauditlog",
            new_name="financial_p_action_1b330b_idx",
            old_name="financial_p_action_c8b9a8e_idx",
        ),
        migrations.RenameIndex(
            model_name="partnerpermission",
            new_name="financial_p_user_id_eabdc8_idx",
            old_name="financial_p_user_id_a8b9a8e_idx",
        ),
        migrations.AlterField(
            model_name="partnerauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="partnerpermission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="partnersettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partnerpermission",
            unique_together={("user", "permission_type")},
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_partner_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="وافق عليه",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="cash_account",
            field=models.ForeignKey(
                help_text="الحساب النقدي أو البنكي",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_cash_transactions",
                to="financial.chartofaccounts",
                verbose_name="حساب الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_partner_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_transaction",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="partnertransaction",
            name="partner_account",
            field=models.ForeignKey(
                help_text="حساب جاري الشريك",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_transactions",
                to="financial.chartofaccounts",
                verbose_name="حساب الشريك",
            ),
        ),
        migrations.AddField(
            model_name="partnerbalance",
            name="partner_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_balance",
                to="financial.chartofaccounts",
                verbose_name="حساب الشريك",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="financial_p_transac_9bc664_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["partner_account", "status"],
                name="financial_p_partner_2931d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnertransaction",
            index=models.Index(
                fields=["status", "created_at"], name="financial_p_status_37ff17_idx"
            ),
        ),
    ]
