# Generated by Django 4.2.26 on 2026-08-04 15:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0009_customerallocationaudit_reversed_audit_and_more"),
        ("supplier", "0002_initial"),
        ("financial", "0017_revenuerecognitionentry_revenuerecognitionpolicy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود الضريبة"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم الضريبة")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("VAT", "ضريبة القيمة المضافة"),
                            ("WITHHOLDING", "ضريبة الخصم والإضافة"),
                            ("SALES_TAX", "ضريبة المبيعات"),
                            ("EXCISE", "ضريبة الجدول / السلع الجدولية"),
                            ("ZERO_RATED", "ضريبة بسعر صفر"),
                            ("EXEMPT", "معفى من الضريبة"),
                        ],
                        default="VAT",
                        max_length=30,
                        verbose_name="نوع الضريبة",
                    ),
                ),
                (
                    "tax_nature",
                    models.CharField(
                        choices=[
                            ("OUTPUT", "ضريبة مخرجات (مبيعات / التزام)"),
                            ("INPUT", "ضريبة مدخلات (مشتريات / أصل مخصوم)"),
                            ("WITHHOLDING", "خصم وإضافة (تحصيل/سداد مستقطع)"),
                            ("NON_RECOVERABLE", "ضريبة غير قابلة للاسترداد"),
                        ],
                        default="OUTPUT",
                        max_length=30,
                        verbose_name="طبيعة الضريبة المحاسبية",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("14.0000"),
                        max_digits=8,
                        verbose_name="نسبة الضريبة %",
                    ),
                ),
                (
                    "is_recoverable",
                    models.BooleanField(
                        default=True, verbose_name="قابلة للاسترداد / الخصم"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="سارية من"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="سارية إلى"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "كود الضريبة",
                "verbose_name_plural": "أكواد الضرائب",
            },
        ),
        migrations.CreateModel(
            name="TaxDeterminationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                ("document_id", models.IntegerField(verbose_name="معرف المستند")),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="رقم المستند"),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الخاضع للضريبة",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الضريبة بالأجنبي",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي الضريبة الوظيفي (EGP)",
                    ),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("CALCULATED", "تم الحساب"),
                            ("POSTED", "مرحل بالقيود"),
                            ("REVERSED", "معكوس"),
                            ("FAILED", "فاشل"),
                        ],
                        default="CALCULATED",
                        max_length=20,
                        verbose_name="حالة السجل",
                    ),
                ),
                (
                    "processed_event_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="معرف الحدث المعالج الفريد",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="معرف التتبع الفريد Correlation UUID",
                    ),
                ),
                (
                    "audit_hash",
                    models.CharField(
                        max_length=64, verbose_name="التوقيع المشفر Canonical SHA256"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد الأستاذ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.taxcode",
                        verbose_name="كود الضريبة الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق احتساب الضريبة",
                "verbose_name_plural": "سجلات تدقيق احتساب الضرائب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxJurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود الهيئة الضريبية"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="اسم الهيئة الضريبية"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Egypt", max_length=100, verbose_name="الدولة"
                    ),
                ),
                (
                    "tax_authority",
                    models.CharField(
                        default="مصلحة الضرائب المصرية",
                        max_length=150,
                        verbose_name="اسم المصلحة / الهيئة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "النطاق الضريبي",
                "verbose_name_plural": "النطاقات الضريبية",
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="كود القاعدة")),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="اسم القاعدة الضريبية"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="إصدار القاعدة"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=10, verbose_name="الأولوية (الرقم الأكبر أعلى أولوية)"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="سارية من"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="سارية إلى"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.taxjurisdiction",
                        verbose_name="النطاق الضريبي",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="financial.taxcode",
                        verbose_name="كود الضريبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة تطبيق الضريبة",
                "verbose_name_plural": "قواعد تطبيق الضرائب",
                "ordering": ["-priority", "-version"],
            },
        ),
        migrations.CreateModel(
            name="TaxRuleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل المشروط"),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUAL", "يساوي"),
                            ("NOT_EQUAL", "لا يساوي"),
                            ("IN", "ينتمي لمجموعة"),
                            ("BETWEEN", "بين قيمتين"),
                            ("GREATER_THAN", "أكبر من"),
                            ("LESS_THAN", "أصغر من"),
                        ],
                        default="EQUAL",
                        max_length=20,
                        verbose_name="المعامل المنطقي",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="القيمة المشروطة"),
                ),
                ("sequence", models.IntegerField(default=1, verbose_name="التسلسل")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="financial.taxrule",
                        verbose_name="القاعدة الضريبية",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرط قاعدة ضريبية",
                "verbose_name_plural": "شروط قواعد الضرائب",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TaxReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reversal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="مبلغ الضريبة المعكوس الوظيفي",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب العكس")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ العكس"),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد العكس بالأستاذ",
                    ),
                ),
                (
                    "original_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="financial.taxdeterminationaudit",
                        verbose_name="السجل الأصلي المعكوس",
                    ),
                ),
            ],
            options={
                "verbose_name": "عكس ضريبة",
                "verbose_name_plural": "عكوسات الضرائب",
            },
        ),
        migrations.CreateModel(
            name="TaxRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[("CUSTOMER", "عميل"), ("SUPPLIER", "مورد")],
                        max_length=20,
                        verbose_name="نوع الطرف",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=100,
                        verbose_name="رقم التسجيل الضريبي / البطاقة الضريبية",
                    ),
                ),
                (
                    "tax_authority",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="المأمورية / الهيئة الضريبية",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ بدء التسجيل",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء التسجيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="ACTIVE", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_registrations",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_registrations",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل ضريبي لطرف",
                "verbose_name_plural": "التسجيلات الضريبية لأطراف التعامل",
            },
        ),
        migrations.CreateModel(
            name="TaxExemptionCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم شهادة الإعفاء"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="صالحة من تاريخ")),
                ("valid_to", models.DateField(verbose_name="صالحة إلى تاريخ")),
                (
                    "exemption_reason",
                    models.TextField(verbose_name="سبب الإعفاء المعتمد قانوناً"),
                ),
                (
                    "attachment_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="مرجع المرفق / الشهادة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="ACTIVE", max_length=20, verbose_name="حالة الشهادة"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_exemptions",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_exemptions",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exemptions",
                        to="financial.taxcode",
                        verbose_name="كود الضريبة المعفى منها",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة إعفاء ضريبي",
                "verbose_name_plural": "شهادات الإعفاء الضريبي",
            },
        ),
        migrations.CreateModel(
            name="TaxCalculationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                ("document_id", models.IntegerField(verbose_name="معرف المستند")),
                (
                    "document_line_id",
                    models.IntegerField(verbose_name="معرف سطر المستند"),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الخاضع للضريبة (الأصلي)",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="نسبة الضريبة المطبقة %",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="قيمة الضريبة المحسوبة (الأصلي)",
                    ),
                ),
                (
                    "exemption_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="سبب الإعفاء (إن وجد)",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calc_lines",
                        to="financial.taxcode",
                        verbose_name="كود الضريبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر حساب الضريبة",
                "verbose_name_plural": "أسطر حساب الضرائب",
            },
        ),
        migrations.CreateModel(
            name="TaxAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "input_tax_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="input_tax_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب ضريبة المدخلات / المشتريات (أصل مسترد)",
                    ),
                ),
                (
                    "output_tax_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="output_tax_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب ضريبة المخرجات / المبيعات (التزام)",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_mappings",
                        to="financial.taxcode",
                        verbose_name="كود الضريبة",
                    ),
                ),
                (
                    "withholding_tax_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withholding_tax_mappings",
                        to="financial.chartofaccounts",
                        verbose_name="حساب ضريبة الخصم والإضافة (أصل/التزام)",
                    ),
                ),
            ],
            options={
                "verbose_name": "توجيه حساب الضريبة",
                "verbose_name_plural": "توجيهات حسابات الضرائب",
            },
        ),
        migrations.AddConstraint(
            model_name="taxrule",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="unique_tax_rule_code_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxdeterminationaudit",
            constraint=models.UniqueConstraint(
                fields=("processed_event_id",), name="unique_tax_processed_event_id"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxaccountmapping",
            unique_together={("tax_code", "currency")},
        ),
    ]
