# Generated by Django 4.2.26 on 2026-08-04 15:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0018_taxcode_taxdeterminationaudit_taxjurisdiction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرف الحدث",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="نوع الحدث الضريبي"),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="رقم المستند"),
                ),
                (
                    "status",
                    models.CharField(
                        default="PROCESSED", max_length=20, verbose_name="حالة الحدث"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المعالجة"
                    ),
                ),
            ],
            options={
                "verbose_name": "حدث ضريبي",
                "verbose_name_plural": "سجل الأحداث الضريبية",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxRuleEvaluationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="رقم المستند"),
                ),
                ("candidate_rules", models.JSONField(verbose_name="القواعد المرشحة")),
                (
                    "selected_rule",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="القاعدة المختارة",
                    ),
                ),
                (
                    "rejected_rules",
                    models.JSONField(
                        verbose_name="القواعد المستبعدة مع أسباب الاستبعاد"
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(default=0, verbose_name="درجة الأولوية"),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقييم"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تقييم قواعد الضرائب",
                "verbose_name_plural": "سجلات تقييم قواعد الضرائب",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="taxaccountmapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="taxaccountmapping",
            name="credit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_credit_mappings",
                to="financial.chartofaccounts",
                verbose_name="حساب الدائن (Credit Account)",
            ),
        ),
        migrations.AddField(
            model_name="taxaccountmapping",
            name="debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_debit_mappings",
                to="financial.chartofaccounts",
                verbose_name="حساب المدين (Debit Account)",
            ),
        ),
        migrations.AddField(
            model_name="taxaccountmapping",
            name="tax_nature",
            field=models.CharField(
                default="OUTPUT", max_length=30, verbose_name="طبيعة الضريبة"
            ),
        ),
        migrations.AddField(
            model_name="taxcode",
            name="recoverability_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100.00"),
                max_digits=5,
                verbose_name="نسبة القابلية للاسترداد %",
            ),
        ),
        migrations.AddField(
            model_name="taxcode",
            name="version",
            field=models.IntegerField(default=1, verbose_name="إصدار كود الضريبة"),
        ),
        migrations.AlterField(
            model_name="taxaccountmapping",
            name="output_tax_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_tax_mappings",
                to="financial.chartofaccounts",
                verbose_name="حساب ضريبة المخرجات / المبيعات (التزام)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxaccountmapping",
            unique_together={("tax_code", "currency", "tax_nature")},
        ),
        migrations.CreateModel(
            name="TaxRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="النسبة السابقة %"
                    ),
                ),
                (
                    "new_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="النسبة الجديدة %"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(verbose_name="تاريخ بدء سريان النسبة الجديدة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_history",
                        to="financial.taxcode",
                        verbose_name="كود الضريبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تتبع سعر الضريبة",
                "verbose_name_plural": "سجلات تتبع أسعار الضرائب",
                "ordering": ["-created_at"],
            },
        ),
    ]
