# Generated by Django 4.2.26 on 2026-08-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0019_taxevent_taxruleevaluationlog_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="revenuerecognitionentry",
            index=models.Index(
                fields=["correlation_id", "created_at"], name="idx_rev_entry_corr_time"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuerecognitionscheduleline",
            index=models.Index(
                condition=models.Q(("status", "SCHEDULED")),
                fields=["status", "recognition_date"],
                name="idx_rev_sched_status_date",
            ),
        ),
        migrations.AddIndex(
            model_name="revenuerecognitionscheduleline",
            index=models.Index(
                fields=["schedule", "status"], name="financial_r_schedul_89cfe9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxdeterminationaudit",
            index=models.Index(
                fields=["correlation_id", "created_at"], name="idx_tax_audit_corr_time"
            ),
        ),
    ]
