# Generated by Django 4.2.26 on 2026-08-05 04:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0011_alter_creditauditlog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supplier", "0003_suppliertransaction_and_more"),
        ("financial", "0021_add_fiscalyear_timestamps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialpostingreference",
            name="journal_entry",
        ),
        migrations.RemoveField(
            model_name="financialstatementsnapshot",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="financialstatementsnapshot",
            name="period",
        ),
        migrations.AlterModelOptions(
            name="bankreconciliationmatch",
            options={
                "verbose_name": "مطابقة بنكية",
                "verbose_name_plural": "المطابقات البنكية",
            },
        ),
        migrations.AlterModelOptions(
            name="bankstatementbatch",
            options={
                "verbose_name": "دفعة كشف حساب بنكي",
                "verbose_name_plural": "دفوعات كشوف الحسابات البنكية",
            },
        ),
        migrations.AlterModelOptions(
            name="bankstatementline",
            options={
                "verbose_name": "سطر كشف حساب بنكي",
                "verbose_name_plural": "سطور كشف الحساب البنكي",
            },
        ),
        migrations.AlterModelOptions(
            name="openingbalancebatch",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "دفعة أرصدة افتتاحية",
                "verbose_name_plural": "دفعات الأرصدة الافتتاحية",
            },
        ),
        migrations.AlterModelOptions(
            name="openingbalanceline",
            options={
                "verbose_name": "سطر رصيد افتتاحي",
                "verbose_name_plural": "أسطر الأرصدة الافتتاحية",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentallocation",
            options={
                "verbose_name": "تسوية مالية",
                "verbose_name_plural": "التسويات المالية",
            },
        ),
        migrations.RemoveConstraint(
            model_name="bankreconciliationmatch",
            name="unique_bank_statement_to_journal_line_match",
        ),
        migrations.RemoveIndex(
            model_name="paymentallocation",
            name="financial_p_debit_d_cb72a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentallocation",
            name="financial_p_credit__e35517_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentallocation",
            name="financial_p_subledg_15eae9_idx",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="posting_reference",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="posting_source",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="credit_document_id",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="credit_document_type",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="debit_document_id",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="debit_document_type",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="entity_id",
        ),
        migrations.RemoveField(
            model_name="paymentallocation",
            name="subledger_type",
        ),
        migrations.AddField(
            model_name="bankreconciliationmatch",
            name="status",
            field=models.CharField(
                choices=[("MATCHED", "مطابق"), ("UNMATCHED", "ملغى المطابقة")],
                default="MATCHED",
                max_length=20,
                verbose_name="حالة المطابقة",
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliationmatch",
            name="unmatched_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ فك المطابقة"
            ),
        ),
        migrations.AddField(
            model_name="bankreconciliationmatch",
            name="unmatched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unmatched_bank_matches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="فك بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="مستورد الكشف",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementline",
            name="line_hash",
            field=models.CharField(
                default="",
                max_length=64,
                unique=True,
                verbose_name="البصمة التشفيرية للسطر",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="allocation_currency",
            field=models.CharField(
                default="EGP", max_length=10, verbose_name="عملة التسوية"
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="allocation_status",
            field=models.CharField(
                choices=[("ACTIVE", "نشط"), ("REVERSED", "ملغى / معكوس")],
                default="ACTIVE",
                max_length=20,
                verbose_name="حالة التسوية",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="functional_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ الوظيفي بالعملة المحلية",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="realized_fx_difference",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="فرق العملة المحقق",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="source_document_id",
            field=models.PositiveIntegerField(
                default=0, verbose_name="معرف مستند المصدر"
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="source_document_type",
            field=models.CharField(
                default="PAYMENT",
                help_text="مثال: PAYMENT, CREDIT_NOTE, ADVANCE, OPENING_BALANCE",
                max_length=64,
                verbose_name="نوع مستند المصدر",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="source_exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="سعر صرف المصدر",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="target_document_id",
            field=models.PositiveIntegerField(
                default=0, verbose_name="معرف مستند الهدف"
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="target_document_type",
            field=models.CharField(
                default="INVOICE",
                help_text="مثال: INVOICE, BILL, DEBIT_NOTE, OPENING_BALANCE",
                max_length=64,
                verbose_name="نوع المستند المستهدف",
            ),
        ),
        migrations.AddField(
            model_name="paymentallocation",
            name="target_exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="سعر صرف الهدف",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods",
                to="financial.fiscalyear",
                verbose_name="السنة المالية",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="period_number",
            field=models.IntegerField(default=1, verbose_name="رقم الفترة"),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="status",
            field=models.CharField(
                choices=[("open", "مفتوحة"), ("closed", "مغلقة")],
                default="open",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="bankreconciliationmatch",
            name="journal_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_matches",
                to="financial.journalentryline",
                verbose_name="بند قيد الأستاذ العام",
            ),
        ),
        migrations.AlterField(
            model_name="bankreconciliationmatch",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("EXACT", "مطابقة تامة"),
                    ("PROBABLE", "مطابقة مرجحة"),
                    ("MANUAL", "مطابقة يدوية"),
                ],
                default="EXACT",
                max_length=20,
                verbose_name="نوع المطابقة",
            ),
        ),
        migrations.AlterField(
            model_name="bankreconciliationmatch",
            name="matched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="bankreconciliationmatch",
            name="statement_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="financial.bankstatementline",
                verbose_name="سطر كشف البنك",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementbatch",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.chartofaccounts",
                verbose_name="حساب البنك المحاسبي",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementbatch",
            name="batch_number",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="رقم الدفعة"
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementbatch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاريخ الاستيراد"
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("imported", "مستورد"),
                    ("reconciling", "قيد التسوية"),
                    ("completed", "مكتمل والتسوية معتمدة"),
                ],
                default="imported",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="financial.bankstatementbatch",
                verbose_name="دفعة الكشف",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="دائن (سحب)",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="debit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مدين (إيداع)",
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="البيان / الوصف"
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="is_matched",
            field=models.BooleanField(default=False, verbose_name="تمت المطابقة"),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="reference_number",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="الرقم المرجعي"
            ),
        ),
        migrations.AlterField(
            model_name="bankstatementline",
            name="value_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الاستحقاق / القيمة"
            ),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="year_code",
            field=models.CharField(
                db_index=True,
                max_length=20,
                unique=True,
                verbose_name="كود السنة المالية",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reversed_by_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="القيد العكسي الذي ألغى هذا القيد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_entries",
                to="financial.journalentry",
                verbose_name="عُكس بواسطة القيد",
            ),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="foreign_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="دائن أجنبي",
            ),
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="foreign_debit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مدين أجنبي",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="batch_number",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="رقم الدفعة"
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="description",
            field=models.TextField(blank=True, verbose_name="البيان"),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opening_batches",
                to="financial.fiscalyear",
                verbose_name="السنة المالية",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_balance_batches",
                to="financial.journalentry",
                verbose_name="قيد الأستاذ العام",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                verbose_name="المبلغ المخصص بعملة المستند",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocation_date",
            field=models.DateField(verbose_name="تاريخ التسوية"),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="allocation_number",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="رقم عملية التسوية",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم بواسطة",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliationmatch",
            index=models.Index(
                fields=["statement_line", "status"],
                name="financial_b_stateme_1ec662_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankreconciliationmatch",
            index=models.Index(
                fields=["journal_line", "status"], name="financial_b_journal_c5887b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["batch", "is_matched"], name="financial_b_batch_i_414002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["transaction_date"], name="financial_b_transac_97bf92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatementline",
            index=models.Index(
                fields=["reference_number"], name="financial_b_referen_6b77a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["source_document_type", "source_document_id"],
                name="financial_p_source__ffc61f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["target_document_type", "target_document_id"],
                name="financial_p_target__4fcac4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentallocation",
            index=models.Index(
                fields=["allocation_status"], name="financial_p_allocat_12ec6e_idx"
            ),
        ),
        migrations.DeleteModel(
            name="FinancialPostingReference",
        ),
        migrations.DeleteModel(
            name="FinancialStatementSnapshot",
        ),
    ]
