# Generated by Django 4.2.26 on 2026-08-05 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0022_remove_financialpostingreference_journal_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPostingReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(max_length=50, verbose_name="نوع المصدر"),
                ),
                (
                    "source_id",
                    models.CharField(max_length=100, verbose_name="معرف المصدر"),
                ),
                (
                    "posting_type",
                    models.CharField(
                        default="MAIN", max_length=50, verbose_name="نوع الترحيل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posting_references",
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي المتربط",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرجع ترحيل مالي",
                "verbose_name_plural": "مراجع الترحيل المالية",
            },
        ),
        migrations.CreateModel(
            name="FinancialStatementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم لقطة التقرير"
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        choices=[
                            ("TRIAL_BALANCE", "ميزان المراجعة"),
                            ("INCOME_STATEMENT", "قائمة الدخل / الأرباح والخسائر"),
                            ("BALANCE_SHEET", "الميزانية العمومية / المركز المالي"),
                            ("CASH_FLOW", "قائمة التدفقات النقدية"),
                        ],
                        max_length=30,
                        verbose_name="نوع القائمة المالية",
                    ),
                ),
                (
                    "as_of_date",
                    models.DateField(verbose_name="تاريخ اللقطة / حتى تاريخ"),
                ),
                (
                    "statement_data",
                    models.JSONField(
                        verbose_name="بيانات التقرير المالية المجمدة (JSON Tree)"
                    ),
                ),
                (
                    "is_closed_period",
                    models.BooleanField(
                        default=False, verbose_name="هل الفترة مغلقة بصفة نهائية؟"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء والتجميد"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_snapshots",
                        to="financial.accountingperiod",
                        verbose_name="الفترة المحاسبية",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة قائمة مالية مجمدة",
                "verbose_name_plural": "لقطات القوائم المالية المجمدة",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["period", "statement_type"],
                        name="financial_f_period__911cc1_idx",
                    ),
                    models.Index(
                        fields=["as_of_date"], name="financial_f_as_of_d_f0aca2_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="financialpostingreference",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_id", "posting_type"),
                name="unique_posting_reference_per_source_and_type",
            ),
        ),
    ]
