# Generated by Django 4.2.26 on 2026-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0023_financialpostingreference_financialstatementsnapshot_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrule",
            name="rule_scope",
            field=models.CharField(
                choices=[
                    ("GLOBAL", "شامل عام"),
                    ("PRODUCT", "منتج محدد"),
                    ("PRODUCT_CATEGORY", "فئة منتجات"),
                    ("CUSTOMER", "عميل محدد"),
                    ("CUSTOMER_TYPE", "فئة عملاء"),
                    ("SUPPLIER", "مورد محدد"),
                    ("SUPPLIER_TYPE", "فئة موردين"),
                    ("TRANSACTION_TYPE", "نوع المعاملة"),
                    ("LOCATION", "الموقع / النطاق"),
                ],
                default="GLOBAL",
                max_length=30,
                verbose_name="نطاق القاعدة الضريبية",
            ),
        ),
        migrations.AddField(
            model_name="taxrule",
            name="scope_value",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="قيمة النطاق المشروط",
            ),
        ),
    ]
