# Generated by Django 4.2.26 on 2026-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0024_taxrule_rule_scope_taxrule_scope_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxTransactionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=50, verbose_name="نوع المستند"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="رقم المستند"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="اسم العميل اللحظي",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="اسم المورد اللحظي",
                    ),
                ),
                (
                    "tax_registration_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم التسجيل الضريبي اللحظي",
                    ),
                ),
                (
                    "applied_rule_code",
                    models.CharField(
                        max_length=100, verbose_name="كود القاعدة المطبقة"
                    ),
                ),
                (
                    "applied_tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="نسبة الضريبة اللحظية %",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقاط اللقطة"
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="financial.taxdeterminationaudit",
                        verbose_name="سجل التدقيق المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة معاملة ضريبية",
                "verbose_name_plural": "لقطات المعاملات الضريبية",
            },
        ),
        migrations.CreateModel(
            name="TaxExemptionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(max_length=100, verbose_name="رقم شهادة الإعفاء"),
                ),
                (
                    "tax_code_code",
                    models.CharField(
                        max_length=50, verbose_name="كود الضريبة المعفى منها"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="صالحة من تاريخ")),
                ("valid_to", models.DateField(verbose_name="صالحة إلى تاريخ")),
                ("exemption_reason", models.TextField(verbose_name="سبب الإعفاء")),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التقاط اللقطة"
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemption_snapshots",
                        to="financial.taxdeterminationaudit",
                        verbose_name="سجل التدقيق المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة إعفاء ضريبي",
                "verbose_name_plural": "لقطات الإعفاءات الضريبية",
            },
        ),
        migrations.CreateModel(
            name="TaxAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("INCREASE", "زيادة التزام / محصل"),
                            ("DECREASE", "تخفيض التزام / محصل"),
                            ("CORRECTION", "تصحيح خطأ محاسبي"),
                        ],
                        max_length=20,
                        verbose_name="نوع التسوية الضريبية",
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="مبلغ التسوية (EGP)",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب التسوية الضريبية")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسوية"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد التسوية بالأستاذ",
                    ),
                ),
                (
                    "original_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="financial.taxdeterminationaudit",
                        verbose_name="السجل الأصلي",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسوية ضريبية",
                "verbose_name_plural": "تسويات ضريبية",
            },
        ),
    ]
