# Generated by Django 4.2.26 on 2026-08-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0025_taxtransactionsnapshot_taxexemptionsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentryline",
            name="cost_center_code_snapshot",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="لقطة كود مركز التكلفة",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="cost_center_name_snapshot",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="لقطة اسم مركز التكلفة",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="cost_center_path_snapshot",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="لقطة المسار الشجري للمركز",
            ),
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="كود مركز التكلفة",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="اسم مركز التكلفة"),
                ),
                (
                    "tree_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="المسار الشجري الفريد بالصيغة /root_id/parent_id/node_id/ لسرعة الاستعلامات الختامية",
                        max_length=255,
                        verbose_name="المسار الشجري المفهرس",
                    ),
                ),
                (
                    "cost_center_policy",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "إلزامي"),
                            ("OPTIONAL", "اختياري"),
                            ("FORBIDDEN", "محظور"),
                        ],
                        default="OPTIONAL",
                        help_text="السياسة المطبقة على المعاملات والحسابات المتعلقة به",
                        max_length=20,
                        verbose_name="سياسة مركز التكلفة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="حماية كائنات النظام التاريخية مثل CC-LEGACY من الحذف أو التعديل",
                        verbose_name="كائن نظام محمي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="financial.costcenter",
                        verbose_name="المركز الأب (في الشجرة)",
                    ),
                ),
            ],
            options={
                "verbose_name": "مركز تكلفة",
                "verbose_name_plural": "مراكز التكلفة",
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="journalentryline",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="financial.costcenter",
                verbose_name="مركز التكلفة",
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(
                fields=["tree_path"], name="financial_c_tree_pa_dc4a7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(
                fields=["is_active", "is_system"], name="financial_c_is_acti_2f12a2_idx"
            ),
        ),
    ]
