# Generated by Django 4.2.26 on 2026-08-05 13:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0026_journalentryline_cost_center_code_snapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenterBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="رقم الإصدار"),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الميزانية المعتمدة (ج.م)",
                    ),
                ),
                (
                    "revised_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الميزانية المعدلة (ج.م)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("APPROVED", "معتمدة"),
                            ("ARCHIVED", "مؤرشفة"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="حالة الميزانية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الميزانية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_center_budgets",
                        to="financial.fiscalyear",
                        verbose_name="السنة المالية",
                    ),
                ),
            ],
            options={
                "verbose_name": "ميزانية مركز تكلفة",
                "verbose_name_plural": "ميزانيات مراكز التكلفة",
                "ordering": ["-fiscal_year", "cost_center", "-version"],
                "unique_together": {("cost_center", "fiscal_year", "version")},
            },
        ),
        migrations.CreateModel(
            name="CostCenterBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي المدين",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي الدائن",
                    ),
                ),
                (
                    "net_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الرصيد الصافي",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_snapshots",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cc_balance_snapshots",
                        to="financial.fiscalyear",
                        verbose_name="السنة المالية",
                    ),
                ),
            ],
            options={
                "verbose_name": "لقطة رصيد مركز تكلفة",
                "verbose_name_plural": "لقطات أرصدة مراكز التكلفة",
                "unique_together": {("cost_center", "fiscal_year", "currency")},
            },
        ),
    ]
