# Generated by Django 4.2.26 on 2026-08-05 13:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0027_costcenterbudget_costcenterbalancesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAllocationRuleAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=150, verbose_name="اسم القاعدة"),
                ),
                ("action", models.CharField(max_length=50, verbose_name="الإجراء")),
                (
                    "performed_by_name",
                    models.CharField(
                        max_length=150, verbose_name="اسم القائم بالإجراء"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="تفاصيل الحركة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق قاعدة توزيع",
                "verbose_name_plural": "سجلات تدقيق قواعد التوزيع",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLineCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="النسبة المئوية",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ الموزع (ج.م)",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_allocations",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_allocations",
                        to="financial.journalentryline",
                        verbose_name="سطر القيد",
                    ),
                ),
            ],
            options={
                "verbose_name": "حصة توزيع سطر",
                "verbose_name_plural": "حصص توزيع الأسطر",
            },
        ),
        migrations.CreateModel(
            name="CostCenterAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "إنشاء"),
                            ("UPDATED", "تحديث"),
                            ("TREE_MOVED", "نقل هيكلي"),
                            ("DELETED", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "user_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="لقطة اسم المستخدم",
                    ),
                ),
                (
                    "changes_json",
                    models.TextField(
                        blank=True, null=True, verbose_name="تفاصيل التغييرات"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="التوقيت"),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="القائم بالإجراء",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق مركز تكلفة",
                "verbose_name_plural": "سجلات تدقيق مراكز التكلفة",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserCostCenterPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("ALLOW", "سماح"), ("DENY", "حظر / منع")],
                        default="ALLOW",
                        max_length=10,
                        verbose_name="نوع الصلاحية",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="الرقم الأقل يعني أولوية أعلى",
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_center_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية مركز تكلفة لمستخدم",
                "verbose_name_plural": "صلاحيات مراكز التكلفة للمستخدمين",
                "ordering": ["priority", "id"],
                "unique_together": {("user", "cost_center")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeCostCenterAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="كود / معرف الموظف"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=150, verbose_name="اسم الموظف"),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="النسبة المئوية من الراتب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التخصيص"
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_allocations",
                        to="financial.costcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "توزيع راتب موظف",
                "verbose_name_plural": "توزيعات رواتب الموظفين",
                "unique_together": {("employee_id", "cost_center")},
            },
        ),
    ]
