# Generated by Django 4.2.26 on 2026-08-05 16:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0028_costallocationruleauditlog_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costcenterbudget",
            old_name="allocated_amount",
            new_name="budget_amount",
        ),
        migrations.RemoveField(
            model_name="costcenterbudget",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="costcenterbudget",
            name="revised_amount",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="is_base",
        ),
        migrations.RemoveField(
            model_name="fiscalyear",
            name="is_closed",
        ),
        migrations.AddField(
            model_name="costcenterbudget",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الاعتماد"
            ),
        ),
        migrations.AddField(
            model_name="costcenterbudget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_cost_center_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costcenterbudget",
            name="budget_allocation_method",
            field=models.CharField(
                default="EQUAL", max_length=20, verbose_name="طريقة توزيع الميزانية"
            ),
        ),
        migrations.AddField(
            model_name="costcenterbudget",
            name="cached_spent_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ المنفق المخزن كاش",
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_functional",
            field=models.BooleanField(
                default=False, verbose_name="العملة المحلية الأساسية؟"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="currency_source",
            field=models.CharField(
                blank=True, default="SYSTEM", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="default_exchange_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="exchange_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                null=True,
                verbose_name="لقطة سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="is_migrated_legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="transaction_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                null=True,
                verbose_name="دائن العملة",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="transaction_debit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                null=True,
                verbose_name="مدين العملة",
            ),
        ),
        migrations.AlterField(
            model_name="costcenterbudget",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("SUBMITTED", "مقدمة للاعتماد"),
                    ("APPROVED", "معتمدة"),
                    ("REVISED", "معدلة"),
                    ("ARCHIVED", "مؤرشفة"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="حالة الميزانية",
            ),
        ),
        migrations.CreateModel(
            name="CostCenterBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المخصص المعتمد",
                    ),
                ),
                (
                    "control_policy",
                    models.CharField(
                        choices=[
                            ("BLOCK", "حظر ترحيل القيد عند التجاوز (BLOCK)"),
                            ("WARN", "تحذير فقط مع السماح بالترحيل (WARN)"),
                            (
                                "REQUIRES_APPROVAL",
                                "يتطلب موافقة استثنائية (REQUIRES_APPROVAL)",
                            ),
                            ("ALLOW", "سماح بدون قيود (ALLOW)"),
                        ],
                        default="BLOCK",
                        max_length=30,
                        verbose_name="سياسة الرقابة الوقائية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="ملاحظات البند"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_center_budget_lines",
                        to="financial.chartofaccounts",
                        verbose_name="الحساب المحاسبي",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financial.costcenterbudget",
                        verbose_name="الموازنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند موازنة مركز تكلفة",
                "verbose_name_plural": "بنود موازنات مراكز التكلفة",
                "unique_together": {("budget", "account")},
            },
        ),
        migrations.CreateModel(
            name="BudgetOverrideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("document_id", models.IntegerField(blank=True, null=True)),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "budget_exceeded_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب التجاوز")),
                ("approval_comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد النظر"),
                            ("APPROVED", "مقبول استثنائياً"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_requests",
                        to="financial.chartofaccounts",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budget_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_requests",
                        to="financial.costcenter",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_budget_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostCenterBudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_allocated_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.accountingperiod",
                    ),
                ),
                (
                    "budget_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="financial.costcenterbudgetline",
                    ),
                ),
            ],
            options={
                "unique_together": {("budget_line", "accounting_period")},
            },
        ),
        migrations.CreateModel(
            name="CostCenterActualSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_snapshots",
                        to="financial.chartofaccounts",
                    ),
                ),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_snapshots",
                        to="financial.accountingperiod",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_snapshots",
                        to="financial.costcenter",
                    ),
                ),
            ],
            options={
                "unique_together": {("cost_center", "account", "accounting_period")},
            },
        ),
    ]
