# Generated by Django 4.2.26 on 2026-08-05 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0029_rename_allocated_amount_costcenterbudget_budget_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcenterbudget",
            name="approved_at",
        ),
    ]
