# Generated by Django 4.2.26 on 2026-08-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0031_accountbalanceperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccounts",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="العملة الخاصة بالخزنة أو الحساب البنكي (إذا تُركت فارغة تعتمد العملة الأساسية للنظام)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="financial.currency",
                verbose_name="عملة الحساب",
            ),
        ),
    ]
