# Generated by Django 4.2.26 on 2026-08-06 23:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0032_chartofaccounts_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccounts",
            name="opening_balance_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الرصيد الافتتاحي بالعملة الأجنبية للحساب عند إنشائه",
                max_digits=15,
                verbose_name="الرصيد الافتتاحي بالعملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="chartofaccounts",
            name="opening_balance_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="سعر الصرف المعتمد للرصيد الافتتاحي الأجنبي",
                max_digits=12,
                verbose_name="سعر صرف الرصيد الافتتاحي",
            ),
        ),
        migrations.AlterField(
            model_name="chartofaccounts",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الرصيد الافتتاحي للحساب بالعملة الوظيفية (EGP)",
                max_digits=15,
                verbose_name="الرصيد الافتتاحي",
            ),
        ),
    ]
