# Generated by Django 4.2.26 on 2026-08-07 11:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0016_customer_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supplier", "0005_supplier_default_currency"),
        ("financial", "0033_chartofaccounts_opening_balance_foreign_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openingbalancebatch",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_batches_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="company_code",
            field=models.CharField(
                default="DEFAULT", max_length=50, verbose_name="كود الشركة"
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_batches_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="opening_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ الرصيد الافتتاحي"
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_batches_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="posting_key",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="مفتاح الترحيل الفريد",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="reversal_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_opening_balance_batches",
                to="financial.journalentry",
                verbose_name="قيد العكس الافتتاحي",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="reversal_reason",
            field=models.TextField(blank=True, verbose_name="سبب العكس"),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_batches_reversed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="credit_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="دائن بالعملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.currency",
                verbose_name="العملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="client.customer",
                verbose_name="العميل",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="debit_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مدين بالعملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="inventory_snapshot_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="معرف Snapshot التقييم للمخزون",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("GL", "حساب عام"),
                    ("AR", "رصيد عميل"),
                    ("AP", "رصيد مورد"),
                    ("TREASURY", "خزينة/بنك"),
                    ("INVENTORY", "مخزون أول المدة"),
                ],
                default="GL",
                max_length=20,
                verbose_name="نوع السطر",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="openingbalanceline",
            name="treasury_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treasury_opening_lines",
                to="financial.chartofaccounts",
                verbose_name="حساب الخزينة/البنك",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_balance_batches",
                to="financial.journalentry",
                verbose_name="قيد الأستاذ العام الافتتاحي",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalancebatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("validated", "مفحوصة"),
                    ("approved", "معتمدة"),
                    ("posted", "مرحلة"),
                    ("reversed", "معكوسة"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalanceline",
            name="credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ بالعملة الوظيفية النظامية",
                max_digits=15,
                verbose_name="دائن (عملة وظيفية)",
            ),
        ),
        migrations.AlterField(
            model_name="openingbalanceline",
            name="debit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ بالعملة الوظيفية النظامية",
                max_digits=15,
                verbose_name="مدين (عملة وظيفية)",
            ),
        ),
        migrations.AddConstraint(
            model_name="openingbalancebatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "posted")),
                fields=("fiscal_year",),
                name="unique_posted_opening_batch_per_fiscal_year",
            ),
        ),
    ]
