# Generated by Django 4.2.26 on 2026-08-07 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0034_remove_openingbalancebatch_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentrylinecostallocation",
            name="foreign_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ الموزع بالعملة الأجنبية",
            ),
        ),
    ]
