# Generated by Django 4.2.26 on 2026-08-07 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0035_journalentrylinecostallocation_foreign_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-created_at", "-date", "-id"],
                "verbose_name": "قيد يومي",
                "verbose_name_plural": "القيود اليومية",
            },
        ),
    ]
