# Generated by Django 4.2.26 on 2026-08-07 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0036_alter_journalentry_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="كود القاعدة",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="اسم القاعدة المحاسبية"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MANDATORY_BLOCKER", "حاسم إجباري - غير قابل للتجاوّز"),
                            ("CONFIGURABLE_BLOCKER", "حاسم قابل للتعديل"),
                            ("WARNING", "تحذير مسموح بالتجاوّز"),
                        ],
                        default="WARNING",
                        max_length=30,
                        verbose_name="درجة الخطورة",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="مفعلة؟")),
                (
                    "applies_to_company",
                    models.CharField(
                        default="DEFAULT", max_length=50, verbose_name="تطبق على الشركة"
                    ),
                ),
                (
                    "applies_to_module",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="تطبق على الموديول",
                    ),
                ),
                (
                    "execution_order",
                    models.IntegerField(default=10, verbose_name="ترتيب التنفيذ"),
                ),
                (
                    "blocking_reason",
                    models.TextField(
                        blank=True, verbose_name="رسالة المنع عند التفعيل"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قاعدة فحص إغلاق",
                "verbose_name_plural": "قواعد فحص الإغلاق",
                "ordering": ["execution_order", "rule_code"],
            },
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="force_close_reason",
            field=models.TextField(
                blank=True, verbose_name="سبب التجاوّز والإغلاق الفوري"
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="force_closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods_force_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أغلق بالتجاوّز بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopen_reason",
            field=models.TextField(blank=True, verbose_name="سبب إعادة الفتح"),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopened_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ إعادة الفتح"
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="reopened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="periods_reopened",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُعيد فتحها بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإغلاق النهائي"
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_years_closed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أغلق بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="closing_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_years_closed",
                to="financial.journalentry",
                verbose_name="قيد تصفية السنة المالية",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="net_profit_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="صافي الربح/الخسارة المحسوب",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="retained_earnings_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_years_retained",
                to="financial.chartofaccounts",
                verbose_name="حساب الأرباح والخسائر المرحلة",
            ),
        ),
        migrations.AlterField(
            model_name="accountingperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "مفتوحة"),
                    ("soft_closed", "مغلقة مؤقتاً للمراجعة"),
                    ("closed", "مغلقة"),
                    ("hard_closed", "مقفلة إقفالاً نهائياً"),
                ],
                default="open",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.CreateModel(
            name="FiscalYearClosingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "closing_run_key",
                    models.CharField(
                        db_index=True,
                        help_text="مفتاح فريد لمنع تكرار الإغلاق مثل CLOSE:company:FY2025",
                        max_length=100,
                        unique=True,
                        verbose_name="مفتاح منع تكرار الإغلاق الفريد",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ بدء التشغيل",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ اكتمال التشغيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة مبدئية"),
                            ("AUDITING", "جاري التدقيق وفحص الاستحقاق"),
                            ("READY", "جاهز للإغلاق"),
                            ("RUNNING", "جاري تنفيذ الإغلاق"),
                            ("COMPLETED", "تم الإغلاق بنجاح"),
                            ("FAILED", "فشل الإغلاق"),
                            ("REVERSED", "معكوس / معاد فتحه"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="حالة الإغلاق",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="DRAFT", max_length=100, verbose_name="الخطوة الحالية"
                    ),
                ),
                (
                    "last_successful_step",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="آخر خطوة مكتملة بنجاح",
                    ),
                ),
                (
                    "snapshot_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="معرف لقطة التقرير الختامي",
                    ),
                ),
                (
                    "logs",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="سجل الأحداث والأخطاء"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_closing_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نفذ بواسطة",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closing_runs",
                        to="financial.fiscalyear",
                        verbose_name="السنة المالية",
                    ),
                ),
            ],
            options={
                "verbose_name": "تشغيل إغلاق سنة مالية",
                "verbose_name_plural": "تشغيلات إغلاق السنوات المالية",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PeriodModuleLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True,
                        help_text="رمز الموديول المحظور (AR, AP, INVENTORY, TREASURY, GL, PAYROLL, etc.)",
                        max_length=50,
                        verbose_name="الموديول",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="locked", max_length=20, verbose_name="حالة الحظر"
                    ),
                ),
                (
                    "lock_type",
                    models.CharField(
                        choices=[
                            ("POST_BLOCK", "منع الترحيل وإنشاء الحركات"),
                            ("EDIT_BLOCK", "منع التعديل على الحركات القائمة"),
                            ("DELETE_BLOCK", "منع الحذف"),
                            ("READ_ONLY", "قراءة فقط - حظر كامل"),
                        ],
                        default="POST_BLOCK",
                        max_length=20,
                        verbose_name="درجة الحظر",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الحظر"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="سبب الحظر")),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_locks_applied",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حظر بواسطة",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_locks",
                        to="financial.accountingperiod",
                        verbose_name="الفترة المحاسبية",
                    ),
                ),
            ],
            options={
                "verbose_name": "حظر موديول فترة محاسبية",
                "verbose_name_plural": "حظر موديولات الفترات المحاسبية",
                "ordering": ["period", "module"],
                "unique_together": {("period", "module")},
            },
        ),
    ]
