# Generated by Django 4.2.26 on 2026-08-08 01:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0037_closingrule_accountingperiod_force_close_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="rounding_tolerance",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.05"),
                max_digits=8,
                verbose_name="حد تحمل فروق التقريب",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="inventory_sync_key",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="مفتاح فرادة المزامنة",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="inventory_sync_status",
            field=models.CharField(
                choices=[
                    ("NONE", "لا يوجد"),
                    ("PENDING", "قيد الانتظار"),
                    ("PROCESSING", "قيد المعالجة"),
                    ("COMPLETED", "مكتملة"),
                    ("FAILED", "فشلت"),
                ],
                default="NONE",
                max_length=20,
                verbose_name="حالة مزامنة المخزون",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ آخر محاولة"
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="last_attempt_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_sync_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="آخر محاول بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="last_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="تفاصيل آخر خطأ للمزامنة"
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد محاولات المزامنة"
            ),
        ),
        migrations.CreateModel(
            name="OpeningBalanceImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="اسم الملف"),
                ),
                (
                    "template_version",
                    models.CharField(
                        default="v1.0", max_length=20, verbose_name="نسخة القالب"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الصفوف"
                    ),
                ),
                (
                    "valid_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الصفوف الصحيحة"
                    ),
                ),
                (
                    "invalid_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الصفوف الفاسدة"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مرفوع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة استيراد أرصدة افتتاحية",
                "verbose_name_plural": "دفعات استيراد الأرصدة الافتتاحية",
            },
        ),
        migrations.CreateModel(
            name="ControlAccountOverrideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب الاستثناء المحاسبي")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "مطلوبة"),
                            ("approved", "معتمدة"),
                            ("rejected", "مرفوضة"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.chartofaccounts",
                        verbose_name="الحساب الحاكم",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_overrides_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعتمد (CFO)",
                    ),
                ),
                (
                    "opening_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_requests",
                        to="financial.openingbalancebatch",
                        verbose_name="الدفعة الافتتاحية",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="control_overrides_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طالب الاستثناء",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب استثناء حساب حاكم",
                "verbose_name_plural": "طلبات استثناء الحسابات الحاكمة",
            },
        ),
    ]
