# Generated by Django 4.2.26 on 2026-08-08 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0038_currency_rounding_tolerance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatementbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("imported", "مستورد"),
                    ("reconciling", "قيد التسوية"),
                    ("partially_matched", "مطابق جزئياً"),
                    ("completed", "مكتمل والتسوية معتمدة"),
                    ("reopened", "أعيد فتحه"),
                    ("failed", "فشل التسوية"),
                ],
                default="imported",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.CreateModel(
            name="BankMatchAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المخصص للمطابقة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط ومطابق"),
                            ("REVIEW_REQUIRED", "تحت المراجعة"),
                            ("REVERSED", "ملغى / مكسور"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="حالة التخصيص",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التخصيص"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="خصص بواسطة",
                    ),
                ),
                (
                    "journal_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_allocations",
                        to="financial.journalentryline",
                        verbose_name="قيد الأستاذ العام المطابق",
                    ),
                ),
                (
                    "statement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="financial.bankstatementline",
                        verbose_name="سطر كشف البنك",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصيص مطابقة بنكية",
                "verbose_name_plural": "تخصيصات المطابقات البنكية",
                "indexes": [
                    models.Index(
                        fields=["statement_line", "status"],
                        name="financial_b_stateme_cfcb0d_idx",
                    ),
                    models.Index(
                        fields=["journal_line", "status"],
                        name="financial_b_journal_cca0b1_idx",
                    ),
                ],
            },
        ),
    ]
