# Generated by Django 4.2.26 on 2026-08-08 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0039_alter_bankstatementbatch_status_bankmatchallocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FXRevaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        default="DEFAULT",
                        max_length=50,
                        verbose_name="رمز الشركة / الكيان",
                    ),
                ),
                (
                    "accounting_book",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "الدفتر الرئيسي"),
                            ("IFRS", "دفتر المعايير الدولية"),
                            ("TAX", "الدفتر الضريبي"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                        verbose_name="الكتاب المحاسبي",
                    ),
                ),
                (
                    "valuation_type",
                    models.CharField(
                        choices=[
                            ("PERIOD_END", "تقييم نهاية الفترة"),
                            ("AD_HOC", "تقييم استثنائي"),
                        ],
                        default="PERIOD_END",
                        max_length=30,
                        verbose_name="نوع التقييم",
                    ),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("OPEN_ITEMS", "البنود المفتوحة"),
                            ("BALANCE_ACCOUNT", "رصيد الحساب"),
                            ("MONETARY_ITEMS", "البنود النقدية فقط"),
                        ],
                        default="OPEN_ITEMS",
                        max_length=30,
                        verbose_name="طريقة التقييم",
                    ),
                ),
                (
                    "currency_scope",
                    models.CharField(
                        choices=[
                            ("ALL_CURRENCIES", "جميع العملات الأجنبية"),
                            ("SPECIFIC", "عملة محددة"),
                        ],
                        default="ALL_CURRENCIES",
                        max_length=30,
                        verbose_name="نطاق العملات",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("CALCULATED", "محسوب"),
                            ("VALIDATED", "معتمد البنود"),
                            ("POSTED", "مرحل بالدفتر"),
                            ("REVERSED", "معكوس"),
                            ("FAILED", "فشل"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "run_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التقييم"
                    ),
                ),
                (
                    "rate_source",
                    models.CharField(
                        default="CBE_OFFICIAL",
                        max_length=100,
                        verbose_name="مصدر سعر الصرف",
                    ),
                ),
                (
                    "total_unrealized_gain_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="إجمالي أرباح/خسائر التقييم",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التشغيل بواسطة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fx_revaluation_runs",
                        to="financial.journalentry",
                        verbose_name="قيد التقييم المرحل",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                        verbose_name="الفترة المحاسبية",
                    ),
                ),
                (
                    "reversal_of_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by_runs",
                        to="financial.fxrevaluationrun",
                        verbose_name="معكوس عن تشغيل سابق",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.currency",
                        verbose_name="العملة المستهدفة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تشغيل تقييم العملات",
                "verbose_name_plural": "تشغيلات تقييم العملات",
            },
        ),
        migrations.CreateModel(
            name="FXRevaluationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("AR_INVOICE", "عقد/فاتورة مبيعات عميل (AR)"),
                            ("AP_INVOICE", "فاتورة مشتريات مورد (AP)"),
                            ("CASH_ACCOUNT", "حساب خزينة/بنك أجنبي"),
                        ],
                        max_length=20,
                        verbose_name="نوع المصدر",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        max_length=100, verbose_name="معرف المصدر / المستند"
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="بصمة التحقق من التعديل (Source Hash)",
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ آخر تعديل للمصدر"
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="اسم العميل / المورد / الجهة",
                    ),
                ),
                (
                    "open_foreign_amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="الرصيد الأجنبي المفتوح الصافي",
                    ),
                ),
                (
                    "old_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="سعر الصرف السابق/التاريخي",
                    ),
                ),
                (
                    "new_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="سعر الإقفال/الجديد",
                    ),
                ),
                (
                    "old_functional_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="القيمة السابقة بالجنيه",
                    ),
                ),
                (
                    "new_functional_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="القيمة الجديدة بالجنيه",
                    ),
                ),
                (
                    "unrealized_difference",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="فرق التقييم غير المحقق",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_revaluation_lines",
                        to="financial.chartofaccounts",
                        verbose_name="الحساب المحاسبي",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.currency",
                        verbose_name="العملة",
                    ),
                ),
                (
                    "gain_loss_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fx_gain_loss_lines",
                        to="financial.chartofaccounts",
                        verbose_name="حساب أرباح/خسائر التقييم",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financial.fxrevaluationrun",
                        verbose_name="تشغيل التقييم",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند تقييم العملات التفصيلي",
                "verbose_name_plural": "بنود تقييم العملات التفصيلية",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FXRateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("CLOSING", "سعر الإقفال الرسمي"),
                            ("AVERAGE", "المتوسط الشهري/الفصلي"),
                            ("HISTORICAL", "السعر التاريخي"),
                            ("TRANSACTION", "سعر المعاملة"),
                        ],
                        default="CLOSING",
                        max_length=20,
                        verbose_name="نوع سعر الصرف",
                    ),
                ),
                ("rate_date", models.DateField(verbose_name="تاريخ سعر الصرف المعتمد")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="سعر الصرف المجمّد",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="CBE_OFFICIAL",
                        max_length=100,
                        verbose_name="مصدر السعر",
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت التجميد والتقاط الصورة"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.currency",
                        verbose_name="العملة",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_snapshots",
                        to="financial.fxrevaluationrun",
                        verbose_name="تشغيل التقييم",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة سعر الصرف المجمّدة",
                "verbose_name_plural": "صور أسعار الصرف المجمّدة",
            },
        ),
        migrations.CreateModel(
            name="FXApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        default="FXRevaluationRun",
                        max_length=50,
                        verbose_name="نوع الكيان",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(max_length=100, verbose_name="معرف الكيان"),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("NORMAL_POSTING_APPROVAL", "اعتماد تقييم عادي"),
                            ("RATE_OVERRIDE_APPROVAL", "تجاوز عمر سعر الصرف المتقادم"),
                            ("PERIOD_CLOSE_APPROVAL", "اعتماد إغلاق الفترة"),
                        ],
                        default="NORMAL_POSTING_APPROVAL",
                        max_length=30,
                        verbose_name="نوع الاعتماد",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القرار"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("APPROVED", "موافق عليه"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="القرار",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="سبب القرار / التبرير المحاسبي",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fx_approvals_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُعتمد",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fx_approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طالب الاعتماد",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل اعتماد وتجاوز التقييم",
                "verbose_name_plural": "سجلات اعتماد وتجاوز التقييم",
            },
        ),
        migrations.AddConstraint(
            model_name="fxrevaluationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["VALIDATED", "POSTED"])),
                fields=(
                    "company_code",
                    "period",
                    "valuation_type",
                    "currency_scope",
                    "accounting_book",
                ),
                name="unique_active_fx_revaluation_run",
            ),
        ),
    ]
