# Generated by Django 4.2.26 on 2026-08-09 02:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0040_fxrevaluationrun_fxrevaluationline_fxratesnapshot_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCurrencyBalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[("supplier", "مورد"), ("customer", "عميل")],
                        max_length=20,
                        verbose_name="نوع الشريك",
                    ),
                ),
                ("partner_id", models.PositiveIntegerField(verbose_name="معرف الشريك")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=10, verbose_name="كود العملة"
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي الجانب المدين بالعملة الأصلي",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="إجمالي الجانب الدائن بالعملة الأصلي",
                    ),
                ),
                (
                    "net_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الرصيد الصافي المتبقي",
                    ),
                ),
                (
                    "functional_net_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المعادل بالعملة الوظيفية (EGP)",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        default="PAYABLE",
                        max_length=20,
                        verbose_name="الطبيعة المحاسبية",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "لقطة انكشاف عملة شريك الأعمال",
                "verbose_name_plural": "لقطات انكشافات عملات شركاء الأعمال",
                "indexes": [
                    models.Index(
                        fields=["partner_type", "partner_id"],
                        name="financial_p_partner_0e4215_idx",
                    ),
                    models.Index(
                        fields=["currency"], name="financial_p_currenc_8d74dc_idx"
                    ),
                ],
                "unique_together": {("partner_type", "partner_id", "currency")},
            },
        ),
    ]
