# Generated by Django 4.2.26 on 2026-08-09 04:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "client",
            "0017_customerpayment_base_amount_customerpayment_currency_and_more",
        ),
        (
            "purchase",
            "0013_purchasepayment_base_amount_purchasepayment_currency_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0030_salepayment_base_amount_salepayment_currency_and_more"),
        ("supplier", "0006_supplieradvancepayment_base_amount_and_more"),
        ("financial", "0042_datamigrationrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerAdvanceSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المخصص والتسوية",
                    ),
                ),
                (
                    "exchange_rate_snapshot",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="لقطة سعر الصرف",
                    ),
                ),
                (
                    "realized_fx_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="فروق عملة محققة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("APPLIED", "مطبق"), ("REVERSED", "معكوس")],
                        default="APPLIED",
                        max_length=20,
                        verbose_name="حالة التسوية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسوية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_settlements",
                        to="financial.currency",
                        verbose_name="عملة التسوية",
                    ),
                ),
                (
                    "customer_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_settlements",
                        to="client.customerpayment",
                        verbose_name="دفعة العميل المقدمة",
                    ),
                ),
                (
                    "fx_gain_loss_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.chartofaccounts",
                        verbose_name="حساب فروق العملة المحققة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي المرفق",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advance_settlements",
                        to="purchase.purchase",
                        verbose_name="فاتورة المشتريات",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advance_settlements",
                        to="sale.sale",
                        verbose_name="فاتورة المبيعات",
                    ),
                ),
                (
                    "supplier_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_settlements",
                        to="supplier.supplieradvancepayment",
                        verbose_name="دفعة المورد المقدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسوية رصيد مسبق",
                "verbose_name_plural": "تسويات الأرصدة المسبقة",
                "ordering": ["-created_at"],
            },
        ),
    ]
