# Generated by Django on 2026-08-20

from django.db import migrations


def fix_account_flags(apps, schema_editor):
    """
    إلغاء صفة الخزينة والحساب البنكي عن الحسابات المحاسبية/الوسيطة:
    11130 - العهد النقدية المستديمة والمؤقتة
    11180 - ودائع نقدية قصيرة الأجل وتحت الطلب
    11190 - نقدية في الطريق وشيكات برسم التحصيل
    """
    ChartOfAccounts = apps.get_model("financial", "ChartOfAccounts")
    ChartOfAccounts.objects.filter(code__in=["11130", "11180", "11190"]).update(
        is_cash_account=False,
        is_bank_account=False,
    )


def reverse_account_flags(apps, schema_editor):
    """
    التراجع في حالة الرجوع بالميجريشن
    """
    ChartOfAccounts = apps.get_model("financial", "ChartOfAccounts")
    ChartOfAccounts.objects.filter(code="11130").update(
        is_cash_account=True, is_bank_account=False
    )
    ChartOfAccounts.objects.filter(code="11180").update(
        is_cash_account=False, is_bank_account=True
    )
    ChartOfAccounts.objects.filter(code="11190").update(
        is_cash_account=True, is_bank_account=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0047_alter_costcenter_code_alter_journalentry_entry_type_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_account_flags, reverse_account_flags),
    ]
