# Generated by Django 4.2.25 on 2025-11-11 17:31

from django.db import migrations


def create_payroll_accounts(apps, schema_editor):
    """إنشاء الحسابات المحاسبية المطلوبة لنظام الرواتب"""
    ChartOfAccounts = apps.get_model('financial', 'ChartOfAccounts')
    AccountType = apps.get_model('financial', 'AccountType')
    
    # الحصول على أنواع الحسابات
    expense_type = AccountType.objects.filter(code='EXPENSE').first()
    current_liability_type = AccountType.objects.filter(code='CURRENT_LIABILITY').first()
    
    if not expense_type or not current_liability_type:
        print("❌ أنواع الحسابات غير موجودة")
        return
    
    # الحصول على الحسابات الأب
    expenses_parent = ChartOfAccounts.objects.filter(code='50000').first()  # المصروفات
    liabilities_parent = ChartOfAccounts.objects.filter(code='20000').first()  # الخصوم
    
    if not expenses_parent or not liabilities_parent:
        print("❌ الحسابات الرئيسية غير موجودة")
        return
    
    # الحسابات المطلوبة للرواتب
    payroll_accounts = [
        # حسابات المصروفات الموجودة (تحديث فقط)
        {
            'code': '52021',
            'name': 'البدلات الثابتة',
            'parent': expenses_parent,
            'account_type': expense_type,
            'description': 'بدلات الانتقال والوجبات والهاتف والتعليم',
        },
        {
            'code': '52022',
            'name': 'المكافآت والحوافز',
            'parent': expenses_parent,
            'account_type': expense_type,
            'description': 'الأجر الإضافي ومكافآت الأداء والمكافآت السنوية',
        },
        {
            'code': '52023',
            'name': 'بدل السكن',
            'parent': expenses_parent,
            'account_type': expense_type,
            'description': 'بدل السكن للموظفين',
        },
        
        # حسابات المصروفات الجديدة
        {
            'code': '52024',
            'name': 'خصومات على الرواتب',
            'parent': expenses_parent,
            'account_type': expense_type,
            'description': 'خصومات التأخير والغياب من الرواتب',
        },
        {
            'code': '52025',
            'name': 'التأمينات الاجتماعية - حصة الشركة',
            'parent': expenses_parent,
            'account_type': expense_type,
            'description': 'مساهمة الشركة في التأمينات الاجتماعية',
        },
        
        # حسابات الخصوم الموجودة (تحديث فقط)
        {
            'code': '21031',
            'name': 'التأمينات الاجتماعية - حصة العامل',
            'parent': liabilities_parent,
            'account_type': current_liability_type,
            'description': 'خصم التأمينات الاجتماعية من راتب الموظف',
        },
        {
            'code': '21032',
            'name': 'ضرائب الدخل',
            'parent': liabilities_parent,
            'account_type': current_liability_type,
            'description': 'ضرائب الدخل المستحقة على الموظفين',
        },
        {
            'code': '21033',
            'name': 'اشتراكات النقابة',
            'parent': liabilities_parent,
            'account_type': current_liability_type,
            'description': 'اشتراكات النقابة المهنية',
        },
        {
            'code': '21034',
            'name': 'التأمين الطبي',
            'parent': liabilities_parent,
            'account_type': current_liability_type,
            'description': 'مستحقات التأمين الطبي',
        },
    ]
    
    created_count = 0
    updated_count = 0
    
    for account_data in payroll_accounts:
        account, created = ChartOfAccounts.objects.get_or_create(
            code=account_data['code'],
            defaults={
                'name': account_data['name'],
                'parent': account_data['parent'],
                'account_type': account_data['account_type'],
                'description': account_data['description'],
                'is_active': True
            }
        )
        
        if created:
            created_count += 1
            print(f"✅ تم إنشاء حساب: {account.code} - {account.name}")
        else:
            # تحديث البيانات إذا كان الحساب موجود
            account.name = account_data['name']
            account.parent = account_data['parent']
            account.account_type = account_data['account_type']
            account.description = account_data['description']
            account.save()
            updated_count += 1
            print(f"🔄 تم تحديث حساب: {account.code} - {account.name}")
    
    print(f"📊 تم إنشاء {created_count} حساب جديد وتحديث {updated_count} حساب")


def reverse_create_payroll_accounts(apps, schema_editor):
    """حذف الحسابات المحاسبية للرواتب"""
    ChartOfAccounts = apps.get_model('financial', 'ChartOfAccounts')
    
    account_codes = ['52021', '52022', '52023', '52024', '52025', '21031', '21032', '21033', '21034']
    deleted_count = 0
    
    for code in account_codes:
        deleted, _ = ChartOfAccounts.objects.filter(code=code).delete()
        if deleted:
            deleted_count += deleted
            print(f"🗑️ تم حذف حساب: {code}")
    
    print(f"📊 تم حذف {deleted_count} حساب")


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        ("financial", "0003_load_chart_of_accounts"),
    ]

    operations = [
        migrations.RunPython(
            create_payroll_accounts,
            reverse_create_payroll_accounts,
            elidable=True
        ),
    ]
