# Generated by Django 4.2.23 on 2025-11-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_salaries', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='financial.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='معالج بواسطة'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.salary', verbose_name='الراتب'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده'),
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='leave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='راجعه'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='direct_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee', verbose_name='المدير المباشر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.shift', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee', verbose_name='مدير القسم'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='hr.department', verbose_name='القسم الأب'),
        ),
        migrations.AddField(
            model_name='contractincrease',
            name='amendment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='increase_schedule', to='hr.contractamendment', verbose_name='التعديل المرتبط'),
        ),
        migrations.AddField(
            model_name='contractincrease',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_increases', to='hr.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='contractincrease',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_increases', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='hr.contract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='contractamendment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, help_text='القسم في هذا العقد', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text='الوظيفة في هذا العقد', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='hr.contract', verbose_name='تم التجديد إلى'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='hr.biometricdevice', verbose_name='الماكينة'),
        ),
        migrations.AddField(
            model_name='biometricusermapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_mappings', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='biometricsynclog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hr.biometricdevice', verbose_name='الجهاز'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.attendance', verbose_name='سجل الحضور'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hr.biometricdevice', verbose_name='الجهاز'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_devices', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='hr.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.shift', verbose_name='الوردية'),
        ),
        migrations.AddField(
            model_name='advance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['employee', 'component_type'], name='hr_salaryco_employe_736ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['contract'], name='hr_salaryco_contrac_8d98d2_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'effective_date'], name='hr_salary_employe_d94faf_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month', 'status'], name='hr_payroll_month_c5d184_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'month'], name='hr_payroll_employe_1bb01d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='hr_leave_employe_7a42a8_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_leave_start_d_aa78ba_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='hr_employee_employe_725225_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['national_id'], name='hr_employee_nationa_e4f2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='hr_employee_departm_1b8ba9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractincrease',
            unique_together={('contract', 'increase_number')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='hr_contract_contrac_554672_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'status'], name='hr_contract_employe_44e3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_contract_start_d_6ecd31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricusermapping',
            unique_together={('employee', 'biometric_user_id')},
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['device', '-started_at'], name='hr_biometri_device__8ff79c_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['started_at'], name='hr_biometri_started_46978e_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriclog',
            index=models.Index(fields=['device', 'timestamp'], name='hr_biometri_device__071d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriclog',
            index=models.Index(fields=['employee', 'timestamp'], name='hr_biometri_employe_e67c20_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriclog',
            index=models.Index(fields=['is_processed'], name='hr_biometri_is_proc_14f075_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='hr_attendan_employe_c63029_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='hr_attendan_date_3a46d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
