# Generated by Django 4.2.26 on 2026-04-13 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمده",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="hr.attendance",
                verbose_name="سجل الحضور",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="permission_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.permissiontype",
                verbose_name="نوع الإذن",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="طلبه",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="penaltyreward",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_penalties_rewards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد/رفض بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="penaltyreward",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_penalties_rewards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="penaltyreward",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="penalties_rewards",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="penaltyreward",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="penalties_rewards",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payroll_periods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معتمد الفترة",
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_payroll_periods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مغلق الفترة",
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payroll_periods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="منشئ الفترة",
            ),
        ),
        migrations.AddField(
            model_name="payrollpaymentline",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="hr.payrollpayment",
                verbose_name="الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payrollpaymentline",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payroll_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معتمد الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payroll_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="منشئ الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="financial_category",
            field=models.ForeignKey(
                blank=True,
                help_text="التصنيف المالي لدفعة الراتب (يحدد الحساب المحاسبي تلقائياً)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_payments",
                to="financial.financialcategory",
                verbose_name="التصنيف المالي",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="القيد المحاسبي المرتبط بالدفعة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="payment_account",
            field=models.ForeignKey(
                help_text="الحساب المحاسبي المدفوع منه (صندوق/بنك)",
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.chartofaccounts",
                verbose_name="حساب الدفع",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payroll_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معالج الدفعة",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="advance_installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.advanceinstallment",
                verbose_name="قسط السلفة المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.attendance",
                verbose_name="سجل الحضور المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="leave_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.leave",
                verbose_name="الإجازة المرتبطة",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="salary_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.salarycomponent",
                verbose_name="بند الراتب المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="payrollauditlog",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="payrollauditlog",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_audit_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="contract",
            field=models.ForeignKey(
                help_text="العقد النشط وقت حساب الراتب",
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="financial_category",
            field=models.ForeignKey(
                blank=True,
                help_text="التصنيف المالي للرواتب (يحدد الحساب المحاسبي تلقائياً)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrolls",
                to="financial.financialcategory",
                verbose_name="التصنيف المالي",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="financial_subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="مركز التكلفة (التصنيف الفرعي) المأخوذ من قسم الموظف",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrolls",
                to="financial.financialsubcategory",
                verbose_name="التصنيف المالي الفرعي",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrolls",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دفع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                help_text="الصندوق أو البنك الذي تم الدفع منه",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_payments",
                to="financial.chartofaccounts",
                verbose_name="الحساب المدفوع منه",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processed_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معالج بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="officialholiday",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_official_holidays",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأها",
            ),
        ),
        migrations.AddField(
            model_name="leavesummary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_summaries",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="leaveencashmentlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encashment_logs",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="leaveencashmentlog",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encashment_logs",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="leaveencashmentlog",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processed_encashments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نفّذ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.leavetype",
                verbose_name="نوع الإجازة",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمده",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.leavetype",
                verbose_name="نوع الإجازة",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="راجعه",
            ),
        ),
        migrations.AddField(
            model_name="jobtitle",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_titles",
                to="hr.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="insurancepayment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="insurance_payments",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="insurancepayment",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="insurancepayment",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.chartofaccounts",
                verbose_name="حساب الاستلام",
            ),
        ),
        migrations.AddField(
            model_name="insurancepayment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="استلم بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_eos_benefits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_eos_benefits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="end_of_service_benefits",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eos_benefits",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_eos_benefits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دفع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="endofservicebenefit",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eos_benefit_payments",
                to="financial.chartofaccounts",
                verbose_name="الحساب المدفوع منه",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hr.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="direct_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="hr.employee",
                verbose_name="المدير المباشر",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="job_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="hr.jobtitle",
                verbose_name="المسمى الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.shift",
                verbose_name="الوردية",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="financial_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="financial.financialsubcategory",
                verbose_name="مركز التكلفة (التصنيف الفرعي)",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="hr.employee",
                verbose_name="مدير القسم",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_departments",
                to="hr.department",
                verbose_name="القسم الأب",
            ),
        ),
        migrations.AddField(
            model_name="contractsalarycomponent",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_components",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractsalarycomponent",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="القالب المستخدم (اختياري)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_instances",
                to="hr.salarycomponenttemplate",
                verbose_name="القالب",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="amendment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="increase_schedule",
                to="hr.contractamendment",
                verbose_name="التعديل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_increases",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_increases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amendments",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="القسم في هذا العقد",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                help_text="الوظيفة في هذا العقد",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.jobtitle",
                verbose_name="المسمى الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="renewed_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewed_from",
                to="hr.contract",
                verbose_name="تم التجديد إلى",
            ),
        ),
        migrations.AddField(
            model_name="biometricusermapping",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_mappings",
                to="hr.biometricdevice",
                verbose_name="الماكينة",
            ),
        ),
        migrations.AddField(
            model_name="biometricusermapping",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_mappings",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="biometricsynclog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="hr.biometricdevice",
                verbose_name="الجهاز",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_logs",
                to="hr.attendance",
                verbose_name="سجل الحضور",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="hr.biometricdevice",
                verbose_name="الجهاز",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_logs",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أضيف بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_devices",
                to="hr.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_summaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_summaries",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.shift",
                verbose_name="الوردية",
            ),
        ),
        migrations.AddField(
            model_name="advanceinstallment",
            name="advance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="hr.advance",
                verbose_name="السلفة",
            ),
        ),
        migrations.AddField(
            model_name="advanceinstallment",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advance_installments",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advances",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="financial_category",
            field=models.ForeignKey(
                blank=True,
                help_text="التصنيف المالي للسلف (يحدد الحساب المحاسبي تلقائياً)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advances",
                to="financial.financialcategory",
                verbose_name="التصنيف المالي",
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advances",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="advance",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advance_payments",
                to="financial.chartofaccounts",
                verbose_name="حساب الصرف (الخزينة/البنك)",
            ),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(
                fields=["employee", "component_type", "is_active"],
                name="hr_salaryco_employe_62c809_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(
                fields=["contract"], name="hr_salaryco_contrac_8d98d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(fields=["code"], name="hr_salaryco_code_5877cd_idx"),
        ),
        migrations.AddIndex(
            model_name="salarycomponent",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="hr_salaryco_effecti_3a783e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salarycomponent",
            constraint=models.UniqueConstraint(
                fields=("employee", "code"), name="unique_employee_component_code"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(
                fields=["employee", "status"], name="hr_permissi_employe_68c4ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(fields=["date"], name="hr_permissi_date_ce8754_idx"),
        ),
        migrations.AddConstraint(
            model_name="permissionrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("duration_hours__lte", 8), ("duration_hours__gt", 0)),
                name="permission_duration_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="penaltyreward",
            index=models.Index(
                fields=["employee", "status"], name="hr_penaltyr_employe_bb706a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltyreward",
            index=models.Index(
                fields=["month", "status"], name="hr_penaltyr_month_e9b3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penaltyreward",
            index=models.Index(
                fields=["category"], name="hr_penaltyr_categor_d106eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["year", "month"], name="hr_payrollp_year_4bd91c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(fields=["status"], name="hr_payrollp_status_55dda7_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["created_at"], name="hr_payrollp_created_b089ce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollperiod",
            unique_together={("year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="payrollpaymentline",
            unique_together={("payment", "payroll")},
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_reference"], name="hr_payrollp_payment_6f20c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_date"], name="hr_payrollp_payment_270a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(fields=["status"], name="hr_payrollp_status_a7ea6d_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_type"], name="hr_payrollp_payment_d2e141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["created_at"], name="hr_payrollp_created_545182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(
                fields=["payroll", "component_type"],
                name="hr_payrolll_payroll_471f6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["source"], name="hr_payrolll_source_6585b1_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["code"], name="hr_payrolll_code_3991ee_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollauditlog",
            index=models.Index(
                fields=["payroll", "timestamp"], name="hr_payrolla_payroll_1686b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollauditlog",
            index=models.Index(
                fields=["performed_by", "timestamp"],
                name="hr_payrolla_perform_6b8bfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["month", "status"], name="hr_payroll_month_c5d184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["employee", "month"], name="hr_payroll_employe_1bb01d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="officialholiday",
            index=models.Index(
                fields=["start_date", "end_date", "is_active"],
                name="hr_official_start_d_9cb671_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leavesummary",
            index=models.Index(
                fields=["employee", "month"], name="hr_leavesum_employe_4fd8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavesummary",
            index=models.Index(
                fields=["month", "is_calculated"], name="hr_leavesum_month_8db85d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavesummary",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="leaveencashmentlog",
            index=models.Index(
                fields=["employee", "year"], name="hr_leaveenc_employe_9e066c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveencashmentlog",
            index=models.Index(
                fields=["encashment_month"], name="hr_leaveenc_encashm_de3320_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["employee", "status"], name="hr_leave_employe_7a42a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leave",
            index=models.Index(
                fields=["start_date", "end_date"], name="hr_leave_start_d_aa78ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepayment",
            index=models.Index(
                fields=["month", "status"], name="hr_insuranc_month_675890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepayment",
            index=models.Index(
                fields=["employee", "month"], name="hr_insuranc_employe_f0b1a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="insurancepayment",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="endofservicebenefit",
            index=models.Index(
                fields=["employee", "status"], name="hr_end_of_s_employe_5e8b2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="endofservicebenefit",
            index=models.Index(
                fields=["status", "calculation_date"],
                name="hr_end_of_s_status_f8f92b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_number"], name="hr_employee_employe_725225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["national_id"], name="hr_employee_nationa_e4f2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="hr_employee_status_75bd6c_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department"], name="hr_employee_departm_1b8ba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractsalarycomponent",
            index=models.Index(
                fields=["contract", "component_type"],
                name="hr_contract_contrac_960933_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractsalarycomponent",
            index=models.Index(fields=["code"], name="hr_contract_code_00fb0c_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractsalarycomponent",
            constraint=models.UniqueConstraint(
                fields=("contract", "code"), name="unique_contract_component_code"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractincrease",
            unique_together={("contract", "increase_number")},
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["contract_number"], name="hr_contract_contrac_554672_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["employee", "status"], name="hr_contract_employe_44e3a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["start_date", "end_date"], name="hr_contract_start_d_6ecd31_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biometricusermapping",
            unique_together={("employee", "biometric_user_id")},
        ),
        migrations.AddIndex(
            model_name="biometricsynclog",
            index=models.Index(
                fields=["device", "-started_at"], name="hr_biometri_device__8ff79c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricsynclog",
            index=models.Index(
                fields=["started_at"], name="hr_biometri_started_46978e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["device", "timestamp"], name="hr_biometri_device__071d7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["employee", "timestamp"], name="hr_biometri_employe_e67c20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["is_processed"], name="hr_biometri_is_proc_14f075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["employee", "month"], name="hr_attendan_employe_66184e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["month", "is_calculated"], name="hr_attendan_month_0f507f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["is_approved"], name="hr_attendan_is_appr_c37c2f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["employee", "date"], name="hr_attendan_employe_c63029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="hr_attendan_date_3a46d7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="advanceinstallment",
            index=models.Index(
                fields=["advance", "month"], name="hr_advancei_advance_71158c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advanceinstallment",
            index=models.Index(fields=["month"], name="hr_advancei_month_2d0de3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="advanceinstallment",
            unique_together={("advance", "month")},
        ),
        migrations.AddIndex(
            model_name="advance",
            index=models.Index(
                fields=["employee", "status"], name="hr_advance_employe_f75faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advance",
            index=models.Index(
                fields=["status", "deduction_start_month"],
                name="hr_advance_status_ae5bb2_idx",
            ),
        ),
    ]
