# Generated by Django 5.2.17 on 2026-09-21 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_paymentterm_code'),
        ('hr', '0002_initial'),
        ('work_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='الحقل المعدل')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='القيمة السابقة')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(verbose_name='سبب التعديل / الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ وتوقيت التعديل')),
            ],
            options={
                'verbose_name': 'سجل تدقيق حضور',
                'verbose_name_plural': 'سجلات تدقيق الحضور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم المقر بالعربية')),
                ('name_en', models.CharField(blank=True, default='', max_length=150, verbose_name='اسم المقر بالإنجليزية')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان التفصيلي')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض (Latitude)')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول (Longitude)')),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='أقصى مسافة مسموح بها للموظف عن مركز المقر للبصم', verbose_name='نطاق البصمة المسموح (متر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='المقر الرئيسي الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مقر عمل',
                'verbose_name_plural': 'مقرات العمل',
                'ordering': ['-is_default', 'name_ar'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'permissions': [('can_manage_employees', 'إدارة الموظفين'), ('can_view_all_employees', 'عرض جميع الموظفين'), ('can_terminate_employees', 'إنهاء خدمة الموظفين'), ('can_manual_attendance', 'إمكانية إضافة وتعديل الحضور اليدوي'), ('can_import_attendance', 'إمكانية استيراد الحضور من Excel'), ('can_reset_device_binding', 'إمكانية إعادة تعيين ربط جهاز الموظف')], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='customer.customer', verbose_name='العميل المرتبط'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_field_visit',
            field=models.BooleanField(default=False, verbose_name='زيارة ميدانية'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='إدخال يدوي'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_missing_checkout',
            field=models.BooleanField(default=False, verbose_name='نسيان بصمة الانصراف'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المقر / الموقع'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manual_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendances_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء يدوياً بواسطة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manual_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإدخال اليدوي'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('device', 'ماكينة'), ('mobile', 'موبايل'), ('field_visit', 'زيارة ميدانية'), ('supervisor', 'مشرف'), ('manual', 'يدوي'), ('excel', 'استيراد إكسيل')], default='device', max_length=20, verbose_name='مصدر البصمة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='work_order.workorder', verbose_name='أمر الشغل المرتبط'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='approved_overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تعديل ساعات الإضافي يدوياً للاعتماد في كشف المرتبات', max_digits=10, null=True, verbose_name='ساعات الإضافي المعتمدة يدوياً'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='overtime_override_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب تعديل ساعات الإضافي'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='timezone_offset_hours',
            field=models.IntegerField(default=0, help_text='إضافة أو خصم ساعات لتعويض فروق التوقيت الصيفي أو خطأ ساعة الماكينة الداخلية', verbose_name='تعويض فارق التوقيت (ساعات)'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='customer.customer', verbose_name='العميل المرتبط'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='device_info',
            field=models.JSONField(blank=True, null=True, verbose_name='معلومات المتصفح/الجهاز'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف عتاد الجهاز'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='is_device_unverified',
            field=models.BooleanField(default=False, verbose_name='جهاز غير موثق (طوارئ)'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='is_offline_synced',
            field=models.BooleanField(default=False, verbose_name='تمت المزامنة أوفلاين'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='دقة الموقع (متر)'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/%Y/%m/', verbose_name='صورة السيلفي'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='source',
            field=models.CharField(choices=[('device', 'ماكينة'), ('mobile', 'موبايل'), ('field_visit', 'زيارة ميدانية'), ('supervisor', 'مشرف'), ('manual', 'يدوي'), ('excel', 'استيراد إكسيل')], default='device', max_length=20, verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='sync_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='توقيت وصول المزامنة'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='work_order.workorder', verbose_name='أمر الشغل المرتبط'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allow_field_visits',
            field=models.BooleanField(default=False, help_text='تمكين تسجيل البصمة الميدانية خارج مقرات الشركة بدون التقيد بنطاق جغرافي محدد', verbose_name='السماح بالزيارات الميدانية والمأموريات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allow_mobile_attendance',
            field=models.BooleanField(default=False, help_text='تمكين الموظف من تسجيل الحضور عبر تطبيق الموبايل PWA', verbose_name='السماح ببصمة الموبايل GPS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_all_locations',
            field=models.BooleanField(default=False, help_text='تمكين الموظف من البصمة في أي فرع أو مقر نشط للشركة', verbose_name='السماح بالبصمة في كافة المقرات (موظف متنقل)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ربط الجهاز'),
        ),
        migrations.AddField(
            model_name='employee',
            name='registered_device_uuid',
            field=models.CharField(blank=True, help_text='بصمة عتاد الهاتف المرتبط بحساب الموظف لمنع تبادل الهواتف', max_length=255, null=True, verbose_name='معرف الجهاز المعتمد'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='يتم تعيينها عند تعديل بيانات الحضور للشهر بعد حساب المسودة', verbose_name='بحاجة لإعادة الحساب'),
        ),
        migrations.AddField(
            model_name='shift',
            name='weekly_off_days',
            field=models.JSONField(blank=True, help_text='قائمة بأيام الإجازة الأسبوعية المخصصة لهذه الوردية (مثلاً [4, 5] للجمعة والسبت)', null=True, verbose_name='الإجازة الأسبوعية للوردية'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='total_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي ساعات العمل الإضافي المحسوبة'),
        ),
        migrations.AlterField(
            model_name='biometriclog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='hr.biometricdevice', verbose_name='الجهاز'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='hr_attendan_date_36f853_idx'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hr.attendance', verbose_name='سجل الحضور'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_audit_edits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفذ'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='supervisor_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_audit_punches', to='hr.employee', verbose_name='المشرف الشاهد والمسؤول'),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='matched_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.worklocation', verbose_name='المقر المطابق'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.worklocation', verbose_name='مقر العمل المعتمد'),
        ),
        migrations.AddIndex(
            model_name='biometriclog',
            index=models.Index(fields=['device', 'is_processed'], name='hr_biometri_device__a24255_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriclog',
            index=models.Index(fields=['source'], name='hr_biometri_source_a1162a_idx'),
        ),
    ]
