# Generated by Django 4.2.25 on 2025-11-11 18:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_load_chart_of_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0002_create_payroll_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        help_text="رقم مرجعي فريد للدفعة",
                        max_length=50,
                        unique=True,
                        verbose_name="مرجع الدفعة",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("individual", "دفعة فردية"),
                            ("batch", "دفعة جماعية"),
                            ("advance", "سلفة على الراتب"),
                            ("bonus", "مكافأة إضافية"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="نوع الدفعة",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقداً"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                            ("online", "دفع إلكتروني"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "في الانتظار"),
                            ("processing", "قيد المعالجة"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الدفعة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="إجمالي مبلغ الدفعة",
                        max_digits=15,
                        verbose_name="إجمالي المبلغ",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="المبلغ الصافي بعد الخصومات",
                        max_digits=15,
                        verbose_name="المبلغ الصافي",
                    ),
                ),
                (
                    "fees_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="رسوم التحويل أو المعالجة",
                        max_digits=10,
                        verbose_name="رسوم التحويل",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="تاريخ تنفيذ الدفعة", verbose_name="تاريخ الدفع"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="تاريخ استحقاق الدفعة",
                        null=True,
                        verbose_name="تاريخ الاستحقاق",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="وقت معالجة الدفعة",
                        null=True,
                        verbose_name="وقت المعالجة",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="وصف تفصيلي للدفعة", verbose_name="الوصف"
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        help_text="رقم المرجع من البنك (للتحويلات البنكية)",
                        max_length=100,
                        verbose_name="مرجع البنك",
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم الشيك (للدفع بالشيك)",
                        max_length=50,
                        verbose_name="رقم الشيك",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="ملاحظات إضافية", verbose_name="ملاحظات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معتمد الدفعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ الدفعة",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="القيد المحاسبي المرتبط بالدفعة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        help_text="الحساب المحاسبي المدفوع منه (صندوق/بنك)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.chartofaccounts",
                        verbose_name="حساب الدفع",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payroll_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معالج الدفعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة الراتب",
                "verbose_name_plural": "دفعات الرواتب",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="سنة فترة الرواتب", verbose_name="السنة"
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="شهر فترة الرواتب (1-12)", verbose_name="الشهر"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="تاريخ بداية فترة الرواتب",
                        verbose_name="تاريخ البداية",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="تاريخ نهاية فترة الرواتب",
                        verbose_name="تاريخ النهاية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("calculated", "محسوبة"),
                            ("approved", "معتمدة"),
                            ("paid", "مدفوعة"),
                            ("closed", "مغلقة"),
                        ],
                        default="draft",
                        help_text="حالة فترة الرواتب",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_employees",
                    models.IntegerField(
                        default=0,
                        help_text="إجمالي عدد الموظفين في هذه الفترة",
                        verbose_name="عدد الموظفين",
                    ),
                ),
                (
                    "total_gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="مجموع جميع الرواتب الإجمالية",
                        max_digits=15,
                        verbose_name="إجمالي الرواتب الإجمالية",
                    ),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="مجموع جميع الرواتب الصافية",
                        max_digits=15,
                        verbose_name="إجمالي الرواتب الصافية",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="مجموع جميع الخصومات",
                        max_digits=15,
                        verbose_name="إجمالي الخصومات",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات إضافية حول فترة الرواتب",
                        verbose_name="ملاحظات",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معتمد الفترة",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مغلق الفترة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ الفترة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة الرواتب",
                "verbose_name_plural": "فترات الرواتب",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="hr_payrollp_year_4bd91c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="hr_payrollp_status_55dda7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="hr_payrollp_created_b089ce_idx"
                    ),
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="PayrollPaymentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        help_text="اسم الموظف (للمرجعية السريعة)",
                        max_length=200,
                        verbose_name="اسم الموظف",
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الإجمالي"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ الصافي"
                    ),
                ),
                (
                    "deductions_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="مبلغ الخصومات",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hr.payrollpayment",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.payroll",
                        verbose_name="قسيمة الراتب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سطر دفعة الراتب",
                "verbose_name_plural": "أسطر دفعات الرواتب",
                "unique_together": {("payment", "payroll")},
            },
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_reference"], name="hr_payrollp_payment_6f20c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_date"], name="hr_payrollp_payment_270a1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(fields=["status"], name="hr_payrollp_status_a7ea6d_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["payment_type"], name="hr_payrollp_payment_d2e141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollpayment",
            index=models.Index(
                fields=["created_at"], name="hr_payrollp_created_545182_idx"
            ),
        ),
    ]
