# Generated by Django 4.2.26 on 2026-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penaltyreward",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="التاريخ"),
        ),
    ]
