# Generated by Django 4.2.26 on 2026-08-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("regular", "وردية أساسية (دائمة)"),
                    ("morning", "وردية صباحية"),
                    ("evening", "وردية مسائية"),
                    ("night", "وردية ليلية"),
                    ("seasonal", "وردية موسمية"),
                    ("annual", "سنة مالية"),
                    ("summer", "مؤقتة"),
                ],
                max_length=20,
                verbose_name="نوع الوردية",
            ),
        ),
    ]
