# Generated by Django 4.2.23 on 2025-11-03 03:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_alter_employee_options_alter_leave_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('contract', 'عقد محدد المدة'), ('internship', 'تدريب'), ('part_time', 'دوام جزئي')], max_length=20, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('probation_period_months', models.IntegerField(default=3, verbose_name='فترة التجربة (بالأشهر)')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التجربة')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل السكن')),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل المواصلات')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدلات أخرى')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الراتب')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4, verbose_name='ساعات العمل اليومية')),
                ('working_days_per_week', models.IntegerField(default=5, verbose_name='أيام العمل الأسبوعية')),
                ('annual_leave_days', models.IntegerField(default=21, verbose_name='أيام الإجازة السنوية')),
                ('sick_leave_days', models.IntegerField(default=30, verbose_name='أيام الإجازة المرضية')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='البنود والشروط')),
                ('special_clauses', models.TextField(blank=True, verbose_name='بنود خاصة')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='ملف العقد')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('renewal_notice_days', models.IntegerField(default=30, verbose_name='أيام الإشعار قبل التجديد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'ساري'), ('expired', 'منتهي'), ('renewed', 'تم التجديد'), ('terminated', 'منهي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='الموظف')),
                ('renewed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='hr.contract', verbose_name='تم التجديد إلى')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-start_date'],
                'permissions': [('can_manage_contracts', 'إدارة العقود'), ('can_sign_contracts', 'توقيع العقود'), ('can_terminate_contracts', 'إنهاء العقود')],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التعديل')),
                ('amendment_type', models.CharField(choices=[('salary_increase', 'زيادة راتب'), ('position_change', 'تغيير منصب'), ('extension', 'تمديد'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التعديل')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('amendment_file', models.FileField(blank=True, null=True, upload_to='contract_amendments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='ملف التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='hr.contract', verbose_name='العقد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تعديل عقد',
                'verbose_name_plural': 'تعديلات العقود',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='hr_contract_contrac_554672_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'status'], name='hr_contract_employe_44e3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_contract_start_d_6ecd31_idx'),
        ),
    ]
