# Generated by Django 5.2.17 on 2026-09-21 20:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_attendanceauditlog_worklocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'permissions': [('can_manual_attendance', 'يمكنه إضافة وتعديل الحضور يدوياً'), ('can_import_attendance', 'يمكنه استيراد الحضور من Excel'), ('can_reset_device_binding', 'يمكنه فك قفل هاتف الموظف المقترن')], 'verbose_name': 'حضور', 'verbose_name_plural': 'سجل الحضور'},
        ),
        migrations.CreateModel(
            name='EmployeeAssetCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_code', models.CharField(help_text='ترقيم آلي فريد عبر SequenceService', max_length=50, unique=True, verbose_name='كود العهدة العينية')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف / الجهاز المسلم')),
                ('category', models.CharField(choices=[('laptop_pc', 'أجهزة كمبيوتر ولابتوب'), ('mobile_tablet', 'هواتف ذكية وأجهزة لوحية'), ('measuring_tech', 'أجهزة مساحة وقياس هندسية'), ('vehicle', 'سيارة / وسيلة انتقال للشركة'), ('power_tool', 'معدات وعدد فنية ثقيلة'), ('ppe_safety', 'مهمات وقاية وأمان شخصي (PPE)'), ('office_furniture', 'أثاث مكتبي وأجهزة مكتبية'), ('other', 'أخرى')], default='laptop_pc', max_length=30, verbose_name='تصنيف العهدة العينية')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم التسلسلي (Serial Number / Asset Tag)')),
                ('is_consumable', models.BooleanField(default=False, help_text='المهمات المستهلكة تسقط تلقائياً بانتهاء عمرها الافتراضي ولا تعطل إخلاء الطرف', verbose_name='مهمات مستهلكة (PPE / مستهلكات)')),
                ('expected_lifespan_months', models.PositiveIntegerField(default=24, verbose_name='العمر الافتراضي بالأشهر')),
                ('delivered_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسليم الفعلي للموظف')),
                ('condition_on_delivery', models.CharField(choices=[('excellent', 'ممتازة / جديد'), ('good', 'جيدة جداً'), ('fair', 'مقبولة / مستعملة'), ('damaged', 'تالفة / معطوبة')], default='good', max_length=20, verbose_name='حالة الأصل عند التسليم')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='القيمة الدفترية / التقديرية للأصل')),
                ('signed_receipt_file', models.FileField(blank=True, null=True, upload_to='hr/asset_receipts/%Y/%m/', verbose_name='إقرار استلام العهدة العينية الموقع')),
                ('status', models.CharField(choices=[('active', 'مسلمة للموظف (جارية)'), ('returned', 'مستردة للمخزن بحالة سليمة'), ('damaged', 'تالفة / تحتاج إصلاح'), ('consumed', 'مستهلكة بالكامل (مهمات وقاية PPE)'), ('under_investigation', 'تحت التحقيق الإداري (سرقة/فقدان/تلف)'), ('in_refurbishment', 'قيد الصيانة والتجهيز الفني'), ('scrapped', 'مكهنة ومستبعدة دفترياً')], db_index=True, default='active', max_length=30, verbose_name='حالة العهدة')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاسترداد الفعلي')),
                ('return_condition', models.CharField(blank=True, choices=[('excellent', 'ممتازة / جديد'), ('good', 'جيدة جداً'), ('fair', 'مقبولة / مستعملة'), ('damaged', 'تالفة / معطوبة')], max_length=20, null=True, verbose_name='حالة الأصل عند الاسترداد')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='تكلفة الإصلاح في حالة التلف')),
                ('repair_charged_to_employee', models.BooleanField(default=False, verbose_name='تحميل تكلفة الإصلاح على الموظف (استقطاع راتب)')),
                ('signed_return_file', models.FileField(blank=True, null=True, upload_to='hr/asset_returns/%Y/%m/', verbose_name='محضر استرداد العهدة الموقع')),
                ('investigation_notes', models.TextField(blank=True, null=True, verbose_name='وقائع وقرار التحقيق الإداري')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية والمواصفات الفنية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custodies', to='hr.employee', verbose_name='الموظف المسؤول')),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_custodies', to='hr.worklocation', verbose_name='مقر العمل / الموقع')),
            ],
            options={
                'verbose_name': 'عهدة عينية لموظف',
                'verbose_name_plural': 'العهد العينية للأجهزة والمهمات',
                'ordering': ['-delivered_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(max_length=50, unique=True, verbose_name='كود محضر المناقلة')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المناقلة الميدانية')),
                ('condition', models.CharField(choices=[('excellent', 'ممتازة / جديد'), ('good', 'جيدة جداً'), ('fair', 'مقبولة / مستعملة'), ('damaged', 'تالفة / معطوبة')], default='good', max_length=20, verbose_name='حالة الأصل وقت المناقلة')),
                ('signed_transfer_file', models.FileField(blank=True, null=True, upload_to='hr/asset_transfers/%Y/%m/', verbose_name='محضر المناقلة الميداني الموقع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='سبب المناقلة الميدانية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_transfers', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة (مدير الموقع / الـ HR)')),
                ('asset_custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hr.employeeassetcustody', verbose_name='الأصل العيني المنقول')),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_assets_out', to='hr.employee', verbose_name='الموظف المسلّم')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_assets_in', to='hr.employee', verbose_name='الموظف المستلِم')),
            ],
            options={
                'verbose_name': 'محضر مناقلة عهدة عينية',
                'verbose_name_plural': 'محاضر مناقلة العهد العينية',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeeassetcustody',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_916575_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetcustody',
            index=models.Index(fields=['category', 'status'], name='hr_employee_categor_1bb39b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetcustody',
            index=models.Index(fields=['serial_number'], name='hr_employee_serial__b6fe2c_idx'),
        ),
    ]
