# Generated by Django 4.2.23 on 2025-11-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_contract_contractamendment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('device_code', models.CharField(max_length=50, unique=True, verbose_name='كود الجهاز')),
                ('device_type', models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('face', 'التعرف على الوجه'), ('card', 'كارت'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع الجهاز')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='الرقم التسلسلي')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('port', models.IntegerField(default=4370, verbose_name='المنفذ')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50, verbose_name='المنطقة الزمنية')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='مزامنة تلقائية')),
                ('sync_interval', models.IntegerField(default=30, verbose_name='فترة المزامنة (دقائق)')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='اسم المستخدم')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='كلمة المرور')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'تحت الصيانة'), ('error', 'خطأ')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('total_users', models.IntegerField(default=0, verbose_name='عدد المستخدمين')),
                ('total_records', models.IntegerField(default=0, verbose_name='عدد السجلات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_devices', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'ماكينة بصمة',
                'verbose_name_plural': 'ماكينات البصمة',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='وقت البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('status', models.CharField(choices=[('success', 'نجحت'), ('failed', 'فشلت'), ('partial', 'جزئية')], max_length=20, verbose_name='الحالة')),
                ('records_fetched', models.IntegerField(default=0, verbose_name='السجلات المجلوبة')),
                ('records_processed', models.IntegerField(default=0, verbose_name='السجلات المعالجة')),
                ('records_failed', models.IntegerField(default=0, verbose_name='السجلات الفاشلة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hr.biometricdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل مزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='معرف المستخدم')),
                ('timestamp', models.DateTimeField(verbose_name='وقت البصمة')),
                ('log_type', models.CharField(choices=[('check_in', 'حضور'), ('check_out', 'انصراف'), ('break_start', 'بداية استراحة'), ('break_end', 'نهاية استراحة')], default='check_in', max_length=20, verbose_name='نوع السجل')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.attendance', verbose_name='سجل الحضور')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hr.biometricdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='hr_biometri_device__071d7e_idx'), models.Index(fields=['employee', 'timestamp'], name='hr_biometri_employe_e67c20_idx'), models.Index(fields=['is_processed'], name='hr_biometri_is_proc_14f075_idx')],
            },
        ),
    ]
