# Generated by Django 4.2.25 on 2025-11-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0004_add_component_classification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="الشهر")),
                (
                    "total_working_days",
                    models.IntegerField(
                        default=0,
                        help_text="عدد أيام العمل في الشهر (بدون الجمع والعطلات)",
                        verbose_name="إجمالي أيام العمل",
                    ),
                ),
                (
                    "present_days",
                    models.IntegerField(default=0, verbose_name="أيام الحضور"),
                ),
                (
                    "absent_days",
                    models.IntegerField(default=0, verbose_name="أيام الغياب"),
                ),
                (
                    "late_days",
                    models.IntegerField(default=0, verbose_name="أيام التأخير"),
                ),
                (
                    "half_days",
                    models.IntegerField(default=0, verbose_name="أيام نصف يوم"),
                ),
                (
                    "paid_leave_days",
                    models.IntegerField(
                        default=0, verbose_name="أيام الإجازات المدفوعة"
                    ),
                ),
                (
                    "unpaid_leave_days",
                    models.IntegerField(
                        default=0, verbose_name="أيام الإجازات غير المدفوعة"
                    ),
                ),
                (
                    "total_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي ساعات العمل",
                    ),
                ),
                (
                    "total_late_minutes",
                    models.IntegerField(default=0, verbose_name="إجمالي دقائق التأخير"),
                ),
                (
                    "total_early_leave_minutes",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي دقائق الانصراف المبكر"
                    ),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="إجمالي ساعات العمل الإضافي",
                    ),
                ),
                (
                    "absence_deduction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ خصم الغياب",
                    ),
                ),
                (
                    "late_deduction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ خصم التأخير",
                    ),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ العمل الإضافي",
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(default=False, verbose_name="تم الحساب"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="معتمد"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="تفاصيل الحساب"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "ملخص حضور شهري",
                "verbose_name_plural": "ملخصات الحضور الشهرية",
                "ordering": ["-month", "employee"],
            },
        ),
        migrations.CreateModel(
            name="LeaveSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="الشهر")),
                (
                    "annual_leave_days",
                    models.IntegerField(default=0, verbose_name="إجازات سنوية"),
                ),
                (
                    "sick_leave_days",
                    models.IntegerField(default=0, verbose_name="إجازات مرضية"),
                ),
                (
                    "emergency_leave_days",
                    models.IntegerField(default=0, verbose_name="إجازات طارئة"),
                ),
                (
                    "unpaid_leave_days",
                    models.IntegerField(default=0, verbose_name="إجازات بدون راتب"),
                ),
                (
                    "total_paid_days",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الأيام المدفوعة"
                    ),
                ),
                (
                    "total_unpaid_days",
                    models.IntegerField(
                        default=0, verbose_name="إجمالي الأيام غير المدفوعة"
                    ),
                ),
                (
                    "deduction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ الخصم",
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(default=False, verbose_name="تم الحساب"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="تفاصيل كل إجازة",
                        null=True,
                        verbose_name="التفاصيل",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "ملخص إجازات شهري",
                "verbose_name_plural": "ملخصات الإجازات الشهرية",
                "ordering": ["-month", "employee"],
            },
        ),
        migrations.AlterModelOptions(
            name="payrollline",
            options={
                "ordering": ["payroll", "component_type", "order"],
                "verbose_name": "بند قسيمة راتب",
                "verbose_name_plural": "بنود قسائم الرواتب",
            },
        ),
        migrations.RemoveIndex(
            model_name="payrollline",
            name="hr_payrolll_salary__30fc9c_idx",
        ),
        migrations.RemoveField(
            model_name="payrollline",
            name="notes",
        ),
        migrations.AddField(
            model_name="payrollline",
            name="advance_installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.advanceinstallment",
                verbose_name="قسط السلفة المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="attendance_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.attendance",
                verbose_name="سجل الحضور المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف"),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="leave_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.leave",
                verbose_name="الإجازة المرتبطة",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="مثال: عدد الأيام، الساعات، إلخ",
                max_digits=10,
                verbose_name="الكمية",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="سعر الوحدة",
                max_digits=10,
                verbose_name="السعر",
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="source",
            field=models.CharField(
                choices=[
                    ("contract", "من العقد"),
                    ("attendance", "من الحضور"),
                    ("leave", "من الإجازات"),
                    ("overtime", "عمل إضافي"),
                    ("advance", "سلفة"),
                    ("bonus", "مكافأة"),
                    ("deduction", "خصم"),
                    ("adjustment", "تعديل"),
                ],
                default="contract",
                max_length=20,
                verbose_name="المصدر",
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="quantity × rate",
                max_digits=10,
                verbose_name="المبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="calculation_details",
            field=models.JSONField(
                blank=True,
                help_text="تخزين تفاصيل الحساب بصيغة JSON",
                null=True,
                verbose_name="تفاصيل الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="code",
            field=models.CharField(default="", max_length=50, verbose_name="الكود"),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="component_type",
            field=models.CharField(
                choices=[("earning", "مستحق"), ("deduction", "خصم")],
                default="earning",
                max_length=20,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="name",
            field=models.CharField(
                default="", max_length=200, verbose_name="اسم البند"
            ),
        ),
        migrations.AlterField(
            model_name="payrollline",
            name="salary_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.salarycomponent",
                verbose_name="بند الراتب المرتبط",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["source"], name="hr_payrolll_source_6585b1_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollline",
            index=models.Index(fields=["code"], name="hr_payrolll_code_3991ee_idx"),
        ),
        migrations.AddField(
            model_name="leavesummary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_summaries",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_summaries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_summaries",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AddIndex(
            model_name="leavesummary",
            index=models.Index(
                fields=["employee", "month"], name="hr_leavesum_employe_4fd8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavesummary",
            index=models.Index(
                fields=["month", "is_calculated"], name="hr_leavesum_month_8db85d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavesummary",
            unique_together={("employee", "month")},
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["employee", "month"], name="hr_attendan_employe_66184e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["month", "is_calculated"], name="hr_attendan_month_0f507f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["is_approved"], name="hr_attendan_is_appr_c37c2f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("employee", "month")},
        ),
    ]
