# Generated by Django 4.2.23 on 2025-11-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_add_leave_accrual_fields'),
        ('hr', '0004_biometricdevice_biometricsynclog_biometriclog'),
    ]

    operations = [
    ]
