# Generated by Django 4.2.25 on 2025-11-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_add_integrated_payroll_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advanceinstallment",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advance_installments",
                to="hr.payroll",
                verbose_name="قسيمة الراتب",
            ),
        ),
    ]
