# Generated by Django 4.2.23 on 2025-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_user_alter_shift_work_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم جهة الاتصال للطوارئ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='هاتف الطوارئ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='صلة القرابة'),
        ),
    ]
