# Generated by Django 4.2.23 on 2025-11-04 00:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_employee_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('component_type', models.CharField(choices=[('earning', 'مستحق'), ('deduction', 'مستقطع')], max_length=20, verbose_name='نوع المكون')),
                ('formula', models.CharField(blank=True, help_text='مثال: basic * 0.25 (للنسبة المئوية) أو basic + 500 (لإضافة مبلغ ثابت)', max_length=255, verbose_name='الصيغة الحسابية')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, help_text='يُستخدم إذا لم تكن هناك صيغة حسابية', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ الافتراضي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قالب مكون راتب',
                'verbose_name_plural': 'قوالب مكونات الرواتب',
                'ordering': ['component_type', 'order', 'name'],
                'indexes': [models.Index(fields=['component_type', 'is_active'], name='hr_salaryco_compone_827086_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('earning', 'مستحق'), ('deduction', 'مستقطع')], max_length=20, verbose_name='نوع المكون')),
                ('name', models.CharField(max_length=100, verbose_name='بند الراتب')),
                ('formula', models.CharField(blank=True, help_text='مثال: basic * 0.1 أو basic + 500', max_length=255, verbose_name='الصيغة الحسابية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_basic', models.BooleanField(default=False, verbose_name='بند أساسي')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='hr.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'مكون راتب',
                'verbose_name_plural': 'مكونات الرواتب',
                'ordering': ['component_type', 'order', 'id'],
                'indexes': [models.Index(fields=['contract', 'component_type'], name='hr_salaryco_contrac_748bfb_idx')],
            },
        ),
    ]
