# Generated by Django 4.2.25 on 2025-11-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0009_salarycomponenttemplate_salarycomponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="probation_period_months",
            field=models.IntegerField(
                blank=True, default=3, null=True, verbose_name="فترة التجربة (بالأشهر)"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="renewal_notice_days",
            field=models.IntegerField(
                blank=True,
                default=30,
                null=True,
                verbose_name="أيام الإشعار قبل التجديد",
            ),
        ),
        migrations.CreateModel(
            name="SalaryIncreaseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم القالب")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الكود"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "increase_type",
                    models.CharField(
                        choices=[
                            ("percentage", "نسبة مئوية"),
                            ("fixed", "مبلغ ثابت"),
                            ("performance", "حسب الأداء"),
                        ],
                        max_length=20,
                        verbose_name="نوع الزيادة",
                    ),
                ),
                (
                    "default_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="النسبة الافتراضية (%)",
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="المبلغ الافتراضي",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("annual", "سنوي"), ("semi_annual", "نصف سنوي")],
                        default="annual",
                        max_length=20,
                        verbose_name="التكرار",
                    ),
                ),
                (
                    "min_service_months",
                    models.IntegerField(
                        default=0, verbose_name="الحد الأدنى لأشهر الخدمة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_increase_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب زيادة المرتب",
                "verbose_name_plural": "قوالب زيادات المرتبات",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeIncreaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفئة")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الكود"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_categories",
                        to="hr.salaryincreasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة موظف للزيادات",
                "verbose_name_plural": "فئات الموظفين للزيادات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnnualIncreasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الخطة")),
                ("year", models.IntegerField(verbose_name="السنة")),
                ("effective_date", models.DateField(verbose_name="تاريخ السريان")),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="إجمالي الميزانية",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="المبلغ المخصص",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("approved", "معتمدة"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتملة"),
                            ("cancelled", "ملغية"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_increase_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_increase_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_plans",
                        to="hr.salaryincreasetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة الزيادات السنوية",
                "verbose_name_plural": "خطط الزيادات السنوية",
                "ordering": ["-year", "-created_at"],
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="PlannedIncrease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الراتب الحالي"
                    ),
                ),
                (
                    "increase_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="نسبة الزيادة (%)",
                    ),
                ),
                (
                    "increase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ الزيادة",
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="المبلغ المحسوب"
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الراتب الجديد"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("approved", "معتمدة"),
                            ("rejected", "مرفوضة"),
                            ("applied", "مطبقة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التطبيق"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_increases",
                        to="hr.contract",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_increases",
                        to="hr.employee",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_increases",
                        to="hr.annualincreaseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "زيادة مخططة",
                "verbose_name_plural": "الزيادات المخططة",
                "ordering": ["plan", "employee"],
                "unique_together": {("plan", "employee")},
            },
        ),
    ]
