# Generated by Django 4.2.25 on 2025-11-07 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0010_add_salary_increase_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("signed_contract", "العقد الموقع"),
                            ("id_copy", "صورة الهوية"),
                            ("certificate", "الشهادات"),
                            ("medical_report", "التقرير الطبي"),
                            ("bank_account", "بيانات الحساب البنكي"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "file",
                    models.FileField(
                        upload_to="contract_documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="الملف",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
            ],
            options={
                "verbose_name": "وثيقة عقد",
                "verbose_name_plural": "وثائق العقود",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractIncrease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "increase_number",
                    models.IntegerField(
                        help_text="الترتيب التسلسلي للزيادة (1، 2، 3...)",
                        verbose_name="رقم الزيادة",
                    ),
                ),
                (
                    "increase_type",
                    models.CharField(
                        choices=[("percentage", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="percentage",
                        max_length=20,
                        verbose_name="نوع الزيادة",
                    ),
                ),
                (
                    "increase_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="مثال: 7.5 للزيادة 7.5%",
                        max_digits=5,
                        null=True,
                        verbose_name="نسبة الزيادة (%)",
                    ),
                ),
                (
                    "increase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ الزيادة الثابت",
                    ),
                ),
                (
                    "months_from_start",
                    models.IntegerField(
                        help_text="مثال: 6 للزيادة بعد 6 أشهر من بداية العقد",
                        verbose_name="عدد الأشهر من بداية العقد",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="التاريخ المتوقع لتطبيق الزيادة",
                        verbose_name="التاريخ المجدول",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("applied", "تم التطبيق"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ التطبيق الفعلي"
                    ),
                ),
                (
                    "applied_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="المبلغ الفعلي الذي تم إضافته للراتب",
                        max_digits=10,
                        null=True,
                        verbose_name="المبلغ المطبق",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "زيادة مجدولة",
                "verbose_name_plural": "الزيادات المجدولة",
                "ordering": ["contract", "increase_number"],
            },
        ),
        migrations.RemoveField(
            model_name="contract",
            name="annual_leave_days",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="housing_allowance",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="other_allowances",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="sick_leave_days",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="total_salary",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="transportation_allowance",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="working_days_per_week",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="working_hours_per_day",
        ),
        migrations.AddField(
            model_name="contract",
            name="biometric_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="رقم الموظف في جهاز البصمة (اختياري - سيتم حفظه في ملف الموظف)",
                null=True,
                verbose_name="رقم البصمة",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="القسم في هذا العقد",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.department",
                verbose_name="القسم",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="job_title",
            field=models.ForeignKey(
                blank=True,
                help_text="الوظيفة في هذا العقد",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hr.jobtitle",
                verbose_name="المسمى الوظيفي",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="field_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="اسم الحقل"
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="is_automatic",
            field=models.BooleanField(default=False, verbose_name="تلقائي"),
        ),
        migrations.AddField(
            model_name="employee",
            name="biometric_user_id",
            field=models.CharField(
                blank=True,
                help_text="رقم تعريف الموظف في نظام البصمة",
                max_length=50,
                null=True,
                verbose_name="رقم الموظف في جهاز البصمة",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="increase_category",
            field=models.ForeignKey(
                blank=True,
                help_text="فئة الموظف لتحديد سياسة الزيادة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.employeeincreasecategory",
                verbose_name="فئة الزيادة",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.shift",
                verbose_name="الوردية",
            ),
        ),
        migrations.AddField(
            model_name="plannedincrease",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_increases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="plannedincrease",
            name="justification",
            field=models.TextField(blank=True, verbose_name="المبرر"),
        ),
        migrations.AddField(
            model_name="plannedincrease",
            name="performance_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="تقييم الأداء",
            ),
        ),
        migrations.AddField(
            model_name="salaryincreasetemplate",
            name="max_increase_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="الحد الأقصى لمبلغ الزيادة",
            ),
        ),
        migrations.AddField(
            model_name="salaryincreasetemplate",
            name="max_increase_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="الحد الأقصى لنسبة الزيادة (%)",
            ),
        ),
        migrations.AddField(
            model_name="salaryincreasetemplate",
            name="min_performance_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="مثال: 3.5 من 5",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="الحد الأدنى لتقييم الأداء",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="allocated_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="المبلغ المخصص فعلياً للموظفين",
                max_digits=12,
                verbose_name="المبلغ المخصص",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_increase_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="اعتمد بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_increase_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="effective_date",
            field=models.DateField(
                help_text="التاريخ المخطط لتطبيق الزيادات", verbose_name="تاريخ السريان"
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="name",
            field=models.CharField(
                help_text="مثال: خطة الزيادات 2025",
                max_length=200,
                verbose_name="اسم الخطة",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annual_plans",
                to="hr.salaryincreasetemplate",
                verbose_name="القالب",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="total_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="الميزانية المخصصة للزيادات",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="إجمالي الميزانية",
            ),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="annualincreaseplan",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2020),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="السنة",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("active", "ساري"),
                    ("suspended", "موقوف"),
                    ("expired", "منتهي"),
                    ("terminated", "منهي"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="contractamendment",
            name="amendment_type",
            field=models.CharField(
                choices=[
                    ("salary_increase", "زيادة راتب"),
                    ("salary_deduction", "استقطاع"),
                    ("position_change", "تغيير منصب"),
                    ("extension", "تمديد"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع التعديل",
            ),
        ),
        migrations.AlterField(
            model_name="employeeincreasecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="employeeincreasecategory",
            name="default_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_categories",
                to="hr.salaryincreasetemplate",
                verbose_name="القالب الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="employeeincreasecategory",
            name="name",
            field=models.CharField(
                help_text="مثال: موظفين إداريين، مديرين، فنيين",
                max_length=100,
                verbose_name="اسم الفئة",
            ),
        ),
        migrations.AlterField(
            model_name="employeeincreasecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="plannedincrease",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_increases",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AlterField(
            model_name="plannedincrease",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="plannedincrease",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_increases",
                to="hr.employee",
                verbose_name="الموظف",
            ),
        ),
        migrations.AlterField(
            model_name="plannedincrease",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_increases",
                to="hr.annualincreaseplan",
                verbose_name="الخطة",
            ),
        ),
        migrations.AlterField(
            model_name="plannedincrease",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="code",
            field=models.CharField(
                help_text="كود فريد للقالب",
                max_length=50,
                unique=True,
                verbose_name="الكود",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_increase_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="default_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="المبلغ الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="default_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="مثال: 10 للزيادة 10%",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="النسبة الافتراضية (%)",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("annual", "سنوي"),
                    ("semi_annual", "نصف سنوي"),
                    ("quarterly", "ربع سنوي"),
                    ("monthly", "شهري"),
                ],
                default="annual",
                max_length=20,
                verbose_name="التكرار",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="increase_type",
            field=models.CharField(
                choices=[
                    ("percentage", "نسبة مئوية"),
                    ("fixed", "مبلغ ثابت"),
                    ("performance", "حسب الأداء"),
                    ("inflation", "حسب التضخم"),
                    ("seniority", "حسب الأقدمية"),
                ],
                max_length=20,
                verbose_name="نوع الزيادة",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="القالب الافتراضي للخطط الجديدة",
                verbose_name="افتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="min_service_months",
            field=models.IntegerField(
                default=0,
                help_text="مثال: 12 لتطبيق الزيادة بعد سنة",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="الحد الأدنى لأشهر الخدمة",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="name",
            field=models.CharField(
                help_text="مثال: زيادة سنوية 10%",
                max_length=200,
                verbose_name="اسم القالب",
            ),
        ),
        migrations.AlterField(
            model_name="salaryincreasetemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddIndex(
            model_name="annualincreaseplan",
            index=models.Index(
                fields=["year", "status"], name="hr_annualin_year_413f4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annualincreaseplan",
            index=models.Index(
                fields=["effective_date"], name="hr_annualin_effecti_70532b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricsynclog",
            index=models.Index(
                fields=["device", "-started_at"], name="hr_biometri_device__8ff79c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricsynclog",
            index=models.Index(
                fields=["started_at"], name="hr_biometri_started_46978e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeincreasecategory",
            index=models.Index(fields=["code"], name="hr_employee_code_2beeaf_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeincreasecategory",
            index=models.Index(
                fields=["is_active"], name="hr_employee_is_acti_c0723c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedincrease",
            index=models.Index(
                fields=["plan", "status"], name="hr_plannedi_plan_id_ccc123_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedincrease",
            index=models.Index(
                fields=["employee", "status"], name="hr_plannedi_employe_9b160e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryincreasetemplate",
            index=models.Index(fields=["code"], name="hr_salaryin_code_cb3789_idx"),
        ),
        migrations.AddIndex(
            model_name="salaryincreasetemplate",
            index=models.Index(
                fields=["is_active", "is_default"],
                name="hr_salaryin_is_acti_c5e393_idx",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="amendment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="increase_schedule",
                to="hr.contractamendment",
                verbose_name="التعديل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_increases",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractincrease",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_increases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="hr.contract",
                verbose_name="العقد",
            ),
        ),
        migrations.AddField(
            model_name="contractdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="رفع بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="plannedincrease",
            name="contract_increase",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planned_increase",
                to="hr.contractincrease",
                verbose_name="الزيادة المطبقة",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractincrease",
            unique_together={("contract", "increase_number")},
        ),
    ]
