# Generated by Django 4.2.23 on 2025-11-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_add_biometric_user_id_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='increase_category',
        ),
        migrations.DeleteModel(
            name='EmployeeIncreaseCategory',
        ),
    ]
