# Generated by Django 4.2.23 on 2025-11-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_remove_employee_increase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='annual_increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مثال: 10 تعني 10% سنوياً', max_digits=5, null=True, verbose_name='نسبة الزيادة السنوية (%)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='has_annual_increase',
            field=models.BooleanField(default=False, verbose_name='يستحق زيادة سنوية'),
        ),
        migrations.AddField(
            model_name='contract',
            name='increase_frequency',
            field=models.CharField(choices=[('annual', 'سنوي'), ('semi_annual', 'نصف سنوي'), ('quarterly', 'ربع سنوي'), ('monthly', 'شهري')], default='annual', max_length=20, verbose_name='تكرار الزيادة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='increase_start_reference',
            field=models.CharField(choices=[('contract_date', 'تاريخ العقد'), ('january', 'يناير'), ('july', 'يوليو')], default='contract_date', max_length=20, verbose_name='بداية احتساب الزيادة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_increase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الزيادة القادمة'),
        ),
    ]
