blank_issues_enabled: false
contact_links:
  - name: ๐ ุงูุชูุซูู ูุงูุฏููู
    url: https://github.com/mwheba-erp/mwheba_erp/wiki
    about: ุฑุงุฌุน ุงููุซุงุฆู ุงูุดุงููุฉ ูุงูุฃุฏูุฉ ุงูุชูุตูููุฉ
  - name: ๐ฌ ูุฌุชูุน ุงููุทูุฑูู
    url: https://github.com/mwheba-erp/mwheba_erp/discussions
    about: ุงูุถู ููููุงุดุงุช ูุน ุงููุทูุฑูู ูุงููุณุชุฎุฏููู ุงูุขุฎุฑูู
  - name: ๐ ุงูุฅุจูุงุบ ุนู ุซุบุฑุฉ ุฃูููุฉ
    url: https://github.com/mwheba-erp/mwheba_erp/security/advisories/new
    about: ุฃุจูุบ ุนู ุงูุซุบุฑุงุช ุงูุฃูููุฉ ุจุดูู ุฎุงุต ูุขูู
  - name: ๐ง ุงูุฏุนู ุงูุชุฌุงุฑู
    url: mailto:support@mwheba-erp.com
    about: ููุฏุนู ุงูุชุฌุงุฑู ูุงูุงุณุชุดุงุฑุงุช ุงููุชุฎุตุตุฉ
