# Generated by Django 4.2.7 on 2025-10-22 13:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoatingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم نوع التغطية"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع التغطية",
                "verbose_name_plural": "أنواع التغطية",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CostCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("material", "تكلفة المواد"),
                            ("printing", "تكلفة الطباعة"),
                            ("finishing", "تكلفة التشطيبات"),
                            ("design", "تكلفة التصميم"),
                            ("total", "التكلفة الإجمالية"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الأساسية",
                    ),
                ),
                (
                    "additional_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكاليف الإضافية",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "calculation_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="تفاصيل مفصلة عن كيفية الحساب",
                        verbose_name="تفاصيل الحساب",
                    ),
                ),
                (
                    "calculation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الحساب"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا هو الحساب الأحدث لهذا النوع",
                        verbose_name="الحساب الحالي",
                    ),
                ),
                (
                    "parameters_used",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="المعايير والقيم المستخدمة في الحساب",
                        verbose_name="المعايير المستخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب التكلفة",
                "verbose_name_plural": "حسابات التكلفة",
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="DigitalMachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم نوع الماكينة"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="رمز الماكينة",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الشركة المصنعة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "max_sheet_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="أقصى مقاس فرخ"
                    ),
                ),
                (
                    "print_quality",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="جودة الطباعة"
                    ),
                ),
                (
                    "is_color",
                    models.BooleanField(default=True, verbose_name="طباعة ملونة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع ماكينة ديجيتال",
                "verbose_name_plural": "أنواع ماكينات الديجيتال",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DigitalSheetSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقاس")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="رمز المقاس",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="العرض (سم)"
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="الطول (سم)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "is_custom_size",
                    models.BooleanField(default=False, verbose_name="مقاس مخصص"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاس ماكينة ديجيتال",
                "verbose_name_plural": "مقاسات ماكينات الديجيتال",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinishingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم نوع التشطيب"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع التشطيب",
                "verbose_name_plural": "أنواع التشطيب",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OffsetMachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم نوع الماكينة"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="رمز الماكينة",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الشركة المصنعة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "max_sheet_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="أقصى مقاس فرخ"
                    ),
                ),
                (
                    "colors_capacity",
                    models.PositiveIntegerField(default=4, verbose_name="عدد الألوان"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع ماكينة أوفست",
                "verbose_name_plural": "أنواع ماكينات الأوفست",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OffsetSheetSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقاس")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="رمز المقاس",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="العرض (سم)"
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="الطول (سم)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "is_custom_size",
                    models.BooleanField(default=False, verbose_name="مقاس مخصص"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاس ماكينة أوفست",
                "verbose_name_plural": "مقاسات ماكينات الأوفست",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "material_type",
                    models.CharField(
                        help_text="ورق، حبر، زنكات، إلخ",
                        max_length=50,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="اسم المادة"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="الكمية المطلوبة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("piece", "بالقطعة"), ("thousand", "بالألف")],
                        max_length=20,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الوحدة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                (
                    "waste_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="نسبة الهالك (%)",
                    ),
                ),
                (
                    "supplier_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="معلومات المورد والأسعار",
                        verbose_name="معلومات المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "مادة الطلب",
                "verbose_name_plural": "مواد الطلبات",
                "ordering": ["material_type", "material_name"],
            },
        ),
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "service_category",
                    models.CharField(
                        choices=[
                            ("printing", "طباعة"),
                            ("finishing", "تشطيبات"),
                            ("binding", "تجليد"),
                            ("cutting", "تقطيع"),
                            ("folding", "طي"),
                            ("lamination", "تقفيل"),
                            ("coating", "تغطية"),
                            ("embossing", "بصمة"),
                            ("perforation", "ثقب"),
                            ("numbering", "ترقيم"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="فئة الخدمة",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="اسم الخدمة"),
                ),
                (
                    "service_description",
                    models.TextField(blank=True, null=True, verbose_name="وصف الخدمة"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("piece", "بالقطعة"), ("thousand", "بالألف")],
                        max_length=20,
                        verbose_name="الوحدة",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر الوحدة",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة الإجمالية",
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الإعداد",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="خدمة اختيارية"),
                ),
                (
                    "supplier_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="معلومات المورد والأسعار",
                        verbose_name="معلومات المورد",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="وقت التنفيذ (ساعات)"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمة الطلب",
                "verbose_name_plural": "خدمات الطلبات",
                "ordering": ["service_category", "service_name"],
            },
        ),
        migrations.CreateModel(
            name="OrderSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة المواد",
                    ),
                ),
                (
                    "printing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الطباعة",
                    ),
                ),
                (
                    "finishing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة التشطيبات",
                    ),
                ),
                (
                    "design_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة التصميم",
                    ),
                ),
                (
                    "other_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكاليف أخرى",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="قيمة الخصم",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="قيمة الضريبة",
                    ),
                ),
                (
                    "rush_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="رسوم الاستعجال",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "profit_margin_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="هامش الربح (%)",
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="قيمة الربح",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر النهائي",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="آخر حساب"),
                ),
                (
                    "calculation_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الحساب"
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص الطلب",
                "verbose_name_plural": "ملخصات الطلبات",
            },
        ),
        migrations.CreateModel(
            name="PaperOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المنشأ")),
                (
                    "code",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="رمز البلد"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "منشأ الورق",
                "verbose_name_plural": "مناشئ الورق",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaperSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقاس")),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="العرض (سم)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="الطول (سم)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "مقاس الورق",
                "verbose_name_plural": "مقاسات الورق",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaperSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "paper_type_name",
                    models.CharField(max_length=100, verbose_name="نوع الورق"),
                ),
                (
                    "paper_weight",
                    models.PositiveIntegerField(verbose_name="وزن الورق (جرام)"),
                ),
                (
                    "paper_size_name",
                    models.CharField(max_length=50, verbose_name="مقاس الورق"),
                ),
                (
                    "sheet_width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="عرض الفرخ (سم)"
                    ),
                ),
                (
                    "sheet_height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="طول الفرخ (سم)"
                    ),
                ),
                (
                    "sheets_needed",
                    models.PositiveIntegerField(verbose_name="عدد الفروخ المطلوبة"),
                ),
                (
                    "montage_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="عدد القطع في الفرخ"
                    ),
                ),
                (
                    "piece_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-- اختر مقاس القطع --"),
                            ("A4", "A4 (21×29.7 سم)"),
                            ("A5", "A5 (14.8×21 سم)"),
                            ("A6", "A6 (10.5×14.8 سم)"),
                            ("10x15", "10×15 سم"),
                            ("15x20", "15×20 سم"),
                            ("20x30", "20×30 سم"),
                            ("custom", "مقاس مخصص"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="مقاس القطع",
                    ),
                ),
                (
                    "sheet_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الفرخ",
                    ),
                ),
                (
                    "total_paper_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="إجمالي تكلفة الورق",
                    ),
                ),
            ],
            options={
                "verbose_name": "مواصفات الورق",
                "verbose_name_plural": "مواصفات الأوراق",
            },
        ),
        migrations.CreateModel(
            name="PaperType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم نوع الورق"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "نوع الورق",
                "verbose_name_plural": "أنواع الورق",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaperWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الوزن")),
                (
                    "gsm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(50)],
                        verbose_name="الوزن (جرام)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "وزن الورق",
                "verbose_name_plural": "أوزان الورق",
                "ordering": ["gsm"],
            },
        ),
        migrations.CreateModel(
            name="PieceSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم المقاس")),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="العرض (سم)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="الطول (سم)"
                    ),
                ),
                (
                    "pieces_per_sheet",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="عدد القطع التي يمكن قطعها من فرخ واحد من مقاس الورق الأساسي",
                        null=True,
                        verbose_name="عدد القطع في الفرخ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاس القطع",
                "verbose_name_plural": "مقاسات القطع",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlateSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم مقاس الزنك"),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="العرض (سم)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="الطول (سم)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاس الزنك",
                "verbose_name_plural": "مقاسات الزنكات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الاتجاه")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "اتجاه الطباعة",
                "verbose_name_plural": "اتجاهات الطباعة",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="رقم فريد للطلب",
                        max_length=50,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان الطلب")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف الطلب"),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("book", "كتاب"),
                            ("magazine", "مجلة"),
                            ("brochure", "بروشور"),
                            ("flyer", "فلاير"),
                            ("poster", "بوستر"),
                            ("business_card", "كارت شخصي"),
                            ("envelope", "مظروف"),
                            ("letterhead", "ورق رسمي"),
                            ("invoice", "فاتورة"),
                            ("catalog", "كتالوج"),
                            ("calendar", "تقويم"),
                            ("notebook", "دفتر"),
                            ("folder", "ملف"),
                            ("box", "علبة"),
                            ("label", "لصقة"),
                            ("sticker", "ستيكر"),
                            ("banner", "بانر"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطلب",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "قيد المراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="حالة الطلب",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "pages_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الصفحات",
                    ),
                ),
                (
                    "copies_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد النسخ",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="العرض (سم)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="الارتفاع (سم)",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="التكلفة المقدرة",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر النهائي",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر البيع",
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="هامش الربح (%)",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التسليم المطلوب"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "press",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المطبعة"
                    ),
                ),
                (
                    "colors_front",
                    models.PositiveIntegerField(default=1, verbose_name="ألوان الوجه"),
                ),
                (
                    "colors_back",
                    models.PositiveIntegerField(default=0, verbose_name="ألوان الظهر"),
                ),
                (
                    "print_sides",
                    models.CharField(
                        choices=[("single", "وجه واحد"), ("double", "وجهين")],
                        default="single",
                        max_length=20,
                        verbose_name="جوانب الطباعة",
                    ),
                ),
                (
                    "coating_service",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="خدمة التغطية",
                    ),
                ),
                (
                    "has_internal_content",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على محتوى داخلي"
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة المواد",
                    ),
                ),
                (
                    "printing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الطباعة",
                    ),
                ),
                (
                    "finishing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة التشطيب",
                    ),
                ),
                (
                    "extra_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة إضافية",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "is_rush_order",
                    models.BooleanField(default=False, verbose_name="طلب عاجل"),
                ),
                (
                    "rush_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="رسوم الاستعجال",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_printing_orders",
                        to="client.customer",
                        verbose_name="العميل (client)",
                    ),
                ),
                (
                    "coating_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_orders",
                        to="printing_pricing.coatingtype",
                        verbose_name="نوع التغطية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_orders",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "paper_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_orders",
                        to="printing_pricing.papertype",
                        verbose_name="نوع الورق",
                    ),
                ),
                (
                    "print_direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_orders",
                        to="printing_pricing.printdirection",
                        verbose_name="اتجاه الطباعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تسعير",
                "verbose_name_plural": "طلبات التسعير",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintSide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الجانب")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "جانب الطباعة",
                "verbose_name_plural": "جوانب الطباعة",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: A4، A5، مقاس مخصص",
                        max_length=100,
                        verbose_name="اسم المقاس",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="عرض المنتج بالسنتيمتر",
                        max_digits=8,
                        verbose_name="العرض (سم)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="طول المنتج بالسنتيمتر",
                        max_digits=8,
                        verbose_name="الطول (سم)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف إضافي للمقاس",
                        null=True,
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل هذا المقاس نشط ومتاح للاستخدام؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا هو المقاس الافتراضي؟",
                        verbose_name="افتراضي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاس المنتج",
                "verbose_name_plural": "مقاسات المنتجات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: كتاب، مجلة، بروشور، كتالوج",
                        max_length=100,
                        verbose_name="اسم نوع المنتج",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف تفصيلي لنوع المنتج",
                        null=True,
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل نوع المنتج هذا نشط ومتاح للاستخدام؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا هو نوع المنتج الافتراضي؟",
                        verbose_name="افتراضي",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع المنتج",
                "verbose_name_plural": "أنواع المنتجات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VATSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False, verbose_name="مفعل")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="النسبة المئوية",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "effective_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ السريان"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_pricing_vat_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد ضريبة القيمة المضافة",
                "verbose_name_plural": "إعدادات ضريبة القيمة المضافة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="مفتاح الإعداد"
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "category",
                    models.CharField(
                        default="general", max_length=50, verbose_name="الفئة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الإنشاء بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="PrintingSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "printing_type",
                    models.CharField(
                        choices=[
                            ("offset", "أوفست"),
                            ("digital", "رقمية"),
                            ("screen", "سلك سكرين"),
                            ("flexo", "فلكسو"),
                            ("letterpress", "ليتر برس"),
                            ("inkjet", "نفث حبر"),
                            ("laser", "ليزر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الطباعة",
                    ),
                ),
                (
                    "colors_front",
                    models.PositiveIntegerField(
                        default=1, verbose_name="عدد الألوان - الوجه"
                    ),
                ),
                (
                    "colors_back",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الألوان - الظهر"
                    ),
                ),
                (
                    "is_cmyk",
                    models.BooleanField(default=True, verbose_name="طباعة CMYK"),
                ),
                (
                    "has_spot_colors",
                    models.BooleanField(
                        default=False, verbose_name="يحتوي على ألوان خاصة"
                    ),
                ),
                (
                    "spot_colors_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الألوان الخاصة"
                    ),
                ),
                (
                    "resolution_dpi",
                    models.PositiveIntegerField(
                        default=300, verbose_name="دقة الطباعة (DPI)"
                    ),
                ),
                (
                    "print_quality",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                            ("premium", "ممتازة"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="جودة الطباعة",
                    ),
                ),
                (
                    "plates_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الزنكات",
                    ),
                ),
                (
                    "printing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الطباعة",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, null=True, verbose_name="متطلبات خاصة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printing_spec",
                        to="printing_pricing.printingorder",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مواصفات الطباعة",
                "verbose_name_plural": "مواصفات الطباعة",
            },
        ),
        migrations.AddField(
            model_name="printingorder",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="printing_pricing.productsize",
                verbose_name="مقاس المنتج",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="printing_pricing.producttype",
                verbose_name="نوع المنتج",
            ),
        ),
    ]
