# Generated by Django 4.2.23 on 2025-10-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperspecification',
            name='piece_size',
            field=models.CharField(blank=True, choices=[('', '-- اختر مقاس القطع --'), ('A4', 'A4 (21×29.7 سم)'), ('A5', 'A5 (14.8×21 سم)'), ('A6', 'A6 (10.5×14.8 سم)'), ('10x15', '10×15 سم'), ('15x20', '15×20 سم'), ('20x30', '20×30 سم'), ('custom', 'مقاس مخصص')], max_length=50, null=True, verbose_name='مقاس القطع'),
        ),
        migrations.AlterField(
            model_name='ordermaterial',
            name='unit',
            field=models.CharField(choices=[('piece', 'بالقطعة'), ('thousand', 'بالألف')], max_length=20, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='unit',
            field=models.CharField(choices=[('piece', 'بالقطعة'), ('thousand', 'بالألف')], max_length=20, verbose_name='الوحدة'),
        ),
    ]
