# Generated by Django 4.2.7 on 2025-10-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
        ("printing_pricing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="piecesize",
            name="paper_type",
            field=models.ForeignKey(
                blank=True,
                help_text="مقاس الورق الأساسي المناسب لهذا المقاس من القطع",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="piece_sizes",
                to="printing_pricing.papersize",
                verbose_name="مقاس الورق الأساسي",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paperweight",
            unique_together={("gsm",)},
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_spec",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="offsetsheetsize",
            name="machine_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheet_sizes",
                to="printing_pricing.offsetmachinetype",
                verbose_name="نوع الماكينة",
            ),
        ),
        migrations.AddField(
            model_name="digitalsheetsize",
            name="machine_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheet_sizes",
                to="printing_pricing.digitalmachinetype",
                verbose_name="نوع الماكينة",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculations",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["order_number"], name="printing_pr_order_n_e9064b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["customer", "status"], name="printing_pr_custome_a38a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["created_at"], name="printing_pr_created_edad46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["due_date"], name="printing_pr_due_dat_40b47a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderservice",
            index=models.Index(
                fields=["order", "service_category"],
                name="printing_pr_order_i_cd143d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordermaterial",
            index=models.Index(
                fields=["order", "material_type"], name="printing_pr_order_i_aadd8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["order", "calculation_type"],
                name="printing_pr_order_i_d24a07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["calculation_date"], name="printing_pr_calcula_aad908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["is_current"], name="printing_pr_is_curr_8dacab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="costcalculation",
            unique_together={("order", "calculation_type", "is_current")},
        ),
    ]
