# Generated by Django 5.2.17 on 2026-09-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0002_initial"),
        ("financial", "0001_initial"),
        ("printing_pricing", "0001_initial"),
        ("supplier", "0001_initial"),
        ("work_order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coatingtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="coatingtype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="finishingtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="finishingtype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="machinedimension",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="machinedimension",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.CreateModel(
            name="DigitalSheetSize",
            fields=[],
            options={
                "verbose_name": "مقاس ماكينة ديجيتال",
                "verbose_name_plural": "مقاسات ماكينات الديجيتال",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("printing_pricing.machinedimension",),
        ),
        migrations.CreateModel(
            name="OffsetSheetSize",
            fields=[],
            options={
                "verbose_name": "مقاس ماكينة أوفست",
                "verbose_name_plural": "مقاسات ماكينات الأوفست",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("printing_pricing.machinedimension",),
        ),
        migrations.CreateModel(
            name="PlateSize",
            fields=[],
            options={
                "verbose_name": "مقاس الزنك",
                "verbose_name_plural": "مقاسات الزنكات",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("printing_pricing.machinedimension",),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="coating_type",
            field=models.ForeignKey(
                blank=True,
                help_text="الربط بنوع التغطية (سلوفان مط، لميع، كوي)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_services",
                to="printing_pricing.coatingtype",
                verbose_name="نوع التغطية/السلوفان",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="finishing_type",
            field=models.ForeignKey(
                blank=True,
                help_text="الربط بنوع التشطيب (سبوت UV، بصمة، كوفراج)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_services",
                to="printing_pricing.finishingtype",
                verbose_name="نوع التشطيب",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="supplier_service",
            field=models.ForeignKey(
                blank=True,
                help_text="الخدمة المحددة من المورد لهذا البند",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_services",
                to="supplier.supplierservice",
                verbose_name="خدمة المورد",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="packagingtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="packagingtype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="packaging_type",
            field=models.ForeignKey(
                blank=True,
                help_text="الربط بنوع التقفيل والتجليد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_services",
                to="printing_pricing.packagingtype",
                verbose_name="نوع التقفيل/التجليد",
            ),
        ),
        migrations.AddField(
            model_name="paperorigin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperorigin",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="papersize",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="papersize",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="papertype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="papertype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperweight",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="paperweight",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="piecesize",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="piecesize",
            name="paper_type",
            field=models.ForeignKey(
                blank=True,
                help_text="مقاس الورق الأساسي المناسب لهذا المقاس من القطع",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="piece_sizes",
                to="printing_pricing.papersize",
                verbose_name="مقاس الورق الأساسي",
            ),
        ),
        migrations.AddField(
            model_name="piecesize",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingmachine",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingmachine",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="machinedimension",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="ربط مقاس الشيت أو الزنكة بالماكينة التابعة لها",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dimensions",
                to="printing_pricing.printingmachine",
                verbose_name="الماكينة المرتبطة",
            ),
        ),
        migrations.CreateModel(
            name="DigitalMachineType",
            fields=[],
            options={
                "verbose_name": "نوع ماكينة ديجيتال",
                "verbose_name_plural": "أنواع ماكينات الديجيتال",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("printing_pricing.printingmachine",),
        ),
        migrations.CreateModel(
            name="OffsetMachineType",
            fields=[],
            options={
                "verbose_name": "نوع ماكينة أوفست",
                "verbose_name_plural": "أنواع ماكينات الأوفست",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("printing_pricing.printingmachine",),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printing_orders",
                to="customer.customer",
                verbose_name="العميل المسجل",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printing_sales_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_specs",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="ordersummary",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="ordermaterial",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="costcalculation",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculations",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="printing_pricing.productsize",
                verbose_name="مقاس المطبوع",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشأ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="product_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="printing_pricing.producttype",
                verbose_name="نوع المطبوع",
            ),
        ),
        migrations.AddIndex(
            model_name="orderservice",
            index=models.Index(
                fields=["order", "service_category"],
                name="printing_pr_order_i_cd143d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ordermaterial",
            index=models.Index(
                fields=["order", "material_type"], name="printing_pr_order_i_aadd8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["order", "calculation_type"],
                name="printing_pr_order_i_d24a07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["calculation_date"], name="printing_pr_calcula_aad908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcalculation",
            index=models.Index(
                fields=["is_current"], name="printing_pr_is_curr_8dacab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costcalculation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("order", "calculation_type"),
                name="unique_current_calculation_per_type",
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["order_number"], name="printing_pr_order_n_e9064b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["customer", "status"], name="printing_pr_custome_a38a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["created_at"], name="printing_pr_created_edad46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printingorder",
            index=models.Index(
                fields=["due_date"], name="printing_pr_due_dat_40b47a_idx"
            ),
        ),
    ]
