# Generated by Django 5.2.17 on 2026-09-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_pricing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingorder',
            options={'ordering': ['-created_at'], 'permissions': [('view_cost_breakdown', 'عرض تفاصيل تكلفة الخامات'), ('view_profit_margins', 'عرض هوامش الربح الصافي للطلبات'), ('view_all_orders', 'عرض طلبات تسعير كافة المناديب'), ('override_pricing_rules', 'تجاوز معادلات التسعير التلقائية'), ('manage_pricing_settings', 'إدارة إعدادات ومقاسات ومعدلات التسعير')], 'verbose_name': 'طلب تسعير مطبوعات', 'verbose_name_plural': 'طلبات تسعير المطبوعات'},
        ),
    ]
