# Generated by Django 4.2.26 on 2026-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printingorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_cost_breakdown", "Can view printing order cost breakdown"),
                    ("view_profit_margins", "Can view printing profit margins"),
                    ("view_all_orders", "Can view all printing pricing orders"),
                    ("override_pricing_rules", "Can override pricing rules"),
                    ("manage_pricing_settings", "Can manage pricing master settings"),
                ],
                "verbose_name": "طلب تسعير",
                "verbose_name_plural": "طلبات التسعير",
            },
        ),
    ]
