# Generated by Django 4.2.26 on 2026-09-03 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_initial"),
        ("printing_pricing", "0002_seed_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="order_date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="تاريخ استلام وتسجيل طلب التسعير الفعلي",
                verbose_name="تاريخ الطلب",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="اسم العميل للتسعيرات السريعة دون الحاجة لتسجيله في الدليل",
                max_length=200,
                null=True,
                verbose_name="اسم العميل",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printing_orders",
                to="customer.customer",
                verbose_name="العميل المسجل",
            ),
        ),
    ]
