# Generated by Django (Consolidated in 0001/0002_initial)

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0002_initial"),
    ]

    operations = []

