# Generated by Django 4.2.26 on 2026-08-31 21:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0002_initial"),
        ("work_order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("printing_pricing", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="costcalculation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="cumulative_waste_sheets",
            field=models.PositiveIntegerField(
                default=0, verbose_name="إجمالي أفرخ الهالك التراكمي"
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="delivery_address_snapshot",
            field=models.TextField(
                blank=True, null=True, verbose_name="لقطة عنوان وهاتف التسليم"
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="design_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="أتعاب التصميم",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="design_service_type",
            field=models.CharField(
                choices=[
                    ("CLIENT_READY", "تصميم جاهز للطباعة من العميل"),
                    ("PREPRESS_EDIT", "تعديل فني ومونتاج وفصل ألوان"),
                    ("NEW_CONCEPT", "تصميم إبداعي جديد بالكامل"),
                ],
                default="CLIENT_READY",
                max_length=20,
                verbose_name="خدمة التصميم",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=18,
                verbose_name="سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="sales_commission_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="مبلغ عمولة المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="sales_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="نسبة عمولة المبيعات %",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printing_sales_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printing_orders",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="costcalculation",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("material", "تكلفة المواد"),
                    ("printing", "تكلفة الطباعة"),
                    ("finishing", "تكلفة خدمات الطباعة"),
                    ("design", "تكلفة التصميم"),
                    ("installation", "تكلفة التركيبات والمعاينة"),
                    ("logistics", "تكلفة النقل والمشاوير"),
                    ("total", "التكلفة الإجمالية"),
                ],
                max_length=20,
                verbose_name="نوع الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="paperspecification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_specs",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="paperspecification",
            name="sheets_needed",
            field=models.PositiveIntegerField(verbose_name="عدد الأفرخ المطلوبة"),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("book", "كتاب"),
                    ("magazine", "مجلة"),
                    ("brochure", "بروشور"),
                    ("flyer", "فلاير"),
                    ("poster", "بوستر"),
                    ("business_card", "كارت شخصي"),
                    ("envelope", "مظروف"),
                    ("letterhead", "ورق رسمي"),
                    ("invoice", "فاتورة"),
                    ("catalog", "كتالوج"),
                    ("calendar", "تقويم"),
                    ("notebook", "دفتر"),
                    ("folder", "ملف"),
                    ("box", "علبة"),
                    ("label", "لصقة"),
                    ("sticker", "ستيكر"),
                    ("banner", "بانر"),
                    ("rollup", "رول اب"),
                    ("signage", "يافطة / واجهة"),
                    ("giveaways", "هدايا دعائية"),
                    ("uniform", "يونيفورم / ملابس"),
                    ("trophy", "دروع وتكريمات"),
                    ("booth", "تجهيز معارض"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="printingspecification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printing_specs",
                to="printing_pricing.printingorder",
                verbose_name="الطلب",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcalculation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("order", "calculation_type"),
                name="unique_current_calculation_per_type",
            ),
        ),
    ]
