# Generated by Django 4.2.23 on 2025-10-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_pricing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع التقفيل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع التقفيل',
                'verbose_name_plural': 'أنواع التقفيل',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='finishingtype',
            options={'ordering': ['name'], 'verbose_name': 'نوع خدمة الطباعة', 'verbose_name_plural': 'أنواع خدمات الطباعة'},
        ),
        migrations.AlterField(
            model_name='finishingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم نوع خدمة الطباعة'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service_category',
            field=models.CharField(choices=[('printing', 'طباعة'), ('finishing', 'خدمات الطباعة'), ('packaging', 'خدمات التقفيل'), ('coating', 'تغطية'), ('other', 'أخرى')], max_length=50, verbose_name='فئة الخدمة'),
        ),
    ]
