# Generated by Django 4.2.26 on 2026-09-03 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0003_printingorder_order_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printingorder",
            name="delivery_address_snapshot",
        ),
    ]
