# Generated by Django 4.2.26 on 2026-09-01 00:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_order", "0001_initial"),
        ("supplier", "0002_initial"),
        ("printing_pricing", "0003_upgrade_specs_to_multi_part"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofSignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="رمز التحقق الآمن",
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="printing_proofs/%Y/%m/",
                        verbose_name="ملف البروفة الرقمية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "بانتظار مراجعة العميل"),
                            ("APPROVED", "معتمد من العميل"),
                            ("REJECTED", "مرفوض مع ملاحظات"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="حالة الاعتماد",
                    ),
                ),
                (
                    "client_feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات العميل"
                    ),
                ),
                (
                    "approved_by_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم الشخص المعتمد",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP للعميل"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_signoff",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعتماد بروفة رقمية",
                "verbose_name_plural": "اعتمادات البروفات الرقمية",
            },
        ),
        migrations.CreateModel(
            name="PriceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل المعدل"),
                ),
                (
                    "old_value",
                    models.CharField(max_length=255, verbose_name="القيمة السابقة"),
                ),
                (
                    "new_value",
                    models.CharField(max_length=255, verbose_name="القيمة الجديدة"),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, null=True, verbose_name="سبب التعديل"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المنفذ للتعديل",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_audit_logs",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق السعر",
                "verbose_name_plural": "سجلات تدقيق الأسعار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderVendorAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="مبلغ العربون / الدفعة",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="CASH", max_length=50, verbose_name="طريقة الدفع"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم الإيصال / السند",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "is_settled",
                    models.BooleanField(
                        default=False, verbose_name="تمت التسوية مع الفاتورة"
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التسوية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_advances",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printing_advances",
                        to="supplier.supplier",
                        verbose_name="المورد / الورشة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_advances",
                        to="work_order.workorder",
                        verbose_name="أمر الشغل المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "عربون مورد / ورشة",
                "verbose_name_plural": "عرابين الموردين والورش",
                "ordering": ["-created_at"],
            },
        ),
    ]
