# Generated by Django 4.2.26 on 2026-09-03 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0004_remove_printingorder_delivery_address_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printingorder",
            name="is_rush_order",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="rush_fee",
        ),
    ]
