# Generated by Django 4.2.26 on 2026-09-01 00:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supplier", "0002_initial"),
        ("customer", "0003_initial"),
        ("work_order", "0001_initial"),
        ("printing_pricing", "0004_phase3_advances_audit_proof"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "stage_name",
                    models.CharField(max_length=100, verbose_name="المرحلة / المحطة"),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم السائق / المندوب",
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="هاتف السائق"
                    ),
                ),
                (
                    "sheets_sent",
                    models.PositiveIntegerField(
                        verbose_name="عدد الأفرخ / القطع المسلمة"
                    ),
                ),
                (
                    "sheets_received",
                    models.PositiveIntegerField(
                        verbose_name="عدد الأفرخ / القطع المستلمة"
                    ),
                ),
                (
                    "waste_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الهالك / التالف"
                    ),
                ),
                (
                    "handoff_date",
                    models.DateTimeField(verbose_name="تاريخ ووقت التسليم"),
                ),
                (
                    "received_by_signature",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم وتوقيع المستلم",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات التسليم"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "from_workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoffs_sent",
                        to="supplier.supplier",
                        verbose_name="من ورشة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff_relays",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "to_workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handoffs_received",
                        to="supplier.supplier",
                        verbose_name="إلى ورشة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printing_handoffs",
                        to="work_order.workorder",
                        verbose_name="أمر الشغل",
                    ),
                ),
            ],
            options={
                "verbose_name": "محضر تسليم وتسلم ورشة",
                "verbose_name_plural": "محاضر التسليم والتسلم بين الورش",
                "ordering": ["-handoff_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplementalRemake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "remake_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم أمر التعويض"
                    ),
                ),
                (
                    "defective_quantity",
                    models.PositiveIntegerField(verbose_name="الكمية المعيبة المرتجعة"),
                ),
                (
                    "fault_allocation",
                    models.CharField(
                        choices=[
                            ("VENDOR_FAULT", "خطأ مورد / ورشة تشغيل"),
                            ("AGENCY_FAULT", "خطأ داخلي بالوكالة"),
                            ("CLIENT_FAULT", "تعديل أو خطأ من العميل"),
                        ],
                        default="VENDOR_FAULT",
                        max_length=20,
                        verbose_name="الطرف المسؤول عن العيب",
                    ),
                ),
                (
                    "estimated_copq",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="تكلفة الهادر الغارق (COPQ)",
                    ),
                ),
                ("reason", models.TextField(verbose_name="سبب العيب والمطالبة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الدراسة والموافقة"),
                            ("IN_PROGRESS", "قيد إعادة التشغيل بالورش"),
                            ("COMPLETED", "تمت إعادة التشغيل والتسليم"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="حالة أمر التعويض",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remakes",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير الأصلي",
                    ),
                ),
                (
                    "responsible_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributed_remakes",
                        to="supplier.supplier",
                        verbose_name="الورشة / المورد المتسبب",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر إعادة تشغيل تكميلي",
                "verbose_name_plural": "أوامر إعادة التشغيل التكميلية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QCSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "inspector_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="اسم مسؤول فحص الجودة",
                    ),
                ),
                ("inspected_at", models.DateTimeField(verbose_name="تاريخ ووقت الفحص")),
                (
                    "bleed_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="فحص خلوص ومسافة الخروج (Bleed 3mm) سليم",
                    ),
                ),
                (
                    "barcode_scannable",
                    models.BooleanField(
                        default=False,
                        verbose_name="فحص قراءة الباركود والـ QR بالماسح الضوئي سليم",
                    ),
                ),
                (
                    "color_registration_passed",
                    models.BooleanField(
                        default=False,
                        verbose_name="فحص تطابق ألوان الطباعة والأوفست سليم",
                    ),
                ),
                (
                    "physical_swatch_matched",
                    models.BooleanField(
                        default=False,
                        verbose_name="فحص مطابقة عينة الألوان المادية المرفقة",
                    ),
                ),
                (
                    "lamination_adhesion_passed",
                    models.BooleanField(
                        default=False, verbose_name="فحص ثبات وقوة التصاق السلوفان سليم"
                    ),
                ),
                (
                    "ncr_sequence_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="فحص تسلسل وترتيب أرقام الفواتير NCR سليم",
                    ),
                ),
                (
                    "sample_vault_archived",
                    models.BooleanField(
                        default=False,
                        verbose_name="تم تحريز 5-10 عينات في خزانة الجودة لمدة 90 يوماً",
                    ),
                ),
                (
                    "sample_vault_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم حرز خزانة العينات",
                    ),
                ),
                (
                    "net_quantity_approved",
                    models.PositiveIntegerField(
                        verbose_name="الكمية الصافية المعتمدة للتسليم"
                    ),
                ),
                (
                    "defect_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد التوالف والمرفوضات"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "مطابق ومعتمد 100%"),
                            ("CONDITIONAL_PASS", "قبول مشروط بتسامح مقبول"),
                            ("REJECTED", "مرفوض - توالف وإعادة تشغيل"),
                        ],
                        default="PASSED",
                        max_length=20,
                        verbose_name="قرار الجودة النهائي",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات تقرير الجودة"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_signoff",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير فحص جودة QC",
                "verbose_name_plural": "تقارير فحص الجودة QC",
            },
        ),
        migrations.CreateModel(
            name="DieMouldCustody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="كود الفورمة / الكليشيه",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="اسم وتوصيف الفورمة"),
                ),
                (
                    "mould_type",
                    models.CharField(
                        choices=[
                            ("DIE_CUT", "فورمة تكسير وريجة"),
                            ("FOIL_STAMP", "كليشيه بصمة حراري"),
                            ("EMBOSSING", "كليشيه كوفراج بارز"),
                            ("SPOT_UV", "شابلونة سبوت يوفي"),
                        ],
                        default="DIE_CUT",
                        max_length=20,
                        verbose_name="نوع الأداة",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="موقع التخزين والرف",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الأبعاد والمقاس",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي عدد الضربات والسحبات"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "صالحة وجاهزة للتشغيل"),
                            ("MAINTENANCE", "تحتاج صيانة / تغيير حشايا"),
                            ("ARCHIVED", "مؤرشفة في مخزن الوكالة"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة الفنية",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات فنية"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "current_workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_moulds",
                        to="supplier.supplier",
                        verbose_name="الورشة الحاضنة للفورمة حالياً",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_moulds",
                        to="customer.customer",
                        verbose_name="العميل المالك (إن وجد)",
                    ),
                ),
                (
                    "last_used_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_moulds",
                        to="printing_pricing.printingorder",
                        verbose_name="آخر أمر شغل تم استخدامها فيه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عهدة فورمة / كليشيه",
                "verbose_name_plural": "أرشيف وعهدة الفورمات والكليشيهات",
                "ordering": ["code"],
            },
        ),
    ]
