# Generated by Django 4.2.23 on 2025-10-20 02:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_add_reference_system_fields'),
        ('supplier', '0028_remove_laserservicedetails_design_cost_per_hour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing_pricing', '0005_add_missing_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع التغطية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع التغطية',
                'verbose_name_plural': 'أنواع التغطية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الماكينة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز الماكينة')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='الشركة المصنعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_sheet_size', models.CharField(blank=True, max_length=50, verbose_name='أقصى مقاس فرخ')),
                ('print_quality', models.CharField(blank=True, max_length=50, verbose_name='جودة الطباعة')),
                ('is_color', models.BooleanField(default=True, verbose_name='طباعة ملونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع ماكينة ديجيتال',
                'verbose_name_plural': 'أنواع ماكينات الديجيتال',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع التشطيب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع التشطيب',
                'verbose_name_plural': 'أنواع التشطيب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OffsetMachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الماكينة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز الماكينة')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='الشركة المصنعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('max_sheet_size', models.CharField(blank=True, max_length=50, verbose_name='أقصى مقاس فرخ')),
                ('colors_capacity', models.PositiveIntegerField(default=4, verbose_name='عدد الألوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع ماكينة أوفست',
                'verbose_name_plural': 'أنواع ماكينات الأوفست',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنشأ')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='رمز البلد')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'منشأ الورق',
                'verbose_name_plural': 'مناشئ الورق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقاس')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مقاس الورق',
                'verbose_name_plural': 'مقاسات الورق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نوع الورق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع الورق',
                'verbose_name_plural': 'أنواع الورق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlateSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم مقاس الزنك')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مقاس الزنك',
                'verbose_name_plural': 'مقاسات الزنكات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاتجاه')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'اتجاه الطباعة',
                'verbose_name_plural': 'اتجاهات الطباعة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجانب')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'جانب الطباعة',
                'verbose_name_plural': 'جوانب الطباعة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: A4، A5، مقاس مخصص', max_length=100, verbose_name='اسم المقاس')),
                ('width', models.DecimalField(decimal_places=2, help_text='عرض المنتج بالسنتيمتر', max_digits=8, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(decimal_places=2, help_text='طول المنتج بالسنتيمتر', max_digits=8, verbose_name='الطول (سم)')),
                ('description', models.TextField(blank=True, help_text='وصف إضافي للمقاس', null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, help_text='هل هذا المقاس نشط ومتاح للاستخدام؟', verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, help_text='هل هذا هو المقاس الافتراضي؟', verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مقاس المنتج',
                'verbose_name_plural': 'مقاسات المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: كتاب، مجلة، بروشور، كتالوج', max_length=100, verbose_name='اسم نوع المنتج')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي لنوع المنتج', null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, help_text='هل نوع المنتج هذا نشط ومتاح للاستخدام؟', verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, help_text='هل هذا هو نوع المنتج الافتراضي؟', verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع المنتج',
                'verbose_name_plural': 'أنواع المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='printingorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_printing_orders', to='client.customer', verbose_name='العميل (client)'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='coating_service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='خدمة التغطية'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='colors_back',
            field=models.PositiveIntegerField(default=0, verbose_name='ألوان الظهر'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='colors_front',
            field=models.PositiveIntegerField(default=1, verbose_name='ألوان الوجه'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة إضافية'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='finishing_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة التشطيب'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='has_internal_content',
            field=models.BooleanField(default=False, verbose_name='يحتوي على محتوى داخلي'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة المواد'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='press',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المطبعة'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='print_sides',
            field=models.CharField(choices=[('single', 'وجه واحد'), ('double', 'وجهين')], default='single', max_length=20, verbose_name='جوانب الطباعة'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='printing_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة الطباعة'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر البيع'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='supplier.supplier', verbose_name='المورد'),
        ),
        migrations.CreateModel(
            name='VATSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='مفعل')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='النسبة المئوية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='تاريخ السريان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printing_pricing_vat_settings', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد ضريبة القيمة المضافة',
                'verbose_name_plural': 'إعدادات ضريبة القيمة المضافة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='مفتاح الإعداد')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PieceSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقاس')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('pieces_per_sheet', models.PositiveIntegerField(blank=True, help_text='عدد القطع التي يمكن قطعها من فرخ واحد من مقاس الورق الأساسي', null=True, verbose_name='عدد القطع في الفرخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('paper_type', models.ForeignKey(blank=True, help_text='مقاس الورق الأساسي المناسب لهذا المقاس من القطع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_sizes', to='printing_pricing.papersize', verbose_name='مقاس الورق الأساسي')),
            ],
            options={
                'verbose_name': 'مقاس القطع',
                'verbose_name_plural': 'مقاسات القطع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaperWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوزن')),
                ('gsm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='الوزن (جرام)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وزن الورق',
                'verbose_name_plural': 'أوزان الورق',
                'ordering': ['gsm'],
                'unique_together': {('gsm',)},
            },
        ),
        migrations.CreateModel(
            name='OffsetSheetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقاس')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز المقاس')),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_custom_size', models.BooleanField(default=False, verbose_name='مقاس مخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_sizes', to='printing_pricing.offsetmachinetype', verbose_name='نوع الماكينة')),
            ],
            options={
                'verbose_name': 'مقاس ماكينة أوفست',
                'verbose_name_plural': 'مقاسات ماكينات الأوفست',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSheetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المقاس')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز المقاس')),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='العرض (سم)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (سم)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_custom_size', models.BooleanField(default=False, verbose_name='مقاس مخصص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_sizes', to='printing_pricing.digitalmachinetype', verbose_name='نوع الماكينة')),
            ],
            options={
                'verbose_name': 'مقاس ماكينة ديجيتال',
                'verbose_name_plural': 'مقاسات ماكينات الديجيتال',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='printingorder',
            name='coating_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='printing_pricing.coatingtype', verbose_name='نوع التغطية'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='paper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='printing_pricing.papertype', verbose_name='نوع الورق'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='print_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='printing_pricing.printdirection', verbose_name='اتجاه الطباعة'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='printing_pricing.productsize', verbose_name='مقاس المنتج'),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='printing_orders', to='printing_pricing.producttype', verbose_name='نوع المنتج'),
        ),
    ]
