# Generated by Django 4.2.26 on 2026-09-01 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0002_initial"),
        (
            "printing_pricing",
            "0005_workshophandoff_supplementalremake_qcsignoff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="current_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prepress", "تجهيز الملفات والزنكات CTP"),
                    ("press", "في المطبعة (طباعة أوفست / ديجيتال)"),
                    ("lamination", "في ورشة السلوفان"),
                    ("die_cutting", "في ورشة التكسير / البصمة"),
                    ("binding", "في ورشة التجليد والتقفيل"),
                    ("packing", "في التعبئة والتغليف"),
                    ("ready_for_delivery", "جاهز للتسليم بالمخزن"),
                    ("delivered", "تم التسليم للعميل"),
                ],
                default="prepress",
                max_length=30,
                null=True,
                verbose_name="مرحلة الإنتاج الحالية (الشغل فين؟)",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="current_workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_printing_orders",
                to="supplier.supplier",
                verbose_name="الموقع / الورشة المتواجد بها الشغل حالياً",
            ),
        ),
    ]
