# Generated by Django 4.2.26 on 2026-09-01 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0006_printingorder_current_stage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkshopHandoff",
        ),
    ]
