# Generated by Django 4.2.26 on 2026-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0006_separate_sheet_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperspecification",
            name="machine_cuts",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="عدد قصات الفرخ للماكينة"
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="piece_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="طول القطع (سم)",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="piece_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="عرض القطع (سم)",
            ),
        ),
        migrations.AlterField(
            model_name="orderservice",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("printing", "طباعة"),
                    ("finishing", "خدمات الطباعة"),
                    ("packaging", "خدمات التقفيل"),
                    ("coating", "تغطية"),
                    ("design", "خدمات التصميم"),
                    ("other", "أخرى"),
                ],
                max_length=50,
                verbose_name="فئة الخدمة",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="open_direction",
            field=models.CharField(
                choices=[
                    ("right", "عربي (يمين)"),
                    ("left", "إنجليزي (يسار)"),
                    ("top", "من أعلى"),
                ],
                default="right",
                max_length=20,
                verbose_name="جهة الفتح والتجليد",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="print_orientation",
            field=models.CharField(
                choices=[("portrait", "طولي"), ("landscape", "عرضي")],
                default="portrait",
                max_length=20,
                verbose_name="اتجاه الطباعة",
            ),
        ),
    ]
