# Generated by Django 4.2.26 on 2026-09-01 01:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supplier", "0002_initial"),
        ("printing_pricing", "0007_delete_workshophandoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTransportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "from_location",
                    models.CharField(
                        max_length=200, verbose_name="نقل من (المكان / الورشة السابقة)"
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        max_length=200, verbose_name="نقل إلى (المكان / الورشة التالية)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="أجرة النقل / المشوار",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(verbose_name="تاريخ ووقت النقل"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_logs",
                        to="printing_pricing.printingorder",
                        verbose_name="أمر التسعير",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_tasks",
                        to="supplier.supplier",
                        verbose_name="المكلف بالنقل (السائق / المشوارجي / شركة الشحن)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حركة ونقل الشغل",
                "verbose_name_plural": "سجلات حركة ونقل الشغل",
                "ordering": ["-transfer_date"],
            },
        ),
    ]
