# Generated by Django 4.2.26 on 2026-09-07 20:18

from django.db import migrations, models


def migrate_legacy_paper_specs(apps, schema_editor):
    PaperSpecification = apps.get_model('printing_pricing', 'PaperSpecification')
    PrintingOrder = apps.get_model('printing_pricing', 'PrintingOrder')
    for order in PrintingOrder.objects.all():
        specs = list(PaperSpecification.objects.filter(order=order).order_by('id'))
        if len(specs) > 1:
            for idx, spec in enumerate(specs):
                if idx > 0 or 'داخلي' in (spec.paper_type_name or '') or 'inner' in (spec.paper_type_name or '').lower():
                    spec.is_inner = True
                    spec.save(update_fields=['is_inner'])


def reverse_legacy_paper_specs(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0008_papertype_is_single_sided"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperspecification",
            name="imposition_orientation",
            field=models.CharField(
                choices=[
                    ("auto", "تلقائي (الأفضل هندسياً)"),
                    ("normal", "أفقي (عادي)"),
                    ("rotated", "رأسي (مدور 90°)"),
                ],
                default="auto",
                max_length=20,
                verbose_name="توجيه المونتاج",
            ),
        ),
        migrations.AddField(
            model_name="paperspecification",
            name="is_inner",
            field=models.BooleanField(
                default=False, verbose_name="ورق الصفحات الداخلية"
            ),
        ),
        migrations.RunPython(migrate_legacy_paper_specs, reverse_legacy_paper_specs),
    ]
