# Generated by Django 4.2.23 on 2025-10-20 02:55

from django.db import migrations, models
from decimal import Decimal
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('printing_pricing', '0008_add_sale_price_field'),
    ]

    operations = [
        # إضافة الحقول الأساسية المطلوبة
        migrations.AddField(
            model_name='printingorder',
            name='material_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
                validators=[MinValueValidator(Decimal('0.00'))],
                verbose_name='تكلفة المواد'
            ),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='printing_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
                validators=[MinValueValidator(Decimal('0.00'))],
                verbose_name='تكلفة الطباعة'
            ),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='finishing_cost',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
                validators=[MinValueValidator(Decimal('0.00'))],
                verbose_name='تكلفة التشطيب'
            ),
        ),
    ]
