# Generated by Django 4.2.26 on 2026-09-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0008_ordertransportlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "نوع المطبوع",
                "verbose_name_plural": "أنواع المطبوعات",
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="base_archetype",
            field=models.CharField(
                choices=[
                    ("flyer", "مطبوع مفرود (كروت / فلاير / بروشور)"),
                    ("catalog", "كتالوج ومجلات (داخلي + غلاف)"),
                    ("folder", "مطبوع مع فورمة تكسير وعلب"),
                    ("invoice", "دفاتر فواتير ومكربن NCR"),
                    ("giveaways", "هدايا دعائية ومستلزمات و UV-DTF"),
                ],
                default="flyer",
                help_text="يحدد مسار التشغيل وتفكيك التكاليف والخطوات في شاشة التسعير",
                max_length=20,
                verbose_name="التصنيف التشغيلي للمحرك",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ترتيب الظهور في القوائم المنسدلة (الأصغر يظهر أولاً)",
                verbose_name="الترتيب",
            ),
        ),
        migrations.AlterField(
            model_name="ordermaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("meter", "بالمتر"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="orderservice",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("meter", "بالمتر"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="مثال: مطبوع مفرود، كتالوج، فولدر، دفاتر فواتير",
                max_length=100,
                unique=True,
                verbose_name="اسم نوع المطبوع",
            ),
        ),
    ]
