# Generated by Django 4.2.7 on 2025-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing_pricing", "0009_add_basic_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
    ]
