# Generated by Django 4.2.26 on 2026-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0010_seed_product_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsize",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "مقاس المطبوع",
                "verbose_name_plural": "مقاسات المطبوعات",
            },
        ),
        migrations.AddField(
            model_name="printingorder",
            name="print_orientation",
            field=models.CharField(
                choices=[("portrait", "طولي (رأسي)"), ("landscape", "عرضي (أفقي)")],
                default="portrait",
                max_length=20,
                verbose_name="اتجاه الطباعة",
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ترتيب الظهور في القوائم المنسدلة (الأصغر يظهر أولاً)",
                verbose_name="الترتيب",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                help_text="ارتفاع المنتج بالسنتيمتر",
                max_digits=8,
                verbose_name="الارتفاع (سم)",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="name",
            field=models.CharField(
                help_text="مثال: A4، A5، كارت شخصي",
                max_length=100,
                unique=True,
                verbose_name="اسم المقاس",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="base_archetype",
            field=models.CharField(
                choices=[
                    ("flyer", "مطبوع مفرود (كروت / فلاير)"),
                    ("catalog", "مطبوع مع داخلي (كتالوج / بلوك نوت)"),
                    ("folder", "مطبوع مع فورمة تكسير"),
                    ("invoice", "دفاتر مكربن"),
                    ("giveaways", "هدايا دعائية و UV"),
                ],
                default="flyer",
                help_text="يحدد مسار التشغيل وتفكيك التكاليف والخطوات في شاشة التسعير",
                max_length=20,
                verbose_name="التصنيف التشغيلي للمحرك",
            ),
        ),
    ]
