# Generated by Django 4.2.7 on 2025-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing_pricing", "0010_add_updated_at_to_papertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperorigin",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddField(
            model_name="papersize",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddField(
            model_name="paperweight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
    ]
