# Generated by Django 4.2.26 on 2026-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0012_seed_product_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="is_closed_size",
            field=models.BooleanField(
                default=False, verbose_name="المقاس المدخل مقفول (مطوي)"
            ),
        ),
    ]
