# Generated by Django 4.2.26 on 2026-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0013_printingorder_is_closed_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="open_direction",
            field=models.CharField(
                choices=[
                    ("right", "عربي (يمين)"),
                    ("left", "إنجليزي (يسار)"),
                    ("top", "من أعلى (رأسي)"),
                ],
                default="right",
                max_length=20,
                verbose_name="جهة الفتح والتجليد",
            ),
        ),
    ]
