# Generated by Django 4.2.26 on 2026-09-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0014_printingorder_open_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="cover_printing_type",
            field=models.CharField(
                choices=[
                    ("offset", "أوفست زنكات CTP"),
                    ("digital", "ديجيتال شيتات A3+"),
                    ("digital_banner", "ديجيتال بانر عريض"),
                    ("screen", "سلك سكرين / بصمة مباشرة"),
                    ("none", "بدون طباعة (خامة جاهزة سادة)"),
                ],
                default="offset",
                max_length=20,
                verbose_name="طريقة طباعة الغلاف / المطبوع الرئيسي",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="inner_printing_type",
            field=models.CharField(
                choices=[
                    ("offset", "أوفست ملازم 16 صفحة"),
                    ("digital", "ديجيتال صفحات ونقرات"),
                    ("rotary", "روتاري ويب / أوفست لون واحد"),
                ],
                default="offset",
                max_length=20,
                verbose_name="طريقة طباعة الصفحات الداخلية",
            ),
        ),
    ]
