# Generated by Django 4.2.26 on 2026-09-01 22:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0015_printingorder_cover_printing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printingorder",
            name="banner_sqm_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=10,
                verbose_name="سعر المتر المربع للخامات الكبيرة",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="digital_color_mode",
            field=models.CharField(
                choices=[
                    ("4_0", "وجه واحد ألوان (4/0)"),
                    ("1_0", "وجه واحد أسود (1/0)"),
                    ("4_4", "وجهين ألوان (4/4)"),
                    ("4_1", "وجه ألوان + ظهر أسود (4/1)"),
                    ("1_1", "وجهين أسود (1/1)"),
                ],
                default="4_0",
                max_length=20,
                verbose_name="نمط نقرات الديجيتال",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="has_white_ink",
            field=models.BooleanField(
                default=False, verbose_name="طباعة طبقة حبر أبيض للشفافيات والـ UV"
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="print_sides_mode",
            field=models.CharField(
                choices=[
                    ("single", "وجه واحد"),
                    ("work_turn", "وجهين - طبع وقلب (على نفس الزنكات)"),
                    ("work_sheet", "وجهين - زنكات مستقلة (وش وضهر)"),
                ],
                default="single",
                max_length=20,
                verbose_name="أسلوب وعدد الأوجه",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="spot_color_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="كود / اسم اللون المخصوص (Pantone)",
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="spot_colors_back",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد ألوان بانتون الظهر"
            ),
        ),
        migrations.AddField(
            model_name="printingorder",
            name="spot_colors_front",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد ألوان بانتون الوجه"
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="cover_printing_type",
            field=models.CharField(
                choices=[
                    ("offset", "أوفست"),
                    ("digital", "ديجيتال"),
                    ("digital_banner", "خامات كبيرة"),
                    ("screen", "سلك سكرين"),
                    ("none", "بدون طباعة"),
                ],
                default="offset",
                max_length=20,
                verbose_name="طريقة طباعة الغلاف / المطبوع الرئيسي",
            ),
        ),
    ]
