# Generated by Django 4.2.26 on 2026-09-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0016_printingorder_banner_sqm_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("meter", "بالمتر الطولي"),
                    ("sqm", "بالمتر المربع"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="orderservice",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("meter", "بالمتر الطولي"),
                    ("sqm", "بالمتر المربع"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="cover_printing_type",
            field=models.CharField(
                choices=[
                    ("offset", "أوفست"),
                    ("digital", "ديجيتال"),
                    ("digital_banner", "خامات كبيرة"),
                    ("screen", "سلك سكرين"),
                    ("none", "بدون طباعة"),
                ],
                default="offset",
                max_length=20,
                verbose_name="نوع الطباعة",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="print_sides_mode",
            field=models.CharField(
                choices=[
                    ("single", "وجه واحد"),
                    ("work_sheet", "وجهين"),
                    ("work_turn", "طبع وقلب"),
                ],
                default="single",
                max_length=20,
                verbose_name="عدد الأوجه",
            ),
        ),
    ]
