# Generated by Django 4.2.26 on 2026-09-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "printing_pricing",
            "0017_alter_ordermaterial_unit_alter_orderservice_unit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="printingorder",
            name="inner_printing_type",
            field=models.CharField(
                choices=[("offset", "أوفست"), ("digital", "ديجيتال")],
                default="offset",
                max_length=20,
                verbose_name="طريقة طباعة الصفحات الداخلية",
            ),
        ),
    ]
