# Generated by Django 4.2.26 on 2026-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0019_printingorder_binding_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printingorder",
            name="inner_spot_colors",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="عدد الألوان المخصوصة (الداخلي)"
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="spot_color_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="كود / اسم اللون المخصوص",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="spot_colors_back",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد الألوان المخصوصة (الظهر)"
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="spot_colors_front",
            field=models.PositiveIntegerField(
                default=0, verbose_name="عدد الألوان المخصوصة (الوجه)"
            ),
        ),
    ]
