# Generated by Django 4.2.26 on 2026-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0025_alter_printingorder_product_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diemouldcustody",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="diemouldcustody",
            name="current_workshop",
        ),
        migrations.RemoveField(
            model_name="diemouldcustody",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="diemouldcustody",
            name="last_used_order",
        ),
        migrations.RemoveField(
            model_name="diemouldcustody",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="ordertransportlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ordertransportlog",
            name="order",
        ),
        migrations.RemoveField(
            model_name="ordertransportlog",
            name="transporter",
        ),
        migrations.RemoveField(
            model_name="ordertransportlog",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="ordervendoradvance",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ordervendoradvance",
            name="order",
        ),
        migrations.RemoveField(
            model_name="ordervendoradvance",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="ordervendoradvance",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="ordervendoradvance",
            name="work_order",
        ),
        migrations.RemoveField(
            model_name="priceauditlog",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="priceauditlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="priceauditlog",
            name="order",
        ),
        migrations.RemoveField(
            model_name="priceauditlog",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="PrintSide",
        ),
        migrations.RemoveField(
            model_name="proofsignoff",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="proofsignoff",
            name="order",
        ),
        migrations.RemoveField(
            model_name="proofsignoff",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="qcsignoff",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qcsignoff",
            name="order",
        ),
        migrations.RemoveField(
            model_name="qcsignoff",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="supplementalremake",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="supplementalremake",
            name="order",
        ),
        migrations.RemoveField(
            model_name="supplementalremake",
            name="responsible_supplier",
        ),
        migrations.RemoveField(
            model_name="supplementalremake",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="banner_sqm_price",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="coating_service",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="coating_type",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="colors_back",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="colors_front",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="current_stage",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="current_workshop",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="extra_cost",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="finishing_cost",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="has_internal_content",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="has_white_ink",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="material_cost",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="paper_type",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="press",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="print_direction",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="print_sides",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="printing_cost",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="sale_price",
        ),
        migrations.RemoveField(
            model_name="printingorder",
            name="supplier",
        ),
        migrations.AlterField(
            model_name="costcalculation",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("material", "تكلفة المواد والورق"),
                    ("printing", "تكلفة الطباعة"),
                    ("finishing", "تكلفة خدمات الطباعة والتشطيب"),
                    ("design", "تكلفة التصميم"),
                    ("total", "التكلفة الإجمالية"),
                ],
                max_length=20,
                verbose_name="نوع الحساب",
            ),
        ),
        migrations.AlterField(
            model_name="ordermaterial",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="orderservice",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "بالقطعة"),
                    ("thousand", "بالألف"),
                    ("sheet", "بالفرخ / شيت"),
                    ("package", "بالباكدج"),
                ],
                max_length=20,
                verbose_name="الوحدة",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="cover_printing_type",
            field=models.CharField(
                choices=[
                    ("offset", "أوفست"),
                    ("digital", "ديجيتال"),
                    ("screen", "سلك سكرين"),
                    ("none", "بدون طباعة"),
                ],
                default="offset",
                max_length=20,
                verbose_name="نوع الطباعة",
            ),
        ),
        migrations.AlterField(
            model_name="printingorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("book", "كتاب"),
                    ("magazine", "مجلة"),
                    ("brochure", "بروشور"),
                    ("flyer", "فلاير"),
                    ("poster", "بوستر"),
                    ("business_card", "كارت شخصي"),
                    ("envelope", "مظروف"),
                    ("letterhead", "ورق رسمي"),
                    ("invoice", "فاتورة"),
                    ("catalog", "كتالوج"),
                    ("calendar", "تقويم"),
                    ("notebook", "دفتر / بلوك نوت"),
                    ("folder", "فولدر / ملف"),
                    ("box", "علبة كرتون خفيفة"),
                    ("label", "لصقة"),
                    ("sticker", "شيت ستيكر"),
                ],
                max_length=20,
                verbose_name="نوع الطلب",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="base_archetype",
            field=models.CharField(
                choices=[
                    ("flyer", "مطبوع مفرود (كروت / فلاير)"),
                    ("catalog", "مطبوع مع داخلي (كتالوج / بلوك نوت / كتاب)"),
                    ("folder", "مطبوع مع فورمة تكسير (فولدر / علب)"),
                    ("invoice", "دفاتر مكربن (فواتير / إيصالات)"),
                ],
                default="flyer",
                help_text="يحدد مسار التشغيل وتفكيك التكاليف والخطوات في شاشة التسعير",
                max_length=20,
                verbose_name="التصنيف التشغيلي للمحرك",
            ),
        ),
        migrations.DeleteModel(
            name="DieMouldCustody",
        ),
        migrations.DeleteModel(
            name="OrderTransportLog",
        ),
        migrations.DeleteModel(
            name="OrderVendorAdvance",
        ),
        migrations.DeleteModel(
            name="PriceAuditLog",
        ),
        migrations.DeleteModel(
            name="PrintDirection",
        ),
        migrations.DeleteModel(
            name="ProofSignOff",
        ),
        migrations.DeleteModel(
            name="QCSignoff",
        ),
        migrations.DeleteModel(
            name="SupplementalRemake",
        ),
    ]
