# Generated by Django 4.2.26 on 2026-09-03 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0026_remove_diemouldcustody_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsetting",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vatsetting",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="PrintingSpecification",
        ),
        migrations.DeleteModel(
            name="SystemSetting",
        ),
        migrations.DeleteModel(
            name="VATSetting",
        ),
    ]
