# Generated by Django 4.2.26 on 2026-04-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "login_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الدخول"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الإنهاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة نشطة",
                "verbose_name_plural": "الجلسات النشطة",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model being audited", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the object being audited"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("ADMIN_ACCESS", "Admin Access"),
                            ("AUTHORITY_VIOLATION", "Authority Violation"),
                            ("EXCEPTION", "Exception"),
                            ("ENFORCE_IMMUTABILITY", "Enforce Immutability"),
                        ],
                        help_text="Type of operation performed",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "before_data",
                    models.JSONField(
                        blank=True, help_text="Data before the operation", null=True
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True, help_text="Data after the operation", null=True
                    ),
                ),
                (
                    "source_service",
                    models.CharField(
                        help_text="Service that initiated the operation", max_length=100
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string", null=True
                    ),
                ),
                (
                    "additional_context",
                    models.JSONField(
                        blank=True,
                        help_text="Additional context information",
                        null=True,
                    ),
                ),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("IGNORED", "Ignored"),
                            ("AUTO_RESOLVED", "Auto Resolved"),
                        ],
                        default="ACTIVE",
                        help_text="Resolution status for exceptions and violations",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the issue was resolved", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the resolution", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AuthorityDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_service",
                    models.CharField(
                        help_text="Service delegating authority", max_length=100
                    ),
                ),
                (
                    "to_service",
                    models.CharField(
                        help_text="Service receiving authority", max_length=100
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model for which authority is delegated",
                        max_length=100,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this delegation expires"),
                ),
                ("reason", models.TextField(help_text="Reason for delegation")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this delegation is currently active",
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Authority Delegation",
                "verbose_name_plural": "Authority Delegations",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="عنوان IP"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "هجوم بروت فورس"),
                            ("SUSPICIOUS_ACTIVITY", "نشاط مشبوه"),
                            ("MANUAL_BLOCK", "حجب يدوي"),
                            ("AUTO_BLOCK", "حجب تلقائي"),
                            ("REPEATED_VIOLATIONS", "انتهاكات متكررة"),
                        ],
                        max_length=50,
                        verbose_name="السبب",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "blocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الحجب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "unblocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ إلغاء الحجب"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المحاولات"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر محاولة"
                    ),
                ),
            ],
            options={
                "verbose_name": "عنوان IP محجوب",
                "verbose_name_plural": "عناوين IP المحجوبة",
                "ordering": ["-blocked_at"],
            },
        ),
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المفتاح"
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("AES-128", "AES-128"),
                            ("AES-256", "AES-256"),
                            ("RSA-2048", "RSA-2048"),
                            ("RSA-4096", "RSA-4096"),
                        ],
                        max_length=20,
                        verbose_name="نوع التشفير",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("EXPIRING_SOON", "قريب الانتهاء"),
                            ("EXPIRED", "منتهي"),
                            ("ROTATED", "تم التدوير"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="Hash للمفتاح - ليس المفتاح نفسه",
                        max_length=255,
                        verbose_name="Hash المفتاح",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاريخ الانتهاء")),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التدوير"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات الاستخدام"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "مفتاح تشفير",
                "verbose_name_plural": "مفاتيح التشفير",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        help_text="Type of operation (e.g., 'journal_entry', 'stock_movement')",
                        max_length=100,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique key for this operation", max_length=255
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(help_text="Serialized result of the operation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this idempotency record expires"
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency Record",
                "verbose_name_plural": "Idempotency Records",
            },
        ),
        migrations.CreateModel(
            name="QuarantineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model containing corrupted data",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the corrupted object"),
                ),
                (
                    "corruption_type",
                    models.CharField(
                        choices=[
                            ("ORPHANED_ENTRY", "Orphaned Journal Entry"),
                            ("NEGATIVE_STOCK", "Negative Stock"),
                            ("UNBALANCED_ENTRY", "Unbalanced Journal Entry"),
                            ("MULTIPLE_ACTIVE_YEAR", "Multiple Active Academic Years"),
                            ("INVALID_SOURCE_LINK", "Invalid Source Linkage"),
                            ("AUTHORITY_VIOLATION", "Authority Boundary Violation"),
                            ("SUSPICIOUS_PATTERN", "Suspicious Data Pattern"),
                        ],
                        help_text="Type of corruption detected",
                        max_length=100,
                    ),
                ),
                (
                    "original_data",
                    models.JSONField(help_text="Original data before quarantine"),
                ),
                (
                    "quarantine_reason",
                    models.TextField(help_text="Detailed reason for quarantine"),
                ),
                ("quarantined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUARANTINED", "Quarantined"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("PERMANENT", "Permanent Quarantine"),
                        ],
                        default="QUARANTINED",
                        max_length=50,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about resolution", null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Quarantine Record",
                "verbose_name_plural": "Quarantine Records",
                "ordering": ["-quarantined_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("RUNNING", "قيد التشغيل"),
                            ("SUCCESS", "نجح"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="وقت التنفيذ (ms)"
                    ),
                ),
                (
                    "rows_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="عدد الصفوف"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="بيانات النتيجة"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="تتبع الخطأ"),
                ),
            ],
            options={
                "verbose_name": "تنفيذ تقرير",
                "verbose_name_plural": "تنفيذات التقارير",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "يومياً"),
                            ("weekly", "أسبوعياً"),
                            ("monthly", "شهرياً"),
                            ("quarterly", "ربع سنوي"),
                        ],
                        max_length=20,
                        verbose_name="التكرار",
                    ),
                ),
                ("schedule_time", models.TimeField(verbose_name="وقت التشغيل")),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=الاثنين, 6=الأحد",
                        null=True,
                        verbose_name="يوم الأسبوع",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="1-31",
                        null=True,
                        verbose_name="يوم الشهر",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(
                        help_text="عناوين البريد الإلكتروني مفصولة بفواصل",
                        verbose_name="المستلمون",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("PAUSED", "متوقف مؤقتاً"),
                            ("DISABLED", "معطل"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="التشغيل التالي"
                    ),
                ),
            ],
            options={
                "verbose_name": "جدولة تقرير",
                "verbose_name_plural": "جدولة التقارير",
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم التقرير")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("table", "جدول"),
                            ("bar", "رسم بياني عمودي"),
                            ("pie", "رسم دائري"),
                            ("line", "رسم خطي"),
                            ("summary", "ملخص إحصائي"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("customers", "العملاء"),
                            ("sales", "فواتير المبيعات"),
                            ("purchases", "فواتير المشتريات"),
                            ("payments", "المدفوعات"),
                            ("employees", "الموظفين"),
                            ("journal_entries", "القيود اليومية"),
                            ("products", "المنتجات"),
                            ("suppliers", "الموردين"),
                        ],
                        max_length=50,
                        verbose_name="مصدر البيانات",
                    ),
                ),
                (
                    "selected_fields",
                    models.JSONField(default=list, verbose_name="الحقول المختارة"),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="المرشحات")),
                (
                    "group_by",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="التجميع حسب"
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الترتيب حسب"
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[("asc", "تصاعدي"), ("desc", "تنازلي")],
                        default="asc",
                        max_length=10,
                        verbose_name="اتجاه الترتيب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
                (
                    "run_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد مرات التشغيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("INACTIVE", "غير نشط"),
                            ("ARCHIVED", "مؤرشف"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="عام")),
            ],
            options={
                "verbose_name": "تقرير محفوظ",
                "verbose_name_plural": "التقارير المحفوظة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGIN", "محاولة دخول فاشلة"),
                            ("UNAUTHORIZED_ACCESS", "وصول غير مصرح"),
                            ("SUSPICIOUS_ACTIVITY", "نشاط مشبوه"),
                            ("BRUTE_FORCE", "هجوم بروت فورس"),
                            ("SQL_INJECTION", "محاولة SQL Injection"),
                            ("XSS_ATTEMPT", "محاولة XSS"),
                            ("CSRF_VIOLATION", "انتهاك CSRF"),
                            ("RATE_LIMIT_EXCEEDED", "تجاوز حد الطلبات"),
                            ("PERMISSION_VIOLATION", "انتهاك صلاحيات"),
                            ("DATA_BREACH_ATTEMPT", "محاولة اختراق بيانات"),
                        ],
                        max_length=50,
                        verbose_name="نوع الحادث",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="الخطورة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("RESOLVED", "تم الحل"),
                            ("FALSE_POSITIVE", "إنذار خاطئ"),
                            ("IGNORED", "تم التجاهل"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "username_attempted",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم المستخدم المحاول"
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="مسار الطلب"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="نوع الطلب"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="وقت الاكتشاف"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الحل"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الحل"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
            ],
            options={
                "verbose_name": "حادث أمني",
                "verbose_name_plural": "الحوادث الأمنية",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "تسجيل دخول ناجح"),
                            ("LOGIN_FAILED", "محاولة دخول فاشلة"),
                            ("ACCOUNT_LOCKED", "حساب مقفل"),
                            ("SESSION_CREATED", "جلسة جديدة"),
                            ("SESSION_TERMINATED", "جلسة منتهية"),
                            ("SECURITY_SCAN", "فحص أمني"),
                            ("KEY_ROTATION", "تدوير مفتاح"),
                            ("POLICY_UPDATE", "تحديث سياسة"),
                            ("INCIDENT_DETECTED", "حادث أمني"),
                            ("INCIDENT_RESOLVED", "حل حادث"),
                        ],
                        max_length=50,
                        verbose_name="نوع المقياس",
                    ),
                ),
                ("value", models.IntegerField(default=1, verbose_name="القيمة")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="التاريخ"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقياس أمني",
                "verbose_name_plural": "المقاييس الأمنية",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("PASSWORD_ENCRYPTION", "تشفير كلمات المرور"),
                            ("SESSION_TIMEOUT", "انتهاء الجلسة"),
                            ("BRUTE_FORCE_PROTECTION", "حماية من البروت فورس"),
                            ("RATE_LIMITING", "تحديد معدل الطلبات"),
                            ("IP_WHITELIST", "قائمة IP البيضاء"),
                            ("TWO_FACTOR_AUTH", "المصادقة الثنائية"),
                            ("PASSWORD_POLICY", "سياسة كلمات المرور"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="نوع السياسة",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="الإعدادات"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سياسة أمنية",
                "verbose_name_plural": "السياسات الأمنية",
                "ordering": ["policy_type"],
            },
        ),
        migrations.CreateModel(
            name="SignalExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "نجح"),
                            ("FAILED", "فشل"),
                            ("TIMEOUT", "انتهت المهلة"),
                            ("SKIPPED", "تم التخطي"),
                        ],
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت التنفيذ"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(verbose_name="وقت التنفيذ (ms)"),
                ),
                (
                    "instance_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="تتبع الخطأ"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنفيذ إشارة",
                "verbose_name_plural": "تنفيذات الإشارات",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalPerformanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("SLOW_EXECUTION", "تنفيذ بطيء"),
                            ("HIGH_FAILURE_RATE", "معدل فشل عالي"),
                            ("TIMEOUT", "انتهاء المهلة"),
                            ("REPEATED_ERRORS", "أخطاء متكررة"),
                            ("CRITICAL_FAILURE", "فشل حرج"),
                        ],
                        max_length=50,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "معلومة"),
                            ("WARNING", "تحذير"),
                            ("ERROR", "خطأ"),
                            ("CRITICAL", "حرج"),
                        ],
                        max_length=20,
                        verbose_name="الخطورة",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="التفاصيل"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="تم الحل"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحل"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه أداء إشارة",
                "verbose_name_plural": "تنبيهات أداء الإشارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="اسم الإشارة"
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("post_save", "Post Save"),
                            ("pre_save", "Pre Save"),
                            ("post_delete", "Post Delete"),
                            ("pre_delete", "Pre Delete"),
                            ("m2m_changed", "M2M Changed"),
                            ("custom", "Custom Signal"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشارة",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(max_length=100, verbose_name="اسم الموديول"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="اسم الموديل"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                            ("CRITICAL", "حرج"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "نشط"),
                            ("DISABLED", "معطل"),
                            ("PAUSED", "متوقف مؤقتاً"),
                            ("ERROR", "خطأ"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("is_critical", models.BooleanField(default=False, verbose_name="حرج")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "handler_function",
                    models.CharField(max_length=200, verbose_name="دالة المعالج"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "max_execution_time_ms",
                    models.IntegerField(
                        default=1000, verbose_name="الحد الأقصى لوقت التنفيذ (ms)"
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إشارة",
                "verbose_name_plural": "سجل الإشارات",
                "ordering": ["module_name", "signal_name"],
                "indexes": [
                    models.Index(
                        fields=["signal_name"], name="governance__signal__330cc2_idx"
                    ),
                    models.Index(
                        fields=["module_name", "status"],
                        name="governance__module__e0be07_idx",
                    ),
                    models.Index(
                        fields=["status", "is_critical"],
                        name="governance__status_b1aa39_idx",
                    ),
                ],
            },
        ),
    ]
