# Generated by Django 4.2.26 on 2026-04-13 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalperformancealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_signal_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الحل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="signalperformancealert",
            name="signal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="governance.signalregistry",
                verbose_name="الإشارة",
            ),
        ),
        migrations.AddField(
            model_name="signalexecution",
            name="signal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="governance.signalregistry",
                verbose_name="الإشارة",
            ),
        ),
        migrations.AddField(
            model_name="signalexecution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signal_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="securitypolicy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_policies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التحديث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securitymetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_metrics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الحل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="securityincident",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="savedreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="governance.savedreport",
                verbose_name="التقرير",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="governance.savedreport",
                verbose_name="التقرير",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="governance.reportschedule",
                verbose_name="الجدولة",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التشغيل بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="quarantinerecord",
            name="quarantined_by",
            field=models.ForeignKey(
                help_text="User or system that quarantined the data",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quarantined_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quarantinerecord",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_quarantine_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who initiated the operation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_idempotency_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encryptionkey",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_encryption_keys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="encryptionkey",
            name="rotated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rotated_encryption_keys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التدوير بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_ips",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الحجب بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="unblocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unblocked_ips",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم إلغاء الحجب بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="authoritydelegation",
            name="granted_by",
            field=models.ForeignKey(
                help_text="User who granted the delegation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="granted_authority_delegations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authoritydelegation",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_authority_delegations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked this as resolved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_audit_trails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the operation (null for system operations)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="governance_audit_trails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activesession",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنهاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="activesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddIndex(
            model_name="signalperformancealert",
            index=models.Index(
                fields=["signal", "-created_at"], name="governance__signal__b82be3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalperformancealert",
            index=models.Index(
                fields=["is_resolved", "-created_at"],
                name="governance__is_reso_3548ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signalperformancealert",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="governance__severit_40d843_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signalexecution",
            index=models.Index(
                fields=["signal", "-executed_at"], name="governance__signal__21b269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalexecution",
            index=models.Index(
                fields=["status", "-executed_at"], name="governance__status_1e3863_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalexecution",
            index=models.Index(
                fields=["-executed_at"], name="governance__execute_bdddb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signalexecution",
            index=models.Index(
                fields=["signal", "status"], name="governance__signal__26f82e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitymetric",
            index=models.Index(
                fields=["metric_type", "-recorded_at"],
                name="governance__metric__b2046a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitymetric",
            index=models.Index(
                fields=["date", "metric_type"], name="governance__date_d39d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitymetric",
            index=models.Index(
                fields=["-recorded_at"], name="governance__recorde_9d65f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["-detected_at"], name="governance__detecte_40f286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["status", "-detected_at"], name="governance__status_1e935d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["severity", "-detected_at"],
                name="governance__severit_130c33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["ip_address", "-detected_at"],
                name="governance__ip_addr_0dc0c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["incident_type", "-detected_at"],
                name="governance__inciden_fb2118_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="governance__created_f8c986_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["data_source", "status"], name="governance__data_so_0c735b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["status", "-last_run_at"], name="governance__status_ec4979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["status", "next_run_at"], name="governance__status_cccb88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["report", "-created_at"], name="governance__report__7ebd01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["report", "-started_at"], name="governance__report__d36261_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="governance__status_3c423b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexecution",
            index=models.Index(
                fields=["-started_at"], name="governance__started_dc561c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="governance__model_n_46026e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["corruption_type", "status"],
                name="governance__corrupt_6d8ed2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(
                fields=["quarantined_at"], name="governance__quarant_a51434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quarantinerecord",
            index=models.Index(fields=["status"], name="governance__status_d525ec_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["operation_type", "idempotency_key"],
                name="governance__operati_19bbc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["expires_at"], name="governance__expires_557490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["created_at"], name="governance__created_0af0e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="idempotencyrecord",
            unique_together={("operation_type", "idempotency_key")},
        ),
        migrations.AddIndex(
            model_name="encryptionkey",
            index=models.Index(
                fields=["key_name", "status"], name="governance__key_nam_f07515_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptionkey",
            index=models.Index(
                fields=["status", "-created_at"], name="governance__status_337c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encryptionkey",
            index=models.Index(
                fields=["expires_at"], name="governance__expires_efadcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(
                fields=["ip_address", "is_active"],
                name="governance__ip_addr_7d0d8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(
                fields=["-blocked_at"], name="governance__blocked_226c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["from_service", "to_service", "model_name"],
                name="governance__from_se_bedaa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="governance__expires_429947_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritydelegation",
            index=models.Index(
                fields=["granted_at"], name="governance__granted_f06bd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="governance__model_n_3ab51c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "timestamp"], name="governance__user_id_72d2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["operation", "timestamp"], name="governance__operati_a05589_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["source_service", "timestamp"],
                name="governance__source__ebee84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["timestamp"], name="governance__timesta_aaedf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["resolution_status", "operation"],
                name="governance__resolut_7b86d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["user", "is_active"], name="governance__user_id_9bad3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["session_key"], name="governance__session_0f9a8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["-last_activity"], name="governance__last_ac_f833a9_idx"
            ),
        ),
    ]
