# Generated by Django 4.2.26 on 2026-08-05 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated the operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_idempotency_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
