# Generated by Django 4.2.7 on 2025-10-22 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial", "0001_initial_clean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecializedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الخدمة")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الخدمة"),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التجهيز",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "خدمة متخصصة",
                "verbose_name_plural": "خدمات متخصصة",
                "ordering": ["supplier", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="VIPGiftDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_category",
                    models.CharField(
                        choices=[
                            ("corporate", "هدايا شركات"),
                            ("promotional", "هدايا دعائية"),
                            ("awards", "جوائز وتكريمات"),
                            ("luxury", "هدايا فاخرة"),
                            ("personalized", "هدايا مخصصة"),
                            ("tech", "هدايا تقنية"),
                            ("accessories", "إكسسوارات"),
                        ],
                        max_length=30,
                        verbose_name="فئة الهدية",
                    ),
                ),
                (
                    "customization_type",
                    models.CharField(
                        choices=[
                            ("engraving", "حفر"),
                            ("printing", "طباعة"),
                            ("embossing", "نقش بارز"),
                            ("embroidery", "تطريز"),
                            ("laser_cutting", "قص ليزر"),
                            ("packaging", "تقفيل"),
                        ],
                        max_length=30,
                        verbose_name="نوع التخصيص",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="اسم المنتج"),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, verbose_name="وصف المنتج"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الماركة"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="بلد المنشأ"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الأساسي"
                    ),
                ),
                (
                    "customization_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التخصيص",
                    ),
                ),
                (
                    "packaging_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التغطية",
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأدنى للكمية"
                    ),
                ),
                (
                    "max_customization_chars",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="أقصى عدد أحرف للتخصيص"
                    ),
                ),
                (
                    "production_time_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="وقت الإنتاج (أيام)"
                    ),
                ),
                (
                    "includes_gift_box",
                    models.BooleanField(default=True, verbose_name="يشمل علبة هدايا"),
                ),
                (
                    "includes_certificate",
                    models.BooleanField(default=False, verbose_name="يشمل شهادة"),
                ),
                (
                    "includes_delivery",
                    models.BooleanField(default=False, verbose_name="يشمل التوصيل"),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التوصيل",
                    ),
                ),
                (
                    "includes_setup_service",
                    models.BooleanField(
                        default=False, verbose_name="يشمل خدمة الإعداد"
                    ),
                ),
                (
                    "setup_service_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة خدمة الإعداد",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_gift_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل هدايا VIP",
                "verbose_name_plural": "تفاصيل هدايا VIP",
            },
        ),
        migrations.CreateModel(
            name="SupplierTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم نوع المورد كما سيظهر في الواجهة",
                        max_length=100,
                        verbose_name="اسم النوع",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="رمز فريد لنوع المورد (بالإنجليزية)",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف مختصر لنوع المورد",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="اسم الأيقونة من Font Awesome (مثل: fas fa-truck)",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون النوع بصيغة HEX (مثل: #007bff)",
                        max_length=7,
                        verbose_name="اللون",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب ظهور النوع في القوائم",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل النوع نشط ويظهر في الواجهة؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="الأنواع الأساسية التي لا يمكن حذفها",
                        verbose_name="نوع نظام",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplier_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_supplier_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُدث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات نوع المورد",
                "verbose_name_plural": "إعدادات أنواع الموردين",
                "db_table": "supplier_type_settings",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون بصيغة HEX",
                        max_length=7,
                        verbose_name="لون",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "settings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_type",
                        to="supplier.suppliertypesettings",
                        verbose_name="إعدادات النوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع مورد",
                "verbose_name_plural": "أنواع الموردين",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierServiceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم الخدمة المقدمة من المورد",
                        max_length=100,
                        unique=True,
                        verbose_name="اسم الخدمة",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("printing", "طباعة"),
                            ("paper", "ورق"),
                            ("finishing", "تشطيب"),
                            ("packaging", "تقفيل"),
                            ("binding", "تجليد"),
                            ("cutting", "قص"),
                            ("coating", "تغطية"),
                            ("digital", "خدمات رقمية"),
                            ("logistics", "لوجستيات"),
                            ("other", "أخرى"),
                        ],
                        help_text="تصنيف الخدمة حسب النوع",
                        max_length=20,
                        verbose_name="فئة الخدمة",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف تفصيلي للخدمة",
                        verbose_name="وصف الخدمة",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        default="#6c757d",
                        help_text="لون الخدمة بصيغة HEX مثل #FF5733",
                        max_length=7,
                        verbose_name="رمز اللون",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="ترتيب عرض الخدمة في القوائم",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل الخدمة متاحة للاستخدام",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="هل تحتاج هذه الخدمة لموافقة خاصة",
                        verbose_name="يتطلب موافقة",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="المدة المقدرة لتنفيذ الخدمة بالأيام",
                        verbose_name="المدة المقدرة (أيام)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "supplier_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="أنواع الموردين التي تقدم هذه الخدمة",
                        related_name="service_tags",
                        to="supplier.suppliertype",
                        verbose_name="أنواع الموردين",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمة مورد",
                "verbose_name_plural": "خدمات الموردين",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المورد")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف بالصيغة: '+999999999'. يسمح بـ 15 رقم كحد أقصى.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="كود المورد"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الشخص المسؤول",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "delivery_time",
                    models.IntegerField(
                        default=7,
                        help_text="مدة التسليم الافتراضية بالأيام",
                        verbose_name="مدة التسليم",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="الحد الأدنى لمبلغ الطلب",
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "pricing_notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات خاصة بالتسعير والخدمات",
                        verbose_name="ملاحظات التسعير",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="شروط الدفع المفضلة",
                        max_length=100,
                        verbose_name="شروط الدفع",
                    ),
                ),
                (
                    "discount_policy",
                    models.TextField(
                        blank=True,
                        help_text="تفاصيل سياسة الخصومات للمورد",
                        verbose_name="سياسة الخصومات",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="هاتف ثانوي"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="مصر", max_length=100, verbose_name="البلد"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: من 9 صباحاً إلى 5 مساءً",
                        max_length=100,
                        verbose_name="ساعات العمل",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا مورد مفضل للشركة؟",
                        verbose_name="مورد مفضل",
                    ),
                ),
                (
                    "supplier_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="تقييم من 0 إلى 5",
                        max_digits=3,
                        verbose_name="تقييم المورد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "financial_account",
                    models.OneToOneField(
                        blank=True,
                        help_text="الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier",
                        to="financial.chartofaccounts",
                        verbose_name="الحساب المحاسبي",
                    ),
                ),
                (
                    "primary_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_suppliers",
                        to="supplier.suppliertype",
                        verbose_name="النوع الأساسي",
                    ),
                ),
                (
                    "service_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الخدمات التي يقدمها هذا المورد",
                        related_name="suppliers",
                        to="supplier.supplierservicetag",
                        verbose_name="خدمات الموردين",
                    ),
                ),
                (
                    "supplier_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suppliers",
                        to="supplier.suppliertype",
                        verbose_name="أنواع المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier.suppliertype",
                verbose_name="فئة الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialized_services",
                to="supplier.supplier",
            ),
        ),
        migrations.CreateModel(
            name="ServicePriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="مثال: 1-20، 21-50",
                        max_length=50,
                        verbose_name="اسم الشريحة",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="الحد الأدنى للكمية"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً للكمية المفتوحة",
                        null=True,
                        verbose_name="الحد الأقصى للكمية",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "floor_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="السعر الخاص للأرضيات (اختياري)",
                        max_digits=10,
                        null=True,
                        verbose_name="السعر للأرضيات",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "شريحة سعرية",
                "verbose_name_plural": "شرائح سعرية",
                "ordering": ["service", "display_order", "min_quantity"],
            },
        ),
        migrations.CreateModel(
            name="PlateServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_size",
                    models.CharField(max_length=50, verbose_name="مقاس الزنك"),
                ),
                (
                    "custom_width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "price_per_plate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الزنك الواحد"
                    ),
                ),
                (
                    "set_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر الطقم (4 زنكات)",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plate_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة زنكات",
                "verbose_name_plural": "تفاصيل خدمات الزنكات",
            },
        ),
        migrations.CreateModel(
            name="PaperServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(max_length=100, verbose_name="نوع الورق"),
                ),
                ("gsm", models.PositiveIntegerField(verbose_name="وزن الورق (جرام)")),
                (
                    "sheet_size",
                    models.CharField(max_length=50, verbose_name="مقاس الفرخ"),
                ),
                (
                    "custom_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="بلد المنشأ"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الماركة"
                    ),
                ),
                (
                    "price_per_sheet",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الفرخ"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة ورق",
                "verbose_name_plural": "تفاصيل خدمات الورق",
            },
        ),
        migrations.CreateModel(
            name="OutdoorPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("vinyl", "فينيل"),
                            ("banner", "بنر"),
                            ("mesh", "شبك"),
                            ("canvas", "كانفاس"),
                            ("backlit", "باك لايت"),
                            ("one_way_vision", "ون واي فيجن"),
                            ("adhesive_vinyl", "فينيل لاصق"),
                        ],
                        max_length=30,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "printing_type",
                    models.CharField(
                        choices=[
                            ("digital_large_format", "طباعة رقمية كبيرة"),
                            ("eco_solvent", "إيكو سولفنت"),
                            ("latex", "لاتكس"),
                            ("uv", "UV"),
                        ],
                        max_length=30,
                        verbose_name="نوع الطباعة",
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى عرض (سم)"
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أقصى ارتفاع (سم)",
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر المتر المربع"
                    ),
                ),
                (
                    "min_order_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="الحد الأدنى (متر مربع)",
                    ),
                ),
                (
                    "includes_hemming",
                    models.BooleanField(default=False, verbose_name="يشمل الحياكة"),
                ),
                (
                    "hemming_cost_per_meter",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الحياكة للمتر",
                    ),
                ),
                (
                    "includes_grommets",
                    models.BooleanField(default=False, verbose_name="يشمل الحلقات"),
                ),
                (
                    "grommet_cost_each",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الحلقة الواحدة",
                    ),
                ),
                (
                    "production_time_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="وقت الإنتاج (أيام)"
                    ),
                ),
                (
                    "includes_installation",
                    models.BooleanField(default=False, verbose_name="يشمل التركيب"),
                ),
                (
                    "installation_cost_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التركيب للمتر المربع",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdoor_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل أوت دور",
                "verbose_name_plural": "تفاصيل أوت دور",
            },
        ),
        migrations.CreateModel(
            name="OffsetPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(max_length=30, verbose_name="نوع الماكينة"),
                ),
                (
                    "sheet_size",
                    models.CharField(max_length=20, verbose_name="مقاس الفرخ"),
                ),
                (
                    "custom_width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "color_calibration_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة معايرة الألوان",
                    ),
                ),
                (
                    "impression_cost_per_1000",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="تكلفة الفرخ لكل 1000",
                    ),
                ),
                (
                    "special_impression_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="سعر التراج مخصوص",
                    ),
                ),
                (
                    "break_impression_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="سعر كسر التراج",
                    ),
                ),
                (
                    "max_colors",
                    models.PositiveIntegerField(
                        default=4, verbose_name="أقصى عدد ألوان"
                    ),
                ),
                (
                    "has_uv_coating",
                    models.BooleanField(default=False, verbose_name="طلاء UV"),
                ),
                (
                    "has_aqueous_coating",
                    models.BooleanField(default=False, verbose_name="طلاء مائي"),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offset_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل طباعة أوفست",
                "verbose_name_plural": "تفاصيل طباعة أوفست",
            },
        ),
        migrations.CreateModel(
            name="LaserServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laser_type",
                    models.CharField(
                        choices=[
                            ("co2", "CO2 ليزر"),
                            ("fiber", "فايبر ليزر"),
                            ("diode", "دايود ليزر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الليزر",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cutting", "قص"),
                            ("engraving", "حفر"),
                            ("marking", "تعليم"),
                            ("cutting_engraving", "قص وحفر"),
                        ],
                        max_length=30,
                        verbose_name="نوع الخدمة",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("wood", "خشب"),
                            ("acrylic", "أكريليك"),
                            ("mdf", "MDF"),
                            ("cardboard", "كرتون"),
                            ("leather", "جلد"),
                            ("fabric", "قماش"),
                            ("metal", "معدن"),
                            ("glass", "زجاج"),
                            ("plastic", "بلاستيك"),
                        ],
                        max_length=20,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى عرض (سم)"
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى ارتفاع (سم)"
                    ),
                ),
                (
                    "max_thickness_mm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="أقصى سمك (مم)"
                    ),
                ),
                (
                    "price_per_minute",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر الدقيقة",
                    ),
                ),
                (
                    "price_per_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر السنتيمتر",
                    ),
                ),
                (
                    "price_per_piece",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر القطعة",
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الإعداد",
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "turnaround_time_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="وقت التسليم (ساعات)"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laser_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة ليزر",
                "verbose_name_plural": "تفاصيل خدمات الليزر",
            },
        ),
        migrations.CreateModel(
            name="FinishingServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finishing_type",
                    models.CharField(
                        choices=[
                            ("cutting", "قص"),
                            ("folding", "طي"),
                            ("binding_spiral", "تجليد حلزوني"),
                            ("binding_perfect", "تجليد كعب"),
                            ("lamination", "تقفيل"),
                            ("uv_coating", "طلاء UV"),
                            ("embossing", "نقش بارز"),
                            ("die_cutting", "تكسير"),
                            ("perforation", "تثقيب"),
                            ("stapling", "تدبيس"),
                        ],
                        max_length=20,
                        verbose_name="نوع الخدمة",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("per_piece", "بالقطعة"),
                            ("per_thousand", "بالألف"),
                            ("per_hour", "بالساعة"),
                            ("per_meter", "بالمتر"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                (
                    "min_size_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أصغر مقاس (سم)",
                    ),
                ),
                (
                    "max_size_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أكبر مقاس (سم)",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="وقت التجهيز (دقائق)"
                    ),
                ),
                (
                    "turnaround_time_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="وقت التسليم (ساعات)"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishing_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمات الطباعة",
                "verbose_name_plural": "تفاصيل خدمات الطباعة",
            },
        ),
        migrations.CreateModel(
            name="DigitalPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("laser_mono", "ليزر أبيض وأسود"),
                            ("laser_color", "ليزر ملون"),
                            ("inkjet_large", "نفث حبر كبير"),
                            ("inkjet_small", "نفث حبر صغير"),
                            ("offset_digital", "أوفست ديجيتال"),
                            ("production_printer", "طابعة إنتاج"),
                        ],
                        max_length=30,
                        verbose_name="نوع الماكينة",
                    ),
                ),
                (
                    "machine_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="موديل الماكينة"
                    ),
                ),
                (
                    "paper_handling",
                    models.CharField(
                        choices=[
                            ("sheet_fed", "تغذية أوراق"),
                            ("roll_fed", "تغذية لفائف"),
                            ("both", "كلاهما"),
                        ],
                        max_length=20,
                        verbose_name="نوع التغذية",
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("a4", "A4"),
                            ("a3", "A3"),
                            ("a3_plus", "A3+"),
                            ("sra3", "SRA3"),
                            ("custom", "مقاس مخصص"),
                        ],
                        max_length=20,
                        verbose_name="مقاس الورق",
                    ),
                ),
                (
                    "price_per_page_bw",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="سعر الصفحة أبيض/أسود",
                    ),
                ),
                (
                    "price_per_page_color",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الصفحة ملونة"
                    ),
                ),
                (
                    "has_price_tiers",
                    models.BooleanField(
                        default=True,
                        help_text="إذا كان نشطاً، سيتم استخدام الشرائح السعرية بدلاً من الأسعار الثابتة",
                        verbose_name="استخدام شرائح سعرية",
                    ),
                ),
                (
                    "duplex_printing",
                    models.BooleanField(default=True, verbose_name="طباعة على الوجهين"),
                ),
                (
                    "variable_data_printing",
                    models.BooleanField(
                        default=False, verbose_name="طباعة بيانات متغيرة"
                    ),
                ),
                (
                    "supports_heavy_paper",
                    models.BooleanField(
                        default=False, verbose_name="يدعم الورق السميك"
                    ),
                ),
                (
                    "max_paper_weight_gsm",
                    models.PositiveIntegerField(
                        default=300, verbose_name="أقصى وزن ورق (جرام)"
                    ),
                ),
                (
                    "pages_per_minute_bw",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="صفحة/دقيقة أبيض وأسود"
                    ),
                ),
                (
                    "pages_per_minute_color",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="صفحة/دقيقة ملون"
                    ),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=5, verbose_name="وقت الإعداد (دقائق)"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل طباعة ديجيتال",
                "verbose_name_plural": "تفاصيل طباعة ديجيتال",
            },
        ),
        migrations.AddIndex(
            model_name="supplierservicetag",
            index=models.Index(
                fields=["category", "is_active"], name="supplier_su_categor_733afa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierservicetag",
            index=models.Index(
                fields=["display_order"], name="supplier_su_display_5dda4f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicepricetier",
            unique_together={("service", "min_quantity")},
        ),
    ]
