# Generated by Django 4.2.26 on 2026-04-13 00:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="الحد الأدنى للكمية"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً للدلالة على بلا حد أعلى",
                        null=True,
                        verbose_name="الحد الأقصى للكمية",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر لكل وحدة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "شريحة سعرية",
                "verbose_name_plural": "الشرائح السعرية",
                "db_table": "supplier_service_price_tier",
                "ordering": ["service", "min_quantity"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="الرمز"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("printing", "طباعة"),
                            ("logistics", "لوجستيات"),
                            ("manufacturing", "تصنيع"),
                            ("general", "عام"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-cog", max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "attribute_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="تعريف الحقول الديناميكية لهذا النوع من الخدمات",
                        verbose_name="مخطط الخصائص",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع خدمة",
                "verbose_name_plural": "أنواع الخدمات",
                "db_table": "supplier_service_type",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المورد")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف بالصيغة: '+999999999'. يسمح بـ 15 رقم كحد أقصى.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="كود المورد",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الشخص المسؤول",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="هاتف ثانوي"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="مصر", max_length=100, verbose_name="البلد"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: من 9 صباحاً إلى 5 مساءً",
                        max_length=100,
                        verbose_name="ساعات العمل",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا مورد مفضل للشركة؟",
                        verbose_name="مورد مفضل",
                    ),
                ),
                (
                    "delivery_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="متوسط مدة التسليم بالأيام",
                        null=True,
                        verbose_name="مدة التسليم (أيام)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="الحد الأدنى لقيمة الطلب",
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 30 يوم، نقداً، آجل",
                        max_length=100,
                        verbose_name="شروط الدفع",
                    ),
                ),
                (
                    "supplier_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="تقييم من 1 إلى 5",
                        max_digits=3,
                        null=True,
                        verbose_name="تقييم المورد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الخدمة")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر الأساسي",
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الإعداد",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="القيم الفعلية حسب attribute_schema الخاص بنوع الخدمة",
                        verbose_name="الخصائص",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "خدمة مورد",
                "verbose_name_plural": "خدمات الموردين",
                "db_table": "supplier_supplier_service",
                "ordering": ["supplier__name", "service_type__name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون بصيغة HEX",
                        max_length=7,
                        verbose_name="لون",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "نوع مورد",
                "verbose_name_plural": "أنواع الموردين",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم نوع المورد كما سيظهر في الواجهة",
                        max_length=100,
                        verbose_name="اسم النوع",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="رمز فريد لنوع المورد (بالإنجليزية)",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف مختصر لنوع المورد",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="اسم الأيقونة من Font Awesome (مثل: fas fa-truck)",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون النوع بصيغة HEX (مثل: #007bff)",
                        max_length=7,
                        verbose_name="اللون",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب ظهور النوع في القوائم",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل النوع نشط ويظهر في الواجهة؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="الأنواع الأساسية التي لا يمكن حذفها",
                        verbose_name="نوع نظام",
                    ),
                ),
                (
                    "is_service_provider",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا المورد يقدم خدمات (بدون مخزون) أم منتجات (تحتاج مخزون)؟",
                        verbose_name="مقدم خدمات",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات نوع المورد",
                "verbose_name_plural": "إعدادات أنواع الموردين",
                "db_table": "supplier_type_settings",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
