# Generated by Django 5.2.17 on 2026-09-08 16:00

import django.core.validators
import django.utils.timezone
import utils.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=255, verbose_name="اسم الخدمة وقت التغيير"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        max_length=255, verbose_name="اسم المورد وقت التغيير"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ ووقت التغيير",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "تعديل يدوي من صفحة الخدمة"),
                            ("QUICK_RENEW", "تجديد سريع لسريان السعر"),
                            ("ORDER_FLOW", "تحديث أثناء تسعير أمر شغل"),
                            ("BULK_PERCENTAGE", "تحديث مجمع بنسبة مئوية"),
                            ("INITIAL", "تسجيل السعر الأولي"),
                        ],
                        default="MANUAL",
                        max_length=30,
                        verbose_name="مصدر التغيير",
                    ),
                ),
                (
                    "quote_reference",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="رقم عرض السعر المرجعي / الإثبات",
                    ),
                ),
                (
                    "exchange_rate_at_change",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف وقت التغيير",
                    ),
                ),
                (
                    "old_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="سعر الوحدة القديم",
                    ),
                ),
                (
                    "new_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="سعر الوحدة الجديد",
                    ),
                ),
                (
                    "price_variance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="نسبة التغير السعري (%)",
                    ),
                ),
                (
                    "old_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اللقطة الكاملة السابقة"
                    ),
                ),
                (
                    "new_snapshot",
                    models.JSONField(
                        default=dict, verbose_name="اللقطة الكاملة الجديدة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات التغيير")),
            ],
            options={
                "verbose_name": "سجل تاريخ سعر الخدمة",
                "verbose_name_plural": "سجلات تاريخ أسعار الخدمات",
                "db_table": "supplier_service_price_history",
                "ordering": ["-change_date"],
            },
        ),
        migrations.CreateModel(
            name="ServicePriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="الحد الأدنى للكمية"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً للدلالة على بلا حد أعلى",
                        null=True,
                        verbose_name="الحد الأقصى للكمية",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر لكل وحدة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "شريحة سعرية",
                "verbose_name_plural": "الشرائح السعرية",
                "db_table": "supplier_service_price_tier",
                "ordering": ["service", "min_quantity"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="الرمز"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("printing", "طباعة"),
                            ("logistics", "لوجستيات"),
                            ("manufacturing", "تصنيع"),
                            ("general", "عام"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="الفئة",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-cog", max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "attribute_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="تعريف الحقول الديناميكية لهذا النوع من الخدمات",
                        verbose_name="مخطط الخصائص",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "default_validity_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="الفترة الافتراضية لصلاحية أسعار هذا النوع من الخدمات بالأيام",
                        verbose_name="صلاحية السعر الافتراضية بالأيام",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع خدمة",
                "verbose_name_plural": "أنواع الخدمات",
                "db_table": "supplier_service_type",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المورد")),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "فرد"),
                            ("company", "شركة / منشأة"),
                            ("government", "جهة حكومية"),
                        ],
                        default="company",
                        help_text="الكيان القانوني والضريبي للمورد (فرد، شركة/منشأة، جهة حكومية)",
                        max_length=20,
                        verbose_name="الكيان القانوني والضريبي",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="الرقم القومي المكون من 14 رقماً للأفراد والحرفيين وموردي الخدمات المستقلين",
                        max_length=14,
                        null=True,
                        validators=[utils.validators.validate_national_id],
                        verbose_name="الرقم القومي (للأفراد)",
                    ),
                ),
                (
                    "commercial_registry",
                    models.CharField(
                        blank=True,
                        help_text="رقم السجل التجاري للشركات والمنشآت",
                        max_length=50,
                        null=True,
                        verbose_name="السجل التجاري",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف بالصيغة: '+999999999'. يسمح بـ 15 رقم كحد أقصى.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="العنوان"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="كود المورد",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="الشخص المسؤول",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الرصيد الحالي",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="الحد الأقصى للتسهيلات الائتمانية الممنوحة من المورد لشركتنا",
                        max_digits=12,
                        verbose_name="سقف التسهيلات الائتمانية",
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="أيام السماح الإضافية بعد تاريخ استحقاق الفاتورة",
                        verbose_name="فترة السماح (أيام)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="الرقم الضريبي",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم البنك الخاص بحساب المورد للتحويلات البنكية",
                        max_length=100,
                        null=True,
                        verbose_name="اسم البنك",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم الحساب البنكي أو الآيبان الدولي للمورد",
                        max_length=50,
                        null=True,
                        verbose_name="رقم الحساب / الآيبان (IBAN)",
                    ),
                ),
                (
                    "bank_beneficiary_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم المستفيد المطابق لبيانات الحساب البنكي",
                        max_length=150,
                        null=True,
                        verbose_name="اسم المستفيد للتحويل البنكي",
                    ),
                ),
                (
                    "is_pricing_supplier",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا المورد معتمد لتقديم خامات أو خدمات طباعة تدخل في تسعير أوامر الشغل؟",
                        verbose_name="مورد معتمد لموديول التسعير",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=17, verbose_name="هاتف ثانوي"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="مصر", max_length=100, verbose_name="البلد"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثال: من 9 صباحاً إلى 5 مساءً",
                        max_length=100,
                        verbose_name="ساعات العمل",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا مورد مفضل للشركة؟",
                        verbose_name="مورد مفضل",
                    ),
                ),
                (
                    "delivery_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="متوسط مدة التسليم بالأيام",
                        null=True,
                        verbose_name="مدة التسليم (أيام)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="الحد الأدنى لقيمة الطلب",
                        max_digits=10,
                        null=True,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 30 يوم، نقداً، آجل",
                        max_length=100,
                        verbose_name="شروط الدفع",
                    ),
                ),
                (
                    "supplier_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="تقييم من 1 إلى 5",
                        max_digits=3,
                        null=True,
                        verbose_name="تقييم المورد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد",
                "verbose_name_plural": "الموردين",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierAdvancePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="مبلغ المعاملة",
                    ),
                ),
                (
                    "exchange_rate_snapshot",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="لقطة سعر الصرف",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأساسية (EGP)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ الأصلي"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المبلغ المخصص على الفواتير",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الصرف"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="طريقة الصرف",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="رقم المرجع / الشيك",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات / السبب"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة مقدمة للمورد",
                "verbose_name_plural": "الدفعات المقدمة للموردين",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierAllocationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_reference",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="مرجع التوزيع الفريد",
                    ),
                ),
                (
                    "source_document_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نوع المستند المصدر",
                    ),
                ),
                (
                    "source_document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند المصدر",
                    ),
                ),
                (
                    "target_document_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نوع المستند المستهدف",
                    ),
                ),
                (
                    "target_document_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رقم المستند المستهدف",
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_TO_BILL", "سداد فاتورة مشتريات"),
                            ("ADVANCE_TO_BILL", "تسوية دفعة مقدمة"),
                            ("DEBIT_NOTE_TO_BILL", "تسوية إشعار خصم/مردودات"),
                            ("REVERSAL", "عكس توزيع سداد"),
                        ],
                        default="ADVANCE_TO_BILL",
                        max_length=30,
                        verbose_name="نوع التوزيع",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المخصص بالعملة الأصلي",
                    ),
                ),
                (
                    "allocation_currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="عملة التوزيع"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي المخصص (EGP)",
                    ),
                ),
                (
                    "realized_fx_difference",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="فروق عملة محققة (EGP)",
                    ),
                ),
                (
                    "allocation_status",
                    models.CharField(
                        choices=[("APPLIED", "مطبق"), ("REVERSED", "معكوس")],
                        default="APPLIED",
                        max_length=20,
                        verbose_name="حالة التوزيع",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التوزيع"
                    ),
                ),
                (
                    "evidence_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="توقيع إثبات التوزيع SHA256",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
            ],
            options={
                "verbose_name": "تدقيق توزيعات سداد الموردين",
                "verbose_name_plural": "سجلات تدقيق توزيعات سداد الموردين",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gsm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الجراماج (جم/م²)"
                    ),
                ),
                (
                    "tooling_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الفورمة / الكليشيه",
                    ),
                ),
                (
                    "price_per_click_bw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر النقرة أبيض وأسود",
                    ),
                ),
                (
                    "price_per_click_color",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر النقرة ألوان",
                    ),
                ),
                (
                    "pricing_formula",
                    models.CharField(
                        choices=[
                            ("PER_PIECE", "بالقطعة / بالنسخة"),
                            ("PER_SHEET", "بالفرخ"),
                            ("PER_SQM", "بالمتر المربع"),
                            ("PER_THOUSAND", "بالألف (سحب / تراج)"),
                            ("PER_SIGNATURE", "بالملزمة"),
                            ("FIXED_TOOLING", "قالب / فورمة مقطوعية"),
                            ("PER_REAM", "بالرزمة (250/500 فرخ)"),
                            ("PER_TON", "بالطن (مع التحويل للفرخ)"),
                        ],
                        default="PER_PIECE",
                        help_text="وحدة وطريقة احتساب تكلفة الخدمة أو الخامة",
                        max_length=30,
                        verbose_name="طريقة / معادلة التسعير",
                    ),
                ),
                (
                    "minimum_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="الحد الأدنى لقيمة أمر الشغل لهذه الخدمة بغض النظر عن صغر الكمية",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="الحد الأدنى للتشغيل",
                    ),
                ),
                (
                    "sheets_per_pack",
                    models.PositiveIntegerField(
                        blank=True,
                        default=500,
                        help_text="يستخدم عند التسعير بالرزمة لحساب سعر الفرخ المفرد",
                        null=True,
                        verbose_name="عدد الأفرخ في الرزمة/الباكيت",
                    ),
                ),
                (
                    "price_per_ton",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="يستخدم عند التسعير بالطن لحساب سعر الفرخ بناءً على الجراماج والمقاس",
                        max_digits=12,
                        null=True,
                        verbose_name="سعر الطن",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الخدمة")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="السعر الأساسي",
                    ),
                ),
                (
                    "set_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="سعر الطقم (لزنكات CTP لطقم 4 ألوان، أو لماكينات الأوفست كفتحة ماكينة شاملة تراج)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="سعر الطقم",
                    ),
                ),
                (
                    "set_included_tirages",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="خاص بماكينات الأوفست: عدد التراجات (بالألف سحبة) المتضمنة داخل سعر الطقم (افتراضياً 1 تراج)",
                        null=True,
                        verbose_name="عدد التراجات المشمولة في الطقم",
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="تكلفة الإعداد",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="القيم الفعلية حسب attribute_schema الخاص بنوع الخدمة",
                        verbose_name="الخصائص",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "price_updated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ آخر تحديث للسعر",
                    ),
                ),
                (
                    "price_valid_until",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="تاريخ انتهاء سريان السعر المعطى من المورد",
                        null=True,
                        verbose_name="تاريخ انتهاء الصلاحية",
                    ),
                ),
                (
                    "is_tax_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا السعر يتضمن ضريبة القيمة المضافة (14%)؟",
                        verbose_name="السعر شامل ضريبة القيمة المضافة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "خدمة مورد",
                "verbose_name_plural": "خدمات الموردين",
                "db_table": "supplier_supplier_service",
                "ordering": ["supplier__name", "service_type__name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(max_length=50, verbose_name="نوع المعاملة"),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=100, verbose_name="رقم المعاملة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأجنبية",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي بالعملة المحلية",
                    ),
                ),
                (
                    "open_amount_foreign",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح بالعملة الأجنبية",
                    ),
                ),
                (
                    "open_amount_functional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح الوظيفي",
                    ),
                ),
                (
                    "open_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المفتوح المتبقي للتسوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="OPEN", max_length=20, verbose_name="الحالة"
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة مالية للمورد",
                "verbose_name_plural": "معاملات الموردين المالية",
            },
        ),
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="الرمز"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون بصيغة HEX",
                        max_length=7,
                        verbose_name="لون",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "نوع مورد",
                "verbose_name_plural": "أنواع الموردين",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierTypeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم نوع المورد كما سيظهر في الواجهة",
                        max_length=100,
                        verbose_name="اسم النوع",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="رمز فريد لنوع المورد (بالإنجليزية)",
                        max_length=50,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف مختصر لنوع المورد",
                        verbose_name="الوصف",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-truck",
                        help_text="اسم الأيقونة من Font Awesome (مثل: fas fa-truck)",
                        max_length=50,
                        verbose_name="الأيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون النوع بصيغة HEX (مثل: #007bff)",
                        max_length=7,
                        verbose_name="اللون",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب ظهور النوع في القوائم",
                        verbose_name="ترتيب العرض",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل النوع نشط ويظهر في الواجهة؟",
                        verbose_name="نشط",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="الأنواع الأساسية التي لا يمكن حذفها",
                        verbose_name="نوع نظام",
                    ),
                ),
                (
                    "is_service_provider",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا المورد يقدم خدمات (بدون مخزون) أم منتجات (تحتاج مخزون)؟",
                        verbose_name="مقدم خدمات",
                    ),
                ),
                (
                    "is_pricing_related",
                    models.BooleanField(
                        default=False,
                        help_text="هل هذا النوع مرتبط بحسابات وموديول تسعير الطباعة؟",
                        verbose_name="مرتبط بموديول التسعير والإنتاج",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="تاريخ التحديث"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات نوع المورد",
                "verbose_name_plural": "إعدادات أنواع الموردين",
                "db_table": "supplier_type_settings",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
