# Generated by Django 4.2.26 on 2026-09-07 23:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("printing_pricing", "0002_initial"),
        ("customer", "0003_initial"),
        ("financial", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliertypesettings",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertypesettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_supplier_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حُدث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertype",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_type",
                to="supplier.suppliertypesettings",
                verbose_name="إعدادات النوع",
            ),
        ),
        migrations.AddField(
            model_name="suppliertransaction",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="coating_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.coatingtype",
                verbose_name="نوع السلوفان / الورنيش",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="عملة التسعير (اتركه فارغاً للعملة الافتراضية)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.machinedimension",
                verbose_name="مقاس الشيت / السلندر",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="finishing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.finishingtype",
                verbose_name="عملية التشطيب / التكسير",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.printingmachine",
                verbose_name="ماكينة الطباعة المعتمدة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="packaging_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.packagingtype",
                verbose_name="نوع التعبئة والتغليف",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="paper_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.paperorigin",
                verbose_name="بلد المنشأ / المصنع",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="paper_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.papersize",
                verbose_name="مقاس الفرخ المعتمد",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="paper_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.papertype",
                verbose_name="خامة الورق المعتمدة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="paper_weight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="printing_pricing.paperweight",
                verbose_name="وزن وجراماج الورق",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="plate_size",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"dimension_type": "plate"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_plate_services",
                to="printing_pricing.machinedimension",
                verbose_name="مقاس ومواصفة زنكة CTP",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_services",
                to="supplier.servicetype",
                verbose_name="نوع الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="supplierallocationaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="supplierallocationaudit",
            name="invoice_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_allocations",
                to="supplier.suppliertransaction",
                verbose_name="معاملة الفاتورة المستهدفة",
            ),
        ),
        migrations.AddField(
            model_name="supplierallocationaudit",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="supplier.suppliertransaction",
                verbose_name="معاملة التحصيل/الإشعار",
            ),
        ),
        migrations.AddField(
            model_name="supplierallocationaudit",
            name="reversed_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="supplier.supplierallocationaudit",
                verbose_name="سجل التدقيق المعكوس",
            ),
        ),
        migrations.AddField(
            model_name="supplierallocationaudit",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation_audits",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="supplieradvancepayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="supplieradvancepayment",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="supplieradvancepayment",
            name="financial_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.chartofaccounts",
                verbose_name="الخزينة / البنك المصدر",
            ),
        ),
        migrations.AddField(
            model_name="supplieradvancepayment",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.journalentry",
                verbose_name="القيد المحاسبي المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="supplieradvancepayment",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advance_payments",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="العملة الافتراضية المعتمدة لفتح فواتير ومعاملات هذا المورد تلقائياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers_default_currency",
                to="financial.currency",
                verbose_name="العملة الافتراضية",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="default_payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="شروط ومهلة السداد المعيارية المتفق عليها مع المورد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers",
                to="customer.paymentterm",
                verbose_name="شروط السداد المعيارية",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="financial_account",
            field=models.OneToOneField(
                blank=True,
                help_text="الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier",
                to="financial.chartofaccounts",
                verbose_name="الحساب المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="primary_type",
            field=models.ForeignKey(
                help_text="تصنيف المورد حسب نوع الخدمة المقدمة",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="supplier.suppliertype",
                verbose_name="نوع المورد",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="provided_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="الخدمات والقدرات التصنيعية المعتمدة لهذا المورد",
                related_name="suppliers_providing",
                to="supplier.servicetype",
                verbose_name="الخدمات المعتمدة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricetier",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_tiers",
                to="supplier.supplierservice",
                verbose_name="الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_price_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المسؤول",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_price_histories",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_history",
                to="supplier.supplierservice",
                verbose_name="الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_price_history",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddIndex(
            model_name="suppliertransaction",
            index=models.Index(
                fields=["supplier", "status"], name="supplier_su_supplie_b76585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppliertransaction",
            index=models.Index(
                fields=["due_date"], name="supplier_su_due_dat_f9db20_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliertransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("open_amount__gte", Decimal("0.00"))),
                name="check_supplier_txn_open_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierservice",
            index=models.Index(
                fields=["supplier", "service_type"],
                name="supplier_su_supplie_4c8ed9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierservice",
            index=models.Index(
                fields=["service_type", "is_active"],
                name="supplier_su_service_3011c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierservice",
            index=models.Index(
                fields=["service_type", "is_active", "price_valid_until"],
                name="supplier_su_service_e1ab38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierallocationaudit",
            index=models.Index(
                fields=["supplier", "allocation_date"],
                name="supplier_su_supplie_5e9342_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierallocationaudit",
            index=models.Index(
                fields=["allocation_reference", "created_at"],
                name="idx_supp_alloc_corr_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepricetier",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("max_quantity__isnull", True),
                    ("max_quantity__gte", models.F("min_quantity")),
                    _connector="OR",
                ),
                name="price_tier_max_gte_min",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["service", "-change_date"],
                name="supplier_se_service_2dabaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["supplier", "-change_date"],
                name="supplier_se_supplie_084e9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["change_source"], name="supplier_se_change__9ea3ab_idx"
            ),
        ),
    ]
