# Generated by Django 4.2.23 on 2025-10-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishingservicedetails',
            name='finishing_type',
            field=models.CharField(choices=[('cutting', 'قص'), ('folding', 'طي / ريجة'), ('die_cutting', 'تكسير'), ('perforation', 'تثقيب / تخريم'), ('scoring', 'سكين'), ('creasing', 'كريزة'), ('numbering', 'ترقيم')], max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.CreateModel(
            name='PackagingServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(choices=[('stapling', 'تدبيس / دبوس'), ('wire_binding', 'تجليد سلك / بشر'), ('spiral_binding', 'تجليد حلزوني / سوستة'), ('perfect_binding', 'تجليد كعب / غراء'), ('saddle_stitch', 'تدبيس وسط / سلك وسط'), ('lamination', 'تقفيل / سلوفان'), ('thermal_binding', 'تجليد حراري'), ('comb_binding', 'تجليد مشط')], max_length=30, verbose_name='نوع التقفيل')),
                ('calculation_method', models.CharField(choices=[('per_piece', 'بالقطعة'), ('per_thousand', 'بالألف'), ('per_hour', 'بالساعة'), ('per_meter', 'بالمتر')], max_length=20, verbose_name='طريقة الحساب')),
                ('min_size_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='أصغر مقاس (سم)')),
                ('max_size_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='أكبر مقاس (سم)')),
                ('max_thickness_mm', models.DecimalField(blank=True, decimal_places=2, help_text='أقصى سُمك للكتاب أو المنتج', max_digits=6, null=True, verbose_name='أقصى سُمك (مم)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, verbose_name='وقت التجهيز (دقائق)')),
                ('turnaround_time_hours', models.PositiveIntegerField(default=24, verbose_name='وقت التسليم (ساعات)')),
                ('wire_color_options', models.CharField(blank=True, help_text='مثال: أسود، أبيض، فضي، ذهبي', max_length=200, verbose_name='ألوان السلك المتاحة')),
                ('cover_material_options', models.CharField(blank=True, help_text='مثال: PVC، جلد صناعي، كرتون مقوى', max_length=200, verbose_name='خامات الغلاف المتاحة')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_details', to='supplier.specializedservice')),
            ],
            options={
                'verbose_name': 'تفاصيل خدمات التقفيل',
                'verbose_name_plural': 'تفاصيل خدمات التقفيل',
            },
        ),
    ]
