# Generated by Django 4.2.23 on 2025-11-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printing_pricing', '0002_initial'),
        ('supplier', '0001_initial'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertypesettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_types', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='suppliertypesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_types', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة'),
        ),
        migrations.AddField(
            model_name='suppliertype',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_type', to='supplier.suppliertypesettings', verbose_name='إعدادات النوع'),
        ),
        migrations.AddField(
            model_name='supplierservicetag',
            name='supplier_types',
            field=models.ManyToManyField(blank=True, help_text='أنواع الموردين التي تقدم هذه الخدمة', related_name='service_tags', to='supplier.suppliertype', verbose_name='أنواع الموردين'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='financial_account',
            field=models.OneToOneField(blank=True, help_text='الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='financial.chartofaccounts', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='primary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_suppliers', to='supplier.suppliertype', verbose_name='النوع الأساسي'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service_tags',
            field=models.ManyToManyField(blank=True, help_text='الخدمات التي يقدمها هذا المورد', related_name='suppliers', to='supplier.supplierservicetag', verbose_name='خدمات الموردين'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_types',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='supplier.suppliertype', verbose_name='أنواع المورد'),
        ),
        migrations.AddField(
            model_name='specializedservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliertype', verbose_name='فئة الخدمة'),
        ),
        migrations.AddField(
            model_name='specializedservice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_services', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='servicepricetier',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='plateservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plate_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='paperservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paper_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='packagingservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='outdoorprintingdetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='offsetprintingdetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offset_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='laserservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laser_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='finishingservicedetails',
            name='finishing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finishing_services', to='printing_pricing.finishingtype', verbose_name='نوع الخدمة'),
        ),
        migrations.AddField(
            model_name='finishingservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='digitalprintingdetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_details', to='supplier.specializedservice'),
        ),
        migrations.AddField(
            model_name='coatingservicedetails',
            name='coating_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coating_services', to='printing_pricing.coatingtype', verbose_name='نوع التغطية'),
        ),
        migrations.AddField(
            model_name='coatingservicedetails',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coating_details', to='supplier.specializedservice'),
        ),
        migrations.AddIndex(
            model_name='supplierservicetag',
            index=models.Index(fields=['category', 'is_active'], name='supplier_su_categor_733afa_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierservicetag',
            index=models.Index(fields=['display_order'], name='supplier_su_display_5dda4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricetier',
            unique_together={('service', 'min_quantity')},
        ),
    ]
