# Generated by Django 4.2.26 on 2026-08-05 04:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(max_length=50, verbose_name="نوع المعاملة"),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=100, verbose_name="رقم المعاملة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "foreign_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ بالعملة الأجنبية",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ الوظيفي بالعملة المحلية",
                    ),
                ),
                (
                    "open_amount_foreign",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح بالعملة الأجنبية",
                    ),
                ),
                (
                    "open_amount_functional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="المبلغ المفتوح الوظيفي",
                    ),
                ),
                (
                    "open_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="المبلغ المفتوح المتبقي للتسوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="OPEN", max_length=20, verbose_name="الحالة"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="supplier.supplier",
                        verbose_name="المورد",
                    ),
                ),
            ],
            options={
                "verbose_name": "معاملة مالية للمورد",
                "verbose_name_plural": "معاملات الموردين المالية",
                "indexes": [
                    models.Index(
                        fields=["supplier", "status"],
                        name="supplier_su_supplie_b76585_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="supplier_su_due_dat_f9db20_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="suppliertransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("open_amount__gte", Decimal("0.00"))),
                name="check_supplier_txn_open_amount_positive",
            ),
        ),
    ]
