# Generated by Django 4.2.24 on 2025-09-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
