# Generated by Django 4.2.26 on 2026-08-22 13:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_customer_country_alter_customer_city_and_more"),
        ("supplier", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="رقم الحساب البنكي أو رقم الآيبان",
                max_length=50,
                null=True,
                verbose_name="رقم الحساب / الآيبان (IBAN)",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_beneficiary_name",
            field=models.CharField(
                blank=True,
                help_text="اسم المستفيد في التحويلات البنكية",
                max_length=255,
                null=True,
                verbose_name="اسم المستفيد المعتمد",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="اسم البنك الخاص بحساب المورد للتحويلات",
                max_length=100,
                null=True,
                verbose_name="اسم البنك",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="commercial_registry",
            field=models.CharField(
                blank=True,
                help_text="رقم السجل التجاري للشركات والمنشآت",
                max_length=50,
                null=True,
                verbose_name="السجل التجاري",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الحد الأقصى للتسهيلات الائتمانية الممنوحة من المورد لشركتنا",
                max_digits=12,
                verbose_name="سقف التسهيلات الائتمانية",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="default_payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="شرط السداد المتفق عليه مع المورد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers",
                to="client.paymentterm",
                verbose_name="شروط السداد المعيارية",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("individual", "فرد"),
                    ("company", "شركة / منشأة"),
                    ("government", "جهة حكومية"),
                ],
                default="company",
                max_length=20,
                verbose_name="الكيان القانوني والضريبي",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="grace_period_days",
            field=models.IntegerField(
                default=0,
                help_text="أيام السماح الإضافية بعد تاريخ الاستحقاق",
                verbose_name="فترة السماح (أيام)",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="الرقم القومي المكون من 14 رقماً للأفراد والحرفيين",
                max_length=14,
                null=True,
                validators=[utils.validators.validate_national_id],
                verbose_name="الرقم القومي (للأفراد)",
            ),
        ),
    ]
