# Generated by Django 4.2.26 on 2026-09-03 02:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0002_initial"),
        ("supplier", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierservice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="عملة التسعير (اتركه فارغاً للعملة الافتراضية)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="minimum_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الحد الأدنى لقيمة أمر الشغل لهذه الخدمة بغض النظر عن صغر الكمية",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="الحد الأدنى للتشغيل",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="price_per_ton",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="يستخدم عند التسعير بالطن لحساب سعر الفرخ بناءً على الجراماج والمقاس",
                max_digits=12,
                null=True,
                verbose_name="سعر الطن",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="pricing_formula",
            field=models.CharField(
                choices=[
                    ("PER_PIECE", "بالقطعة / بالنسخة"),
                    ("PER_SHEET", "بالفرخ"),
                    ("PER_SQM", "بالمتر المربع"),
                    ("PER_THOUSAND", "بالألف (سحب / تراج)"),
                    ("PER_SIGNATURE", "بالملزمة"),
                    ("FIXED_TOOLING", "قالب / فورمة مقطوعية"),
                    ("PER_REAM", "بالرزمة (250/500 فرخ)"),
                    ("PER_TON", "بالطن (مع التحويل للفرخ)"),
                ],
                default="PER_PIECE",
                help_text="وحدة وطريقة احتساب تكلفة الخدمة أو الخامة",
                max_length=30,
                verbose_name="طريقة / معادلة التسعير",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="sheets_per_pack",
            field=models.PositiveIntegerField(
                blank=True,
                default=500,
                help_text="يستخدم عند التسعير بالرزمة لحساب سعر الفرخ المفرد",
                null=True,
                verbose_name="عدد الأفرخ في الرزمة/الباكيت",
            ),
        ),
    ]
