# Generated by Django 5.2.17 on 2026-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='whatsapp_opt_out',
            field=models.BooleanField(default=False, help_text='هل قام المورد بإلغاء الاشتراك في إشعارات الواتساب', verbose_name='إلغاء الاشتراك في واتساب'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='whatsapp_opt_out_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ وتوقيت إلغاء الاشتراك في الواتساب', null=True, verbose_name='تاريخ إلغاء الاشتراك'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='whatsapp_opt_out_reason',
            field=models.CharField(blank=True, default='', help_text='سبب إلغاء الاشتراك أو الرسالة الواردة', max_length=255, verbose_name='سبب إلغاء الاشتراك'),
        ),
    ]
