# Generated by Django 4.2.23 on 2025-10-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing_pricing', '0003_add_packaging_type_model'),
        ('supplier', '0003_change_finishing_type_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(choices=[('per_piece', 'بالقطعة'), ('per_thousand', 'بالألف'), ('per_hour', 'بالساعة'), ('per_square_meter', 'بالمتر المربع')], max_length=20, verbose_name='طريقة الحساب')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('setup_time_minutes', models.PositiveIntegerField(default=30, verbose_name='وقت التجهيز (دقائق)')),
                ('turnaround_time_hours', models.PositiveIntegerField(default=6, verbose_name='وقت التسليم (ساعات)')),
                ('coating_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coating_services', to='printing_pricing.coatingtype', verbose_name='نوع التغطية')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coating_details', to='supplier.specializedservice')),
            ],
            options={
                'verbose_name': 'تفاصيل خدمات التغطية',
                'verbose_name_plural': 'تفاصيل خدمات التغطية',
            },
        ),
    ]
