# Generated by Django 4.2.26 on 2026-09-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("printing_pricing", "0006_separate_sheet_dimensions"),
        ("supplier", "0003_supplierservice_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierservice",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.machinedimension",
                verbose_name="مقاس الشيت / السلندر",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.printingmachine",
                verbose_name="ماكينة الطباعة المعتمدة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="paper_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_services",
                to="printing_pricing.papertype",
                verbose_name="خامة الورق المعتمدة",
            ),
        ),
    ]
