# Generated by Django 4.2.26 on 2026-08-22 13:14

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0008_customer_country_alter_customer_city_and_more"),
        ("supplier", "0003_supplier_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="رقم الحساب البنكي أو الآيبان الدولي للمورد",
                max_length=50,
                null=True,
                verbose_name="رقم الحساب / الآيبان (IBAN)",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_beneficiary_name",
            field=models.CharField(
                blank=True,
                help_text="اسم المستفيد المطابق لبيانات الحساب البنكي",
                max_length=150,
                null=True,
                verbose_name="اسم المستفيد للتحويل البنكي",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="اسم البنك الخاص بحساب المورد للتحويلات البنكية",
                max_length=100,
                null=True,
                verbose_name="اسم البنك",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="default_payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text="شروط ومهلة السداد المعيارية المتفق عليها مع المورد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers",
                to="client.paymentterm",
                verbose_name="شروط السداد المعيارية",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("individual", "فرد"),
                    ("company", "شركة / منشأة"),
                    ("government", "جهة حكومية"),
                ],
                default="company",
                help_text="الكيان القانوني والضريبي للمورد (فرد، شركة/منشأة، جهة حكومية)",
                max_length=20,
                verbose_name="الكيان القانوني والضريبي",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="grace_period_days",
            field=models.IntegerField(
                default=0,
                help_text="أيام السماح الإضافية بعد تاريخ استحقاق الفاتورة",
                verbose_name="فترة السماح (أيام)",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="الرقم القومي المكون من 14 رقماً للأفراد والحرفيين وموردي الخدمات المستقلين",
                max_length=14,
                null=True,
                validators=[utils.validators.validate_national_id],
                verbose_name="الرقم القومي (للأفراد)",
            ),
        ),
    ]
