# Generated by Django 4.2.7 on 2025-10-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0015_remove_cash_movements"),
        ("supplier", "0003_delete_supplierpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="financial_account",
            field=models.OneToOneField(
                blank=True,
                help_text="الحساب المحاسبي المرتبط بهذا المورد في دليل الحسابات",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier",
                to="financial.chartofaccounts",
                verbose_name="الحساب المحاسبي",
            ),
        ),
    ]
