# Generated by Django 4.2.26 on 2026-08-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0033_chartofaccounts_opening_balance_foreign_and_more"),
        ("supplier", "0004_supplieradvancepayment_supplierallocationaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="العملة الافتراضية المعتمدة لفتح فواتير ومعاملات هذا المورد تلقائياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppliers_default_currency",
                to="financial.currency",
                verbose_name="العملة الافتراضية",
            ),
        ),
    ]
