# Generated by Django 4.2.26 on 2026-08-22 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0004_alter_supplier_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="الحد الأقصى للتسهيلات الائتمانية الممنوحة من المورد لشركتنا",
                max_digits=12,
                verbose_name="سقف التسهيلات الائتمانية",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "فرد"),
                    ("company", "شركة / منشأة"),
                    ("government", "جهة حكومية"),
                ],
                default="company",
                help_text="الكيان القانوني والضريبي للمورد (فرد، شركة/منشأة، جهة حكومية)",
                max_length=20,
                verbose_name="الكيان القانوني والضريبي",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="grace_period_days",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="أيام السماح الإضافية بعد تاريخ استحقاق الفاتورة",
                verbose_name="فترة السماح (أيام)",
            ),
        ),
    ]
