# Generated by Django 4.2.7 on 2025-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0004_supplier_financial_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="delivery_time",
            field=models.IntegerField(
                default=7,
                help_text="مدة التسليم الافتراضية بالأيام",
                verbose_name="مدة التسليم",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pricing_notes",
            field=models.TextField(
                blank=True,
                help_text="ملاحظات خاصة بالتسعير والخدمات",
                verbose_name="ملاحظات التسعير",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pricing_services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="قائمة الخدمات التي يقدمها المورد",
                verbose_name="الخدمات المتاحة",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=3,
                help_text="تقييم المورد من 1 إلى 5 نجوم",
                verbose_name="تقييم المورد",
            ),
        ),
    ]
