# Generated by Django 4.2.7 on 2025-10-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0005_add_pricing_services_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الفئة")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("paper", "مخزن ورق"),
                            ("offset_printing", "طباعة أوفست"),
                            ("digital_printing", "طباعة ديجيتال"),
                            ("finishing", "خدمات طباعة"),
                            ("plates", "مكتب فصل"),
                            ("packaging", "تغليف"),
                            ("design", "تصميم"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="أيقونة"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="لون"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "فئة خدمة",
                "verbose_name_plural": "فئات الخدمات",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم النوع")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("paper", "مخزن ورق"),
                            ("offset_printing", "مطبعة أوفست"),
                            ("digital_printing", "مطبعة ديجيتال"),
                            ("finishing", "خدمات طباعة"),
                            ("plates", "مكتب فصل"),
                            ("packaging", "تغليف"),
                            ("design", "تصميم"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="الرمز",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="اسم الأيقونة من Font Awesome",
                        max_length=50,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="لون بصيغة HEX",
                        max_length=7,
                        verbose_name="لون",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
            ],
            options={
                "verbose_name": "نوع مورد",
                "verbose_name_plural": "أنواع الموردين",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="pricing_services",
        ),
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="المدينة"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country",
            field=models.CharField(
                blank=True, default="مصر", max_length=100, verbose_name="البلد"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="discount_policy",
            field=models.TextField(
                blank=True,
                help_text="تفاصيل سياسة الخصومات للمورد",
                verbose_name="سياسة الخصومات",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_preferred",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا مورد مفضل للشركة؟",
                verbose_name="مورد مفضل",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="الحد الأدنى لمبلغ الطلب",
                max_digits=10,
                verbose_name="الحد الأدنى للطلب",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(
                blank=True,
                help_text="شروط الدفع المفضلة",
                max_length=100,
                verbose_name="شروط الدفع",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="quality_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=3.0,
                help_text="تقييم جودة الخدمات من 1.0 إلى 5.0",
                max_digits=3,
                verbose_name="تقييم الجودة",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="secondary_phone",
            field=models.CharField(
                blank=True, max_length=17, verbose_name="هاتف ثانوي"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="website",
            field=models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20, verbose_name="واتساب"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="working_hours",
            field=models.CharField(
                blank=True,
                help_text="مثال: من 9 صباحاً إلى 5 مساءً",
                max_length=100,
                verbose_name="ساعات العمل",
            ),
        ),
        migrations.CreateModel(
            name="SpecializedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم الخدمة")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الخدمة"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الأساسي"
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التجهيز",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأدنى للكمية"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier.supplierservicecategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialized_services",
                        to="supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمة متخصصة",
                "verbose_name_plural": "خدمات متخصصة",
                "ordering": ["supplier", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaperServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("coated", "كوشيه"),
                            ("offset", "أوفست"),
                            ("cardboard", "كرتون"),
                            ("art_paper", "ورق فني"),
                            ("newsprint", "ورق جرائد"),
                        ],
                        max_length=20,
                        verbose_name="نوع الورق",
                    ),
                ),
                ("gsm", models.PositiveIntegerField(verbose_name="وزن الورق (جرام)")),
                (
                    "sheet_size",
                    models.CharField(
                        choices=[
                            ("full_70x100", "فرخ كامل 70×100"),
                            ("half_50x70", "نصف فرخ 50×70"),
                            ("quarter_35x50", "ربع فرخ 35×50"),
                            ("a3", "A3"),
                            ("a4", "A4"),
                            ("custom", "مقاس مخصص"),
                        ],
                        max_length=20,
                        verbose_name="مقاس الفرخ",
                    ),
                ),
                (
                    "custom_width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="بلد المنشأ"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الماركة"
                    ),
                ),
                (
                    "price_per_sheet",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الفرخ"
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر الكيلو",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة ورق",
                "verbose_name_plural": "تفاصيل خدمات الورق",
            },
        ),
        migrations.CreateModel(
            name="FinishingServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finishing_type",
                    models.CharField(
                        choices=[
                            ("cutting", "قص"),
                            ("folding", "طي"),
                            ("binding_spiral", "تجليد حلزوني"),
                            ("binding_perfect", "تجليد كعب"),
                            ("lamination", "تغليف"),
                            ("uv_coating", "طلاء UV"),
                            ("embossing", "نقش بارز"),
                            ("die_cutting", "تكسير"),
                            ("perforation", "تثقيب"),
                            ("stapling", "تدبيس"),
                        ],
                        max_length=20,
                        verbose_name="نوع الخدمة",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("per_piece", "بالقطعة"),
                            ("per_thousand", "بالألف"),
                            ("per_hour", "بالساعة"),
                            ("per_meter", "بالمتر"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الحساب",
                    ),
                ),
                (
                    "min_size_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أصغر مقاس (سم)",
                    ),
                ),
                (
                    "max_size_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أكبر مقاس (سم)",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="وقت التجهيز (دقائق)"
                    ),
                ),
                (
                    "turnaround_time_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="وقت التسليم (ساعات)"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishing_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمات الطباعة",
                "verbose_name_plural": "تفاصيل خدمات الطباعة",
            },
        ),
        migrations.CreateModel(
            name="DigitalPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("laser", "ليزر"),
                            ("inkjet", "نفث حبر"),
                            ("offset_digital", "أوفست ديجيتال"),
                        ],
                        max_length=20,
                        verbose_name="نوع الماكينة",
                    ),
                ),
                (
                    "paper_handling",
                    models.CharField(
                        choices=[
                            ("sheet_fed", "تغذية أوراق"),
                            ("roll_fed", "تغذية لفائف"),
                            ("both", "كلاهما"),
                        ],
                        max_length=20,
                        verbose_name="نوع التغذية",
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى عرض (سم)"
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى ارتفاع (سم)"
                    ),
                ),
                (
                    "price_per_page_bw",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="سعر الصفحة أبيض/أسود",
                    ),
                ),
                (
                    "price_per_page_color",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الصفحة ملونة"
                    ),
                ),
                (
                    "duplex_printing",
                    models.BooleanField(default=True, verbose_name="طباعة على الوجهين"),
                ),
                (
                    "variable_data_printing",
                    models.BooleanField(
                        default=False, verbose_name="طباعة بيانات متغيرة"
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل طباعة ديجيتال",
                "verbose_name_plural": "تفاصيل طباعة ديجيتال",
            },
        ),
        migrations.AddField(
            model_name="supplier",
            name="primary_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_suppliers",
                to="supplier.suppliertype",
                verbose_name="النوع الأساسي",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="suppliers",
                to="supplier.suppliertype",
                verbose_name="أنواع المورد",
            ),
        ),
    ]
