# Generated by Django 4.2.26 on 2026-09-05 12:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0005_supplierservice_coating_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierservice",
            name="set_included_tirages",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="خاص بماكينات الأوفست: عدد التراجات (بالألف سحبة) المتضمنة داخل سعر الطقم (افتراضياً 1 تراج)",
                null=True,
                verbose_name="عدد التراجات المشمولة في الطقم",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="set_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="سعر الطقم (لزنكات CTP لطقم 4 ألوان، أو لماكينات الأوفست كفتحة ماكينة شاملة تراج)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="سعر الطقم",
            ),
        ),
    ]
