# Generated by Django 4.2.26 on 2026-09-05 14:07

from django.db import migrations, models


def backfill_pricing_suppliers(apps, schema_editor):
    SupplierTypeSettings = apps.get_model('supplier', 'SupplierTypeSettings')
    Supplier = apps.get_model('supplier', 'Supplier')
    SupplierService = apps.get_model('supplier', 'SupplierService')

    pricing_codes = ['press', 'offset_printing', 'paper', 'paper_supplier', 'ctp', 'coating', 'cellophane', 'finishing', 'packaging']
    SupplierTypeSettings.objects.filter(code__in=pricing_codes).update(is_pricing_related=True)

    for svc in SupplierService.objects.select_related('supplier', 'service_type').all():
        if svc.supplier and svc.service_type:
            if not svc.supplier.is_pricing_supplier:
                svc.supplier.is_pricing_supplier = True
                svc.supplier.save(update_fields=['is_pricing_supplier'])
            svc.supplier.provided_services.add(svc.service_type)

    for supplier in Supplier.objects.filter(is_pricing_supplier=False).select_related('primary_type'):
        if supplier.primary_type and supplier.primary_type.code.lower() in pricing_codes:
            supplier.is_pricing_supplier = True
            supplier.save(update_fields=['is_pricing_supplier'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0006_supplierservice_set_included_tirages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="is_pricing_supplier",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا المورد معتمد لتقديم خامات أو خدمات طباعة تدخل في تسعير أوامر الشغل؟",
                verbose_name="مورد معتمد لموديول التسعير",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="provided_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="الخدمات والقدرات التصنيعية المعتمدة لهذا المورد",
                related_name="suppliers_providing",
                to="supplier.servicetype",
                verbose_name="الخدمات المعتمدة",
            ),
        ),
        migrations.AddField(
            model_name="suppliertypesettings",
            name="is_pricing_related",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا النوع مرتبط بحسابات وموديول تسعير الطباعة؟",
                verbose_name="مرتبط بموديول التسعير والإنتاج",
            ),
        ),
        migrations.RunPython(backfill_pricing_suppliers, reverse_backfill),
    ]
