# Generated by Django 4.2.7 on 2025-10-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0006_add_specialized_services_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="has_price_tiers",
            field=models.BooleanField(
                default=True,
                help_text="إذا كان نشطاً، سيتم استخدام الشرائح السعرية بدلاً من الأسعار الثابتة",
                verbose_name="استخدام شرائح سعرية",
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="machine_model",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="موديل الماكينة"
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="max_paper_weight_gsm",
            field=models.PositiveIntegerField(
                default=300, verbose_name="أقصى وزن ورق (جرام)"
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="pages_per_minute_bw",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="صفحة/دقيقة أبيض وأسود"
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="pages_per_minute_color",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="صفحة/دقيقة ملون"
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="paper_size",
            field=models.CharField(
                choices=[
                    ("a4", "A4"),
                    ("a3", "A3"),
                    ("a3_plus", "A3+"),
                    ("sra3", "SRA3"),
                    ("custom", "مقاس مخصص"),
                ],
                default=0,
                max_length=20,
                verbose_name="مقاس الورق",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="setup_time_minutes",
            field=models.PositiveIntegerField(
                default=5, verbose_name="وقت الإعداد (دقائق)"
            ),
        ),
        migrations.AddField(
            model_name="digitalprintingdetails",
            name="supports_heavy_paper",
            field=models.BooleanField(default=False, verbose_name="يدعم الورق السميك"),
        ),
        migrations.AlterField(
            model_name="digitalprintingdetails",
            name="machine_type",
            field=models.CharField(
                choices=[
                    ("laser_mono", "ليزر أبيض وأسود"),
                    ("laser_color", "ليزر ملون"),
                    ("inkjet_large", "نفث حبر كبير"),
                    ("inkjet_small", "نفث حبر صغير"),
                    ("offset_digital", "أوفست ديجيتال"),
                    ("production_printer", "طابعة إنتاج"),
                ],
                max_length=30,
                verbose_name="نوع الماكينة",
            ),
        ),
        migrations.AlterField(
            model_name="supplierservicecategory",
            name="code",
            field=models.CharField(
                choices=[
                    ("paper", "مخزن ورق"),
                    ("offset_printing", "طباعة أوفست"),
                    ("digital_printing", "طباعة ديجيتال"),
                    ("finishing", "خدمات طباعة"),
                    ("plates", "مكتب فصل"),
                    ("packaging", "تغليف"),
                    ("design", "تصميم"),
                    ("outdoor", "أوت دور"),
                    ("laser", "ليزر"),
                    ("vip_gifts", "هدايا VIP"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                unique=True,
                verbose_name="الرمز",
            ),
        ),
        migrations.AlterField(
            model_name="suppliertype",
            name="code",
            field=models.CharField(
                choices=[
                    ("paper", "مخزن ورق"),
                    ("offset_printing", "مطبعة أوفست"),
                    ("digital_printing", "مطبعة ديجيتال"),
                    ("finishing", "خدمات طباعة"),
                    ("plates", "مكتب فصل"),
                    ("packaging", "تغليف"),
                    ("design", "تصميم"),
                    ("outdoor", "أوت دور"),
                    ("laser", "ليزر"),
                    ("vip_gifts", "هدايا VIP"),
                    ("other", "أخرى"),
                ],
                max_length=20,
                unique=True,
                verbose_name="الرمز",
            ),
        ),
        migrations.CreateModel(
            name="VIPGiftDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_category",
                    models.CharField(
                        choices=[
                            ("corporate", "هدايا شركات"),
                            ("promotional", "هدايا دعائية"),
                            ("awards", "جوائز وتكريمات"),
                            ("luxury", "هدايا فاخرة"),
                            ("personalized", "هدايا مخصصة"),
                            ("tech", "هدايا تقنية"),
                            ("accessories", "إكسسوارات"),
                        ],
                        max_length=30,
                        verbose_name="فئة الهدية",
                    ),
                ),
                (
                    "customization_type",
                    models.CharField(
                        choices=[
                            ("engraving", "حفر"),
                            ("printing", "طباعة"),
                            ("embossing", "نقش بارز"),
                            ("embroidery", "تطريز"),
                            ("laser_cutting", "قص ليزر"),
                            ("packaging", "تغليف مخصص"),
                        ],
                        max_length=30,
                        verbose_name="نوع التخصيص",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="اسم المنتج"),
                ),
                (
                    "product_description",
                    models.TextField(blank=True, verbose_name="وصف المنتج"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الماركة"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="بلد المنشأ"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر الأساسي"
                    ),
                ),
                (
                    "customization_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التخصيص",
                    ),
                ),
                (
                    "packaging_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التغطية",
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأدنى للكمية"
                    ),
                ),
                (
                    "max_customization_chars",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="أقصى عدد أحرف للتخصيص"
                    ),
                ),
                (
                    "production_time_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="وقت الإنتاج (أيام)"
                    ),
                ),
                (
                    "includes_gift_box",
                    models.BooleanField(default=True, verbose_name="يشمل علبة هدايا"),
                ),
                (
                    "includes_certificate",
                    models.BooleanField(default=False, verbose_name="يشمل شهادة"),
                ),
                (
                    "includes_delivery",
                    models.BooleanField(default=False, verbose_name="يشمل التوصيل"),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التوصيل",
                    ),
                ),
                (
                    "includes_setup_service",
                    models.BooleanField(
                        default=False, verbose_name="يشمل خدمة الإعداد"
                    ),
                ),
                (
                    "setup_service_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة خدمة الإعداد",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_gift_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل هدايا VIP",
                "verbose_name_plural": "تفاصيل هدايا VIP",
            },
        ),
        migrations.CreateModel(
            name="PlateServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_size",
                    models.CharField(
                        choices=[
                            ("35x50", "35×50 سم"),
                            ("50x70", "50×70 سم"),
                            ("70x100", "70×100 سم"),
                            ("custom", "مقاس مخصص"),
                        ],
                        max_length=20,
                        verbose_name="مقاس الزنك",
                    ),
                ),
                (
                    "plate_type",
                    models.CharField(
                        choices=[
                            ("positive", "زنك موجب"),
                            ("negative", "زنك سالب"),
                            ("thermal", "زنك حراري"),
                            ("uv", "زنك UV"),
                        ],
                        max_length=20,
                        verbose_name="نوع الزنك",
                    ),
                ),
                (
                    "custom_width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "price_per_plate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الزنك الواحد"
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الانتقالات",
                    ),
                ),
                (
                    "min_plates_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="الحد الأدنى لعدد الزنكات"
                    ),
                ),
                (
                    "turnaround_time_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="وقت التسليم (ساعات)"
                    ),
                ),
                (
                    "includes_proofing",
                    models.BooleanField(default=True, verbose_name="يشمل البروفة"),
                ),
                (
                    "digital_proof_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة البروفة الرقمية",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plate_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة زنكات",
                "verbose_name_plural": "تفاصيل خدمات الزنكات",
            },
        ),
        migrations.CreateModel(
            name="OutdoorPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("vinyl", "فينيل"),
                            ("banner", "بنر"),
                            ("mesh", "شبك"),
                            ("canvas", "كانفاس"),
                            ("backlit", "باك لايت"),
                            ("one_way_vision", "ون واي فيجن"),
                            ("adhesive_vinyl", "فينيل لاصق"),
                        ],
                        max_length=30,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "printing_type",
                    models.CharField(
                        choices=[
                            ("digital_large_format", "طباعة رقمية كبيرة"),
                            ("eco_solvent", "إيكو سولفنت"),
                            ("latex", "لاتكس"),
                            ("uv", "UV"),
                        ],
                        max_length=30,
                        verbose_name="نوع الطباعة",
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى عرض (سم)"
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="أقصى ارتفاع (سم)",
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر المتر المربع"
                    ),
                ),
                (
                    "min_order_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="الحد الأدنى (متر مربع)",
                    ),
                ),
                (
                    "includes_hemming",
                    models.BooleanField(default=False, verbose_name="يشمل الحياكة"),
                ),
                (
                    "hemming_cost_per_meter",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الحياكة للمتر",
                    ),
                ),
                (
                    "includes_grommets",
                    models.BooleanField(default=False, verbose_name="يشمل الحلقات"),
                ),
                (
                    "grommet_cost_each",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الحلقة الواحدة",
                    ),
                ),
                (
                    "production_time_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="وقت الإنتاج (أيام)"
                    ),
                ),
                (
                    "includes_installation",
                    models.BooleanField(default=False, verbose_name="يشمل التركيب"),
                ),
                (
                    "installation_cost_per_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التركيب للمتر المربع",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdoor_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل أوت دور",
                "verbose_name_plural": "تفاصيل أوت دور",
            },
        ),
        migrations.CreateModel(
            name="OffsetPrintingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("heidelberg_sm52", "هايدلبرج SM52"),
                            ("heidelberg_sm74", "هايدلبرج SM74"),
                            ("heidelberg_sm102", "هايدلبرج SM102"),
                            ("komori_ls40", "كوموري LS40"),
                            ("komori_ls29", "كوموري LS29"),
                            ("ryobi_524", "ريوبي 524"),
                            ("gto_52", "GTO 52"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع الماكينة",
                    ),
                ),
                (
                    "machine_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="موديل الماكينة"
                    ),
                ),
                (
                    "sheet_size",
                    models.CharField(
                        choices=[
                            ("35x50", "35×50 سم"),
                            ("50x70", "50×70 سم"),
                            ("70x100", "70×100 سم"),
                            ("custom", "مقاس مخصص"),
                        ],
                        max_length=20,
                        verbose_name="مقاس الفرخ",
                    ),
                ),
                (
                    "custom_width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="العرض المخصص (سم)",
                    ),
                ),
                (
                    "custom_height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="الارتفاع المخصص (سم)",
                    ),
                ),
                (
                    "plate_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="تكلفة اللوح الواحد",
                    ),
                ),
                (
                    "color_calibration_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة معايرة الألوان",
                    ),
                ),
                (
                    "impression_cost_per_1000",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="تكلفة الفرخ لكل 1000",
                    ),
                ),
                (
                    "min_impressions",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="الحد الأدنى للفرخات"
                    ),
                ),
                (
                    "max_colors",
                    models.PositiveIntegerField(
                        default=4, verbose_name="أقصى عدد ألوان"
                    ),
                ),
                (
                    "has_uv_coating",
                    models.BooleanField(default=False, verbose_name="طلاء UV"),
                ),
                (
                    "has_aqueous_coating",
                    models.BooleanField(default=False, verbose_name="طلاء مائي"),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offset_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل طباعة أوفست",
                "verbose_name_plural": "تفاصيل طباعة أوفست",
            },
        ),
        migrations.CreateModel(
            name="LaserServiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laser_type",
                    models.CharField(
                        choices=[
                            ("co2", "CO2 ليزر"),
                            ("fiber", "فايبر ليزر"),
                            ("diode", "دايود ليزر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الليزر",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cutting", "قص"),
                            ("engraving", "حفر"),
                            ("marking", "تعليم"),
                            ("cutting_engraving", "قص وحفر"),
                        ],
                        max_length=30,
                        verbose_name="نوع الخدمة",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("wood", "خشب"),
                            ("acrylic", "أكريليك"),
                            ("mdf", "MDF"),
                            ("cardboard", "كرتون"),
                            ("leather", "جلد"),
                            ("fabric", "قماش"),
                            ("metal", "معدن"),
                            ("glass", "زجاج"),
                            ("plastic", "بلاستيك"),
                        ],
                        max_length=20,
                        verbose_name="نوع المادة",
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى عرض (سم)"
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="أقصى ارتفاع (سم)"
                    ),
                ),
                (
                    "max_thickness_mm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="أقصى سمك (مم)"
                    ),
                ),
                (
                    "price_per_minute",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر الدقيقة",
                    ),
                ),
                (
                    "price_per_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر السنتيمتر",
                    ),
                ),
                (
                    "price_per_piece",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="سعر القطعة",
                    ),
                ),
                (
                    "setup_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة الإعداد",
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "turnaround_time_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="وقت التسليم (ساعات)"
                    ),
                ),
                (
                    "includes_design",
                    models.BooleanField(default=False, verbose_name="يشمل التصميم"),
                ),
                (
                    "design_cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="تكلفة التصميم للساعة",
                    ),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laser_details",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل خدمة ليزر",
                "verbose_name_plural": "تفاصيل خدمات الليزر",
            },
        ),
        migrations.CreateModel(
            name="ServicePriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="مثال: 1-20، 21-50",
                        max_length=50,
                        verbose_name="اسم الشريحة",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="الحد الأدنى للكمية"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً للكمية المفتوحة",
                        null=True,
                        verbose_name="الحد الأقصى للكمية",
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="supplier.specializedservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "شريحة سعرية",
                "verbose_name_plural": "شرائح سعرية",
                "ordering": ["service", "display_order", "min_quantity"],
                "unique_together": {("service", "min_quantity")},
            },
        ),
    ]
