# Generated by Django 4.2.23 on 2025-10-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0008_add_supplier_service_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializedservice",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="supplier.suppliertype",
                verbose_name="فئة الخدمة",
            ),
        ),
        migrations.DeleteModel(
            name="SupplierServiceCategory",
        ),
    ]
