# Generated by Django 4.2.26 on 2026-09-06 14:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0002_initial"),
        ("supplier", "0008_sync_legacy_supplier_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=255, verbose_name="اسم الخدمة وقت التغيير"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        max_length=255, verbose_name="اسم المورد وقت التغيير"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاريخ ووقت التغيير",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "تعديل يدوي من صفحة الخدمة"),
                            ("QUICK_RENEW", "تجديد سريع لسريان السعر"),
                            ("ORDER_FLOW", "تحديث أثناء تسعير أمر شغل"),
                            ("BULK_PERCENTAGE", "تحديث مجمع بنسبة مئوية"),
                            ("INITIAL", "تسجيل السعر الأولي"),
                        ],
                        default="MANUAL",
                        max_length=30,
                        verbose_name="مصدر التغيير",
                    ),
                ),
                (
                    "quote_reference",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="رقم عرض السعر المرجعي / الإثبات",
                    ),
                ),
                (
                    "exchange_rate_at_change",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف وقت التغيير",
                    ),
                ),
                (
                    "old_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="سعر الوحدة القديم",
                    ),
                ),
                (
                    "new_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="سعر الوحدة الجديد",
                    ),
                ),
                (
                    "price_variance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="نسبة التغير السعري (%)",
                    ),
                ),
                (
                    "old_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="اللقطة الكاملة السابقة"
                    ),
                ),
                (
                    "new_snapshot",
                    models.JSONField(
                        default=dict, verbose_name="اللقطة الكاملة الجديدة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات التغيير")),
            ],
            options={
                "verbose_name": "سجل تاريخ سعر الخدمة",
                "verbose_name_plural": "سجلات تاريخ أسعار الخدمات",
                "db_table": "supplier_service_price_history",
                "ordering": ["-change_date"],
            },
        ),
        migrations.AddField(
            model_name="servicetype",
            name="default_validity_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="الفترة الافتراضية لصلاحية أسعار هذا النوع من الخدمات بالأيام",
                verbose_name="صلاحية السعر الافتراضية بالأيام",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="is_tax_inclusive",
            field=models.BooleanField(
                default=False,
                help_text="هل هذا السعر يتضمن ضريبة القيمة المضافة (14%)؟",
                verbose_name="السعر شامل ضريبة القيمة المضافة",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="price_updated_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ آخر تحديث للسعر",
            ),
        ),
        migrations.AddField(
            model_name="supplierservice",
            name="price_valid_until",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="تاريخ انتهاء سريان السعر المعطى من المورد",
                null=True,
                verbose_name="تاريخ انتهاء الصلاحية",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierservice",
            index=models.Index(
                fields=["service_type", "is_active", "price_valid_until"],
                name="supplier_su_service_e1ab38_idx",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_price_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المسؤول",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_price_histories",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_history",
                to="supplier.supplierservice",
                verbose_name="الخدمة",
            ),
        ),
        migrations.AddField(
            model_name="servicepricehistory",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_price_history",
                to="supplier.supplier",
                verbose_name="المورد",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["service", "-change_date"],
                name="supplier_se_service_2dabaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["supplier", "-change_date"],
                name="supplier_se_supplie_084e9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepricehistory",
            index=models.Index(
                fields=["change_source"], name="supplier_se_change__9ea3ab_idx"
            ),
        ),
    ]
