# Generated by Django 4.2.23 on 2025-10-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0017_add_offset_printing_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalprintingdetails",
            name="max_height_cm",
        ),
        migrations.RemoveField(
            model_name="digitalprintingdetails",
            name="max_width_cm",
        ),
    ]
