# Generated by Django 4.2.23 on 2025-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0022_update_plate_service_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='تقييم من 0 إلى 5', max_digits=3, verbose_name='تقييم المورد'),
        ),
    ]
