# Generated by Django 4.2.23 on 2025-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0023_add_supplier_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliertype",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, verbose_name="الرابط"),
        ),
    ]
