# Generated by Django 4.2.23 on 2025-10-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0024_suppliertype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='الرابط'),
        ),
    ]
