# Generated by Django 4.2.7 on 2025-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0026_update_coating_terminology"),
    ]

    operations = [
        migrations.AddField(
            model_name="specializedservice",
            name="specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="البيانات المتخصصة حسب نوع الخدمة (ورق، طباعة، إلخ)",
                verbose_name="المواصفات المتخصصة",
            ),
        ),
    ]
