# Generated by Django 4.2.23 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0027_specializedservice_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laserservicedetails',
            name='design_cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='laserservicedetails',
            name='includes_design',
        ),
        migrations.RemoveField(
            model_name='specializedservice',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='finishingservicedetails',
            name='finishing_type',
            field=models.CharField(choices=[('cutting', 'قص'), ('folding', 'طي'), ('binding_spiral', 'تجليد حلزوني'), ('binding_perfect', 'تجليد كعب'), ('lamination', 'تقفيل'), ('uv_coating', 'طلاء UV'), ('embossing', 'نقش بارز'), ('die_cutting', 'تكسير'), ('perforation', 'تثقيب'), ('stapling', 'تدبيس')], max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='paperservicedetails',
            name='paper_type',
            field=models.CharField(max_length=100, verbose_name='نوع الورق'),
        ),
        migrations.AlterField(
            model_name='paperservicedetails',
            name='sheet_size',
            field=models.CharField(max_length=50, verbose_name='مقاس الفرخ'),
        ),
        migrations.AlterField(
            model_name='plateservicedetails',
            name='plate_size',
            field=models.CharField(max_length=50, verbose_name='مقاس الزنك'),
        ),
        migrations.AlterField(
            model_name='supplierservicetag',
            name='category',
            field=models.CharField(choices=[('printing', 'طباعة'), ('paper', 'ورق'), ('finishing', 'تشطيب'), ('packaging', 'تقفيل'), ('binding', 'تجليد'), ('cutting', 'قص'), ('coating', 'تغطية'), ('digital', 'خدمات رقمية'), ('logistics', 'لوجستيات'), ('other', 'أخرى')], help_text='تصنيف الخدمة حسب النوع', max_length=20, verbose_name='فئة الخدمة'),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='code',
            field=models.CharField(choices=[('paper', 'مخزن ورق'), ('offset_printing', 'مطبعة أوفست'), ('digital_printing', 'مطبعة ديجيتال'), ('finishing', 'خدمات الطباعة'), ('plates', 'مكتب فصل'), ('packaging', 'تقفيل'), ('coating', 'تغطية'), ('outdoor', 'أوت دور'), ('laser', 'ليزر'), ('vip_gifts', 'هدايا VIP'), ('other', 'أخرى')], max_length=20, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='vipgiftdetails',
            name='customization_type',
            field=models.CharField(choices=[('engraving', 'حفر'), ('printing', 'طباعة'), ('embossing', 'نقش بارز'), ('embroidery', 'تطريز'), ('laser_cutting', 'قص ليزر'), ('packaging', 'تقفيل')], max_length=30, verbose_name='نوع التخصيص'),
        ),
    ]
