# Generated by Django 4.2.7 on 2025-10-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0021_add_is_default_to_coating_type"),
        ("supplier", "0027_specializedservice_specifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specializedservice",
            name="specifications",
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="paper_origin",
            field=models.ForeignKey(
                blank=True,
                help_text="بلد منشأ الورق",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.paperorigin",
                verbose_name="منشأ الورق",
            ),
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="paper_size",
            field=models.ForeignKey(
                blank=True,
                help_text="مقاس الورق المستخدم",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.papersize",
                verbose_name="مقاس الورق",
            ),
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="paper_type",
            field=models.ForeignKey(
                blank=True,
                help_text="نوع الورق المستخدم في هذه الخدمة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.papertype",
                verbose_name="نوع الورق",
            ),
        ),
        migrations.AddField(
            model_name="specializedservice",
            name="paper_weight",
            field=models.ForeignKey(
                blank=True,
                help_text="وزن الورق بالجرام",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pricing.paperweight",
                verbose_name="وزن الورق (جرام)",
            ),
        ),
    ]
