# Generated by Django 4.2.7 on 2025-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0028_add_paper_fields_to_specialized_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specializedservice",
            name="paper_origin",
        ),
        migrations.RemoveField(
            model_name="specializedservice",
            name="paper_size",
        ),
        migrations.RemoveField(
            model_name="specializedservice",
            name="paper_type",
        ),
        migrations.RemoveField(
            model_name="specializedservice",
            name="paper_weight",
        ),
        migrations.AlterField(
            model_name="paperservicedetails",
            name="paper_type",
            field=models.CharField(max_length=100, verbose_name="نوع الورق"),
        ),
        migrations.AlterField(
            model_name="paperservicedetails",
            name="sheet_size",
            field=models.CharField(max_length=50, verbose_name="مقاس الفرخ"),
        ),
    ]
