# Generated by Django 4.2.7 on 2025-10-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0028_remove_offset_choices_constraints"),
        ("supplier", "0029_update_paper_service_fields"),
    ]

    operations = []
