# Generated by Django 4.2.23 on 2025-10-20 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0029_merge_20251020_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرمز'),
        ),
        migrations.CreateModel(
            name='SupplierTypeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم نوع المورد كما سيظهر في الواجهة', max_length=100, verbose_name='اسم النوع')),
                ('code', models.CharField(help_text='رمز فريد لنوع المورد (بالإنجليزية)', max_length=50, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, help_text='وصف مختصر لنوع المورد', verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-truck', help_text='اسم الأيقونة من Font Awesome (مثل: fas fa-truck)', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#007bff', help_text='لون النوع بصيغة HEX (مثل: #007bff)', max_length=7, verbose_name='اللون')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتيب ظهور النوع في القوائم', verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, help_text='هل النوع نشط ويظهر في الواجهة؟', verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, help_text='الأنواع الأساسية التي لا يمكن حذفها', verbose_name='نوع نظام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_types', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_types', to=settings.AUTH_USER_MODEL, verbose_name='حُدث بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات نوع المورد',
                'verbose_name_plural': 'إعدادات أنواع الموردين',
                'db_table': 'supplier_type_settings',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='suppliertype',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_type', to='supplier.suppliertypesettings', verbose_name='إعدادات النوع'),
        ),
    ]
