# Generated by Django 4.2.23 on 2025-10-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0037_cleanup_design_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperservicedetails',
            name='price_per_sheet',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='سعر الفرخ'),
        ),
        migrations.AlterField(
            model_name='supplierservicetag',
            name='category',
            field=models.CharField(choices=[('printing', 'طباعة'), ('paper', 'ورق'), ('finishing', 'تشطيب'), ('packaging', 'تقفيل'), ('binding', 'تجليد'), ('cutting', 'قص'), ('coating', 'تغطية'), ('digital', 'خدمات رقمية'), ('logistics', 'لوجستيات'), ('other', 'أخرى')], help_text='تصنيف الخدمة حسب النوع', max_length=20, verbose_name='فئة الخدمة'),
        ),
    ]
