# Generated by Django 4.2.23 on 2025-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0038_increase_price_per_sheet_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperservicedetails',
            name='price_per_sheet',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الفرخ'),
        ),
    ]
