# Generated by Django 4.2.7 on 2025-10-22 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import financial.models.audit_trail


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("financial", "0001_initial_clean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الفاتورة"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ الفاتورة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("confirmed", "مؤكدة"),
                            ("cancelled", "ملغية"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الضريبة",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("credit", "آجل"),
                            ("bank_transfer", "تحويل بنكي"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "مدفوعة"),
                            ("partially_paid", "مدفوعة جزئياً"),
                            ("unpaid", "غير مدفوعة"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="حالة الدفع",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="product.warehouse",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة مبيعات",
                "verbose_name_plural": "فواتير المبيعات",
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.sale",
                        verbose_name="الفاتورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند الفاتورة",
                "verbose_name_plural": "بنود الفاتورة",
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم المرتجع"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاريخ المرتجع")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المجموع الفرعي"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الضريبة",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("confirmed", "مؤكد"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sale.sale",
                        verbose_name="فاتورة المبيعات",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns",
                        to="product.warehouse",
                        verbose_name="المخزن",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرتجع مبيعات",
                "verbose_name_plural": "مرتجعات المبيعات",
                "ordering": ["-date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="الكمية")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="الإجمالي"
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="سبب الإرجاع"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_items",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sale.saleitem",
                        verbose_name="بند المبيعات",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.salereturn",
                        verbose_name="مرتجع المبيعات",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند مرتجع مبيعات",
                "verbose_name_plural": "بنود مرتجعات المبيعات",
            },
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="تاريخ الدفع")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bank_transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        max_length=20,
                        verbose_name="طريقة الدفع",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم المرجع"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "financial_status",
                    models.CharField(
                        choices=[
                            ("pending", "معلق"),
                            ("synced", "مربوط"),
                            ("failed", "فشل"),
                            ("manual", "يدوي"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة الربط المالي",
                    ),
                ),
                (
                    "financial_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="خطأ الربط المالي"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "مسودة"), ("posted", "مرحّلة")],
                        default="draft",
                        help_text="المسودات يمكن تعديلها، المرحّلة لا يمكن تعديلها",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الترحيل"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_payments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="الخزينة أو البنك المستخدم للدفع",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financial.chartofaccounts",
                        verbose_name="الحساب المالي",
                    ),
                ),
                (
                    "financial_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="المعاملة المالية",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_payments_posted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رحّلها",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sale.sale",
                        verbose_name="الفاتورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة الفاتورة",
                "verbose_name_plural": "دفعات الفواتير",
                "ordering": ["-payment_date"],
            },
            bases=(financial.models.audit_trail.PaymentAuditMixin, models.Model),
        ),
    ]
