# Generated by Django 4.2.26 on 2026-08-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_inventorycostlayer_warehouse_and_more"),
        ("sale", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_notes",
                to="product.warehouse",
                verbose_name="المخزن",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="product.warehouse",
                verbose_name="المخزن",
            ),
        ),
    ]
