# Generated by Django 4.2.26 on 2026-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotation",
            options={
                "ordering": ["-date", "-number"],
                "permissions": [
                    ("convert_quotation", "تحويل عروض الأسعار إلى فواتير"),
                    ("change_quotation_price", "تعديل أسعار عروض الأسعار"),
                    ("view_all_quotations", "الاطلاع على عروض أسعار كافة المناديب"),
                    ("convert_to_order", "تحويل عرض السعر إلى أمر بيع"),
                ],
                "verbose_name": "عرض سعر",
                "verbose_name_plural": "عروض الأسعار",
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-date", "-number"],
                "permissions": [
                    (
                        "change_sale_salesman",
                        "تغيير مسؤول المبيعات في الفواتير وعروض الأسعار",
                    ),
                    ("manage_custom_fields", "إدارة وتعديل الحقول الإضافية المخصصة"),
                    ("change_unit_price", "تعديل سعر البيع الرسمي"),
                    ("apply_special_discount", "تطبيق خصم إضافي/استثنائي"),
                    ("cancel_approved_sale", "إلغاء فاتورة مبيعات معتمدة"),
                    ("print_sale_invoice", "طباعة فاتورة المبيعات"),
                    ("view_all_sales", "الاطلاع على فواتير كافة المناديب"),
                ],
                "verbose_name": "فاتورة مبيعات",
                "verbose_name_plural": "فواتير المبيعات",
            },
        ),
    ]
