# Generated by Django 5.2.17 on 2026-09-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date', '-id'], 'permissions': [('approve_sales_order', 'اعتماد أمر البيع'), ('change_sales_order_price', 'تعديل أسعار أوامر البيع'), ('view_all_salesorders', 'الاطلاع على أوامر بيع كافة المناديب')], 'verbose_name': 'أمر بيع', 'verbose_name_plural': 'أوامر البيع'},
        ),
    ]
