# Generated by Django 4.2.26 on 2026-08-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0006_unify_and_cleanup_tax_codes"),
        ("sale", "0003_alter_deliverynote_warehouse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="financial.costcenter",
                verbose_name="مركز التكلفة الرئيسي",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_invoices_direct",
                to="sale.deliverynote",
                verbose_name="إذن التسليم المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_invoices_direct",
                to="sale.salesorder",
                verbose_name="أمر البيع المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="financial.costcenter",
                verbose_name="مركز التكلفة",
            ),
        ),
    ]
