# Generated by Django 4.2.7 on 2025-09-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0007_add_bank_reconciliation"),
        ("sale", "0003_salepayment_financial_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="financial.journalentry",
                verbose_name="القيد المحاسبي",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("confirmed", "مؤكدة"),
                    ("cancelled", "ملغية"),
                ],
                default="confirmed",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
