# Generated by Django 5.2.17 on 2026-09-21 20:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_salesorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12, verbose_name='سعر الصرف'),
        ),
    ]
