# Generated by Django 4.2.23 on 2025-09-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_accountingperiod_status'),
        ('sale', '0004_sale_journal_entry_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='cash_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.cashmovement', verbose_name='حركة الخزن'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='الخزينة أو البنك المستخدم للدفع', null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.chartofaccounts', verbose_name='الحساب المالي'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='financial_error',
            field=models.TextField(blank=True, null=True, verbose_name='خطأ الربط المالي'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='financial_status',
            field=models.CharField(choices=[('pending', 'معلق'), ('synced', 'مربوط'), ('failed', 'فشل'), ('manual', 'يدوي')], default='pending', max_length=20, verbose_name='حالة الربط المالي'),
        ),
    ]
