# Generated by Django 4.2.26 on 2026-08-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_inventorymovement_purpose_type"),
        ("sale", "0004_sale_cost_center_sale_delivery_note_sale_sales_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="aggregation_type",
            field=models.CharField(
                choices=[
                    ("LINE_ONLY", "على مستوى السطر المنفرد"),
                    ("CATEGORY_TOTAL", "تجميع كميات نفس الفئة في السلة"),
                ],
                default="LINE_ONLY",
                max_length=20,
                verbose_name="طريقة تجميع الكميات",
            ),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_rules",
                to="product.product",
                verbose_name="المنتج المحدد (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="scope",
            field=models.CharField(
                choices=[
                    ("ITEM", "خصم تجاري على مستوى البند"),
                    ("INVOICE", "خصم تسوية إجمالي على الفاتورة"),
                ],
                default="ITEM",
                max_length=20,
                verbose_name="نطاق الخصم",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="sale.pricelist",
                verbose_name="قائمة الأسعار",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="price_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="تفاصيل وحيثيات احتساب السعر وقواعد الخصم المطبقة للتدقيق المالي",
                verbose_name="لقطة تفاصيل السعر والخصم",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="sale.pricelist",
                verbose_name="قائمة الأسعار",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="price_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="تفاصيل وحيثيات احتساب السعر وقواعد الخصم المطبقة للتدقيق المالي",
                verbose_name="لقطة تفاصيل السعر والخصم",
            ),
        ),
        migrations.AddIndex(
            model_name="discountrule",
            index=models.Index(
                fields=[
                    "customer",
                    "category",
                    "product",
                    "is_active",
                    "effective_date",
                ],
                name="sale_discou_custome_977329_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountrule",
            index=models.Index(
                fields=["product", "is_active"], name="sale_discou_product_a51717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountrule",
            index=models.Index(
                fields=["category", "is_active"], name="sale_discou_categor_3f76ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountrule",
            index=models.Index(
                fields=["is_active", "priority"], name="sale_discou_is_acti_f36e13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["is_active", "effective_from", "effective_to"],
                name="sale_pricel_is_acti_bbdda2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["customer_type", "is_active"],
                name="sale_pricel_custome_4d57c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistitem",
            index=models.Index(
                fields=["price_list", "product", "is_active", "effective_date"],
                name="sale_pricel_price_l_6ff9bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistitem",
            index=models.Index(
                fields=["product", "is_active"], name="sale_pricel_product_99ad77_idx"
            ),
        ),
    ]
