# Generated by Django 4.2.26 on 2026-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0004_quotation_quotationitem_sale_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="tax_active",
            field=models.BooleanField(default=True, verbose_name="الضريبة نشطة"),
        ),
    ]
