# Generated by Django 5.2.17 on 2026-10-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_financialaccountrole'),
        ('product', '0004_product_pricing_currency'),
        ('sale', '0004_alter_creditnote_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='المخزن الفعلي المعتمد لصرف هذا البند', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='product.warehouse', verbose_name='المخزن المنصرف منه'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='product.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['warehouse'], name='sale_saleit_warehou_015701_idx'),
        ),
    ]
