# Generated by Django 4.2.26 on 2026-08-23 19:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0009_alter_journalentry_entry_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0005_discountrule_aggregation_type_discountrule_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="delivery_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات التسليم والبوابة"
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اسم السائق"
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="driver_phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="هاتف السائق"
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="truck_plate_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم لوحة الشاحنة"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="adjustment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ التسوية",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="adjustment_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اسم التسوية"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financial.costcenter",
                verbose_name="مركز التكلفة",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=list, verbose_name="الحقول الإضافية"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="قيمة الخصم",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_type",
            field=models.CharField(
                default="fixed", max_length=10, verbose_name="نوع الخصم"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="expected_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ التسليم المتوقع"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="الشروط والملاحظات"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="required_down_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="الدفعة المقدمة المطلوبة",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="reservation_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ انتهاء مهلة الحجز"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="salesman",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="عنوان التسليم الفعلي"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("PICKUP", "استلام من المخزن"),
                    ("COMPANY_FLEET", "أسطول سيارات الشركة"),
                    ("COURIER", "شركة شحن خارجية"),
                ],
                default="PICKUP",
                max_length=20,
                verbose_name="طريقة التوصيل",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المجموع الفرعي",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="الضريبة التقديرية (VAT)",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("14.00"),
                max_digits=5,
                verbose_name="نسبة القيمة المضافة %",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="wht_active",
            field=models.BooleanField(default=False, verbose_name="خصم المنبع نشط"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="wht_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ خصم المنبع",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="wht_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="نسبة خصم المنبع %",
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="module",
            field=models.CharField(
                choices=[
                    ("quotation", "عروض الأسعار"),
                    ("sales_order", "أوامر البيع"),
                    ("sale", "فواتير المبيعات"),
                    ("both", "عروض الأسعار وفواتير المبيعات"),
                    ("all", "الكل (عروض الأسعار، أوامر البيع، والفواتير)"),
                ],
                default="both",
                max_length=20,
                verbose_name="الموديول المستهدف",
            ),
        ),
    ]
