# Generated by Django 4.2.26 on 2026-07-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("work_order", "__first__"),
        ("sale", "0005_quotation_tax_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="work_order.workorder",
                verbose_name="أمر الشغل المرتبط",
            ),
        ),
    ]
