# Generated by Django 4.2.23 on 2025-09-30 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0005_add_financial_integration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="posted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الترحيل"
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_payments_posted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رحّلها",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="status",
            field=models.CharField(
                choices=[("draft", "مسودة"), ("posted", "مرحّلة")],
                default="draft",
                help_text="المسودات يمكن تعديلها، المرحّلة لا يمكن تعديلها",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
    ]
