# Generated by Django 4.2.26 on 2026-08-23 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0006_deliverynote_delivery_notes_deliverynote_driver_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="down_payment_override",
            field=models.BooleanField(
                default=False, verbose_name="تجاوز شرط الدفعة المقدمة إدارياً"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="down_payment_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders_overridden",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التجاوز بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="down_payment_override_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="سبب التجاوز الإداري"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="down_payment_type",
            field=models.CharField(
                choices=[("fixed", "مبلغ ثابت"), ("percentage", "نسبة مئوية")],
                default="fixed",
                max_length=15,
                verbose_name="نوع الدفعة المقدمة",
            ),
        ),
    ]
