# Generated by Django 4.2.26 on 2026-07-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_customerpayment_work_order"),
        ("sale", "0006_quotation_work_order_sale_work_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="customer_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="client.customerpayment",
                verbose_name="دفعة العميل المقدمة",
            ),
        ),
    ]
