# Generated by Django 4.2.7 on 2025-10-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0006_salepayment_posted_at_salepayment_posted_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salepayment",
            name="cash_movement",
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "نقدي"),
                    ("credit", "آجل"),
                    ("bank_transfer", "تحويل بنكي"),
                ],
                max_length=20,
                verbose_name="طريقة الدفع",
            ),
        ),
    ]
