# Generated by Django 4.2.26 on 2026-08-27 01:00

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0007_salesorder_down_payment_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="exempt_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المجموع الفرعي المعفى من الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="taxable_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="المجموع الفرعي الخاضع للضريبة",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="is_taxable",
            field=models.BooleanField(
                default=True,
                help_text="هل البند خاضع لضريبة القيمة المضافة",
                verbose_name="خاضع للضريبة",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="table_tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="table_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="قيمة الضريبة المحسوبة للبند",
                max_digits=12,
                verbose_name="مبلغ الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="نسبة ضريبة القيمة المضافة للبند",
                max_digits=6,
                verbose_name="نسبة الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="is_taxable",
            field=models.BooleanField(
                default=True,
                help_text="هل البند خاضع لضريبة القيمة المضافة",
                verbose_name="خاضع للضريبة",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="table_tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="table_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="قيمة الضريبة المحسوبة للبند",
                max_digits=12,
                verbose_name="مبلغ الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="نسبة ضريبة القيمة المضافة للبند",
                max_digits=6,
                verbose_name="نسبة الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="salereturnitem",
            name="is_taxable",
            field=models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
        ),
        migrations.AddField(
            model_name="salereturnitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="مبلغ الضريبة"
            ),
        ),
        migrations.AddField(
            model_name="salereturnitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="نسبة الضريبة"
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="is_taxable",
            field=models.BooleanField(default=True, verbose_name="خاضع للضريبة"),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="table_tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="table_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة ضريبة الجدول",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ الضريبة",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="نسبة الضريبة",
            ),
        ),
        migrations.AlterField(
            model_name="discountrule",
            name="effective_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="تاريخ البدء"
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="effective_from",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="تاريخ بدء السريان",
            ),
        ),
        migrations.AlterField(
            model_name="pricelistitem",
            name="effective_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="تاريخ السريان"
            ),
        ),
    ]
