# Generated by Django 4.2.26 on 2026-07-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0008_sale_adjustment_amount_sale_adjustment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salepayment",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="sale.sale",
                verbose_name="الفاتورة",
            ),
        ),
    ]
