# Generated by Django 4.2.26 on 2026-08-01 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0009_alter_salepayment_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="salesman",
            field=models.ForeignKey(
                blank=True,
                help_text="المستخدم أو مسؤول المبيعات الخاص بعرض السعر",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="salesman",
            field=models.ForeignKey(
                blank=True,
                help_text="المستخدم أو مسؤول المبيعات الخاص بالفاتورة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مسؤول المبيعات",
            ),
        ),
    ]
