# Generated by Django 4.2.26 on 2026-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0010_quotation_salesman_sale_salesman"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="مفتاح فريد كود إنجليزي يولد آلياً",
                        max_length=100,
                        unique=True,
                        verbose_name="المفتاح الفريد",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل بالعربي"),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("quotation", "عروض الأسعار"),
                            ("sale", "فواتير المبيعات"),
                            ("both", "عروض الأسعار وفواتير المبيعات"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="الموديول المستهدف",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "نص قصير"),
                            ("number", "رقم"),
                            ("date", "تاريخ"),
                            ("select", "قائمة منسدلة"),
                            ("checkbox", "مربع اختيار (نعم/لا)"),
                            ("textarea", "نص طويل"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="نوع البيانات",
                    ),
                ),
                (
                    "select_options",
                    models.TextField(
                        blank=True,
                        help_text="مفصولة بفاصلة (,) في حال اختيار قائمة منسدلة",
                        null=True,
                        verbose_name="خيارات القائمة المنسدلة",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="إجباري في النموذج"
                    ),
                ),
                (
                    "show_on_print",
                    models.BooleanField(
                        default=True, verbose_name="إظهار في طباعة A4 و PDF"
                    ),
                ),
                (
                    "show_on_thermal",
                    models.BooleanField(
                        default=False, verbose_name="إظهار في الطباعة الحرارية 80mm"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب الظهور"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تعريف حقل إضافي",
                "verbose_name_plural": "تعاريف الحقول الإضافية",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["-date", "-number"],
                "permissions": [
                    (
                        "change_sale_salesman",
                        "تغيير مسؤول المبيعات في الفواتير وعروض الأسعار",
                    ),
                    ("manage_custom_fields", "إدارة وتعديل الحقول الإضافية المخصصة"),
                ],
                "verbose_name": "فاتورة مبيعات",
                "verbose_name_plural": "فواتير المبيعات",
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="مصفوفة الحقول الإضافية المخصصة",
                verbose_name="الحقول الإضافية",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="مصفوفة الحقول الإضافية المخصصة",
                verbose_name="الحقول الإضافية",
            ),
        ),
    ]
