# Generated by Django 4.2.26 on 2026-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0011_customfielddefinition_alter_sale_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfielddefinition",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="اسم الحقل بالإنجليزية",
            ),
        ),
    ]
