# Generated by Django 4.2.26 on 2026-08-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0012_customfielddefinition_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfielddefinition",
            name="show_in_header",
            field=models.BooleanField(
                default=False,
                help_text="إذا تم تفعيله، سيظهر الحقل في قسم بيانات الفاتورة الرئيسي العلوي بدلاً من قسم الحقول المخصصة",
                verbose_name="إظهار في قسم معلومات الفاتورة (أعلى الصفحة)",
            ),
        ),
    ]
