# Generated by Django 4.2.26 on 2026-08-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0013_customfielddefinition_show_in_header"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["-date", "-number"], name="sale_quotat_date_ea7214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["customer", "-date"], name="sale_quotat_custome_078981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["status", "-date"], name="sale_quotat_status_084547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["-date", "-number"], name="sale_sale_date_fbb80d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer", "-date"], name="sale_sale_custome_815f6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["warehouse", "-date"], name="sale_sale_warehou_6f9586_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["payment_status", "-date"], name="sale_sale_payment_64cf4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["status", "-date"], name="sale_sale_status_125f5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["sale", "product"], name="sale_saleit_sale_id_1748c5_idx"
            ),
        ),
    ]
