# Generated by Django 4.2.26 on 2026-08-04 13:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_customertransaction_customerallocationaudit_and_more"),
        ("product", "0012_category_valuation_method"),
        ("sale", "0014_quotation_sale_quotat_date_ea7214_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم قائمة الأسعار"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "قائمة أسعار",
                "verbose_name_plural": "قوائم الأسعار",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="اسم قاعدة الخصم"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الحد الأدنى لقيمة الطلب",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_rules",
                        to="product.category",
                        verbose_name="فئة المنتج (اختياري)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_rules",
                        to="client.customer",
                        verbose_name="العميل (اختياري)",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة خصم",
                "verbose_name_plural": "قواعد الخصم",
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=12,
                        verbose_name="الحد الأدنى للكمية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.pricelist",
                        verbose_name="قائمة الأسعار",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_list_items",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "سعر بند في القائمة",
                "verbose_name_plural": "أسعار البنود في القوائم",
                "unique_together": {("price_list", "product", "min_quantity")},
            },
        ),
    ]
