# Generated by Django 4.2.26 on 2026-08-04 13:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial", "0015_enterpriseapprovalrule_enterpriseapprovalrequest"),
        ("client", "0004_customertransaction_customerallocationaudit_and_more"),
        ("product", "0012_category_valuation_method"),
        ("sale", "0015_pricelist_discountrule_pricelistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم إذن التسليم"
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="تاريخ التسليم")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("DELIVERED", "تم التسليم"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_notes",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد التكلفة (COGS)",
                    ),
                ),
            ],
            options={
                "verbose_name": "إذن تسليم مخزني",
                "verbose_name_plural": "أذون التسليم المخزنية",
                "ordering": ["-delivery_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivered_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المسلمة"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="سعر التكلفة (FIFO)",
                    ),
                ),
                (
                    "delivery_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.deliverynote",
                        verbose_name="إذن التسليم",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند إذن تسليم",
                "verbose_name_plural": "بنود أذون التسليم",
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم فاتورة المبيعات"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="تاريخ الفاتورة")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("POSTED", "مرحلة"),
                            ("PAID", "مسددة بالكامل"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بالعملة المخصصة",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بالعملة الوظيفية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "delivery_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="sale.deliverynote",
                        verbose_name="إذن التسليم المرتبط",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="القيد المحاسبي للإيراد",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاتورة مبيعات",
                "verbose_name_plural": "فواتير المبيعات",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم أمر البيع"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="تاريخ أمر البيع")),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="سعر الصرف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم للاعتماد"),
                            ("APPROVED", "معتمد"),
                            ("PARTIALLY_DELIVERED", "مسلم جزئياً"),
                            ("FULLY_DELIVERED", "مسلم بالكامل"),
                            ("CANCELLED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بعملة الفاتورة",
                    ),
                ),
                (
                    "functional_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="الإجمالي بالعملة الوظيفية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sale.pricelist",
                        verbose_name="قائمة الأسعار",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="product.warehouse",
                        verbose_name="المستودع",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر بيع",
                "verbose_name_plural": "أوامر البيع",
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المطلوبة"
                    ),
                ),
                (
                    "delivered_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المسلمة",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="سعر الوحدة الأصلي",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="نسبة الخصم %",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي السطر"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_items",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.salesorder",
                        verbose_name="أمر البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند أمر بيع",
                "verbose_name_plural": "بنود أوامر البيع",
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billed_qty",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المفوترة"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="سعر الوحدة"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="إجمالي السطر"
                    ),
                ),
                (
                    "dn_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="sale.deliverynoteitem",
                        verbose_name="بند إذن التسليم",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.salesinvoice",
                        verbose_name="فاتورة المبيعات",
                    ),
                ),
                (
                    "so_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="sale.salesorderitem",
                        verbose_name="بند أمر البيع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند فاتورة مبيعات",
                "verbose_name_plural": "بنود فواتير المبيعات",
            },
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sale.salesorder",
                verbose_name="أمر البيع",
            ),
        ),
        migrations.AddField(
            model_name="deliverynoteitem",
            name="so_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_items",
                to="sale.salesorderitem",
                verbose_name="بند أمر البيع الأصلي",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="sales_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_notes",
                to="sale.salesorder",
                verbose_name="أمر البيع",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_notes",
                to="product.warehouse",
                verbose_name="المستودع",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesinvoice",
            unique_together={("customer", "invoice_number")},
        ),
    ]
