# Generated by Django 4.2.26 on 2026-08-04 14:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_category_valuation_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0016_deliverynote_deliverynoteitem_salesinvoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="effective_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ البدء"
            ),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الانتهاء"
            ),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="priority",
            field=models.IntegerField(default=10, verbose_name="الأولوية"),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "نسبة مئوية"),
                    ("FIXED_AMOUNT", "مبلغ ثابت"),
                    ("TIERED_QUANTITY", "شريحة كمية"),
                ],
                default="PERCENTAGE",
                max_length=20,
                verbose_name="نوع القاعدة",
            ),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="قيمة الخصم الثابتة",
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="customer_type",
            field=models.CharField(
                blank=True,
                default="ALL",
                max_length=50,
                verbose_name="تصنيف العملاء المستهدف",
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="effective_from",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ بدء السريان"
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="effective_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ نهاية السريان"
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "نشطة"), ("INACTIVE", "غير نشطة")],
                default="ACTIVE",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="effective_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاريخ السريان"
            ),
        ),
        migrations.CreateModel(
            name="PricingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="السعر القديم"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="السعر الجديد"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="سبب التغيير")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="الوقت والتاريخ"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تغيير بواسطة",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sale.pricelist",
                        verbose_name="قائمة الأسعار",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_audit_logs",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق الأسعار",
                "verbose_name_plural": "سجلات تدقيق الأسعار",
                "ordering": ["-timestamp"],
            },
        ),
    ]
