# Generated by Django 4.2.26 on 2026-08-04 14:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0016_enterpriseapprovalrequest_requested_by_and_more"),
        ("sale", "0017_discountrule_effective_date_discountrule_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="approval_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="financial.enterpriseapprovalrequest",
                verbose_name="طلب الاعتماد المؤسسي",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="quotation_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_orders",
                to="sale.quotation",
                verbose_name="عرض السعر المرتبط",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="invoiced_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=15,
                verbose_name="الكمية المفوترة",
            ),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="price_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="لقطة التسعير المحوكمة"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("PENDING_APPROVAL", "معلق الاعتماد"),
                    ("APPROVED", "معتمد"),
                    ("CONFIRMED", "مؤكد"),
                    ("PARTIALLY_DELIVERED", "مسلم جزئياً"),
                    ("FULLY_DELIVERED", "مسلم بالكامل"),
                    ("PARTIALLY_INVOICED", "مفوتر جزئياً"),
                    ("INVOICED", "مفوتر بالكامل"),
                    ("CANCELLED", "ملغى"),
                ],
                default="DRAFT",
                max_length=30,
                verbose_name="الحالة",
            ),
        ),
    ]
