# Generated by Django 4.2.26 on 2026-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0018_salesorder_approval_request_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم السياسة"
                    ),
                ),
                (
                    "sales_mode",
                    models.CharField(
                        choices=[
                            ("FAST_CASH", "نقدي سريع بدون ائتمان"),
                            ("FAST_CREDIT", "آجل سريع محوكم بالائتمان"),
                            ("STANDARD", "معياري متعدد المراحل"),
                        ],
                        default="STANDARD",
                        max_length=20,
                        verbose_name="نمط المبيعات",
                    ),
                ),
                (
                    "require_credit_check",
                    models.BooleanField(
                        default=True, verbose_name="يتطلب فحص الائتمان"
                    ),
                ),
                (
                    "allow_fast_invoice",
                    models.BooleanField(
                        default=False, verbose_name="إصدار فاتورة سريعة مباشرة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "سياسة مبيعات",
                "verbose_name_plural": "سياسات المبيعات",
            },
        ),
    ]
