# Generated by Django 4.2.26 on 2026-08-04 15:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0019_taxevent_taxruleevaluationlog_and_more"),
        ("client", "0009_customerallocationaudit_reversed_audit_and_more"),
        ("product", "0013_inventoryreservation_inventoryreservationaudit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sale", "0019_salespolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorization_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم تصريح الإرجاع"
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_COMPLAINT", "شكوى عميل"),
                            ("WRONG_DELIVERY", "تسليم خاطئ"),
                            ("WARRANTY", "ضمان وسياسة الاستبدال"),
                            ("DAMAGED_SHIPMENT", "تلف أثناء الشحن"),
                        ],
                        default="CUSTOMER_COMPLAINT",
                        max_length=40,
                        verbose_name="تصنيف سبب الإرجاع",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="تفاصيل السبب والملاحظات"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الانتظار"),
                            ("APPROVED", "معتمد"),
                            ("REJECTED", "مرفوض"),
                            ("EXPIRED", "منتهي الصلاحية"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="حالة التصريح",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمد بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_authorizations",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصريح إرجاع مبيعات",
                "verbose_name_plural": "تصاريح إرجاع المبيعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم مستند الإرجاع"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم"),
                            ("UNDER_INSPECTION", "قيد الفحص الفني"),
                            ("INSPECTED", "تم الفحص"),
                            ("APPROVED", "موافق عليه"),
                            ("REJECTED", "مرفوض"),
                            ("PROCESSED", "تم التنفيذ المحاسبي والمخزني"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="DRAFT",
                        max_length=25,
                        verbose_name="حالة دورة مستند الإرجاع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sale.returnauthorization",
                        verbose_name="تصريح الإرجاع المرتبط",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="client.customer",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "delivery_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="sale.deliverynote",
                        verbose_name="إذن التسليم الأصلي",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_returns",
                        to="sale.salesinvoice",
                        verbose_name="فاتورة المبيعات المرتبطة",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="sale.salesorder",
                        verbose_name="أمر البيع الأصلي",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="product.warehouse",
                        verbose_name="مخزن الاستلام الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند إرجاع مبيعات",
                "verbose_name_plural": "مستندات إرجاع المبيعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_qty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="الكمية المطلوبة للإرجاع",
                    ),
                ),
                (
                    "approved_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية الموافق عليها",
                    ),
                ),
                (
                    "inspected_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المفحوصة فعلياً",
                    ),
                ),
                (
                    "restored_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المعادة للمخزون الصالح",
                    ),
                ),
                (
                    "unit_cost_restored",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="تكلفة الوحدة المرتجعة المستردة (FIFO Cost)",
                    ),
                ),
                (
                    "delivery_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sale.deliverynoteitem",
                        verbose_name="سطر إذن التسليم الأصلي",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="product.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "return_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sale.salesreturnheader",
                        verbose_name="مستند الإرجاع",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند مستند إرجاع المبيعات",
                "verbose_name_plural": "بنود مستندات إرجاع المبيعات",
            },
        ),
        migrations.CreateModel(
            name="SalesReturnInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_result",
                    models.CharField(
                        choices=[
                            ("GOOD", "سليم قابل للبيع"),
                            ("DAMAGED", "تالف يوجه للمحجر/التخريد"),
                            ("SCRAP_REJECTED", "مرفوض ومرفوض استلامه"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="نتيجة الفحص الفني",
                    ),
                ),
                (
                    "good_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية السليمة",
                    ),
                ),
                (
                    "damaged_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية التالفة",
                    ),
                ),
                (
                    "scrap_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="الكمية المرفوضة/المكهنة",
                    ),
                ),
                (
                    "unit_cost_restored",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=15,
                        verbose_name="تكلفة الوحدة من FIFO",
                    ),
                ),
                (
                    "damaged_disposition",
                    models.CharField(
                        choices=[
                            ("QUARANTINE", "تحويل لمخزن المحجر"),
                            ("SCRAP", "تخريد وتخفيض مخزون"),
                            ("WRITE_OFF", "إعدام خسارة"),
                            ("RETURN_TO_VENDOR", "إرجاع للمورد"),
                        ],
                        default="QUARANTINE",
                        max_length=30,
                        verbose_name="قرار التعامل مع التالف",
                    ),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الفحص"),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فحص بواسطة",
                    ),
                ),
                (
                    "return_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="sale.salesreturnitem",
                        verbose_name="بند الإرجاع",
                    ),
                ),
            ],
            options={
                "verbose_name": "فحص جودة مرتجع مبيعات",
                "verbose_name_plural": "سجلات فحص جودة مرتجعات المبيعات",
                "ordering": ["-inspected_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="نوع الحدث"),
                ),
                (
                    "old_status",
                    models.CharField(max_length=30, verbose_name="الحالة السابقة"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=30, verbose_name="الحالة الجديدة"),
                ),
                (
                    "inspection_result",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="نتيجة الفحص الفني",
                    ),
                ),
                (
                    "movement_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مرجع حركة المخزون",
                    ),
                ),
                (
                    "journal_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="مرجع القيد المحاسبي",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="معرف التتبع Correlation UUID",
                    ),
                ),
                (
                    "processed_event_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="معرف الحدث المعالج الفريد",
                    ),
                ),
                (
                    "audit_hash",
                    models.CharField(
                        max_length=64, verbose_name="التوقيع المشفر Canonical SHA256"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.journalentry",
                        verbose_name="قيد الأستاذ",
                    ),
                ),
                (
                    "return_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="sale.salesreturnheader",
                        verbose_name="مستند الإرجاع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تدقيق مرتجع المبيعات",
                "verbose_name_plural": "سجلات تدقيق مرتجعات المبيعات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnCostTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_stock_movement_id",
                    models.IntegerField(verbose_name="معرف حركة الصرف الأصلي"),
                ),
                (
                    "delivery_document_number",
                    models.CharField(
                        max_length=100, verbose_name="رقم إذن التسليم الأصلي"
                    ),
                ),
                (
                    "fifo_layer_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="معرف طبقة FIFO"
                    ),
                ),
                (
                    "original_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="الكمية الأصلية المسلمة",
                    ),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="الكمية المرتجعة"
                    ),
                ),
                (
                    "original_unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="تكلفة الوحدة الأصلية",
                    ),
                ),
                (
                    "restored_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="إجمالي القيمة المستردة (EGP)",
                    ),
                ),
                (
                    "return_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_traces",
                        to="sale.salesreturnitem",
                        verbose_name="بند الإرجاع",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تتبع تكلفة المرتجع FIFO",
                "verbose_name_plural": "سجلات تتبع تكاليف المرتجعات FIFO",
            },
        ),
        migrations.AddConstraint(
            model_name="salesreturnaudit",
            constraint=models.UniqueConstraint(
                fields=("processed_event_id",), name="unique_return_processed_event_id"
            ),
        ),
    ]
