# Generated by Django 4.2.26 on 2026-08-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0023_creditnote_sale_alter_creditnote_sales_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salereturn",
            name="inspection_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="تقرير فحص الجودة QC Notes"
            ),
        ),
        migrations.AddField(
            model_name="salereturn",
            name="inspection_status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الفحص"),
                    ("passed", "مقبول جودة"),
                    ("rejected", "مرفوض جودة"),
                ],
                default="passed",
                max_length=20,
                verbose_name="حالة فحص الجودة",
            ),
        ),
    ]
