# Generated by Django 4.2.26 on 2026-08-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0025_delete_salespolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CASH", "نقدي"),
                    ("BANK", "تحويل بنكي / شيك"),
                    ("PREPAID_BALANCE", "خصم من الرصيد المسبق / دفعة مقدمة"),
                    ("CREDIT_NOTE", "تسوية إشعار دائن"),
                ],
                default="CASH",
                help_text="التصنيف الشفاف لمصدر الدفعة المدفوعة",
                max_length=30,
                verbose_name="نوع مصدر الدفعة",
            ),
        ),
    ]
