# Generated by Django 4.2.26 on 2026-08-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0031_accountbalanceperiod"),
        ("sale", "0026_salepayment_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6, default=1.0, max_digits=18, verbose_name="سعر الصرف"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="total_foreign",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="الإجمالي بالعملة الأجنبية",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="total_functional",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="الإجمالي بالعملة الأساسية",
            ),
        ),
    ]
