# Generated by Django 4.2.26 on 2026-08-09 03:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0027_sale_currency_sale_exchange_rate_sale_total_foreign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="adjustment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ التسوية",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="adjustment_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="اسم التسوية"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="vat_active",
            field=models.BooleanField(
                default=True, verbose_name="ضريبة القيمة المضافة نشطة"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("14.00"),
                max_digits=5,
                verbose_name="نسبة القيمة المضافة %",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="wht_active",
            field=models.BooleanField(
                default=False, verbose_name="ضريبة الخصم والإضافة نشطة"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="wht_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ الخصم والإضافة",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="wht_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="نسبة الخصم والإضافة %",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="tax_active",
            field=models.BooleanField(default=True, verbose_name="الضريبة نشطة"),
        ),
        migrations.AddField(
            model_name="sale",
            name="vat_active",
            field=models.BooleanField(
                default=True, verbose_name="ضريبة القيمة المضافة نشطة"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("14.00"),
                max_digits=5,
                verbose_name="نسبة القيمة المضافة %",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="wht_active",
            field=models.BooleanField(
                default=False, verbose_name="ضريبة الخصم والإضافة نشطة"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="wht_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="مبلغ الخصم والإضافة",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="wht_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                verbose_name="نسبة الخصم والإضافة %",
            ),
        ),
    ]
