# Generated by Django 4.2.26 on 2026-08-09 04:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0042_datamigrationrun_and_more"),
        ("sale", "0029_quotation_currency_quotation_exchange_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="المبلغ بالعملة الأساسية (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="financial.currency",
                verbose_name="العملة",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="exchange_rate_snapshot",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                max_digits=12,
                verbose_name="لقطة سعر الصرف",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="transaction_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="مبلغ المعاملة",
            ),
        ),
    ]
