# Generated by Django 4.2.26 on 2026-08-20 08:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0047_alter_costcenter_code_alter_journalentry_entry_type_and_more",
        ),
        ("sale", "0030_salepayment_base_amount_salepayment_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="amount_functional",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="القيمة المعادلة بالجنيه المصري المودعة بالخزينة",
                max_digits=15,
                verbose_name="المعادل بالعملة الوظيفية (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="amount_paid_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ الفعلي المحصل بعملة الخزينة أو البنك",
                max_digits=15,
                verbose_name="المبلغ المسدد بعملة الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="amount_settled_invoice_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="المبلغ المخصوم من أصل الفاتورة بعملة الفاتورة",
                max_digits=15,
                verbose_name="المبلغ المقفول بعملة الفاتورة",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="payment_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_payments_as_payment_currency",
                to="financial.currency",
                verbose_name="عملة السداد / الخزينة",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="payment_exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="سعر صرف عملة السداد مقابل العملة الأساسية وقت التحصيل",
                max_digits=18,
                verbose_name="سعر صرف السداد",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="realized_fx_difference",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="صافي أرباح أو خسائر فروق العملة الناتجة عن التحصيل",
                max_digits=15,
                verbose_name="أرباح / خسائر فروق الصرف المحققة",
            ),
        ),
    ]
