# Generated by Django 4.2.26 on 2026-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0031_salepayment_amount_functional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salepayment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مفتاح فريد لمنع تكرار ترحيل الدفعة",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="مفتاح منع التكرار",
            ),
        ),
    ]
