from presentation.services.customer_dashboard_presenter import CustomerDashboardPresenter
from presentation.services.financial_dashboard_presenter import FinancialDashboardPresenter
from presentation.services.document_financial_presenter import DocumentFinancialPresenter
