# Generated by Django 4.2.26 on 2026-08-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
        ),
    ]
